### PR TITLE
AsyncScrolling: add ScrollingTreePositionedNode base class

### PR DESCRIPTION
**Pull request by carlosgcampos**
#### 8df9660de3fcb9c1cd5b79bee37a9f39662caf79
<pre>
AsyncScrolling: add ScrollingTreePositionedNode base class
<a href="https://bugs.webkit.org/show_bug.cgi?id=246453">https://bugs.webkit.org/show_bug.cgi?id=246453</a>

Reviewed by Žan Doberšek.

Make Cocoa and Nicosia implementations inherit from the base class and move the common code there.

* Source/WebCore/Sources.txt:
* Source/WebCore/SourcesCocoa.txt:
* Source/WebCore/SourcesGTK.txt:
* Source/WebCore/SourcesWPE.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/page/scrolling/ScrollingTreePositionedNode.cpp: Renamed from Source/WebCore/page/scrolling/cocoa/ScrollingTreePositionedNode.mm.
(WebCore::ScrollingTreePositionedNode::commitStateBeforeChildren):
(WebCore::ScrollingTreePositionedNode::scrollDeltaSinceLastCommit const):
* Source/WebCore/page/scrolling/ScrollingTreePositionedNode.h: Copied from Source/WebCore/page/scrolling/cocoa/ScrollingTreePositionedNode.h.
* Source/WebCore/page/scrolling/cocoa/ScrollingTreeFixedNode.mm:
(WebCore::ScrollingTreeFixedNode::applyLayerPositions):
* Source/WebCore/page/scrolling/cocoa/ScrollingTreePositionedNodeCocoa.h: Renamed from Source/WebCore/page/scrolling/cocoa/ScrollingTreePositionedNode.h.
(WebCore::ScrollingTreePositionedNodeCocoa::layer const):
* Source/WebCore/page/scrolling/cocoa/ScrollingTreePositionedNodeCocoa.mm: Added.
(WebCore::ScrollingTreePositionedNodeCocoa::create):
(WebCore::ScrollingTreePositionedNodeCocoa::ScrollingTreePositionedNodeCocoa):
(WebCore::ScrollingTreePositionedNodeCocoa::commitStateBeforeChildren):
(WebCore::ScrollingTreePositionedNodeCocoa::applyLayerPositions):
* Source/WebCore/page/scrolling/mac/ScrollingTreeMac.mm:
(ScrollingTreeMac::createScrollingTreeNode):
* Source/WebCore/page/scrolling/nicosia/ScrollingTreeFixedNode.cpp:
(WebCore::ScrollingTreeFixedNode::applyLayerPositions):
* Source/WebCore/page/scrolling/nicosia/ScrollingTreeNicosia.cpp:
(WebCore::ScrollingTreeNicosia::createScrollingTreeNode):
* Source/WebCore/page/scrolling/nicosia/ScrollingTreePositionedNodeNicosia.cpp: Renamed from Source/WebCore/page/scrolling/nicosia/ScrollingTreePositionedNode.cpp.
(WebCore::ScrollingTreePositionedNodeNicosia::create):
(WebCore::ScrollingTreePositionedNodeNicosia::ScrollingTreePositionedNodeNicosia):
(WebCore::ScrollingTreePositionedNodeNicosia::commitStateBeforeChildren):
(WebCore::ScrollingTreePositionedNodeNicosia::applyLayerPositions):
* Source/WebCore/page/scrolling/nicosia/ScrollingTreePositionedNodeNicosia.h: Renamed from Source/WebCore/page/scrolling/nicosia/ScrollingTreePositionedNode.h.
* Source/WebKit/UIProcess/RemoteLayerTree/RemoteScrollingTree.cpp:
(WebKit::RemoteScrollingTree::createScrollingTreeNode):

Canonical link: <a href="https://commits.webkit.org/255724@main">https://commits.webkit.org/255724@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/6ff4bc4e667f5870e95c76841d69d8ecda207428

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/93095 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/2295 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/23743 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/102802 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/163111 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/97097 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/2303 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/30623 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/85490 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/98920 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/98760 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/1589 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/79569 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/28518 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/83503 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/83268 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/71626 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/37016 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/17153 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/34828 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/18387 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3962 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/38699 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/40928 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/40629 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/37591 "Passed tests") | |

### CODE REVIEW

**Comment by carlosgcampos** [comment]
I need help with the iOS failures...

**Comment by smfr** [comment]
You have both:
`SPECIALIZE_TYPE_TRAITS_SCROLLING_NODE(ScrollingTreePositionedNode, isPositionedNode())`
and
`SPECIALIZE_TYPE_TRAITS_SCROLLING_NODE(ScrollingTreePositionedNodeCocoa, isPositionedNode())`
which can result in type confusion. The Cocoa one needs a unique predicate.

`ScrollingTreeStickyNodeCocoa` is also wrong.

**Comment by carlosgcampos** [comment]
Thanks @smfr, I indeed took the sticky one as reference, it looked weird to me, but since it worked I assumed it was right.

**Comment by carlosgcampos** [comment]
hmm, I guess I don't know how to make the type traits properly...

**Review by zdobersek — APPROVED** [review]

**Pull request merged**
