### PR TITLE
Re-import css/css-pseudo WPT

### PR DESCRIPTION
**Pull request by Andrew-Fryer**
#### 99676bd3c1785d4171c028ff3d39288409ccfbbc
<pre>
Re-import css/css-pseudo WPT
<a href="https://bugs.webkit.org/show_bug.cgi?id=277692">https://bugs.webkit.org/show_bug.cgi?id=277692</a>
<a href="https://rdar.apple.com/problem/133307533">rdar://problem/133307533</a>

Reviewed by Tim Nguyen.

Upstream commit: web-platform-tests/wpt@881381e

* LayoutTests/TestExpectations:
* LayoutTests/imported/w3c/resources/resource-files.json:
* LayoutTests/imported/w3c/web-platform-tests/css/css-pseudo/*
* LayoutTests/platform/ios/TestExpectations:
* LayoutTests/platform/mac-wk1/TestExpectations:
* LayoutTests/platform/mac-wk2/TestExpectations:

Canonical link: <a href="https://commits.webkit.org/282581@main">https://commits.webkit.org/282581@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/45675999879616ad24e19c96bf8e473135e9afee

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/63543 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/42899 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/16140 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/67564 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/14151 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/50587 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/14431 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/51169 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/9788 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/66612 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/39824 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/55027 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/31854 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/36507 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/12398 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/13023 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/58017 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/12719 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/69260 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/7490 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/12300 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/58476 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/7523 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/55110 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/58707 "Found 2 new API test failures: /WebKitGTK/TestContextMenu:/webkit/WebKitWebView/popup-event-signal, /WebKitGTK/TestContextMenu:/webkit/WebKitWebView/context-menu-key (failure)") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/14069 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/6257 "Passed tests") | | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/38720 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/39799 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/40911 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/39542 "Built successfully") | | |

### CODE REVIEW

**Comment by Andrew-Fryer** [comment]
I just added the following to `LayoutTests/TestExpectations` to combat build failures:
```

# failures: https://github.com/WebKit/WebKit/pull/31874
imported/w3c/web-platform-tests/css/css-pseudo/first-letter-width-2.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-001.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-002.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-004.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-005.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-painting-currentcolor-001.html [ ImageOnlyFailure ]
imported/w3c/web-platform-tests/css/css-pseudo/highlight-painting-currentcolor-001a.html [ ImageOnlyFailure ]
```
Please lmk if that's bad practice 🙃

**Comment by mdubet** [comment]
> I just added the following to `LayoutTests/TestExpectations` to combat build failures:
> 
> ```
> 
> # failures: https://github.com/WebKit/WebKit/pull/31874
> imported/w3c/web-platform-tests/css/css-pseudo/first-letter-width-2.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-001.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-002.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-004.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-cascade/cascade-highlight-005.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-painting-currentcolor-001.html [ ImageOnlyFailure ]
> imported/w3c/web-platform-tests/css/css-pseudo/highlight-painting-currentcolor-001a.html [ ImageOnlyFailure ]
> ```
> 
> Please lmk if that's bad practice 🙃

Those tests were already failing (cf the deleted lines in `TextExpectations`), the just got moved to a subdirectory.
We could just edit the line in TextExpectations to make that clearer (instead of deleting/appending a line)

**Comment by Andrew-Fryer** [comment]
Looks like some tests were actually passing only on iOS, so I enabled those...

**Comment by Andrew-Fryer** [comment]
the Misc Style bot error seems to be wrong
```
ERROR: LayoutTests/TestExpectations:3427:  Path does not exist.  [test/expectations] [5]
ERROR: LayoutTests/TestExpectations:3428:  Path does not exist.  [test/expectations] [5]
```
...but those paths do exist after this commit 😕

**Review by nt1m — APPROVED** [review]
r=me if EWS is green

**Comment by Andrew-Fryer** [comment]
@nt1m 
The only failing tests now I also see failing on another PR.
Can we merge this?

failing tests:
```
/WebKitGTK/TestContextMenu:/webkit/WebKitWebView/context-menu-key
/WebKitGTK/TestContextMenu:/webkit/WebKitWebView/popup-event-signal
```
other PR:
https://ews-build.webkit.org/#/builders/21/builds/58708

**Comment by mdubet** [comment]
> @nt1m The only failing tests now I also see failing on another PR. Can we merge this?
> 
> failing tests:
> 
> ```
> /WebKitGTK/TestContextMenu:/webkit/WebKitWebView/context-menu-key
> /WebKitGTK/TestContextMenu:/webkit/WebKitWebView/popup-event-signal
> ```
> 
> other PR: [ews-build.webkit.org](https://ews-build.webkit.org/#/builders/21/builds/58708)

Yes you can ignore those

**Pull request merged**
