### PR TITLE
Remove insecure Crypto algorithms from WebCrypto

### PR DESCRIPTION
**Pull request by angelaizg**
#### d171fefed730740ee8772c1edf33bc3037e93e90
<pre>
Remove insecure Crypto algorithms from WebCrypto
<a href="https://bugs.webkit.org/show_bug.cgi?id=247358">https://bugs.webkit.org/show_bug.cgi?id=247358</a>
rdar://101765059

Reviewed by NOBODY (OOPS!).

Removing RSAES_v1_5 from the list of algorithms we have.

* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-jwk-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-jwk.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-pkcs8-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-pkcs8.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-spki-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-export-key-spki.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key-encrypt-decrypt-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key-encrypt-decrypt.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key-extractable-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key-extractable.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-generate-key.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-private-key-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-private-key.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-empty-usages-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-empty-usages.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-leading-zero-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-leading-zero.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-minimum-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-minimum.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-non-extractable-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key-non-extractable.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-jwk-public-key.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-key-decrypt-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-key-decrypt.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-key-encrypt-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-key-encrypt.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-pkcs8-key-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-pkcs8-key.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-spki-key-empty-usages-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-spki-key-empty-usages.html: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-spki-key-expected.txt: Removed.
* LayoutTests/crypto/subtle/rsaes-pkcs1-v1_5-import-spki-key.html: Removed.
* Source/WebCore/Sources.txt:
* Source/WebCore/SourcesCocoa.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/bindings/js/SerializedScriptValue.cpp:
(WebCore::CloneSerializer::write):
(WebCore::CloneDeserializer::read):
* Source/WebCore/crypto/CryptoAlgorithmIdentifier.h:
* Source/WebCore/crypto/SubtleCrypto.cpp:
(WebCore::normalizeCryptoAlgorithmParameters):
(WebCore::isSupportedExportKey):
* Source/WebCore/crypto/gcrypt/CryptoAlgorithmRSAES_PKCS1_v1_5GCrypt.cpp: Removed.
* Source/WebCore/crypto/gcrypt/CryptoAlgorithmRegistryGCrypt.cpp:
(WebCore::CryptoAlgorithmRegistry::platformRegisterAlgorithms):
* Source/WebCore/crypto/mac/CryptoAlgorithmAES_CTRMac.cpp:
* Source/WebCore/crypto/mac/CryptoAlgorithmRegistryMac.cpp:
(WebCore::CryptoAlgorithmRegistry::platformRegisterAlgorithms):
* Source/WebCore/crypto/openssl/CryptoAlgorithmRSAES_PKCS1_v1_5OpenSSL.cpp: Removed.
* Source/WebCore/crypto/openssl/CryptoAlgorithmRegistryOpenSSL.cpp:
(WebCore::CryptoAlgorithmRegistry::platformRegisterAlgorithms):
</pre>
https://github.com/WebKit/WebKit/commit/20ce8561f600d9e15552ca4d216aa3a5e40b6d57

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/100805 "2 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/9949 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/33847 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/110103 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/170379 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/10886 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/724 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/93208 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/107950 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/106586 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/8226 "Found 2 new test failures: crypto/subtle/rsa-generate-key-malformed-parameters.html, crypto/subtle/rsa-import-key-malformed-parameters.html (failure)") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/91480 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/34837 "Found 2 new test failures: crypto/subtle/rsa-generate-key-malformed-parameters.html, crypto/subtle/rsa-import-key-malformed-parameters.html (failure)") | 
| | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/90135 "Found 1 new API test failure: TestWebKitAPI.InAppBrowserPrivacy.AppBoundDomainAllowsServiceWorkers (failure)") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/22874 "Found 2 new test failures: crypto/subtle/rsa-generate-key-malformed-parameters.html, crypto/subtle/rsa-import-key-malformed-parameters.html (failure)") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/77813 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/3642 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/24397 "Found 2 new test failures: crypto/subtle/rsa-generate-key-malformed-parameters.html, crypto/subtle/rsa-import-key-malformed-parameters.html (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/3664 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/695 "Found 2 new test failures: crypto/subtle/rsa-generate-key-malformed-parameters.html, crypto/subtle/rsa-import-key-malformed-parameters.html (failure)") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/9775 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/43896 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/5442 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by aproskuryakov** [comment]
Have other browser engines removed this algorithm?

**Comment by angelaizg** [comment]
> Have other browser engines removed this algorithm?

Firefox and Chrome don't support it, don't know if they did it previously. Just following the security guidelines
https://www.rfc-editor.org/rfc/rfc7518#section-8.3
rdar://28499687

**Comment by foopoiuyt** [comment]
This has been breaking the WinCairo EWS, not entirely sure why it's not recovering nicely. But the CryptoAlgorithmRSAES_PKCS1_v1_5OpenSSL.cpp file seems to be referenced in Source/WebCore/platform/OpenSSL.cmake and presumably needs to be removed from there.

**Comment by angelaizg** [comment]
> This has been breaking the WinCairo EWS, not entirely sure why it's not recovering nicely. But the CryptoAlgorithmRSAES_PKCS1_v1_5OpenSSL.cpp file seems to be referenced in Source/WebCore/platform/OpenSSL.cmake and presumably needs to be removed from there.

Ok thank you

**Comment by aj062** [comment]
~~Marked it as draft for now so that it doesn't break WinCairo ews.~~
Marking as draft doesn't stop EWS. Removed draft.

**Comment by youennf** [comment]
Let's introduce a runtime flag instead of removing the support directly.

**Pull request closed without merging**
