### PR TITLE
[JSC] Remove Wasm FastTLS

### PR DESCRIPTION
**Pull request by Constellation**
#### 5b971463eaad3a705207799ef68ab8dcb3ee9277
<pre>
[JSC] Remove Wasm FastTLS
<a href="https://bugs.webkit.org/show_bug.cgi?id=249993">https://bugs.webkit.org/show_bug.cgi?id=249993</a>
rdar://103809090

Reviewed by Saam Barati.

This was originally introduced to make Wasm Position-Independent-Code (PIC).
However, this is no longer meaningful.

1. At that time, we are embedding VM&apos;s pointer directly into Wasm&apos;s Module code. But this is no longer happening.
   So, without FastTLS, Wasm Module is already PIC.
2. Original patch was considering about serializing Wasm code into IndexedDB, but that proposal was now completely abandoned.
3. In super hot leaf function in OMG, FastTLS is unnecessarily emitting code to load instance while pinned-register version
   can eliminate this. So, pinned register version gets better code generation.
4. This makes OSS and Internal wasm call etc. the same since both just uses pinned registers. It also reduces # of variants of stress tests.

This patch removes Wasm FastTLS and always use pinned registers.

* Source/JavaScriptCore/assembler/JITOperationList.cpp:
(JSC::llintOperations):
* Source/JavaScriptCore/bytecode/BytecodeList.rb:
* Source/JavaScriptCore/jit/AssemblyHelpers.cpp:
(JSC::AssemblyHelpers::loadWasmContextInstance):
(JSC::AssemblyHelpers::storeWasmContextInstance):
(JSC::AssemblyHelpers::loadWasmContextInstanceNeedsMacroScratchRegister):
(JSC::AssemblyHelpers::storeWasmContextInstanceNeedsMacroScratchRegister):
* Source/JavaScriptCore/llint/LLIntExceptions.cpp:
(JSC::LLInt::handleWasmCatch):
(JSC::LLInt::handleWasmCatchAll):
* Source/JavaScriptCore/llint/LLIntThunks.cpp:
(JSC::LLInt::wasmFunctionEntryThunk):
(JSC::LLInt::wasmFunctionEntryThunkSIMD):
(JSC::LLInt::handleWasmCatchThunk):
(JSC::LLInt::handleWasmCatchAllThunk):
* Source/JavaScriptCore/llint/LowLevelInterpreter.asm:
* Source/JavaScriptCore/llint/WebAssembly.asm:
* Source/JavaScriptCore/runtime/Gate.h:
* Source/JavaScriptCore/runtime/Options.cpp:
(JSC::Options::notifyOptionsChanged):
* Source/JavaScriptCore/runtime/OptionsList.h:
* Source/JavaScriptCore/wasm/WasmAirIRGeneratorBase.h:
(JSC::Wasm::ExpressionType&gt;::restoreWasmContextInstance):
(JSC::Wasm::ExpressionType&gt;::AirIRGeneratorBase):
(JSC::Wasm::ExpressionType&gt;::finalizeEntrypoints):
* Source/JavaScriptCore/wasm/WasmB3IRGenerator.cpp:
(JSC::Wasm::B3IRGenerator::restoreWasmContextInstance):
(JSC::Wasm::B3IRGenerator::B3IRGenerator):
* Source/JavaScriptCore/wasm/WasmContext.h:
(JSC::Wasm::Context::pointerToInstance):
* Source/JavaScriptCore/wasm/WasmContextInlines.h:
(JSC::Wasm::Context::load const):
(JSC::Wasm::Context::store):
(JSC::Wasm::Context::tryLoadInstanceFromTLS):
(JSC::Wasm::Context::useFastTLS): Deleted.
* Source/JavaScriptCore/wasm/WasmFaultSignalHandler.cpp:
(JSC::Wasm::trapHandler):
* Source/JavaScriptCore/wasm/WasmLLIntGenerator.cpp:
(JSC::Wasm::LLIntGenerator::addCatchToUnreachable):
(JSC::Wasm::LLIntGenerator::addCatchAllToUnreachable):
(JSC::Wasm::LLIntGenerator::addCall):
(JSC::Wasm::LLIntGenerator::addCallIndirect):
(JSC::Wasm::LLIntGenerator::addCallRef):
* Source/JavaScriptCore/wasm/WasmMemoryInformation.cpp:
(JSC::Wasm::PinnedRegisterInfo::get):
* Source/JavaScriptCore/wasm/WasmSlowPaths.cpp:
(JSC::LLInt::WASM_SLOW_PATH_DECL):
* Source/JavaScriptCore/wasm/WasmSlowPaths.h:
* Source/JavaScriptCore/wasm/js/JSToWasm.cpp:
(JSC::Wasm::marshallJSResult):
(JSC::Wasm::createJSToWasmWrapper):
* Source/JavaScriptCore/wasm/js/WasmToJS.cpp:
(JSC::Wasm::wasmToJS):
* Source/JavaScriptCore/wasm/js/WebAssemblyFunction.cpp:
(JSC::JSC_DEFINE_HOST_FUNCTION):
(JSC::WebAssemblyFunction::jsCallEntrypointSlow):
* Tools/Scripts/run-jsc-stress-tests:

Canonical link: <a href="https://commits.webkit.org/258458@main">https://commits.webkit.org/258458@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/5d820ff1a4191328b9df38e9de2a85420270560e

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/102047 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/11190 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/35114 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/111371 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/171561 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/106028 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/12162 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/2102 "Built successfully") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/94437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/109115 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/107828 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/9314 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/92581 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/94437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/91194 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/24063 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/36/builds/94437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/1/builds/92413 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/81/builds/4755 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/25491 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/88609 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/83/builds/2374 "Built successfully and passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/4860 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/1935 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/29465 "Passed tests") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/80/builds/10922 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/62/builds/44982 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/91525 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/6609 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/20459 "Passed tests") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/3056 "Built successfully and passed tests") | | | |

### CODE REVIEW

**Comment by saambarati** [comment]
> This was originally introduced to make Wasm Position-Independent-Code (PIC).
> However, this is no longer meaningful.
> 
> 1. At that time, we are embedding VM's pointer directly into Wasm's Module code. But this is no longer happening.
>    So, without FastTLS, Wasm Module is already PIC.
> 2. Original patch was considering about serializing Wasm code into IndexedDB, but that proposal was now completely abandoned.
> 3. In super hot leaf function in OMG, FastTLS is unnecessarily emitting code to load instance while pinned-register version
>    can eliminate this. So, pinned register version gets better code generation.
> 4. This makes OSS and Internal wasm call etc. the same since both just uses pinned registers. It also reduces # of variants of stress tests.
> 
> This patch removes Wasm FastTLS and always use pinned registers.


One of the motivations was also perf. Is the pinned register approach faster?

**Review by saambarati — APPROVED** [review]
r=me based on the answer to my question.

**Comment by Constellation** [comment]
> > This was originally introduced to make Wasm Position-Independent-Code (PIC).
> > However, this is no longer meaningful.
> > 
> > 1. At that time, we are embedding VM's pointer directly into Wasm's Module code. But this is no longer happening.
> >    So, without FastTLS, Wasm Module is already PIC.
> > 2. Original patch was considering about serializing Wasm code into IndexedDB, but that proposal was now completely abandoned.
> > 3. In super hot leaf function in OMG, FastTLS is unnecessarily emitting code to load instance while pinned-register version
> >    can eliminate this. So, pinned register version gets better code generation.
> > 4. This makes OSS and Internal wasm call etc. the same since both just uses pinned registers. It also reduces # of variants of stress tests.
> > 
> > This patch removes Wasm FastTLS and always use pinned registers.
> 
> One of the motivations was also perf. Is the pinned register approach faster?

Yes. A/B test showed that pinned register one is neutral and/or faster.

**Comment by Constellation** [comment]
Pass locally.

**Pull request merged**
