### PR TITLE
Enable Metal validation in WebGPU crashtests

### PR DESCRIPTION
**Pull request by heycam**
#### 6cf946ba4efa9cc829f36dcd21b5c64eed19e5f3
<pre>
Enable Metal validation in WebGPU crashtests
<a href="https://bugs.webkit.org/show_bug.cgi?id=283453">https://bugs.webkit.org/show_bug.cgi?id=283453</a>
<a href="https://rdar.apple.com/problem/140314054">rdar://problem/140314054</a>

Reviewed by Mike Wyrzykowski.

Enabling Metal validation when these tests run will help us find if they
regress more quickly than running them at desk.

* LayoutTests/fast/webgpu/nocrash/fuzz-283157.html

Minimize this test while we&apos;re here.

* LayoutTests/fast/webgpu/nocrash/fuzz-277928b-no-validation.html: Copied from LayoutTests/fast/webgpu/nocrash/fuzz-277928b.html.
* LayoutTests/fast/webgpu/nocrash/fuzz-277928b-no-validation-expected.txt: Added.

Adding a copy of this test without Metal validation enabled, since the
test uncovered a separate crash that only occurred when validation was
disabled.

* LayoutTests/platform/mac-ventura/TestExpectations:

Skip some tests that trigger unrelated Metal validation errors on
Ventura.

* LayoutTests/fast/webgpu/nocrash/RenderBundle_WRITE.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-128396311.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-272863.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-272903.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-272911.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273017.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273021.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273023.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273323.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273503.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273505.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273566.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273570.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273573.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273578.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-273585.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274161.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274171.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274270.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274275.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274289.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274290.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-274334.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275167.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275172.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275218.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275225.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275228.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275229.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275294.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-275371.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277017.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277552.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277557.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277642.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277864.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277928.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-277928b.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-278049.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-278474.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-278545.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-279086.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-279449.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-279453.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-279912.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281271.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281272.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281539.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281555.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281603.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281614.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-281778.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282052.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282086.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282097.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282116.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282485.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282499.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282937.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-282995.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-283006.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-283008.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-283071.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-283157.html:
* LayoutTests/fast/webgpu/nocrash/fuzz-283196.html:
* LayoutTests/fast/webgpu/nocrash/repro_274977.html:
* LayoutTests/fast/webgpu/nocrash/webgpu_oob_attribute_offset.html:

Add WKTR test options appropriate for each test.

Canonical link: <a href="https://commits.webkit.org/287922@main">https://commits.webkit.org/287922@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/67b0d86334d26d299839cfa9874bb9c556692ee2

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/81302 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/827 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/35245 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/85831 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/32288 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/845 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/8643 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/63468 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/21237 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/84371 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/571 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/73994 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/43764 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/469 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/28156 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/30746 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/71964 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/28737 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/87266 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/8532 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/6065 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/71777 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/8713 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/69824 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/71011 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/15070 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/13981 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/12611 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/8494 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/8330 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/11851 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/10138 "Built successfully") | | |

### CODE REVIEW

**Review by mwyrzykowski — COMMENTED** [review]
Is there any way to have the tests run twice, once without validation and once with it on?

If we don’t run with it disabled we risk missing crashes which customers would otherwise encounter.

**Comment by mwyrzykowski** [comment]
> Is there any way to have the tests run twice, once without validation and once with it on?
> 
> If we don’t run with it disabled we risk missing crashes which customers would otherwise encounter.

I guess we could just duplicate the test cases?

**Comment by heycam** [comment]
At least with how I've used the WebKitTestRunner options, I don't think it's possible to run the test twice with different options. It'd need to be a different builtbot queue configured differently. Duplicating the tests (like I've done for that one test) would work. Do you think we need to do that for all of the tests? Or can we just check whether the test fails in some interesting way without the Metal debug options enabled when addressing the bug, and checking in a no-validation version at that point if it does?

**Comment by heycam** [comment]
Could also factor out the meat of the testcase into a .js file and have two .html files reference it (one with Metal validation enabled one without).

**Review by mwyrzykowski — APPROVED** [review]

**Comment by heycam** [comment]
> Is there any way to have the tests run twice, once without validation and once with it on?

I'll think about that in a followup patch.

**Pull request merged**
