### PR TITLE
REGRESSION(254232@main): Causes process launching to use fork + exec instead of posix_spawn

### PR DESCRIPTION
**Pull request by mcatanzaro**
#### 9d195cb5d885d32433a7d79547c6a70c16c0959f
<pre>
REGRESSION(254232@main): Causes process launching to use fork + exec instead of posix_spawn
<a href="https://bugs.webkit.org/show_bug.cgi?id=245784">https://bugs.webkit.org/show_bug.cgi?id=245784</a>

Reviewed by Carlos Garcia Campos.

254232@main removed use of G_SUBPROCESS_FLAGS_INHERIT_FDS since we
actually do not ever want to inherit fds into our child processes,
except for those that we explicitly pass along using
g_subprocess_launcher_take_fd(). This was a good change since it makes
WebKit more robust to file descriptor leaks, but there is an unfortunate
side effect: it prevents gspawn from using posix_spawn() to launch
subprocesses, so we wind up falling back to fork() and exec() instead. I
had left an insufficient warning comment about this, but it only
mentioned one of the many things that could cause us to fall back to
fork()/exec(). So:

 * Revert 254232@main
 * Avoid reintroducing bug #221489 by setting CLOEXEC on the client end
   of the IPC socket
 * Improve the warning comments to indicate there is more than one way
   to cause us to fall back to fork()/exec()

* Source/WebKit/UIProcess/Launcher/glib/ProcessLauncherGLib.cpp:
(WebKit::connectionOptions):
(WebKit::ProcessLauncher::launchProcess):
* Source/WebKit/UIProcess/Launcher/glib/XDGDBusProxy.cpp:
(WebKit::XDGDBusProxy::launch):

Canonical link: <a href="https://commits.webkit.org/255325@main">https://commits.webkit.org/255325@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/917e08fda8c040b2ebcc91d89f385fd9e6a64e69

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/91097 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/90 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/21632 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/100585 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/98 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/29147 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/83463 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/97221 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/96753 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/81 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/77860 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/27063 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/82031 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/81680 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/70098 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/35246 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/15705 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/33043 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/16708 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3693 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/36825 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/39646 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/38752 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/35792 "Passed tests") | |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Is this OK? I know it's weird to inherit fds when we don't really want them to be inherited, but I think my explanation makes sense.

**Comment by SilverGozas** [comment]
Hi. Not a contributor here, but I just wanted to point out that the removal of the `G_SUBPROCESS_FLAGS_INHERIT_FDS` flag broke a few older programs that use Webkit and rely on that flag for interprocess communication (bug found in [surf](http://surf.suckless.org/) initially due to its use of sockets for communication with its web extensions); and while Webkit itself does not require that flag as it can just use `g_subprocess_launcher_take_fd` to pass on all of the file descriptors that it needs, the tools that use Webkit don't have that option, and would have to either abandon the interprocess communication altogether, or rewrite everything to use other methods of communication. So I think that it is better to use that flag, since you can prevent
passing FDs from the application by using `O_CLOEXEC`, but you can not do it the other way around when that flag is missing.

---
EDIT: another problem is that some of those older programs break in quite a bad way, because since they do not expect such a change in the behavior of Webkit, they still compile and run, but still try to use the same file descriptor, that they used before, and start reading out of a different file descriptor with the same number and break in a very bad way, since that situation is a UB and there's no telling what *might* happen.

**Comment by 8dcc** [comment]
> Hi. Not a contributor here, but I just wanted to point out that the removal of the `G_SUBPROCESS_FLAGS_INHERIT_FDS` flag broke a few older programs that use Webkit and rely on that flag for interprocess communication (bug found in [surf](http://surf.suckless.org/) initially due to its use of sockets for communication with its web extensions); and while Webkit itself does not require that flag as it can just use `g_subprocess_launcher_take_fd` to pass on all of the file descriptors that it needs, the tools that use Webkit don't have that option, and would have to either abandon the interprocess communication altogether, or rewrite everything to use other methods of communication. So I think that it is better to use that flag, since you can prevent passing FDs from the application by using `O_CLOEXEC`, but you can not do it the other way around when that flag is missing.

My man :100:

**Comment by mcatanzaro** [comment]
> (bug found in [surf](http://surf.suckless.org/) initially due to its use of sockets for communication with its web extensions);

Can you point to what surf is doing? Is it using pipe(), for instance? I don't think it's fair to expect file descriptors to inherit into the child process. There's no way to do that safely: you'll wind up with the descriptor open in multiple subprocesses, which is actually exactly the problem that 254232@main was designed to fix. Difference is, WebKit can avoid that for its own file descriptors, but application code can never avoid it. I would pick a different way to communicate with the web process.

So even if this PR does land (and it might not), you should change surf anyway to avoid relying on fd inheritance.

**Comment by SilverGozas** [comment]
> Can you point to what surf is doing?

Surf uses a web extension for some tasks that require custom javascript to be run in a page on some user commands (like using keyboard shortcuts to scroll the page) and to communicate with that web extension it creates a Unix socket pair using the `socketpair` function, afterwards it makes it's end of the socket into a `GLib.IOChannel` with `close_on_unref` set to `TRUE`, the other end, it passes to the webextension (the file descriptor number is passed as an argument) and then the extension makes a similar `IOChannel` out of it.

> I don't think it's fair to expect file descriptors to inherit into the child process.

Maybe, but most C programmers have come to expect that behavior, since if they did not ask the system to close that file descriptor by setting `O_CLOEXEC`, then it should not have been closed. I actually spent quite some time debugging to even find out that this is not the case with WebKit, which closes them (while I am no expert with glib, from my understanding, underneath the wrapper it's not the passing of file descriptors that happens when you set that flag, but it's actually just stopping glib wrapper from explicitly closing them, *but please correct me if I'm wrong*) and even when I asked a person, who is even more experienced in C and Linux programming, even they did not expect file descriptors being closed on fork inside Webkit.

I don't mean, however that this **should** be the case, but you'd expect that to be reflected in the documentation, or at least the patch notes.

> There's no way to do that safely

Once again, if a developer of an app that uses Webkit finds themselves to have problems with file descriptors being passed to Webkit processes, they can always change their code to set the `O_CLOEXEC`, or just close them themselves when they no longer need them. But the change in release 2.38 is irreversible unless you recompile Webkit yourself.

And I would not consider this a problem if it wasn't so hard to find out about. So I think there **is** a place for Webkit without descriptors being passed to the child processes, but it should be possible for the developers to find out about this without having to first make the mistake of relying on that behavior, then spending days to find out what's wrong, and then on top of that going through hundreds of thousands lines of code to find out what the problem is.

**PS: sorry if some of this reads as overdramatic, critical, or even entitled — if it does, I did not intend it that way. I am not here to wage internet wars, and I think that what you, and all of the devs are doing here is great, I'm just here to bring up some suggestions of what could be changed to make everyones lifes easier.**

Thank you for your time:)

**Comment by mcatanzaro** [comment]
Well, I guess if we land this, it will fix your problem... still, to be robust, I would recommend using WebKit's APIs for IPC (webkit_web_context_send_message_to_all_extensions(), webkit_web_extension_send_message_to_context(), webkit_web_view_send_message_to_page(), webkit_web_page_send_message_to_view()).

**Comment by SilverGozas** [comment]
> Well, I guess if we land this, it will fix your problem... still, to be robust, I would recommend using WebKit's APIs for IPC (webkit_web_context_send_message_to_all_extensions(), webkit_web_extension_send_message_to_context(), webkit_web_view_send_message_to_page(), webkit_web_page_send_message_to_view()).

Thanks, I have already found this solution. I do also find this to be a better way to handle inter-process communication, but I still think that what I said before applies, and if this pull request does **not** get merged, there should be at least some mention in the documentation or changelog about the FDs not being passed to child subprocesses anymore, because judging by commit dates, when surf (and most likely a few more tools that I just don't know about) began using sockets to communicate to its extensions, Webkit did not have these functions yet, and since with these indie tools, most of the time everyone just goes by the rule: "If it works — don't fix it", everyone just fell behind, and now that it finally **doesn't** work, nobody know why or **how** to fix it.

I think I will still be reporting the changed behavior as a bug to suckless (org behind surf), and maybe try to patch it myself, since it is now clear, that going forward FD passing to child processes can not be relied on, and even if it can, there's still already one stable version of Webkit that does not do that in a way that is expected.

Once again, thank you for your time.

**Review by carlosgcampos — APPROVED** [review]
Ok, let's do this

**Pull request merged**
