### PR TITLE
[EWS] Use github.head.sha instead of revision

### PR DESCRIPTION
**Pull request by JonWBedard**
#### f0fdf2139ddc2523b0e824ff89da75d17df21913
<pre>
[EWS] Use github.head.sha instead of revision
<a href="https://bugs.webkit.org/show_bug.cgi?id=235521">https://bugs.webkit.org/show_bug.cgi?id=235521</a>
&lt;rdar://problem/87970427 &gt;

Reviewed by Aakash Jain.

* Tools/CISupport/ews-build/events.py:
(Events.buildFinishedGitHub): Use github.head.sha instead of revision.
(Events.stepStartedGitHub): Ditto.
* Tools/CISupport/ews-build/master.cfg: Extract github.head.sha from hook.
* Tools/CISupport/ews-build/steps.py:
(GitHubMixin._is_pr_obsolete): Use github.head.sha instead of revision.
(ConfigureBuild.add_pr_details): Ditto.
(ValidateChange.validate_github): Ditto.
* Tools/CISupport/ews-build/steps_unittest.py:

Canonical link: <a href="https://commits.webkit.org/246357@main">https://commits.webkit.org/246357@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@288474">https://svn.webkit.org/repository/webkit/trunk@288474</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by aj062** [comment]
Looks good. Please check if you need to include github.head.sha in properties_to_pass in Trigger() step, so that the triggered builds can also get this property.

**Review by aj062 — APPROVED** [review]

**Comment by JonWBedard** [comment]
> Looks good. Please check if you need to include github.head.sha in properties_to_pass in Trigger() step, so that the triggered builds can also get this property.

We will! Quite a bit more than just that, actually. Will have another change shortly with that in it

**Comment by JonWBedard** [comment]
Landed https://commits.webkit.org/246357@main (f0fdf2139ddc2523b0e824ff89da75d17df21913)!

**Comment by JonWBedard** [comment]
> Looks good. Please check if you need to include github.head.sha in properties_to_pass in Trigger() step, so that the triggered builds can also get this property.

#93 has the `Trigger` changes @jain-aakash was referring to.

**Pull request merged**
