### PR TITLE
Enable Intersection Observer in WebKit1

### PR DESCRIPTION
**Pull request by cdumez**
#### ea72d728429e3a0b627083a0f5b2a83967c4f111
<pre>
Enable Intersection Observer in WebKit1
<a href="https://bugs.webkit.org/show_bug.cgi?id=231767">https://bugs.webkit.org/show_bug.cgi?id=231767</a>
&lt;rdar://84280812&gt;

Reviewed by Simon Fraser.

Enable Intersection Observer for WebKit1 as the implementation resides entirely
in WebCore and works for WebKit1 (validated using Minibrowser).

* Source/WTF/Scripts/Preferences/WebPreferencesExperimental.yaml:

Canonical link: <a href="https://commits.webkit.org/251787@main">https://commits.webkit.org/251787@main</a>
</pre>

### CODE REVIEW

**Comment by smfr** [comment]
Don't we also need to change some TestExpectations?

**Comment by cdumez** [comment]
> Don't we also need to change some TestExpectations?

Not that I am aware, experimental features get enabled by default by WKTR / DRT. I'll double check that nobody is explicitly disabling the feature in DRT.

**Comment by cdumez** [comment]
> > Don't we also need to change some TestExpectations?
> 
> Not that I am aware, experimental features get enabled by default by WKTR / DRT. I'll double check that nobody is explicitly disabling the feature in DRT.

Actually you're right, the tests are disabled for WK1:
LayoutTests/platform/mac-wk1/TestExpectations:http/tests/intersection-observer [ Skip ]
LayoutTests/platform/mac-wk1/TestExpectations:imported/w3c/web-platform-tests/intersection-observer [ Skip ]
LayoutTests/platform/mac-wk1/TestExpectations:intersection-observer [ Skip ]

I'll investigate why and un-skip.

**Comment by cdumez** [comment]
Ok, I updated the TestExpectations.

**Review by smfr — APPROVED** [review]

**Pull request merged**
