### PR TITLE
Introduce compile-time checking and alternate allocation for compact pointer types

### PR DESCRIPTION
**Pull request by ddegazio**
#### 2c04bdef58462df5c867b8179e74bb69675512d8
<pre>
Introduce compile-time checking and alternate allocation for compact pointer types
<a href="https://bugs.webkit.org/show_bug.cgi?id=266080">https://bugs.webkit.org/show_bug.cgi?id=266080</a>
<a href="https://rdar.apple.com/119382681">rdar://119382681</a>

Reviewed by Mark Lam.

Adds compile-time checking to WTF compact and packed pointer types requiring the
pointed-to types to be explicitly marked as compatible with compact pointers. Also
adds new equivalents to the existing WTF::fastMalloc and WTF::isoMalloc allocation
functions for compactible types, giving us an API point to play with how types
used in compact pointers are allocated.

* Source/JavaScriptCore/bytecode/CallLinkInfoBase.h:
* Source/JavaScriptCore/bytecode/CodeBlock.h:
* Source/JavaScriptCore/bytecode/InlineCallFrame.h:
* Source/JavaScriptCore/bytecode/InlineCallFrameSet.h:
* Source/JavaScriptCore/bytecode/StructureStubClearingWatchpoint.h:
* Source/JavaScriptCore/bytecode/Watchpoint.h:
* Source/JavaScriptCore/dfg/DFGJITCode.h:
* Source/JavaScriptCore/heap/FastMallocAlignedMemoryAllocator.cpp:
* Source/JavaScriptCore/heap/IsoAlignedMemoryAllocator.cpp:
* Source/JavaScriptCore/jit/BaselineJITCode.h:
* Source/JavaScriptCore/jit/ExecutableMemoryHandle.h:
* Source/JavaScriptCore/jit/JITCode.h:
* Source/JavaScriptCore/jit/PolymorphicCallStubRoutine.h:
* Source/JavaScriptCore/runtime/ClassInfo.h:
* Source/JavaScriptCore/runtime/JSArray.h:
* Source/JavaScriptCore/wasm/WasmTypeDefinition.h:
* Source/WTF/wtf/Bag.h:
* Source/WTF/wtf/CompactPointerTuple.h:
* Source/WTF/wtf/CompactPtr.h:
* Source/WTF/wtf/DebugHeap.h:
* Source/WTF/wtf/FastMalloc.cpp:
* Source/WTF/wtf/FastMalloc.h:
* Source/WTF/wtf/IsoMalloc.h:
* Source/WTF/wtf/IsoMallocInlines.h:
* Source/WTF/wtf/SentinelLinkedList.h:
* Source/WTF/wtf/WeakPtr.h:
* Source/WTF/wtf/text/StringImpl.h:
* Source/WTF/wtf/text/WTFString.h:
* Source/WebCore/dom/Node.h:
* Source/WebCore/dom/NodeRareData.h:
* Source/WebCore/rendering/RenderObject.cpp:
* Source/WebCore/rendering/RenderObject.h:
* Source/bmalloc/bmalloc/AllocationCounts.h:
* Source/bmalloc/bmalloc/IsoHeap.cpp:
* Source/bmalloc/bmalloc/IsoHeap.h:
* Source/bmalloc/bmalloc/IsoHeapImpl.h:
* Source/bmalloc/bmalloc/IsoHeapInlines.h:
* Source/bmalloc/bmalloc/Packed.h:
* Tools/TestWebKitAPI/Tests/WTF/AlignedRefLogger.h:
* Tools/TestWebKitAPI/Tests/WTF/CompactRefPtr.cpp:
* Tools/TestWebKitAPI/Tests/WTF/CompactUniquePtrTuple.cpp:
* Tools/TestWebKitAPI/Tests/WTF/RefLogger.h:

Canonical link: <a href="https://commits.webkit.org/271819@main">https://commits.webkit.org/271819@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ed4ead0b6fc07584fa47a36279eed3a9f06c5541

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/29776 "7 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/8436 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/31079 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/32277 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/26920 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/30398 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/10605 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/5704 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/26946 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/30055 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/47/builds/7052 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/25385 "Passed tests") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/41/builds/6009 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/6173 "Passed tests") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/10/builds/26472 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/33614 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/25562 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/27148 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/26896 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/32355 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/29961 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/6099 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/50/builds/4296 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/30136 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/7846 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/36342 "Built successfully") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/6852 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/7843 "Passed tests") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/3837 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/6630 "Built successfully") | | |

### CODE REVIEW

**Comment by ddegazio** [comment]
Reopening this patch since the previous one (https://github.com/WebKit/WebKit/pull/21517) broke watchOS build and had to be reverted. This patch should contain the fix, but I'll make sure we build and test on watchOS before landing this time.

**Comment by ddegazio** [comment]
Specifically: in `bmalloc/IsoHeapInlines.h:115-119`, when defining some constructors out-of-line, I had ```
template<typename Type>
constexpr IsoHeap(const char* name): IsoHeapBase<Type>(name) { }
template<typename Type>
constexpr CompactIsoHeap(const char* name): IsoHeapBase<Type>(name) { }
```...which is obviously (in hindsight) missing the class name as a namespace. I've changed it to: ```
template<typename Type>
constexpr IsoHeap<Type>::IsoHeap(const char* name): IsoHeapBase<Type>(name) { }
template<typename Type>
constexpr CompactIsoHeap<Type>::CompactIsoHeap(const char* name): IsoHeapBase<Type>(name) { }
```Hopefully this is the only issue! I'll keep an eye on our EWS build.

**Review by MenloDorian — APPROVED** [review]
r=me

**Comment by ddegazio** [comment]
...turns out we probably don't need or want those out-of-line constructor definitions at all, I forgot I left some in-line versions in the base `IsoHeap.h`. Latest push removes those to address the newest watch build error.

**Comment by ddegazio** [comment]
Watch build finally passing...given we passed everything else previously, and all the changes for watchOS are defined out on other platforms (since we don't use bmalloc, or don't use bmalloc without libpas), I'm gonna re-land this patch.

**Pull request merged**
