### PR TITLE
Use correct HRTF elevation response for negative elevations

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Use correct HRTF elevation response for negative elevations
<a href="https://bugs.webkit.org/show_bug.cgi?id=250279">https://bugs.webkit.org/show_bug.cgi?id=250279</a>
rdar://problem/104265673

Reviewed by NOBODY (OOPS!).

Merge - <a href="https://src.chromium.org/viewvc/blink?view=revision&revision=181986">https://src.chromium.org/viewvc/blink?view=revision&revision=181986</a>

The computed index for negative elevations was off by one. When the elevation is -45 deg,
the selected response corresponded to the entry for 90 deg, not 315 deg.

To simplify things, we just use a short table to map the index to the (positive) elevation angle.

* Source/WebCore/platform/audio/HRTFElevation.cpp: Introduce static short table
(HRTFElevation::calculateKernelsForAzimuthElevation): Leverage on positive elevation angle
</pre>

https://github.com/WebKit/WebKit/commit/2b592f8c5a89ac7d52b63a8515f1c83c1fa6fbfd

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/106179 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/15230 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/39013 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/115362 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/175441 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/110084 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/16671 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/6415 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/98383 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/115049 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/111938 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/12686 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/95657 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/40220 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/94560 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/27300 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/81904 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/8477 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/28652 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/8977 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/5206 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/14593 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/48198 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/10513 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by cdumez — COMMENTED** [review]
This needs a test.

**Comment by Ahmad-S792** [comment]
> This needs a test.

I did PR after confirming with @eric-carlson that this bug is reproducible and also tested via local build using the test case present on the bug, where if the elevation goes below -29, it shifts and it does not happen with this patch and it matches in behavior to Chrome Canary 112. Unfortunately, I don't have automated testcase for it. Should I close this PR and document the rationale on bug ticket so someone else can take it up?

**Comment by cdumez** [comment]
I don't think we can land such a change without an automated test.

**Comment by Ahmad-S792** [comment]
> I don't think we can land such a change without an automated test.

Thanks! I will document this conclusion on the bug ticket and close this PR now. Appreciate your input!

**Pull request closed without merging**
