### PR TITLE
[ANGLE] Implement GL_ANGLE_metal_schedule extension

### PR DESCRIPTION
**Pull request by djg**
#### dae93fe89b6e876f2bfce95e8006394041993293
<pre>
[ANGLE] Implement GL_ANGLE_metal_schedule extension
<a href="https://bugs.webkit.org/show_bug.cgi?id=254386">https://bugs.webkit.org/show_bug.cgi?id=254386</a>
rdar://problem/107163821

Reviewed by NOBODY (OOPS!).

In angleproject:7809 the default behavior of Flush() was changed to become a &quot;no
wait&quot; instead of &quot;wait for scheduled&quot;. This changes the semantics of Flush() on
ANGLE compared to Apple OpenGL, meaning that Flush() can no longer to signal to
the GPU the dependency of operations affecting IOSurfaces when working with
multiple APIs, such as CoreGraphics.

Instead of reverting the behavior change to Flush(), this change provides a way
to ensure that all queued operations currently in the pipeline have had their
resources readied and are waiting for the GPU to process them. Currently,
Finish() is required to ensure these dependencies are met where Schedule() would
suffice.

* Source/ThirdParty/ANGLE/doc/ExtensionSupport.md:
* Source/ThirdParty/ANGLE/include/GLES2/gl2ext_angle.h:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/Extension_files.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/GL_EGL_WGL_loader.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/GL_EGL_entry_points.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/GLenum_value_to_string_map.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/Test_spec_JSON.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/Vulkan_mandatory_format_support_table.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/interpreter_utils.json:
* Source/ThirdParty/ANGLE/scripts/code_generation_hashes/proc_table.json:
* Source/ThirdParty/ANGLE/scripts/gl_angle_ext.xml:
* Source/ThirdParty/ANGLE/scripts/registry_xml.py:
* Source/ThirdParty/ANGLE/src/common/entry_points_enum_autogen.cpp:
(angle::GetEntryPointName):
* Source/ThirdParty/ANGLE/src/common/entry_points_enum_autogen.h:
* Source/ThirdParty/ANGLE/src/libANGLE/Context.cpp:
(gl::Context::schedule):
* Source/ThirdParty/ANGLE/src/libANGLE/Context_gles_ext_autogen.h:
* Source/ThirdParty/ANGLE/src/libANGLE/capture/capture_gles_ext_autogen.cpp:
(gl::CaptureScheduleANGLE):
* Source/ThirdParty/ANGLE/src/libANGLE/capture/capture_gles_ext_autogen.h:
* Source/ThirdParty/ANGLE/src/libANGLE/gles_extensions_autogen.cpp:
(gl::GetExtensionInfoMap):
* Source/ThirdParty/ANGLE/src/libANGLE/gles_extensions_autogen.h:
* Source/ThirdParty/ANGLE/src/libANGLE/renderer/ContextImpl.cpp:
(rx::ContextImpl::schedule):
* Source/ThirdParty/ANGLE/src/libANGLE/renderer/ContextImpl.h:
* Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.h:
* Source/ThirdParty/ANGLE/src/libANGLE/renderer/metal/ContextMtl.mm:
(rx::ContextMtl::schedule):
* Source/ThirdParty/ANGLE/src/libANGLE/validationES2.cpp:
(gl::ValidateScheduleANGLE):
* Source/ThirdParty/ANGLE/src/libANGLE/validationESEXT_autogen.h:
* Source/ThirdParty/ANGLE/src/libGLESv2/entry_points_gles_ext_autogen.cpp:
* Source/ThirdParty/ANGLE/src/libGLESv2/entry_points_gles_ext_autogen.h:
* Source/ThirdParty/ANGLE/src/libGLESv2/libGLESv2_autogen.cpp:
* Source/ThirdParty/ANGLE/src/libGLESv2/libGLESv2_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/libGLESv2_no_capture_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/libGLESv2_vulkan_secondaries_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/libGLESv2_with_capture_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/opengl32_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/opengl32_with_wgl_autogen.def:
* Source/ThirdParty/ANGLE/src/libGLESv2/proc_table_egl_autogen.cpp:
* Source/ThirdParty/ANGLE/src/libGLESv2/proc_table_glx_autogen.cpp:
* Source/ThirdParty/ANGLE/src/libGLESv2/proc_table_wgl_autogen.cpp:
* Source/ThirdParty/ANGLE/util/capture/frame_capture_replay_autogen.cpp:
(angle::ReplayTraceFunctionCall):
* Source/ThirdParty/ANGLE/util/capture/trace_gles_loader_autogen.cpp:
* Source/ThirdParty/ANGLE/util/capture/trace_gles_loader_autogen.h:
* Source/ThirdParty/ANGLE/util/capture/trace_interpreter_autogen.cpp:
(angle::ParseCallCapture):
* Source/ThirdParty/ANGLE/util/gles_loader_autogen.cpp:
* Source/ThirdParty/ANGLE/util/gles_loader_autogen.h:
</pre>
https://github.com/WebKit/WebKit/commit/dae93fe89b6e876f2bfce95e8006394041993293

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/403 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/417 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/435 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/405 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/367 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/459 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/462 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/606 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/409 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/395 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/387 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/434 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/436 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/377 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/435 "4 flakes 120 failures") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/352 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/393 "Passed tests") | [⏳ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/API-Tests-GTK-EWS "Waiting to run tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/379 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/372 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/346 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/388 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/386 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by djg** [comment]
This extension is a candidate to upstream to ANGLE but it's currently a dependency for another WebKit bug, so I want to land it as a local modification first.

**Review by kkinnunen-apple — COMMENTED** [review]
Since this is such a ready-to-upstream change, I'd prefer if you just submitted upstream and we'd hash it out there.

**Comment by kenrussell** [comment]
Oh no - this functionality was already implemented in ANGLE as the EGL extension EGL_ANGLE_wait_until_work_scheduled in https://bugs.chromium.org/p/angleproject/issues/detail?id=7890 . I haven't synced WebKit to top-of-tree but is that extension already in your ANGLE snapshot? Does it suit your needs?

**Review by kenrussell — CHANGES_REQUESTED** [review]
I'm sorry that our teams' work overlapped. Per update above and on the linked bug, I think WebKit's copy of ANGLE should already contain the EGL_ANGLE_wait_until_work_scheduled extension. Does it suit your needs?

**Comment by djg** [comment]
Duplicate work. Closing infavor of `EGL_ANGLE_wait_until_work_scheduled`.

**Pull request closed without merging**
