### PR TITLE
Remove TextTrack.{add,remove}Region

### PR DESCRIPTION
**Pull request by cola119**
#### 2a314fd952938b151bde894bde18960353c18638
<pre>
Remove TextTrack.{add,remove}Region
<a href="https://bugs.webkit.org/show_bug.cgi?id=260767">https://bugs.webkit.org/show_bug.cgi?id=260767</a>

Reviewed by Eric Carlson and Chris Dumez.

These APIs were removed from the spec by <a href="https://github.com/w3c/webvtt/pull/31">https://github.com/w3c/webvtt/pull/31</a>

* LayoutTests/imported/w3c/web-platform-tests/webvtt/api/historical-expected.txt:
* LayoutTests/media/track/regions-webvtt/vtt-region-list-expected.txt: Removed.
* LayoutTests/media/track/regions-webvtt/vtt-region-list.html: Removed.
* Source/WebCore/html/track/TextTrack.cpp:
(WebCore::TextTrack::addRegion): Deleted.
(WebCore::TextTrack::removeRegion): Deleted.
* Source/WebCore/html/track/TextTrack.h:
* Source/WebCore/html/track/TextTrack.idl:

Canonical link: <a href="https://commits.webkit.org/267694@main">https://commits.webkit.org/267694@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/d8478e5a90bfa6ca9e022c92b3c02b5cdeffdf16

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/17382 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/17706 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/18217 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/19169 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/16266 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/17579 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/20982 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/17848 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/18431 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/17587 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/17918 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/15114 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/19987 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/15158 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/15812 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/22474 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/16157 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/15981 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/20301 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/16563 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/17/builds/14088 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/15708 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/4156 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/20078 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/16399 "Built successfully") | | |

### CODE REVIEW

**Review by cdumez — COMMENTED** [review]
It would be nice to add a test to make sure that those operations are no longer exposed on TextTrack.

Looks good otherwise.

**Comment by rniwa** [comment]
Are we sure there is no web content relying on these functions?

**Comment by cdumez** [comment]
> Are we sure there is no web content relying on these functions?

I guess @eric-carlson (or someone else on the media team) is the best person to answer that.

However, given that Blink doesn't ship this (not sure if they ever did or if they recently dropped it), I personally think it is worth trying at least. We can always revert if we find breakage and now is not a particularly bad time for riskier changes.

**Review by eric-carlson — APPROVED** [review]

**Comment by Ahmad-S792** [comment]
@cola119 - once EWS is green, I will merge this and also in future - you can add 'request-merge-queue' tag once EWS is green and review is being done.

**Review by cdumez — APPROVED** [review]

**Comment by cola119** [comment]
Chromium and FireFox dropped these APIs over 5 years ago:
https://chromium.googlesource.com/chromium/src/+/54cf4b70b9b91b67258d0909188772c43c11c09f
https://bugzilla.mozilla.org/show_bug.cgi?id=978163
https://wpt.fyi/results/webvtt/api/historical.html?label=experimental&label=master&aligned&q=webvtt
and I believe it would be beneficial for most websites if all browsers followed a consistent behavior instead of WebKit being the only one with different behavior.

**Comment by Ahmad-S792** [comment]
debug build failures seems to be flaky and unrelated. :-)

**Pull request merged**
