### PR TITLE
Disable ASan version check

### PR DESCRIPTION
**Pull request by ddkilzer**
#### 7d72812ad4ae768d4f2f5691076bfbb186837601
<pre>
Disable ASan version check
&lt;<a href="https://bugs.webkit.org/show_bug.cgi?id=275242">https://bugs.webkit.org/show_bug.cgi?id=275242</a>&gt;
&lt;<a href="https://rdar.apple.com/129379793">rdar://129379793</a>&gt;

Reviewed by NOBODY (OOPS!).

* Configurations/CommonBase.xcconfig:
(WK_COMMON_OTHER_SWIFT_FLAGS): Add.
(OTHER_SWIFT_FLAGS): Add.
* Configurations/Sanitizers.xcconfig:
(WK_SANITIZER_OTHER_SWIFT_FLAGS): Add.
(WK_ADDRESS_SANITIZER_OTHER_CFLAGS_YES):
- Add `-mllvm -asan-guard-against-version-mismatch=0` flags.
(WK_ADDRESS_SANITIZER_OTHER_SWIFT_FLAGS_YES): Add.
- Add `-Xllvm -asan-guard-against-version-mismatch=0` flags.
</pre>
https://github.com/WebKit/WebKit/commit/7d72812ad4ae768d4f2f5691076bfbb186837601

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/54591 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/34010 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/7163 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/57872 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/5325 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/41549 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/5327 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/44212 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/3582 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/56686 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/32154 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/47283 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/25338 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/28951 "Passed tests") | | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/3465 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/50705 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/4829 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/59462 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/29824 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/4968 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/51636 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/30974 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/47369 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/51013 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/31952 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/30762 "Built successfully") | | |

### CODE REVIEW

**Comment by aproskuryakov** [comment]
What is the motivation for this? This seems very dangerous, and if I correctly understand what check is being disabled, it was always catching real misconfigurations.

**Comment by ddkilzer** [comment]
> What is the motivation for this? This seems very dangerous, and if I correctly understand what check is being disabled, it was always catching real misconfigurations.

Noted in radar.

**Review by aproskuryakov — CHANGES_REQUESTED** [review]
Thank you, marking as "request changed" to avoid any confusion while discussion is ongoing.

**Comment by ddkilzer** [comment]
This is no longer needed.

**Pull request closed without merging**
