### PR TITLE
Make narrowPrecisionToFloat() use clampTo<float>() instead of static_cast

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Make narrowPrecisionToFloat() use clampTo<float>() instead of static_cast

<a href="https://bugs.webkit.org/show_bug.cgi?id=245356">https://bugs.webkit.org/show_bug.cgi?id=245356</a>

Reviewed by NOBODY (OOPS!).

Merge - <a href="https://src.chromium.org/viewvc/blink?view=revision&revision=182563">https://src.chromium.org/viewvc/blink?view=revision&revision=182563</a>

For numbers within the range of valid floats, this has no effect.  For numbers outside that range, the old code was technically undefined behavior (and in practice would result in bad things like converting to infinity).  Now such numbers will be deterministically clamped to +/-FLOAT_MAX.

* Source/WebCore/platform/FloatConversion.h: Update "static_cast<float>" to 'clampTo<float>" & added "MathsExtra" header
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/font-variation-settings-interpolation-expected.txt: Updated Test Expectations

</pre>

https://github.com/WebKit/WebKit/commit/42978d3545f97515f3a87eb41d84e556232ffd2d

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/90120 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/34666 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/20736 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/99437 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/156938 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/94126 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/33158 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/28523 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/82451 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/94528 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95770 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/26367 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/76945 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/26259 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/81213 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/80996 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/69258 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/34321 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/15074 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/32162 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/16018 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/35906 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/38987 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/37809 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/35102 "Passed tests") | |

### CODE REVIEW

**Comment by nikolaszimmermann** [comment]
What about the svg/text/... testcase in Blink which motivated the fix? Would be good to have another dedicated test to verify the behavior.

**Comment by Ahmad-S792** [comment]
> What about the svg/text/... testcase in Blink which motivated the fix? Would be good to have another dedicated test to verify the behavior.

**Background** - this Blink patch is subsequent patch to the work done to [fix Microsoft Visual Compiler (MSVC) warnings in WTF](https://src.chromium.org/viewvc/blink?revision=183172&view=revision) in which it caused assert failures in following test case (svg/text/svg-zoom-large-value.xhtml), which we already have in Webkit LayoutTests folder.

Although, my intention to merge this is to be more future proof and avoid any pitfalls in case of any SVG Text Zoom or other bits and it does not have any dedicated test separately because the test which this one fixed is already available in Webkit LayoutTests folder and working fine.

**Comment by Ahmad-S792** [comment]
@nikolaszimmermann - Is it something good to go or should I close this? Thanks!

**Comment by nikolaszimmermann** [comment]
I would like to hear opinion from our code sheriffs - @darinadler would be a great candidate to comment on this.

**Review by darinadler — COMMENTED** [review]
It’s fine to change this, but I don’t like the tactical choice.

If we want to use `clampTo<float>` we should change the call sites, not change the meaning of this function. The reason we invented `narrowPrecisionToFloat` was to give a way to convert to float that would not warn and would not be type-unsafe, since `static_cast<float>` can be used on other types, not just `double`. It’s possible that we don’t need that, and it would be better to clamp. If so, I’d like to be explicit about the clamping. Unless perhaps we want a type-safe version of `clampTo<float>` that compiles only for `double` and gives a compiler error if you use it on other types. In that case I think a new function would be OK, but I would not name it the same thing.

**Comment by Ahmad-S792** [comment]
> It’s fine to change this, but I don’t like the tactical choice.
> 
> If we want to use `clampTo<float>` we should change the call sites, not change the meaning of this function. The reason we invented `narrowPrecisionToFloat` was to give a way to convert to float that would not warn and would not be type-unsafe, since `static_cast<float>` can be used on other types, not just `double`. It’s possible that we don’t need that, and it would be better to clamp. If so, I’d like to be explicit about the clamping. Unless perhaps we want a type-safe version of `clampTo<float>` that compiles only for `double` and gives a compiler error if you use it on other types. In that case I think a new function would be OK, but I would not name it the same thing.

Thanks @darinadler for your guidance and comment and it makes sense that we shouldn't change the main function behavior but leave it up to discretion of individuals to clampTo whenever they need. I will close this since it does not make sense to change main function. Thanks!

**Comment by darinadler** [comment]
We may want to accomplish the same thing by changing all the callers!

**Comment by Ahmad-S792** [comment]
> We may want to accomplish the same thing by changing all the callers!

ClampTo<> thing? - I can give it a go directory by directory, if you want like DOM, CSS etc.

**Comment by darinadler** [comment]
It looks like there are about 100 callers. We could do them in small batches. I agree that doing by directory makes the most sense. Might want to figure out which ones were really considered important and do them first.

**Pull request closed without merging**
