### PR TITLE
Much more aggressively remove duplicate layout test results

### PR DESCRIPTION
**Pull request by gsnedders**
#### 6533667eb99289893ebc466b6f0dfc97607604e0
<pre>
Much more aggressively remove duplicate layout test results
<a href="https://bugs.webkit.org/show_bug.cgi?id=273271">https://bugs.webkit.org/show_bug.cgi?id=273271</a>

Unreviewed test gardening.

This is based on some work-in-progress code to find the ideal location
for each expectation. This allows us to merge many duplicate
expectations, especially merging duplicates from gtk and wpe into glib,
along with getting rid of many redundant expectations that the existing
check-for-duplicated-platform-test-results doesn&apos;t manage to deal with.

* [Changelog omitted because it&apos;s many, many KBs]

Canonical link: <a href="https://commits.webkit.org/278225@main">https://commits.webkit.org/278225@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/b8188e62142ab183524c33436a59f09c25430bdb

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/49918 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/29206 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/2199 "Built successfully") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/53161 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/59/builds/595 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/35268 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/164 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/53161 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/52016 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/47/builds/26773 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/42949 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/5/builds/53161 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/24208 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/64/builds/175 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wpe-skia~~](https://ews-build.webkit.org/#/builders/52/builds/8288 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/46301 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/63/builds/221 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/2/builds/54742 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/25012 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/62/builds/157 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/2/builds/54742 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/26269 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/43140 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/2/builds/54742 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/27131 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/7195 "Built successfully and passed tests") | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/25999 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@gsnedders - AWESOME clean-up!!

**Comment by gsnedders** [comment]
I think the only bug here might be that everywhere where we moved expectations to generic ending up with… the expectation going missing. So let's try this again with that fixed.

**Comment by gsnedders** [comment]
OK, there's at least two problems remaining:

One is we're not coping with tests in `platform` whose names match those further up:

```
gsnedders@gsnedders-milk OS2 % find LayoutTests -name 'pip-support-enabled*'                                                
LayoutTests/platform/ipad/media/modern-media-controls/pip-support/pip-support-enabled.html
LayoutTests/platform/ipad/media/modern-media-controls/pip-support/pip-support-enabled-expected.txt
LayoutTests/media/modern-media-controls/pip-support/pip-support-enabled.html
LayoutTests/media/modern-media-controls/pip-support/pip-support-enabled-expected.txt
```

We conclude that `LayoutTests/platform/ipad/media/modern-media-controls/pip-support/pip-support-enabled-expected.txt` is redundant, which it isn't, because it's the only baseline for `LayoutTests/platform/ipad/media/modern-media-controls/pip-support/pip-support-enabled.html`.

(Once again, tests in `platform` bite us.)

The other is we seem to be removing too much when migrating things from gtk/wpe to glib:

```
470b45878194b8c77ff58246a1746ee071509167  LayoutTests/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
b7aafec49b0de6c0d9c9037387feb8fb5c49affb  LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/gtk/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/ios/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/mac-wk2/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/wpe/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
```

is turning into:

```
470b45878194b8c77ff58246a1746ee071509167  LayoutTests/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/ios/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
fef01e970638f22adde5d20cdec425b165a8ee83  LayoutTests/platform/mac/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/inferred-mrow-baseline-expected.txt
```

which means there's no glib-specific expectation.

(Ideally in this case we'd realise that we should just move the current generic expectation to `wincairo`!)

**Comment by gsnedders** [comment]
Landing via unsafe-merge-queue because otherwise this'll never land for conflicts being introduced.

**Pull request merged**
