### PR TITLE
[Site Isolation] Send events to the frame invoking `eventSender` functions

### PR DESCRIPTION
**Pull request by charliewolfe**
#### 9ea3854625bf3a7cda0c0326567ec5f7dd7fb015
<pre>
[Site Isolation] Send events to the frame invoking `eventSender` functions
<a href="https://bugs.webkit.org/show_bug.cgi?id=276924">https://bugs.webkit.org/show_bug.cgi?id=276924</a>
<a href="https://rdar.apple.com/132293403">rdar://132293403</a>

Reviewed by NOBODY (OOPS!).

When running layout tests with `—site-isolation`, many tests that use `eventSender` fail because iframe
contents may shift between the time the `eventSender` function is invoked and when the iframe process
receives the event. This happens because, with site isolation, input events need to be sent to the
mainframe first before they can be sent to a child frame, and the additional asynchronous IPC message
means that web content could change before the iframe receives the event.

This fixes the issue by always initially sending these events to the frame that invoked the function on
`eventSender`.

* LayoutTests/platform/mac-site-isolation/TestExpectations:
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::processNextQueuedMouseEvent):
(WebKit::WebPageProxy::targetFrameForEvents):
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/UIProcess/WebPageProxy.messages.in:
* Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleFrame.cpp:
(_WKBundleFrameTargetFrameForEvents):
* Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleFramePrivate.h:
* Source/WebKit/WebProcess/WebPage/WebFrame.cpp:
(WebKit::WebFrame::targetFrameForEvents const):
* Source/WebKit/WebProcess/WebPage/WebFrame.h:
* Tools/WebKitTestRunner/InjectedBundle/EventSendingController.cpp:
(WTR::EventSendingController::mouseDown):
(WTR::EventSendingController::mouseUp):
(WTR::EventSendingController::mouseMoveTo):
* Tools/WebKitTestRunner/InjectedBundle/EventSendingController.h:
</pre>
https://github.com/WebKit/WebKit/commit/9ea3854625bf3a7cda0c0326567ec5f7dd7fb015

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/59194 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/38537 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/11712 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/63151 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/9637 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/61323 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/46191 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/9866 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/48131 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/6873 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/61224 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/36031 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/51236 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/28953 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/32744 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/8497 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/8641 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/54701 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/8777 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/64868 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/3122 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/8717 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/55472 "") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/3133 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/51239 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/55563 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/2606 "Passed tests") | | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/34353 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/35436 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/36522 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/35181 "Built successfully") | | |

### CODE REVIEW

**Comment by aproskuryakov** [comment]
This feels quite dangerous, I feel like we have some tests for critical security issues that rely on events being sent to the frame with focus, not to the one that invokes the function.

**Comment by charliewolfe** [comment]
> This feels quite dangerous, I feel like we have some tests for critical security issues that rely on events being sent to the frame with focus, not to the one that invokes the function.

This doesn’t prevent other frames from receiving events; it just makes the frame using eventSender the first to receive the IPC message.

**Comment by aproskuryakov** [comment]
Of course, but the safe step would be to identify tests for even targeting, and check if they are still effective.

Also, if it doesn't matter which frame is the first to receive the event, why not start with the main frame consistently?

**Comment by charliewolfe** [comment]
> Also, if it doesn't matter which frame is the first to receive the event, why not start with the main frame consistently?

Because if an isolated iframe uses eventSender, there first needs to be an additional asynchronous message to the main frame process, so the iframe’s content could have changed since the event was sent.

**Comment by aproskuryakov** [comment]
Right, this is exactly the kind of thing that used to cause real security bugs.

**Comment by charliewolfe** [comment]
> Right, this is exactly the kind of thing that used to cause real security bugs.

Ok. I'm not sure I completely understand the security worry. If we don't do something like this, these tests will be broken in this testing mode anyways.

**Comment by charliewolfe** [comment]
I'll try something else to fix these tests.

**Comment by aproskuryakov** [comment]
As discussed in person, I didn't intend to block this change, but suggested some due diligence.

**Pull request closed without merging**
