### PR TITLE
[ews] Mirror GitHub Status-bubbles in PR description

### PR DESCRIPTION
**Pull request by aj062**
#### 64bae1121de61b427f105cc5abf9323b79dbca3b
<pre>
[ews] Mirror GitHub Status-bubbles in PR description
<a href="https://bugs.webkit.org/show_bug.cgi?id=243951">https://bugs.webkit.org/show_bug.cgi?id=243951</a>

Reviewed by Jonathan Bedard.

* Tools/CISupport/ews-app/ews/common/github.py:
(GitHub.update_or_leave_comment_on_pr):
(GitHub.update_pr_description_with_status_bubble):
(GitHubEWS):
(GitHubEWS.generate_updated_pr_description):
(GitHubEWS.add_or_update_comment_for_change_id):

Canonical link: <a href="https://commits.webkit.org/253442@main">https://commits.webkit.org/253442@main</a>
</pre>

### CODE REVIEW

**Comment by JonWBedard** [comment]
If we do this in the PR description instead of the comment, updating the PR description will overwrite it, is that what we want? Previous discussions had described this approach as being a comment (also, as we discovered a few weeks ago, there is a limit on PR description that is low enough a contributor hit it with a legitimate commit message...it was a WPT import, I think, so an abnormally large commit message, but still worth calling out)

**Comment by aj062** [comment]
> If we do this in the PR description instead of the comment, updating the PR description will overwrite it, is that what we want? Previous discussions had described this approach as being a comment (also, as we discovered a few weeks ago, there is a limit on PR description that is low enough a contributor hit it with a legitimate commit message...it was a WPT import, I think, so an abnormally large commit message, but still worth calling out)

Yeah, this PR ensures that we don't overwrite the description, instead it just appends the status-bubble, and if status-bubbles are already present, it replaces them. If we hit the character limit issue, we can fix it as needed.

Tested it in https://github.com/WebKit/WebKit/pull/933

**Comment by JonWBedard** [comment]
> > ...
> 
> Yeah, this PR ensures that we don't overwrite the description, instead it just appends the status-bubble, and if status-bubbles are already present, it replaces them. If we hit the character limit issue, we can fix it as needed.
> 
> Tested it in #933

Oh, right, it's just a mirror. In the example, I see that the hash in the description is different than the hash of the `HEAD` commit. That would seem to be impossible in production, right?

**Comment by aj062** [comment]
> Oh, right, it's just a mirror. In the example, I see that the hash in the description is different than the hash of the `HEAD` commit. That would seem to be impossible in production, right?

That's right. That PR is currently being used for all sort of testing.

**Review by JonWBedard — APPROVED** [review]
Worth noting that `git-webkit pr` and landing will clobber this, although it's a mirror, so probably not a huge problem.

**Pull request merged**
