### PR TITLE
[GStreamer] Video encoder caps reported as leaked

### PR DESCRIPTION
**Pull request by philn**
#### 5a8358f7d8ad2e226e6b09f4fa16373e5f35d81f
<pre>
[GStreamer] Video encoder caps reported as leaked
<a href="https://bugs.webkit.org/show_bug.cgi?id=256907">https://bugs.webkit.org/show_bug.cgi?id=256907</a>

Reviewed by Xabier Rodriguez-Calvar.

Flag the EncoderDefinition caps fields as MAY_BE_LEAKED, so that they can be ignored by the
GStreamer leak tracer. Those caps are static for the whole WebProcess lifetime.

* Source/WebCore/platform/gstreamer/VideoEncoderPrivateGStreamer.cpp:
(Encoders::registerEncoder):

Canonical link: <a href="https://commits.webkit.org/264249@main">https://commits.webkit.org/264249@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/2e413895186e5377bd304eb31840bf4acf1f9e31

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/7007 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/7248 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/7428 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/8620 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/7241 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/7016 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/8510 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/7182 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/10152 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/7133 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/7803 "2 new passes 2 flakes 1 failures") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/6465 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/8723 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/5170 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/6373 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/14148 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/6838 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/6467 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/9318 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/6943 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/5689 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/6311 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/1693 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/10505 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/6693 "Built successfully") | | |

### CODE REVIEW

**Review by calvaris — COMMENTED** [review]
Should't the singleton still have a destructor to be able to unref everything that is needed?

**Comment by philn** [comment]
http://sprunge.us/aPZu1i is what i tried but it seems the leak tracer gathers its infos before the map is cleared.

**Review by calvaris — APPROVED** [review]
Excellent solution. Just add a comment about why you're adding that flag and land.

**Comment by philn** [comment]
> Excellent solution. Just add a comment about why you're adding that flag and land.

The commit message is not sufficient?

**Comment by calvaris** [comment]
> > Excellent solution. Just add a comment about why you're adding that flag and land.
> 
> The commit message is not sufficient?

Sufficient, yes, better, IMHO no.

**Pull request merged**
