### PR TITLE
Replace makeprop.pl with a more structured parser/code generator

### PR DESCRIPTION
**Pull request by weinig**
#### 9047d68a603f31c0aadda6b7e42f3d9fff946006
<pre>
Replace makeprop.pl with a more structured parser/code generator
<a href="https://bugs.webkit.org/show_bug.cgi?id=247470">https://bugs.webkit.org/show_bug.cgi?id=247470</a>
rdar://101940205

Reviewed by Darin Adler.

Replaces makeprop.pl with new script, process-css-properties.py, written
in python rather than perl to make it a bit more friendly to approach for
more people.

* Source/WebCore/CMakeLists.txt:
* Source/WebCore/DerivedSources-input.xcfilelist:
* Source/WebCore/DerivedSources.make:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/css/makeprop.pl: Removed.
* Source/WebCore/css/process-css-properties.py: Added.
Replace makeprop.pl with process-css-properties.py

* Source/WebCore/css/CSSProperties.json:
process-css-properties.py is a bit more strict than makeprop.pl was, and
requires all declared longhands for a property to actually exist in an
enabled form. The flipside is that process-css-properties.py supports
conditionally excluded longhands like done with other parts of the format.

Canonical link: <a href="https://commits.webkit.org/256414@main">https://commits.webkit.org/256414@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/95b33895da0c6d95bf5b01be724d3b41d137e28f

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/95627 "3 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/4888 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/28674 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/105205 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/165499 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/99612 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/4947 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/33641 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/87999 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/101054 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/101288 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/3626 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/82243 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/30686 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/85497 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/87404 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/73522 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/39377 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/18953 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/37076 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/20260 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4436 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/41072 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/42911 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/43060 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/39509 "Passed tests") | |

### CODE REVIEW

**Review by darinadler — COMMENTED** [review]
Sure looks great.

One other thing I’d like to do is to not generate code we don’t have to. Currently, I think there is too much generated, with long stretches of handwritten code written out by script alongside generated tables. We had to generate more when C++ wasn’t as capable at compile time.

This might involve splitting headers.

Another thing I don’t like is directly generating bodies for function members of classes defined in other header files, specifically CSSProperty. We should reduce that to the minimum necessary for a good practical solution.

**Comment by weinig** [comment]
I completely agree with all of those...but, for the sake of my sanity, I am going to try to do a pretty close to character-for-character reproduction first, just to make sure I don't regress anything and then I start the dissection.

For the first generated file, I tried to break things up a bit, so most of the function have either their own function or in a few cases, I was able to template out a function to be shared. I don't super love where it is, but it's in the right direction.

**Comment by weinig** [comment]
All the files are generating now. Next step is to do a diff between the old and the new.

**Comment by aproskuryakov** [comment]
Is this expected to have impact (good or bad) on build performance? 

Also, incremental build correctness is a problem with any script phases, so moving in a direction where that's less of an issue would be welcome. Not sure if this PR will be changing anything in how the generator in integrated with build system.

**Comment by weinig** [comment]
> Is this expected to have impact (good or bad) on build performance?
> 
> Also, incremental build correctness is a problem with any script phases, so moving in a direction where that's less of an issue would be welcome. Not sure if this PR will be changing anything in how the generator in integrated with build system.

I don't expect this change to have any measurable effect (good or bad) on build performance. Trying to do a pretty 1-to-1 port as an initial step, so the only real difference will the language the generator is written in (the DerivedSources.make part is just changing which script is called and changing it to use a python executable rather than the perl one).

To be safe, I will measure the performance of the two scripts to ensure there has not be a regression there. 

(As for incremental build performance outside of this change, once thing I have been meaning to try is moving a generator like this one off of DerivedSources.make and plugging it directly into its own build phase with fixed input and outputs specified, to see if Xcode can schedule the generation concurrently.)

**Comment by weinig** [comment]
Assuming https://github.com/WebKit/WebKit/pull/6189 is merged, the final diff between the old and the new is pretty small:

https://bugs.webkit.org/attachment.cgi?id=463441&action=prettypatch

Just some inconsequential whitespace improvements, changing the name of the script in the comment at the head of each file, some style improvements in CSSPropertySettings functions, the removal of an an unneeded semicolon, and some sort changes to the `areInSameLogicalPropertyGroupWithDifferentMappingLogic` function, which don't change any behavior but are now alphabetical.

**Comment by weinig** [comment]
Oh, I am not in love with "process-css-properties.py" as a name, so if there are any suggestions, I will gladly take them.

**Comment by darinadler** [comment]
I have only worse names like `generate-css-properties-code.py`

**Comment by darinadler** [comment]
Yes, looks great. Not sure why builds are failing.

**Comment by weinig** [comment]
> Yes, looks great. Not sure why builds are failing.

Seems some of the bots have different versions of python on them and don't have functools.cache. Didn't know when I was writing it, bit that is new in version 3.9. (I don't know what our minimum version of python supported is).

Seems that `@lru_cache(maxsize=None)` is an equivalent so I will get that go.

**Comment by weinig** [comment]
Actually, I can just do it manually in almost the same space.

**Comment by weinig** [comment]
Ok, looks like things are building now, phew.

**Review by darinadler — APPROVED** [review]

**Pull request merged**
