### PR TITLE
[Buildstream SDK] Update to FDO 23.08 release

### PR DESCRIPTION
**Pull request by philn**
#### 60f1940c69fed978c05c98fd4a2b522bd8c59f3a
<pre>
[Buildstream SDK] Update to FDO 23.08 release
<a href="https://bugs.webkit.org/show_bug.cgi?id=262879">https://bugs.webkit.org/show_bug.cgi?id=262879</a>

Reviewed by Carlos Alberto Lopez Perez and Carlos Garcia Campos.

This new SDK version notably ships:

- ICU 73.2
- GCC 13.2.0
- clang 16.0.6
- sccache 0.7.1
- Mesa 23.1.8
- Cairo 1.18.0
- Ruby 3.2.2
- Python 3.11.5

The SDK build infrastructure was migrated from Pipenv to a Podman container shipping BuildStream2.
This new approach should make the build easier to setup.

The ccls recipe was removed, clangd is now preferred. The GStreamer kate plugin was removed,
upstream has also removed it and it won&apos;t ship in GStreamer 1.24.

This patch updates only the build recipes. The updated SDK will be deployed on the bots later on.

* .gitignore:
* Tools/Scripts/bst-wrapper:
(run):
(ensure_environment):
(main):
(run_pipenv): Deleted.
(run_bst): Deleted.
* Tools/Scripts/webkit-flatpak-sdk:
(run_wrapper):
* Tools/buildstream/Makefile:
* Tools/buildstream/Pipfile: Removed.
* Tools/buildstream/Pipfile.lock: Removed.
* Tools/buildstream/README.md:
* Tools/buildstream/elements/flatpak-platform-extensions-extra.bst:
* Tools/buildstream/elements/flatpak-platform-extensions.bst:
* Tools/buildstream/elements/flatpak-runtimes.bst:
* Tools/buildstream/elements/freedesktop-sdk.bst:
* Tools/buildstream/elements/plugins/bst-plugins-experimental.bst: Added.
* Tools/buildstream/elements/plugins/buildstream-plugins.bst: Added.
* Tools/buildstream/elements/qt5/qtbase.bst:
* Tools/buildstream/elements/qt5/qtdeclarative.bst:
* Tools/buildstream/elements/qt5/qtquickcontrols.bst:
* Tools/buildstream/elements/qt5/qtquickcontrols2.bst:
* Tools/buildstream/elements/qt5/qtwayland.bst:
* Tools/buildstream/elements/qt5/qtx11extras.bst:
* Tools/buildstream/elements/sdk-build-depends/rapidjson.bst: Removed.
* Tools/buildstream/elements/sdk-build-depends/scons.bst:
* Tools/buildstream/elements/sdk-platform.bst:
* Tools/buildstream/elements/sdk.bst:
* Tools/buildstream/elements/sdk/apitrace.bst:
* Tools/buildstream/elements/sdk/breakpad.bst:
* Tools/buildstream/elements/sdk/capnp.bst:
* Tools/buildstream/elements/sdk/cargo-c.bst:
* Tools/buildstream/elements/sdk/ccls.bst: Removed.
* Tools/buildstream/elements/sdk/clangd.bst:
* Tools/buildstream/elements/sdk/eigen.bst:
* Tools/buildstream/elements/sdk/flite.bst:
* Tools/buildstream/elements/sdk/gi-docgen.bst:
* Tools/buildstream/elements/sdk/gst-plugin-closedcaption.bst:
* Tools/buildstream/elements/sdk/gst-plugin-dav1d.bst:
* Tools/buildstream/elements/sdk/gst-plugin-rtp.bst:
* Tools/buildstream/elements/sdk/gtk+-3.bst:
* Tools/buildstream/elements/sdk/gtk.bst:
* Tools/buildstream/elements/sdk/icecc.bst:
* Tools/buildstream/elements/sdk/libavif.bst:
* Tools/buildstream/elements/sdk/libbacktrace.bst:
* Tools/buildstream/elements/sdk/libevent.bst:
* Tools/buildstream/elements/sdk/libjxl.bst:
* Tools/buildstream/elements/sdk/libmanette.bst:
* Tools/buildstream/elements/sdk/libusrsctp.bst:
* Tools/buildstream/elements/sdk/libwpe.bst:
* Tools/buildstream/elements/sdk/mold.bst:
* Tools/buildstream/elements/sdk/monado.bst:
* Tools/buildstream/elements/sdk/openxr.bst:
* Tools/buildstream/elements/sdk/patchelf.bst:
* Tools/buildstream/elements/sdk/psmisc.bst:
* Tools/buildstream/elements/sdk/python3-smartypants.bst:
* Tools/buildstream/elements/sdk/rr.bst:
* Tools/buildstream/elements/sdk/sccache.bst:
* Tools/buildstream/elements/sdk/sparkle-cdm.bst:
* Tools/buildstream/elements/sdk/svt-av1.bst:
* Tools/buildstream/elements/sdk/tbb.bst:
* Tools/buildstream/elements/sdk/wpebackend-fdo.bst:
* Tools/buildstream/elements/sdk/xdg-dbus-proxy.bst:
* Tools/buildstream/elements/test-infra.bst:
* Tools/buildstream/elements/test-infra/apr.bst:
* Tools/buildstream/elements/test-infra/httpd.bst:
* Tools/buildstream/elements/test-infra/perl-digest-crc-pm.bst: Added.
* Tools/buildstream/elements/test-infra/webkitgtk-test-dicts.bst:
* Tools/buildstream/patches/fdo-0001-gst-plugins-bad-Add-support-Kate.patch: Removed.
* Tools/buildstream/patches/fdo-0001-mesa-Bump-to-23.1.5.patch: Removed.
* Tools/buildstream/patches/fdo-0001-pipewire-base-Disable-AEC-module.patch: Removed.
* Tools/buildstream/patches/fdo-0002-ffmpeg-Support-more-codecs.patch:
* Tools/buildstream/patches/fdo-0003-gst-plugins-bad-Support-for-updated-webrtc-audio-pro.patch: Removed.
* Tools/buildstream/patches/fdo-0004-gst-plugins-ugly-Enable-x264-encoder.patch:
* Tools/buildstream/patches/fdo-0005-GStreamer-Bump-to-1.22.6.patch:
* Tools/buildstream/patches/fdo-0006-gst-plugins-bad-Enable-soundtouch.patch:
* Tools/buildstream/patches/fdo-0007-components-Bump-GLib-to-version-2.76.patch: Removed.
* Tools/buildstream/patches/fdo-0008-components-Bump-g-i-to-version-1.76.patch: Removed.
* Tools/buildstream/patches/fdo-0009-gst-plugins-bad-Enable-x265-encoder.patch:
* Tools/buildstream/patches/flite-fix-voice-list-build.patch: Added.
* Tools/buildstream/patches/rapidjson-0001-Fix-build-warnings-emitted-by-GCC-10-on-Aarch64.patch: Removed.
* Tools/buildstream/patches/tbb-Retry-if-pthread_create-fails-with-EAGAIN.patch: Removed.
* Tools/buildstream/project.conf:

Canonical link: <a href="https://commits.webkit.org/270440@main">https://commits.webkit.org/270440@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/dbb8247868bfc31464978e014faa57e9c342533f

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/25221 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/3762 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/26477 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/27335 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/23144 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/25490 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/5503 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/1198 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/23372 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/25464 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/2808 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/21766 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/27914 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/2493 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/22706 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/28827 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/21936 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/23042 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/23054 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/26656 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/24458 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/2421 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/710 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/31883 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/3771 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/6976 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/6116 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/2860 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/2755 "Built successfully") | | |

### CODE REVIEW

**Comment by philn** [comment]
This is ready for review i think. One issue though the default font in GTK MiniBrowser looks... a bit weird... Testing requires this PR: https://github.com/WebKit/WebKit/pull/19996

**Comment by philn** [comment]
@aperezdc i took the liberty to import your changes from https://github.com/WebKit/WebKit/pull/19942 here. I hope that's ok!

**Comment by philn** [comment]
> This is ready for review i think. One issue though the default font in GTK MiniBrowser looks... a bit weird...

Fixed by including `freedesktop-sdk.bst:components/fontconfig-flatpak-config.bst` in runtime...

**Comment by aperezdc** [comment]
> @aperezdc i took the liberty to import your changes from #19942 here. I hope that's ok!

That's fine, thanks!

**Review by carlosgcampos — APPROVED** [review]

**Review by clopez — APPROVED** [review]
We have to keep an eye on the bots once the new SDK is uploaded and the bots start to test with it.

Have you already  a gardening patch ready to update the baselines for the new SDK?

**Comment by philn** [comment]
This patch updates only the build recipes. The updated SDK will be deployed on the bots later on.

See https://github.com/WebKit/WebKit/pull/19996

**Pull request merged**
