### PR TITLE
Update ANGLE to 2023-04-04 (3aea3cfd1a02ecae97fa550940178c9232b748e4)

### PR DESCRIPTION
**Pull request by kkinnunen-apple**
#### 8677d5e59890f5d91e14ed8167c992d210a77a9b
<pre>
Update ANGLE to 2023-04-04 (3aea3cfd1a02ecae97fa550940178c9232b748e4)
<a href="https://bugs.webkit.org/show_bug.cgi?id=254975">https://bugs.webkit.org/show_bug.cgi?id=254975</a>
rdar://problem/107598751

Unreviewed, to be reviewed by Dean Jackson.

Contains upstream commits:
git log --oneline 5fcd027edec5ae756c4484a7d6e32f8aad147984..3aea3cfd1a02ecae97fa550940178c9232b748e4 --pretty=%h %s
3aea3cfd1 Vulkan: Workaround depth bias constant factor on ANV
c723d71fc Trace Interpreter: Improve StringToGLenum performance.
96cda1ac0 Vulkan: Switch to modified framebuffer should trigger submit
c5e9de232 Revert &quot;Vulkan: Use midRenderPass clear if RP has started but inactive&quot;
f1f80e1e3 Metal: Always prefer staged GPU uploads for textures.
ec307af4a Fix bug in DeallocateGlobalMutex().
a1319e7fe Tests: Fix EGLContextSharingTestNoFixture.SwapBuffersShared.
d57a322ea Roll vulkan-deps from bb601a935e1d to e671d7c87d3b (14 revisions)
52286481d Roll SwiftShader from c85d70d97009 to 3ecab9c1aa60 (1 revision)
f4af659fa Roll Chromium from 1393a98c62ae to 198e6d1c360e (603 revisions)
b24b5568e Vulkan: Skip sample coverage for single sample rendering
55fbc2c50 Revert &quot;Tests: Add Gacha Life trace&quot;
61cd24d46 MTLPixelFormatRGB9E5Float is not renderable on simulator.
f176027fc CGL: implement EGL_ANGLE_wait_until_work_scheduled
552d4271e Vulkan: Refactor buffer init logic
98deaef0e Tests: Add Gacha Life trace
e975f9dc4 Capture/Replay: handle paletted textures
336bfd60d GL: Fix the RewriteRepeatedAssignToSwizzled workaround
e9f57b073 Roll VK-GL-CTS from e873c6862868 to a3d054bf72ab (4 revisions)
f066ae7de Tests: Add Teslagrad trace
6458cd95b [GL backend] Remove over-zealous ASSERT in StateManagerGL.cpp
090c6fad9 Roll vulkan-deps from e13e8828cf66 to bb601a935e1d (9 revisions)
a3a649b02 Skip BlitFramebufferTest.scissorDrawBlitAndDrawAgain on Mac AMD GL
c3c41889f Roll Chromium from f7c2a70f23b1 to 1393a98c62ae (1678 revisions)
</pre>
https://github.com/WebKit/WebKit/commit/8677d5e59890f5d91e14ed8167c992d210a77a9b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/1914 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/1945 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/2007 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/2840 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/2001 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/2020 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/1990 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/1769 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/1933 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/1722 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/1714 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/2685 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/1713 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/1698 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/1613 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/1757 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/1745 "11 flakes 5 failures") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/2849 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/1770 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/1575 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/1696 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/1709 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/1861 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by djg — APPROVED** [review]
:shipit:

**Comment by kkinnunen-apple** [comment]
No, need to understand the regression.

**Review by djg — CHANGES_REQUESTED** [review]
Need to diagnose regression of RGB9E5

**Comment by kkinnunen-apple** [comment]
superseded

**Pull request closed without merging**
