### PR TITLE
Add WebGLSampler objects validation

### PR DESCRIPTION
**Pull request by lexaknyazev**
#### 99093a3a17ba338e7b98191b18a30552dd22fa6d
<pre>
Add WebGLSampler objects validation
<a href="https://bugs.webkit.org/show_bug.cgi?id=242580">https://bugs.webkit.org/show_bug.cgi?id=242580</a>

Reviewed by Kenneth Russell.

* Simplified deleteSampler flow.
* Added required validation to bindSampler,
samplerParameteri, samplerParameterf, and
getSamplerParameter.

Fixes forthcoming strengthened conformance test in
<a href="https://github.com/KhronosGroup/WebGL/pull/3459">https://github.com/KhronosGroup/WebGL/pull/3459</a>

Drive-by:
* Added context pending check to drawBuffers.

* Source/WebCore/html/canvas/WebGL2RenderingContext.cpp:
(WebCore::WebGL2RenderingContext::drawBuffers):
(WebCore::WebGL2RenderingContext::deleteSampler):
(WebCore::WebGL2RenderingContext::bindSampler):
(WebCore::WebGL2RenderingContext::samplerParameteri):
(WebCore::WebGL2RenderingContext::samplerParameterf):
(WebCore::WebGL2RenderingContext::getSamplerParameter):

Canonical link: <a href="https://commits.webkit.org/252555@main">https://commits.webkit.org/252555@main</a>
</pre>

### CODE REVIEW

**Review by kenrussell — COMMENTED** [review]
Looks good but one question - does this fix any WebGL 2.0 conformance tests? If so, can they be explicitly enabled under the already-integrated webgl/2.0.y/ copy?

**Comment by lexaknyazev** [comment]
> Looks good but one question - does this fix any WebGL 2.0 conformance tests?

https://github.com/KhronosGroup/WebGL/pull/3459

**Comment by kenrussell** [comment]
> > Looks good but one question - does this fix any WebGL 2.0 conformance tests?
> 
> [KhronosGroup/WebGL#3459](https://github.com/KhronosGroup/WebGL/pull/3459)

Please mention in the PR description that this fixes a forthcoming WebGL test in https://github.com/KhronosGroup/WebGL/pull/3459 .

**Review by kenrussell — APPROVED** [review]
Looks good to me. Please mention the KhronosGroup/WebGL PR strengthening the test in this PR's description.

**Comment by kenrussell** [comment]
The EWS test failures are unrelated to this PR. Attempting merge-queue.

**Pull request merged**
