### PR TITLE
Expose WebKitWebView from WPEQtView

### PR DESCRIPTION
**Pull request by tusooa**
CCBUG: https://bugs.webkit.org/show_bug.cgi?id=236746

### CODE REVIEW

**Comment by JonWBedard** [comment]
The WebKit project is in a bit of a transition period at the moment, not all workflows have been moved to GitHub. We are far enough that pull-requests are functional, though. We ask that you format your commit message per the project guidelines, running `Tools/Scripts/git-webkit setup` on your repository and then `Tools/Scripts/git-webkit pr` to upload your patch should format your change correctly.

Alternatively, using `Tools/Scripts/prepare-ChangeLog`, making the appropriate edits in `Source/WebKit/ChangeLog` and then running `Tools/Scripts/webkit-patch upload` will upload your change to https://bugs.webkit.org/show_bug.cgi?id=236746.

I've also CCed some folks qualified to review WPE changes.

**Comment by JonWBedard** [comment]
The WebKit project is in a bit of a transition period at the moment, not all workflows have been moved to GitHub. We are far enough that pull-requests are functional, though. We ask that you format your commit message per the project guidelines, running `Tools/Scripts/git-webkit setup` on your repository and then `Tools/Scripts/git-webkit pr` to upload your patch should format your change correctly.

Alternatively, using `Tools/Scripts/prepare-ChangeLog`, making the appropriate edits in `Source/WebKit/ChangeLog` and then running `Tools/Scripts/webkit-patch upload` will upload your change to https://bugs.webkit.org/show_bug.cgi?id=236746.

I've also CCed some folks qualified to review WPE changes.

**Comment by tusooa** [comment]
> 

Hi, I got the following when running the command you mentioned:

```
] Tools/Scripts/git-webkit pr
'tusooa/expose-webview' is not a pull request branch, enter name of new branch (or bug URL): https://bugs.webkit.org/show_bug.cgi?id=236746
ERROR:dbus.connection:Unable to set arguments (dbus.Int32(262639689), 'https://bugs.webkit.org', None, 'Tools/Scripts/git-webkit') according to signature 'isss': <class 'TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "/home/tusooa/Code/WebKit/Tools/Scripts/git-webkit", line 69, in <module>
    sys.exit(program.main(
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py", line 134, in main
    return parsed.main(
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/pull_request.py", line 139, in main
    if Branch.main(args, repository, why="'{}' is not a pull request branch".format(repository.branch), **kwargs):
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py", line 98, in main
    if issue and issue.title:
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/issue.py", line 84, in title
    self.tracker.populate(self, 'title')
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 150, in populate
    response = requests.get('{}/rest/bug/{}{}'.format(self.url, issue.id, self._login_arguments(required=False)))
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 129, in _login_arguments
    username, password = self.credentials(required=required)
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 121, in credentials
    return webkitcorepy.credentials(
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitcorepy/webkitcorepy/credentials.py", line 78, in credentials
    key = keyring.get_password(url, username)
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/chainer.py", line 51, in get_password
    password = keyring.get_password(service, username)
  File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/kwallet.py", line 113, in get_password
    if not self.iface.hasEntry(self.handle, service, username, self.appid):
  File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
```

Anything I can do here?

**Comment by JonWBedard** [comment]
> Hi, I got the following when running the command you mentioned:
> 
> ```
> ] Tools/Scripts/git-webkit pr
> 'tusooa/expose-webview' is not a pull request branch, enter name of new branch (or bug URL): https://bugs.webkit.org/show_bug.cgi?id=236746
> ERROR:dbus.connection:Unable to set arguments (dbus.Int32(262639689), 'https://bugs.webkit.org', None, 'Tools/Scripts/git-webkit') according to signature 'isss': <class 'TypeError'>: Expected a string or unicode object
> Traceback (most recent call last):
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/git-webkit", line 69, in <module>
>     sys.exit(program.main(
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py", line 134, in main
>     return parsed.main(
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/pull_request.py", line 139, in main
>     if Branch.main(args, repository, why="'{}' is not a pull request branch".format(repository.branch), **kwargs):
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py", line 98, in main
>     if issue and issue.title:
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/issue.py", line 84, in title
>     self.tracker.populate(self, 'title')
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 150, in populate
>     response = requests.get('{}/rest/bug/{}{}'.format(self.url, issue.id, self._login_arguments(required=False)))
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 129, in _login_arguments
>     username, password = self.credentials(required=required)
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 121, in credentials
>     return webkitcorepy.credentials(
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitcorepy/webkitcorepy/credentials.py", line 78, in credentials
>     key = keyring.get_password(url, username)
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/core.py", line 55, in get_password
>     return get_keyring().get_password(service_name, username)
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/chainer.py", line 51, in get_password
>     password = keyring.get_password(service, username)
>   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/kwallet.py", line 113, in get_password
>     if not self.iface.hasEntry(self.handle, service, username, self.appid):
>   File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
>     return self._connection.call_blocking(self._named_service,
>   File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 643, in call_blocking
>     message.append(signature=signature, *args)
> TypeError: Expected a string or unicode object
> ```
> 
> Anything I can do here?

That would be a bug in git-webkit pr, https://commits.webkit.org/248390@main should have fixed it. Rebasing your PR on main (`git-webkit pull` should do it for you) will get the update.

**Comment by tusooa** [comment]
> > Hi, I got the following when running the command you mentioned:
> > ```
> > ] Tools/Scripts/git-webkit pr
> > 'tusooa/expose-webview' is not a pull request branch, enter name of new branch (or bug URL): https://bugs.webkit.org/show_bug.cgi?id=236746
> > ERROR:dbus.connection:Unable to set arguments (dbus.Int32(262639689), 'https://bugs.webkit.org', None, 'Tools/Scripts/git-webkit') according to signature 'isss': <class 'TypeError'>: Expected a string or unicode object
> > Traceback (most recent call last):
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/git-webkit", line 69, in <module>
> >     sys.exit(program.main(
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py", line 134, in main
> >     return parsed.main(
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/pull_request.py", line 139, in main
> >     if Branch.main(args, repository, why="'{}' is not a pull request branch".format(repository.branch), **kwargs):
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py", line 98, in main
> >     if issue and issue.title:
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/issue.py", line 84, in title
> >     self.tracker.populate(self, 'title')
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 150, in populate
> >     response = requests.get('{}/rest/bug/{}{}'.format(self.url, issue.id, self._login_arguments(required=False)))
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 129, in _login_arguments
> >     username, password = self.credentials(required=required)
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitbugspy/webkitbugspy/bugzilla.py", line 121, in credentials
> >     return webkitcorepy.credentials(
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/webkitcorepy/webkitcorepy/credentials.py", line 78, in credentials
> >     key = keyring.get_password(url, username)
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/core.py", line 55, in get_password
> >     return get_keyring().get_password(service_name, username)
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/chainer.py", line 51, in get_password
> >     password = keyring.get_password(service, username)
> >   File "/home/tusooa/Code/WebKit/Tools/Scripts/libraries/autoinstalled/python-3-x86_64/keyring/backends/kwallet.py", line 113, in get_password
> >     if not self.iface.hasEntry(self.handle, service, username, self.appid):
> >   File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
> >     return self._connection.call_blocking(self._named_service,
> >   File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 643, in call_blocking
> >     message.append(signature=signature, *args)
> > TypeError: Expected a string or unicode object
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Anything I can do here?
> 
> That would be a bug in git-webkit pr, https://commits.webkit.org/248390@main should have fixed it. Rebasing your PR on main (`git-webkit pull` should do it for you) will get the update.

I gave up on git-webkit, as I cannot get it work. I uploaded a patch to bugzilla instead.

**Comment by JonWBedard** [comment]
Closing this PR since it is being handled on bugzilla via the patch review system.

**Pull request closed without merging**
