### PR TITLE
Add Moe Bazzi to contributors.json

### PR DESCRIPTION
**Pull request by MoeBazziGIT**
#### f2273e6fcbdafe21755a87502d632fda572c85ab
<pre>
Add Moe Bazzi to contributors.json

Unreviewed contributor addition.

* metadata/contributors.json:

Canonical link: <a href="https://commits.webkit.org/269600@main">https://commits.webkit.org/269600@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/489dd1b68f45c517459a7d32d32e43c2d70e6c33

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/23016 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/1095 "Built successfully") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/14/builds/24130 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/24931 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/21292 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/2328 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/16/builds/23557 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/22163 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/23258 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/49/builds/2328 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/14/builds/24130 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/25785 "Built successfully") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/23203 "Passed tests") | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/49/builds/2328 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/14/builds/24130 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/27024 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/49/builds/2328 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/14/builds/24130 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/24886 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/529 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/16/builds/23557 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/454 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/14/builds/24130 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/937 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/2921 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/722 "Built successfully") | | |

### CODE REVIEW

**Comment by JonWBedard** [comment]
You'll need to say something about review in this commit. If you have `Reviewed by NOBODY (OOPS!).`, then infrastructure will automagically insert your reviewer. Or (for this case), you could put something like `Unreviewed contributor addition.`

**Comment by MoeBazziGIT** [comment]
> You'll need to say something about review in this commit. If you have `Reviewed by NOBODY (OOPS!).`, then infrastructure will automagically insert your reviewer. Or (for this case), you could put something like `Unreviewed contributor addition.`

Hey @JonWBedard, afaik `Reviewed by NOBODY (OOPS!).` is not included in the commit message, do I still need to add `Unreviewed contributor addition.`?

**Comment by JonWBedard** [comment]
> > You'll need to say something about review in this commit. If you have `Reviewed by NOBODY (OOPS!).`, then infrastructure will automagically insert your reviewer. Or (for this case), you could put something like `Unreviewed contributor addition.`
> 
> Hey @JonWBedard, afaik `Reviewed by NOBODY (OOPS!).` is not included in the commit message, do I still need to add `Unreviewed contributor addition.`?

You need to say something about the review. Basically, if a commit message doesn't have `Reviewed by ...` or `Unreviewed.+`  in it, `Merge-Queue` will reject it.

**Comment by MoeBazziGIT** [comment]
> > > You'll need to say something about review in this commit. If you have `Reviewed by NOBODY (OOPS!).`, then infrastructure will automagically insert your reviewer. Or (for this case), you could put something like `Unreviewed contributor addition.`
> > 
> > 
> > Hey @JonWBedard, afaik `Reviewed by NOBODY (OOPS!).` is not included in the commit message, do I still need to add `Unreviewed contributor addition.`?
> 
> You need to say something about the review. Basically, if a commit message doesn't have `Reviewed by ...` or `Unreviewed.+` in it, `Merge-Queue` will reject it.

this makes sense, thanks!

**Comment by MoeBazziGIT** [comment]
@JonWBedard done ✅

**Pull request merged**
