### PR TITLE
WebCore::Cursor::Type should be an enum class

### PR DESCRIPTION
**Pull request by aprotyas**
#### a7d211b90cd35048285c77d129432799d915be4a
<pre>
WebCore::Cursor::Type should be an enum class
<a href="https://bugs.webkit.org/show_bug.cgi?id=264899">https://bugs.webkit.org/show_bug.cgi?id=264899</a>
<a href="https://rdar.apple.com/118477108">rdar://118477108</a>

Reviewed by Aditya Keerthi.

This is a mechanical patch that makes `WebCore::Cursor::Type` an enum
class. There are only two interesting bits:

1. We remove the need for a sentinel `static_cast&lt;-1&gt;` to mark an
   invalid cursor value, which is possibly undefined behavior, and
   instead just introduce an `Invalid` enumeration case that
   `Cursor.type` defaults to.

2. We move the `Type` enumeration outside of the `Cursor` class scope
   and into the `WebCore` namespace, renaming it to `PlatformCursorType`
   in the process. Moving out this enumeration allows us to forward
   declare it instead of pulling in the entire `Cursor` class
   definition. The rename was necessary because `WebCore::CursorType`
   exists in RenderStyleConstants.cpp already.

* Source/WebCore/platform/Cursor.cpp:
(WebCore::Cursor::fromType):
(WebCore::Cursor::Cursor):
(WebCore::pointerCursor):
(WebCore::crossCursor):
(WebCore::handCursor):
(WebCore::moveCursor):
(WebCore::verticalTextCursor):
(WebCore::cellCursor):
(WebCore::contextMenuCursor):
(WebCore::aliasCursor):
(WebCore::zoomInCursor):
(WebCore::zoomOutCursor):
(WebCore::copyCursor):
(WebCore::noneCursor):
(WebCore::progressCursor):
(WebCore::noDropCursor):
(WebCore::notAllowedCursor):
(WebCore::iBeamCursor):
(WebCore::waitCursor):
(WebCore::helpCursor):
(WebCore::eastResizeCursor):
(WebCore::northResizeCursor):
(WebCore::northEastResizeCursor):
(WebCore::northWestResizeCursor):
(WebCore::southResizeCursor):
(WebCore::southEastResizeCursor):
(WebCore::southWestResizeCursor):
(WebCore::westResizeCursor):
(WebCore::northSouthResizeCursor):
(WebCore::eastWestResizeCursor):
(WebCore::northEastSouthWestResizeCursor):
(WebCore::northWestSouthEastResizeCursor):
(WebCore::columnResizeCursor):
(WebCore::rowResizeCursor):
(WebCore::middlePanningCursor):
(WebCore::eastPanningCursor):
(WebCore::northPanningCursor):
(WebCore::northEastPanningCursor):
(WebCore::northWestPanningCursor):
(WebCore::southPanningCursor):
(WebCore::southEastPanningCursor):
(WebCore::southWestPanningCursor):
(WebCore::westPanningCursor):
(WebCore::grabCursor):
(WebCore::grabbingCursor):
* Source/WebCore/platform/Cursor.h:
(WebCore::Cursor::type const):
* Source/WebCore/platform/gtk/CursorGtk.cpp:
(WebCore::Cursor::ensurePlatformCursor const):
* Source/WebCore/platform/mac/CursorMac.mm:
(WebCore::Cursor::ensurePlatformCursor const):
* Source/WebCore/platform/win/CursorWin.cpp:
(WebCore::Cursor::ensurePlatformCursor const):
* Source/WebCore/testing/Internals.cpp:
(WebCore::cursorTypeToString):
* Source/WebKit/Shared/WebCoreArgumentCoders.cpp:
(IPC::ArgumentCoder&lt;Cursor&gt;::encode):
(IPC::ArgumentCoder&lt;Cursor&gt;::decode):
* Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm:
(-[WKContentView pointerRegionForPositionInformation:point:]):
(-[WKContentView pointerInteraction:styleForRegion:]):
* Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm:
(WebKit::populateCaretContext):

Canonical link: <a href="https://commits.webkit.org/270837@main">https://commits.webkit.org/270837@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/86f2f1cd679dd753d40bfaccf7923ca32725f5fa

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/26524 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/5139 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/27771 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/28733 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/24253 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/26933 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/6943 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/2547 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/24218 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/26784 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/3961 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/22776 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/3491 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/3537 "Passed tests") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/23775 "Found 1 new test failure: platform/mac/media/encrypted-media/fps-generateRequest.html (failure)") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/29218 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/24175 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/24158 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/29811 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/3569 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/1773 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/27703 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/5005 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/6376 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/4043 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/3897 "Built successfully") | | |

### CODE REVIEW

**Review by pxlcoder — APPROVED** [review]

**Comment by pxlcoder** [comment]
I just took a look at https://github.com/WebKit/WebKit/pull/20576. You should consider making the enum not nested, and rename to `CursorType`, so we can forward declare in `PDFPluginBase.h`.

**Comment by aprotyas** [comment]
@pxlcoder what do you think about?

```c++
enum class CursorType {
    ...
};

class Cursor {
    using Type = CursorType;
};
```

That way we can forward declare as needed without having to rewrite the world 😛

**Comment by pxlcoder** [comment]
> ```c++
> using Type =
> ```

No strong opinions, and I see other examples of this in the code, so sounds fine to me.

**Comment by cdumez** [comment]
> @pxlcoder what do you think about?
> 
> ```c++
> enum class CursorType {
>     ...
> };
> 
> class Cursor {
>     using Type = CursorType;
> };
> ```
> 
> That way we can forward declare as needed without having to rewrite the world 😛

Yes, this is common practice.

**Comment by aprotyas** [comment]
The test failure (`platform/mac/media/encrypted-media/fps-generateRequest.html`) on `mac-wk1` is unrelated to this change. Thanks for the review, merging!

**Pull request merged**
