### PR TITLE
Use the placeholder SVG as a mask to respect semantic color changes

### PR DESCRIPTION
**Pull request by squelart**
#### 09e40749eec19e82da91fffce3a3c43171370469
<pre>
Use the placeholder SVG as a mask to respect semantic color changes
<a href="https://bugs.webkit.org/show_bug.cgi?id=257881">https://bugs.webkit.org/show_bug.cgi?id=257881</a>
rdar://110501919

Reviewed by Tim Nguyen.

When used as a background-image, SVGs do not actually change color as expected in dark mode.
Instead, the SVG is now used as a mask over a semantic background color that correctly changes when appropriate.

Added simple mismatch test to verify that dark appearance leads to different results from light.

* LayoutTests/fast/attachment/cocoa/wide-attachment-rendering-dark-expected-mismatch.html: Added.
* LayoutTests/fast/attachment/cocoa/wide-attachment-rendering-dark.html: Added.
* LayoutTests/platform/ios-wk2/fast/attachment/cocoa/wide-attachment-rendering-expected.txt:
* LayoutTests/platform/mac-wk2/fast/attachment/cocoa/wide-attachment-rendering-expected.txt:
* Source/WebCore/html/shadow/attachmentElementShadow.css:
(div#attachment-placeholder):

Canonical link: <a href="https://commits.webkit.org/265037@main">https://commits.webkit.org/265037@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/1e894a81cd00241155844d1e0bd990686086f34b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/9506 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/9767 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/10007 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/11167 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/9327 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/9516 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/11744 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/9723 "Built successfully") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/12235 "96 failures") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/9657 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/10536 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/8123 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/11325 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/7830 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/8653 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/16074 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/8925 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/8803 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/12140 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/9291 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/7555 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/8493 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/8559 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/2305 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/12716 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/9059 "Built successfully") | | |

### CODE REVIEW

**Review by nt1m — APPROVED** [review]

**Review by nt1m — CHANGES_REQUESTED** [review]
Please don't use a render tree dump

**Comment by squelart** [comment]
> Please don't use a render tree dump

It's a modified copy of an existing test, why suddenly can't I do that?

**Comment by squelart** [comment]
How else could I test semantic colors inside a UA shadow tree?

**Comment by nt1m** [comment]
I would use a mismatch test, e.g. an `-expected-mismatch.html` file that displays the attachments in light mode. It wouldn't test the icon specifically (but the current render tree dump really doesn't either, since it just asserts a square is drawn at that place), but it would cover dark mode properly.

**Comment by nt1m** [comment]
FWIW, render tree dumps are not great choice because:
- it's easy to rebaseline incorrectly and ship regressions if you don't know what to look for in the dump
- unrelated changes (IFC, etc.) can affect dumps, making them a maintenance burden

**Comment by nt1m** [comment]
> It's a modified copy of an existing test, why suddenly can't I do that?

We shouldn't repeat mistakes of the past (I did also bring this up for other wide attachment tests fwiw), especially when they're easy to avoid, like here, the -expected-mismatch.html can just be:

```html
<html><!-- webkit-test-runner [ AttachmentElementEnabled=true AttachmentWideLayoutEnabled=true ] -->
 <head>
 </head>
 <body style="color-scheme: only light;">
 <div>Blank: <attachment></attachment></div>
 <div>Title: <attachment title="Title" subtitle="Subtitle"></attachment></div>
 <div>and subtitle: <attachment title="Title" subtitle="Subtitle"></attachment></div>
 <div>Action: <attachment action="Tap to download" title="Title.txt" subtitle="Subtitle"></attachment></div>
 <div>Save: <attachment title="Title.pdf" save></attachment></div>
 <div>Zero progress: <attachment title="Title.pdf" progress="0"></attachment></div>
 <div>75% progress: <attachment title="Title.pdf" progress="0.75"></attachment></div>
 <div>100% progress: <attachment title="Title.pdf" progress="1"></attachment></div>
 </body>
 </html>
```

**Review by nt1m — APPROVED** [review]

**Pull request merged**
