### PR TITLE
Lots of missing tiles when scrolling large source files in github

### PR DESCRIPTION
**Pull request by smfr**
#### ba91bd60a084adf34535571b5a30db3af4d5d5c4
<pre>
Lots of missing tiles when scrolling large source files in github
<a href="https://bugs.webkit.org/show_bug.cgi?id=242424">https://bugs.webkit.org/show_bug.cgi?id=242424</a>
&lt;rdar://91790051&gt;

Reviewed by Darin Adler.

Pages like <a href="https://github.com/WebKit/WebKit/blame/main/Source/WebCore/dom/Element.cpp">https://github.com/WebKit/WebKit/blame/main/Source/WebCore/dom/Element.cpp</a>, which trigger
sideways scrolling because of long lines, end up with a nested overflow:scroll, with many tiles.
This triggered a slow painting behavior because of the check for
`paintBehavior.contains(PaintBehavior::CompositedOverflowScrollContent)` in RenderBlock::paint(),
which bypasses an optimization to skip renderers whose visual overflow rect is entirely outside the
paint rect.

We only need to consult the PaintBehavior::CompositedOverflowScrollContent bit for the RenderBlock
that is the composited scroller, because that&apos;s the renderer that has content that we need to paint
into the scrolled contents compositing layer that exists outside the visual overflow rect. This
change restores the optimization for deeper descendants of composited scrollers.

* Source/WebCore/rendering/RenderBlock.cpp:
(WebCore::RenderBlock::paint):

Canonical link: <a href="https://commits.webkit.org/252221@main">https://commits.webkit.org/252221@main</a>
</pre>

### CODE REVIEW

**Review by darinadler — APPROVED** [review]
This looks great. Is there a straightforward way to add a regression test?

**Comment by smfr** [comment]
It would have to be a performance test. Given how we're all using GitHub now, I think we'd notice if this regressed again.

**Comment by darinadler** [comment]
We have a tradition of creating test frameworks that count how much we repaint; it seems something roughly like that could apply here.

**Comment by smfr** [comment]
The fix doesn't affect how much we (re)paint, but how expensive each paint is (it reduces the amount of render tree traversal when painting each tile).

**Comment by darinadler** [comment]
I promise I won’t push further after this. My last thought.

For algorithmic mistakes like this one we should make extreme examples that exaggerate the performance issue, and while such a test would **technically** be a performance test, there will be such a dramatic performance effect that we can make it more like a “this does not hang“ test.

I understand your claim that “we’ll just notice while using GitHub” is enough coverage, but I’m not completely convinced. Like, what if GitHub changes their design, but this still affects other websites.

**Pull request merged**
