### PR TITLE
submit disabled="disabled" doesn't stop form from being posted with ENTER key

### PR DESCRIPTION
**Pull request by rniwa**
#### 7f2b47eeff03586875c526e4e5763c8a52c033f8
<pre>
submit disabled=&quot;disabled&quot; doesn&apos;t stop form from being posted with ENTER key
<a href="https://bugs.webkit.org/show_bug.cgi?id=243594">https://bugs.webkit.org/show_bug.cgi?id=243594</a>

Reviewed by Aditya Keerthi.

Change the behavior of WebKit to match that of Blink and Gecko by disallowing
implicit submission of a form when the first submit button is disabled.

* LayoutTests/fast/forms/implicit-submission-expected.txt:
* LayoutTests/fast/forms/implicit-submission.html:
* LayoutTests/platform/mac/fast/forms/implicit-submission-expected.txt:
* LayoutTests/platform/win-7sp0/fast/forms/implicit-submission-expected.txt: Removed.
* LayoutTests/platform/win/fast/forms/implicit-submission-expected.txt:

* Source/WebCore/html/HTMLButtonElement.cpp:
(WebCore::HTMLButtonElement::isSuccessfulSubmitButton const): Changed the condition
to be considered as &quot;successful&quot; submit button.
* Source/WebCore/html/HTMLInputElement.cpp:
(WebCore::HTMLInputElement::isSuccessfulSubmitButton const): Ditto.

Canonical link: <a href="https://commits.webkit.org/253228@main">https://commits.webkit.org/253228@main</a>
</pre>

### CODE REVIEW

**Review by pxlcoder — APPROVED** [review]
Should we add a WPT for this?

**Comment by rniwa** [comment]
> Should we add a WPT for this?

Maybe? It's kind of tricky to emulate ENTER key in WPT though.

**Comment by rniwa** [comment]
Also, implicit submission isn't something all browsers are required to support although they're strongly encouraged to:
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

**Comment by nt1m** [comment]
> > Should we add a WPT for this?
> 
> Maybe? It's kind of tricky to emulate ENTER key in WPT though.

You can with test_driver.send_keys()

**Comment by rniwa** [comment]
> > > Should we add a WPT for this?
> > 
> > 
> > Maybe? It's kind of tricky to emulate ENTER key in WPT though.
> 
> You can with test_driver.send_keys()

Right but the other issue that implicit submission via enter isn't a spec mandated behavior remains. So I don't think it's quite appropriate to add a WPT test for it. Or the test needs to allow implicit submission to not work, which sort of defeats the point of this test.

**Comment by cdumez** [comment]
> > > > Should we add a WPT for this?
> > > 
> > > 
> > > Maybe? It's kind of tricky to emulate ENTER key in WPT though.
> > 
> > 
> > You can with test_driver.send_keys()
> 
> Right but the other issue that implicit submission via enter isn't a spec mandated behavior remains. So I don't think it's quite appropriate to add a WPT test for it. Or the test needs to allow implicit submission to not work, which sort of defeats the point of this test.

There is already testing for this in WPT though no?
html/semantics/forms/form-submission-0/implicit-submission.optional.html

**Comment by rniwa** [comment]
> > 
> > Right but the other issue that implicit submission via enter isn't a spec mandated behavior remains. So I don't think it's quite appropriate to add a WPT test for it. Or the test needs to allow implicit submission to not work, which sort of defeats the point of this test.
> 
> There is already testing for this in WPT though no? html/semantics/forms/form-submission-0/implicit-submission.optional.html

Oh, interesting. I guess .optional denotes that it's optional, not required.

**Comment by cdumez** [comment]
> > > Right but the other issue that implicit submission via enter isn't a spec mandated behavior remains. So I don't think it's quite appropriate to add a WPT test for it. Or the test needs to allow implicit submission to not work, which sort of defeats the point of this test.
> > 
> > 
> > There is already testing for this in WPT though no? html/semantics/forms/form-submission-0/implicit-submission.optional.html
> 
> Oh, interesting. I guess .optional denotes that it's optional, not required.

I guess so, first time I see this as well.

**Comment by rniwa** [comment]
Adding a WPT test case in https://github.com/web-platform-tests/wpt/pull/35385

**Pull request merged**
