### PR TITLE
[Win][DRT] Add missing implementation to didReceiveAuthenticationChallenge

### PR DESCRIPTION
**Pull request by kshukuwa**
#### 9cb67601803390b20ac011654ced9336f50bf91a
<pre>
[Win][DRT] Add missing implementation to didReceiveAuthenticationChallenge
<a href="https://bugs.webkit.org/show_bug.cgi?id=191385">https://bugs.webkit.org/show_bug.cgi?id=191385</a>

Reviewed by NOBODY (OOPS!).

Add a case that reject protection space and continue for authentication
challenge to didReceptionAuthenticationChallenge.

* LayoutTests/platform/win/TestExpectations:
* LayoutTests/platform/wincairo-wk1/TestExpectations:
* Tools/DumpRenderTree/win/ResourceLoadDelegate.cpp:
(ResourceLoadDelegate::didReceiveAuthenticationChallenge):
</pre>
https://github.com/WebKit/WebKit/commit/9cb67601803390b20ac011654ced9336f50bf91a

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/96666 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/5925 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/29750 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/106190 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/166510 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/100650 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/6128 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/34660 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/89044 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/102900 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/102342 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/4579 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/83270 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/31542 "Passed tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/86421 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/88294 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/74459 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/40390 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/19785 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/38052 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/21194 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/4321 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/43734 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/1134 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/40476 "Passed tests") | |

### CODE REVIEW

**Comment by kshukuwa** [comment]
References:

mac-DRT:
https://github.com/WebKit/WebKit/blob/60d2086f9b7043ac24841f29e39f8e5ac4e13283/Tools/DumpRenderTree/mac/ResourceLoadDelegate.mm#L202-L207

WTR:
https://github.com/WebKit/WebKit/blob/60d2086f9b7043ac24841f29e39f8e5ac4e13283/Tools/WebKitTestRunner/TestController.cpp#L2337-L2341

**Review by fujii — APPROVED** [review]

**Comment by fujii** [comment]
Should I wait for AppleWin EWS to finish?

**Review by fujii — CHANGES_REQUESTED** [review]
This doesn't seem like a WinCairo specific change. I think we should use `[Win]` tag instead of `[WinCairo]` in this case.

**Comment by fujii** [comment]
Let's unmark http/tests/xmlhttprequest/auth-reject-protection-space.html of AppleWin's TestExpectations. And wait for a EWS result.

**Comment by kshukuwa** [comment]
I'm sorry. This fix is incorrect. I will close this PR.

It seems that we should call `rejectProtectionSpaceAndContinueWithChallenge` like function instead of `continueWithoutCredentialForAuthenticationChallenge`. However, WebKitLegacy doesn't have it. Also, curl port doesn't implement `ResourceHandle::receivedChallengeRejection()`.

**Pull request closed without merging**
