### PR TITLE
[macOS] Upgrade sandbox version

### PR DESCRIPTION
**Pull request by pvollan**
#### 18713b70852e4784a3087ddad9306946ca8f9fe2
<pre>
[macOS] Upgrade sandbox version
<a href="https://bugs.webkit.org/show_bug.cgi?id=243400">https://bugs.webkit.org/show_bug.cgi?id=243400</a>
&lt;rdar://problem/97906921&gt;

Reviewed by Chris Dumez.

Upgrade to recent sandbox version in WebKit sandboxes on macOS.

* Source/WebKit/GPUProcess/mac/com.apple.WebKit.GPUProcess.sb.in:
* Source/WebKit/NetworkProcess/mac/com.apple.WebKit.NetworkProcess.sb.in:
* Source/WebKit/Shared/Sandbox/macOS/common.sb:
* Source/WebKit/WebProcess/com.apple.WebProcess.sb.in:

Canonical link: <a href="https://commits.webkit.org/255662@main">https://commits.webkit.org/255662@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/df8cd491f2ba4b54d7d6f716ea1055c0d51a4145

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/93118 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/2319 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/23770 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/102826 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/2324 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/30646 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/85509 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/98944 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/98784 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/1605 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/79593 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/28530 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/83518 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/83289 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/71639 "Found 1 new API test failure: /WebKitGTK/TestWebKitWebView:/webkit/WebKitWebView/title-change (failure)") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/37038 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/17169 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/34852 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/18407 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3923 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/38722 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/40946 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/40651 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/37616 "Passed tests") | |

### CODE REVIEW

**Review by cdumez — APPROVED** [review]
LGTM

**Comment by aj062** [comment]
Stopped https://ews-build.webkit.org/#/builders/3/builds/77682 as it showed a lot of failures and was taking too long. Please check.

**Comment by aj062** [comment]
This PR resulted in over 1 million lines of output in run-api-tests in https://ews-build.webkit.org/#/builders/3/builds/78330. Please check.

**Comment by aj062** [comment]
api-mac was taking 5+ hours in https://ews-build.webkit.org/#/builders/3/builds/79626 with lot of output. I cancelled it for now. Please check.

**Comment by aj062** [comment]
I cancelled api-mac run: https://ews-build.webkit.org/#/builders/3/builds/81895 since it showed 1793 api tests failures and was taking too long. Please have a look.

**Review by cdumez — APPROVED** [review]
LGTM

**Comment by pvollan** [comment]
> LGTM

Thanks for reviewing!

**Pull request merged**
