### PR TITLE
Fix the Mac JSCOnly build

### PR DESCRIPTION
**Pull request by emw-apple**
#### ac35e5bfba5d7ef551a4e102c57bbbd2a7b5f370
<pre>
Fix the Mac JSCOnly build
<a href="https://bugs.webkit.org/show_bug.cgi?id=247927">https://bugs.webkit.org/show_bug.cgi?id=247927</a>

Reviewed by Brent Fulgham.

* Source/JavaScriptCore/API/WebKitAvailability.h: Disable
  JSC availability macros when building JSCOnly.
* Source/WTF/wtf/FileSystem.h: Add missing include.
* Source/WTF/wtf/PlatformHave.h: Don&apos;t redeclare HAVE macros from
  cmakeconfig.h.
* Source/WTF/wtf/UUID.cpp: Add missing include.
* Source/WTF/wtf/text/StringHasher.h: Add missing include.
* Source/cmake/OptionsCommon.cmake: Feature-detect some linker options,
  instead of just assuming any LLD is GNU-compatible ld.
* Source/cmake/WebKitFeatures.cmake: Use check_symbol_exists instead of
  check_function_exists, because it works better with macOS SDK headers.
* Tools/TestWebKitAPI/Tests/JavaScriptCore/PropertySlot.cpp: Add missing
  include.
* Tools/TestWebKitAPI/config.h: JSCOnly&apos;s test target is called
  &quot;TestJavaScriptCore&quot;; recognize it as TestJSC.

Canonical link: <a href="https://commits.webkit.org/257142@main">https://commits.webkit.org/257142@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/0c3bb7a1f7b288197ec3a9839c19ffa79aae305d

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/96605 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/5861 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/29682 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/106131 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/166464 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/100589 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/6057 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/34599 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/88980 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/102842 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/102280 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/4519 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/83208 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/31496 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/86362 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/88244 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/74410 "Found 1 new API test failure: /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/text/state-changed (failure)") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/87559 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/40330 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/19735 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/82986 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/37993 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/21139 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/28341 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4914 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/4262 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/43678 "Found 1 new test failure: imported/w3c/web-platform-tests/webxr/xrWebGLLayer_viewports.https.html (failure)") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/85666 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/1075 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/40415 "Passed tests") | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/19317 "Passed tests") |

### CODE REVIEW

**Comment by emw-apple** [comment]
One thing we should clear up early on is whether this is called the "status" field or the "state" field -- I've heard both. @brentfulgham @hortont424: any strong preference?

**Comment by brentfulgham** [comment]
> One thing we should clear up early on is whether this is called the "status" field or the "state" field -- I've heard both. @brentfulgham @hortont424: any strong preference?

It should be status, per the Quip document. I fouled it up and typed 'state' once, and then copied it everywhere. Would you like me to prepare a revised YAML file?

**Comment by bfulgham** [comment]
The current PR doesn't seem to contain the changes discussed in the commit message (e.g., Source/WTF/Scripts/GeneratePreferences.rb, the changes to Experimental Features, etc.)

Is this a partial patch?

**Comment by emw-apple** [comment]
@bfulgham Yes, I was hoping to get this one landed ahead of the generator changes. I expect to have that patch ready in the next few days.

If you'd like to hold off on reviewing until it's all ready, and review as one big patch, that's fine with me.

**Review by brentfulgham — APPROVED** [review]
This initial step looks good,

**Comment by emw-apple** [comment]
I think I understand Brent's confusion now about the PR description not lining up with the code. I accidentally pushed the commit for https://github.com/WebKit/WebKit/pull/6496 to this branch last week (without using `git-webkit pr`), so that's what landed. Upon merging, EWS updated this PR's description. So now it looks like I have two PRs for "Fix the Mac JSCOnly build" – this one and #6496.

The commit I was _trying_ to get reviewed here is https://github.com/WebKit/WebKit/commit/25619c09b1e30b01cd9e9d30ff6d5a74ebd6eb3a.

I have opened https://github.com/WebKit/WebKit/pull/6945 to propose it again.

**Pull request merged**
