### PR TITLE
utext_setup() can fail

### PR DESCRIPTION
**Pull request by litherum**
#### 45a531fbee9aae168c5795cc191a49b415f10e66
<pre>
utext_setup() can fail
<a href="https://bugs.webkit.org/show_bug.cgi?id=259468">https://bugs.webkit.org/show_bug.cgi?id=259468</a>
rdar://112426537

Reviewed by Brent Fulgham.

Simply add a null check.

We don&apos;t know of any content that can cause this, but
we are getting reports of crashes at this stack trace.
So I don&apos;t know how to make a test :(

* Source/WTF/wtf/text/icu/TextBreakIteratorICU.h:
(WTF::TextBreakIteratorICU::TextBreakIteratorICU):
(WTF::TextBreakIteratorICU::operator=):
(WTF::TextBreakIteratorICU::setText):

Canonical link: <a href="https://commits.webkit.org/266388@main">https://commits.webkit.org/266388@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/15e984ed73e1f60b55295cfb6de1e0c6e7352657

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/13685 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/13999 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/14332 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/15421 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/12996 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/16507 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/14080 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/15678 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/13851 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/14475 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/11580 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/16119 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/11764 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/12338 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/19376 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/11663 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/12839 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/12503 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/15716 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/12954 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/13030 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/10910 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/13727 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/12300 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/3580 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/3332 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/16631 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/14114 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/12871 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/3389 "Passed tests") |

### CODE REVIEW

**Review by brentfulgham — CHANGES_REQUESTED** [review]
This fix doesn't seem to address the call stack in the crash, which passes through the TextBreakIteratorICU constructor that takes a StringView. In that case, this code seems suspicious:

```
        UErrorCode status = U_ZERO_ERROR;
        m_iterator = ubrk_open(type, localeWithOptionalBreakKeyword.string().utf8().data(), nullptr, 0, &status);
        if (!m_iterator) {
            status = U_ZERO_ERROR;
            m_iterator = ubrk_open(type, "", nullptr, 0, &status);
        }
        ASSERT(U_SUCCESS(status));

        setText(string, priorContext, priorContextLength);
```

If the second call to `ubrk_open` fails, we will ASSERT in debug builds, but will happily continue to `setText()` and attempt to dereference the nullptr (or garbage pointer).

It seems like a proper fix here would involve an additional nullptr check after the second `ubrk_open` with an early return or perhaps just a hard CRASH().

**Comment by litherum** [comment]
> This fix doesn't seem to address the call stack in the crash, which passes through the TextBreakIteratorICU constructor that takes a StringView. In that case, this code seems suspicious:
> 
> ```
>         UErrorCode status = U_ZERO_ERROR;
>         m_iterator = ubrk_open(type, localeWithOptionalBreakKeyword.string().utf8().data(), nullptr, 0, &status);
>         if (!m_iterator) {
>             status = U_ZERO_ERROR;
>             m_iterator = ubrk_open(type, "", nullptr, 0, &status);
>         }
>         ASSERT(U_SUCCESS(status));
> 
>         setText(string, priorContext, priorContextLength);
> ```
> 
> If the second call to `ubrk_open` fails, we will ASSERT in debug builds, but will happily continue to `setText()` and attempt to dereference the nullptr (or garbage pointer).
> 
> It seems like a proper fix here would involve an additional nullptr check after the second `ubrk_open` with an early return or perhaps just a hard CRASH().

The stack says:

```
18 ubrk_setUText <==
  18 WTF::TextBreakIteratorICU::setText(WTF::StringView, char16_t const*, unsigned int)
    18 WTF::TextBreakIteratorICU::TextBreakIteratorICU()
```

What this is telling us is either:
1. ICU has a bug in it, or
2. We are passing bad parameters to `ubrk_setUText()`

The signature for `ubrk_setUText()` is `ubrk_setUText(UBreakIterator *bi, UText *text, UErrorCode *status)`. The `status` error code is clearly not the problem, so that just leaves the iterator and the text.

The code you quoted above:
```
m_iterator = ubrk_open(type, localeWithOptionalBreakKeyword.string().utf8().data(), nullptr, 0, &status);
if (!m_iterator) {
    status = U_ZERO_ERROR;
    m_iterator = ubrk_open(type, "", nullptr, 0, &status);
}
```

says "if you can't create the iterator, try again with default values." Looking at the default values:
- The `type` parameter is clearly correct
- The empty locale string is clearly acceptable
- The nullptr / 0 string parameters are clearly acceptable
- The status pointer is also clearly acceptable

There is no reason for `ubrk_open(type, "", nullptr, 0, &status)` to ever fail, unless there is an allocation failure, in which case we _should_ be crashing - all our allocators crash on failure. This is valuable because it means the ICU iterator can never be null, so we don't need to check for null in all of the member functions that use it. This is good for performance - adding a new branch to a hot function like this isn't great.

So, this `ubrk_open()` logic is "if the requested function doesn't work, fall back to a set of parameters which we know will succeed." So, the iterator can't be the problem here.

That leaves just the `UText` parameter as the culprit. That gets set via this:
```
UText* text = nullptr;
if (string.is8Bit())
    text = openLatin1ContextAwareUTextProvider(&textLocal, string.characters8(), string.length(), priorContext, priorContextLength, &status);
else
    text = openUTF16ContextAwareUTextProvider(&textLocal.text, string.characters16(), string.length(), priorContext, priorContextLength, &status);
```

Looking at those functions, we have:
```
UText* text = utext_setup(&utWithBuffer->text, sizeof(utWithBuffer->buffer), status);
if (U_FAILURE(*status)) {
    ASSERT(!text);
    return nullptr;
}
```
So the output of this isn't checked before we pass it into `ubrk_open()`. That's why this patch simply checks the result.

If one creates an iterator with `ubrk_open(type, "", nullptr, 0, &status)` but never executes `ubrk_setUText()` on it, then the iterator behaves as if it's at the end of the text (there are no breaking opportunities anywhere in the string. This is well-defined, and won't cause a crash.

So, I think that's why this patch is correct. However, if we want to be mega-cautions, we _can_ add null checks to every method of this class to check if the iterator is null before using it. I think this will be bad for perf, and is unnecessary (due to the argument above), but it may be warranted if we want to be extra super duper mega sure that we're always passing valid arguments to ICU functions. I also haven't run any perf tests, so I don't _know_ what perf impact there would be, though I'd imagine it would be worse for perf.

**Comment by litherum** [comment]
I updated the patch to add some `RELEASE_ASSERT()s` to verify some of the claims I made above.

**Review by brentfulgham — APPROVED** [review]
Thanks for adding the asserts! r=me

**Pull request merged**
