### PR TITLE
[MSE] Skip initial buffering rate computation

### PR DESCRIPTION
**Pull request by eocanha**
#### 1581c8aa2d3c0f9613a9d1bd881929ead44a4ea2
<pre>
[MSE] Skip initial buffering rate computation
<a href="https://bugs.webkit.org/show_bug.cgi?id=253074">https://bugs.webkit.org/show_bug.cgi?id=253074</a>

Reviewed by Jer Noble.

m_timeOfBufferingMonitor is initialized in SourceBuffer at creation
time. If the first call to monitorBufferingRate() takes too much to
happen for whatever reason (eg: because the webpage takes too much to
perform the first append), the computed interval is already going to be
too big and generate an artificially low m_averageBufferRate.

To mitigate this, I&apos;ve added code to initialize m_timeOfBufferingMonitor
to zero, detect that special value in monitorBufferingRate() and skip
the first time that the rate computation is done (just assigning the
&quot;now&quot; time to m_timeOfBufferingMonitor, so when the next update is done,
the interval is most realistic).

However, since monitorBufferingRate() calls are only done from
canPlayThroughRange() and that call might happen only once in some
layout tests and production scenarios, m_averageBufferRate might not
reach accurate values on time and make the test fail. To mitigate that,
I&apos;ve also added extra calls every time a buffer is appended and every
time the append completes.

See: <a href="https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/928#issuecomment-1327746356">https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/928#issuecomment-1327746356</a>

* Source/WebCore/Modules/mediasource/SourceBuffer.cpp: Initialize m_timeOfBufferingMonitor to zero, meaning &quot;never updated before&quot;.
(WebCore::SourceBuffer::appendBuffer): Update monitorBufferingRate.
(WebCore::SourceBuffer::sourceBufferPrivateAppendComplete): UpdateMonitorBufferingRate.
(WebCore::SourceBuffer::monitorBufferingRate): Skip first m_averageBufferRate update.

Canonical link: <a href="https://commits.webkit.org/261328@main">https://commits.webkit.org/261328@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/b16b73ba1a28c56639ed0b7fb0f23227b0c81b72

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/110231 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/19328 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/42887 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/1651 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/119219 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/114182 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/20790 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/10520 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/86/builds/1124 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/115975 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/15496 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/98685 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/102490 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/97439 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/30349 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/43694 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/12017 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/31686 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/85544 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/12629 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/8651 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/17995 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/51303 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7852 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/14438 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by jernoble — APPROVED** [review]

**Comment by eocanha** [comment]
The patch as it is is causing 3 regressions in glib platforms:
- media/media-source/media-source-canplaythrough-event.html
- media/media-source/media-source-video-renders.html
- media/media-source/media-source-webm-append-buffer-after-abort.html

I'm going to have a quick look into them before considering merging the patch.

**Comment by philn** [comment]
Seems to break tests on mac ports too.

**Comment by eocanha** [comment]
The problem seemed to be that just one call to `monitorBufferingRate()` before the test checks canplaythrough isn't enough to get the new mechanism working (2 calls at minimum are needed). I've added extra calls every time an append is done and everytime an append is completed. That solved the issues on WebKitGTK. Let's see if it solves them too for Apple ports.

**Comment by eocanha** [comment]
@jernoble, if you confirm that you don't see anything wrong about calling `monitorBufferingRate()` from `SourceBuffer::appendBuffer()` and `SourceBuffer::sourceBufferPrivateAppendComplete()` to force a more frequent update of `m_averageBufferRate`, I can merge the patch. All the tests are passing now.

**Comment by eocanha** [comment]
@jernoble, in case there's no complain from your side in some days, I'll merge this PR next week.

**Pull request merged**
