### PR TITLE
Remove ExternStringImpl

### PR DESCRIPTION
**Pull request by justinmichaud**
#### 3cba421238f98881d36ce74dbd250a5cc4d905f8
<pre>
Remove ExternStringImpl
<a href="https://bugs.webkit.org/show_bug.cgi?id=256870">https://bugs.webkit.org/show_bug.cgi?id=256870</a>

Reviewed by NOBODY (OOPS!).

We want to cage StringImpls in a 32-bit VA space, so ExternalStringImpl
will no longer work.

When <a href="https://bugs.webkit.org/show_bug.cgi?id=189991">https://bugs.webkit.org/show_bug.cgi?id=189991</a> added this, it was
for node-jsc. That project is now dead.

This will break bun, but let&apos;s see what Jared thinks about copying in
these places instead.

* Source/WTF/WTF.xcodeproj/project.pbxproj:
* Source/WTF/wtf/CMakeLists.txt:
* Source/WTF/wtf/text/ExternalStringImpl.cpp: Removed.
* Source/WTF/wtf/text/ExternalStringImpl.h: Removed.
* Source/WTF/wtf/text/StringImpl.cpp:
(WTF::StringImpl::~StringImpl):
* Source/WTF/wtf/text/StringImpl.h:
(WTF::StringImpl::isExternal const): Deleted.
* Tools/TestWebKitAPI/Tests/WTF/StringImpl.cpp:
</pre>
https://github.com/WebKit/WebKit/commit/3cba421238f98881d36ce74dbd250a5cc4d905f8

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/6840 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/7064 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/7248 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/8435 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/7090 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/6842 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/8254 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/7006 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/9986 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/6959 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/7569 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/6282 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/8530 "Built successfully") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/39/builds/4981 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/6201 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/13987 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/20/builds/5765 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/6699 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/6284 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/9058 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/6414 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/6769 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/17/builds/5539 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/6978 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/6148 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/1632 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/10330 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/7169 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/6527 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/1768 "Passed tests") |

### CODE REVIEW

**Comment by justinmichaud** [comment]
cc @Jarred-Sumner

**Comment by Jarred-Sumner** [comment]
Thanks for the heads up 

This will break some stuff for us. Will need to think about how to reuse  strings allocated externally

**Comment by Jarred-Sumner** [comment]
Most of our usages of ExternalStringImpl is when a string from the network or filesystem is sent and it's ascii so we don't need to copy it

**Comment by justinmichaud** [comment]
Can you allocate the buffer from inside the JSC small heap (once that patch lands), then write into it directly? Alternatively, is there some other way for you to manage the lifetime of the backing data other than the StringImpl ref count?

**Comment by Jarred-Sumner** [comment]
One tricky thing is we don't always know ahead of time it's going to be a string

Consider `await (await fetch("https://example.com).text()`

If the body is available and an ascii string, we skip cloning the string and make it a StringImpl. But we don't know when the buffer is allocated whether it will be a string or not (only that it is an HTTP response body)

**Comment by Constellation** [comment]
@Jarred-Sumner @justinmichaud Talked offline, I think we do not need to have this change since ExternalStringImpl itself is allocated via WebKit Malloc. It is just holding external string buffer. :)

**Pull request closed without merging**
