### PR TITLE
Add myself (Loïc Yhuel) to contributors.json

### PR DESCRIPTION
**Pull request by hwti**
#### 123411aa4969b2d6201c2012b9d6ac597e3b1bee
<pre>
Add myself (Loïc Yhuel) to contributors.json
<a href="https://bugs.webkit.org/show_bug.cgi?id=267090">https://bugs.webkit.org/show_bug.cgi?id=267090</a>

Reviewed by Michael Catanzaro.

* metadata/contributors.json:

Canonical link: <a href="https://commits.webkit.org/275828@main">https://commits.webkit.org/275828@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/563e10493e5a3f623f48718caae0b2bd5835cf41

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/42855 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/21876 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/45256 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/45472 "Built successfully") | [❌ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/38980 "Failed to checkout and rebase branch from PR 22389") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/25568 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/19256 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/35464 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/43428 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/18904 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/36893 "Passed tests") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/16435 "Found 1 new API test failure: /WPE/TestWebKitWebView:/webkit/WebKitWebView/save (failure)") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/42725 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/16514 "Passed tests") | | [✅ 🛠 wpe-skia](https://ews-build.webkit.org/#/builders/52/builds/911 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/39034 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/38288 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/46991 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/17682 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/14576 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/42208 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/19307 "Built successfully") | | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/40852 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/9576 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/19471 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/18937 "Built successfully") | | |

### CODE REVIEW

**Comment by blino** [comment]
@JonWBedard : hi, is it possible to merge this to allow @hwti to use the repo?
This is needed for example to add the `request-merge-queue` label to PRs.
Thanks!

**Review by mcatanzaro — APPROVED** [review]

**Comment by hwti** [comment]
GitHub secret detection prevented the merge-queue from pushing to the branch on my fork.
After synchronizing the main branch of the fork from the GitHub pages, I was able to push the rebased branch.

**Comment by hwti** [comment]
`wincairo` seems to have an issue with the branch name (but it didn't prevent the merge-queue from running on the first commit).
`api-wpe` failed on a test, which is obviously unrelated, is it why the merge queue didn't run on the rebased branch ?

**Comment by mcatanzaro** [comment]
Merge queue will add the merge-blocking label if it fails. I assume it's just slow today.

**Pull request merged**
