### PR TITLE
[WTF] Remove master variations of main constants

### PR DESCRIPTION
**Pull request by LumioseSil**
#### a4b7b565fd3bec00480fe0079fa9cc3893f95242
<pre>
[WTF] Remove master variations of main constants
<a href="https://bugs.webkit.org/show_bug.cgi?id=279000">https://bugs.webkit.org/show_bug.cgi?id=279000</a>

Reviewed by Brent Fulgham.

All supported macOS versions use IOMainPort, and
kAudioObjectPropertyElementMaster now.
IOMasterPort was supported until Big Sur.

<a href="https://commits.webkit.org/260226@main">https://commits.webkit.org/260226@main</a> added a
check for the main port, but now we can remove
that as well.

* Source/WTF/wtf/PlatformHave.h: Remove check for Main.
* Source/WebCore/platform/audio/mac/AudioHardwareListenerMac.cpp: Ditto.
(WebCore::isAudioHardwareProcessRunning):
(WebCore::currentDeviceSupportedBufferSizes):
(WebCore::processIsRunningPropertyDescriptor):
(WebCore::outputDevicePropertyDescriptor):
* Source/WebCore/platform/audio/mac/AudioSessionMac.mm:
(WebCore::defaultDeviceWithoutCaching):
(WebCore::defaultDeviceTransportIsBluetooth):
(WebCore::AudioSessionMac::defaultOutputDeviceAddress):
(WebCore::AudioSessionMac::nominalSampleRateAddress):
(WebCore::AudioSessionMac::bufferSizeAddress):
(WebCore::AudioSessionMac::maximumNumberOfOutputChannels const):
(WebCore::AudioSessionMac::setPreferredBufferSize):
(WebCore::AudioSessionMac::isMuted const):
(WebCore::AudioSessionMac::muteAddress):
* Source/WebCore/platform/graphics/mac/GraphicsChecksMac.cpp:
(WebCore::attachToAppleGraphicsControl):
* Source/WebCore/platform/mediastream/mac/CoreAudioCaptureDevice.cpp:
(WebCore::getDeviceInfo):
(WebCore::CoreAudioCaptureDevice::CoreAudioCaptureDevice):
(WebCore::CoreAudioCaptureDevice::relatedAudioDeviceIDs):
* Source/WebCore/platform/mediastream/mac/CoreAudioCaptureDeviceManager.cpp:
(WebCore::deviceHasInputStreams):
(WebCore::deviceHasOutputStreams):
(WebCore::isValidCaptureDevice):
(WebCore::CoreAudioCaptureDeviceManager::coreAudioCaptureDevices):
(WebCore::computeAudioDeviceList):
* Source/WebCore/platform/mediastream/mac/CoreAudioSharedUnit.cpp:
(WebCore::CoreAudioSharedInternalUnit::defaultOutputDevice):
* Tools/DumpRenderTree/mac/LayoutTestHelper.m:
(lockDownDiscreteGraphics):

Canonical link: <a href="https://commits.webkit.org/283100@main">https://commits.webkit.org/283100@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/6704a939a430df38087228b259bfabe1b2c794e2

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/65222 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/44591 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/17836 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/69246 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/15828 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/67340 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/52373 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/16110 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/52399 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/10959 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/68288 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/41216 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/56457 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/33022 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/37887 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/13828 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/14705 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/58335 "Built successfully and passed tests") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/59771 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/14168 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/70951 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/64465 "Built successfully and passed tests") | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/9174 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/13644 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/59724 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/9206 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/56518 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/59999 "22 api tests failed or timed out") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/14380 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/7584 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/1256 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/86233 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/40401 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/15190 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/41478 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/42659 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/41222 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@RSilicon - one bug is one change, can you open newer one for this PR?

**Comment by RSilicon** [comment]
> @RSilicon - one bug is one change, can you open newer one for this PR?

Ok.

**Comment by Ahmad-S792** [comment]
@RSilicon - commit message is also missing `Reviewed by NOBODY...` line - so even if reviewed, it will lead to issue of being merged. Plus this commit is in top of your work in the past ([260226@main](https://commits.webkit.org/260226@main)), I would say that if you can add along the lines that it is deprecated API and was only supported till BigSur etc., it would be more helpful for @brentfulgham for his review or context.

**Comment by RSilicon** [comment]
> @RSilicon - commit message is also missing `Reviewed by NOBODY...` line - so even if reviewed, it will lead to issue of being merged. Plus this commit is in top of your work in the past ([260226@main](https://commits.webkit.org/260226@main)), I would say that if you can add along the lines that it is deprecated API and was only supported till BigSur etc., it would be more helpful for @brentfulgham for his review or context.

Done!

**Review by brentfulgham — APPROVED** [review]
Nice clean-up. Thank you! r=me

**Pull request merged**
