### PR TITLE
WebKit ignores the nowrap on td nowrap="nowrap", if an absolute width is specified

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
WebKit ignores the nowrap on td nowrap="nowrap", if an absolute width is specified

<a href="https://bugs.webkit.org/show_bug.cgi?id=183642">https://bugs.webkit.org/show_bug.cgi?id=183642</a>

Reviewed by NOBODY (OOPS!).

Merge - <a href="https://chromium.googlesource.com/chromium/src/+/5e6c851254f90f6f495713f7248ffe9a155de413">https://chromium.googlesource.com/chromium/src/+/5e6c851254f90f6f495713f7248ffe9a155de413</a>

Previously we only applied it when a 'td' element had no fixed-width. This was incorrect behavior and it will align Webkit with Blink and Gecko for Web interop.

* Source/WebCore/html/HTMLTableCellElement.cpp (HTMLTableCellElement::hasPresentationalHintsForAttribute) - Update nowrap Attribute to respect CSSValueNowrap rather than CSSValueWebkitNowrap
* Source/WebCore/style/StyleAdjuster.cpp (Adjuster:adjust) - Removed logic about td tag only accepting wrap for Fixed Width
* LayoutTests/imported/w3c/web-platform-tests/quirks/table-cell-nowrap-minimum-width-calculation-expected.txt - Updated Test Expectations
* LayoutTests/platform/gtk/fast/table/003-expected.png - Updated Test Expectations
* LayoutTests/platform/gtk/fast/table/003-expected.txt - Updated Test Expectations
* LayoutTests/platform/gtk/fast/tables/021-expected.png - Updated Test Expectations
* LayoutTests/platform/glib/fast/tables/021-expected.txt - Updated Test Expectations
* LayoutTests/platform/gtk/fast/table/rowspan-paint-order-vertical-expected.png - Updated Test Expectations
* LayoutTests/platform/gtk/fast/table/rowspan-paint-order-vertical-expected.txt - Updated Test Expectations
* LayoutTests/platform/gtk/tables/mozilla/bugs/bug57828-expected.png - Updated Test Expectations
* LayoutTests/platform/gtk/tables/mozilla/bugs/bug78162-expected.png - Updated Test Expectations
* LayoutTests/platform/gtk/tables/mozilla/bugs/bug78162-expected.txt - Updated Test Expectations
* LayoutTests/platform/gtk/tables/mozilla/bugs/bug92143-expected.txt - Updated Test Expectations
* LayoutTests/platform/ios/fast/table/021-expected.txt - Updated Test Expectations
* LayoutTests/platform/ios/fast/table/rowspan-paint-order-vertical-expected.txt - Updated Test Expectations
* LayoutTests/platform/ios/tables/mozilla/bugs/bug57828-expected.txt - Updated Test Expectations
* LayoutTests/platform/ios/tables/mozilla/bugs/bug78162-expected.txt - Updated Tests Expectations
* LayoutTests/platform/ios/tables/mozilla/bugs/bug92143-expected.txt - Updated Tests Expectations
* LayoutTests/platform/mac/fast/table/003-expected.png - Updated Tests Expectations
* LayoutTests/platform/mac/fast/table/003-expected.txt - Updated Test Expectations
* LayoutTests/platform/mac/fast/table/021-expected.png - Updated Test Expectations
* LayoutTests/platform/mac/fast/table/021-expected.txt - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug57828-expected.png - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug57828-expected.txt - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug78162-expected.png - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug78162-expected.txt - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug92143-expected.png - Updated Test Expectations
* LayoutTests/platform/mac/fast/tables/mozilla/bugs/bug92143-expected.txt - Updated Test Expectations
* LayoutTests/platform/mac/fast/table/rowspan-paint-order-vertical-expected.png - Updated Test Expectations
* LayoutTests/platform/mac/fast/table/rowspan-paint-order-vertical-expected.txt - Updated Test Expectations
* LayoutTests/platform/glib/mozilla/bugs/bug57828-expected.txt - Updated Test Expectations

</pre>

https://github.com/WebKit/WebKit/commit/b791f1b5a1f43d8228ca07f99be571291f946ab3

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/89198 "Failed to checkout and rebase branch from PR 4317") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/33759 "Failed to checkout and rebase branch from PR 4317") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/43/builds/20018 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/8/builds/98517 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/154830 "Failed to checkout and rebase branch from PR 4317") 
| [❌ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/93207 "Failed to checkout and rebase branch from PR 4317") | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/32267 "Failed to checkout and rebase branch from PR 4317") | [  ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/27814 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/81560 "Failed to checkout and rebase branch from PR 4317") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/92986 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [❌ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/94845 "Failed to checkout and rebase branch from PR 4317") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/32267 "Failed to checkout and rebase branch from PR 4317") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/76122 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/36/builds/81560 "Failed to checkout and rebase branch from PR 4317") | 
| | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/32267 "Failed to checkout and rebase branch from PR 4317") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/43/builds/20018 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/36/builds/81560 "Failed to checkout and rebase branch from PR 4317") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/66/builds/30046 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/43/builds/20018 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [❌ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/29770 "Failed to checkout and rebase branch from PR 4317") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/43/builds/20018 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [❌ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/33217 "Failed to checkout and rebase branch from PR 4317") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/76122 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [❌ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/31918 "Failed to checkout and rebase branch from PR 4317") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/43/builds/20018 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | |

### CODE REVIEW

**Review by alanbaradlay — APPROVED** [review]

**Comment by nt1m** [comment]
Looks like the commit has conflicts, can you fix them so we can merge it?

**Comment by Ahmad-S792** [comment]
> Looks like the commit has conflicts, can you fix them so we can merge it?

I am not super good with Git to resolve branch conflict. I might have to close this PR and create new one now. :-(

**Comment by nt1m** [comment]
You can use `git rebase` or delete your branch (`git branch -D fix183642-new`), pull `main` and create a new one with the same name `fix183642-new` and use `git-webkit pr`

**Comment by Ahmad-S792** [comment]
> You can use `git rebase` or delete your branch (`git branch -D fix183642-new`), pull `main` and create a new one with the same name `fix183642-new` and use `git-webkit pr`

I will close this and create new one. Still learning.. Will remember this for next PR and whenever I came across such case.

**Pull request closed without merging**
