### PR TITLE
[git-webkit] Retain old commits in pull-request

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 4ff32c7f3dc0c6c38d367a06a3bad4c61334ac7d
<pre>
[git-webkit] Retain old commits in pull-request
<a href="https://bugs.webkit.org/show_bug.cgi?id=234453">https://bugs.webkit.org/show_bug.cgi?id=234453</a>
&lt;rdar://problem/86654956 &gt;

Reviewed by Dewei Zhu.

* Tools/Scripts/libraries/webkitscmpy/setup.py: Bump version.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py: Ditto.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/land.py:
(Land.main): Find all numbered branches for landing pull-request.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/pull_request.py:
(PullRequest.parser): Add history option.
(PullRequest.main): Add a numbered branch which persists through the life of the pull-request.

Canonical link: <a href="https://commits.webkit.org/245899@main">https://commits.webkit.org/245899@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@287853">https://svn.webkit.org/repository/webkit/trunk@287853</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by JonWBedard** [comment]
At first, I was a bit unsure that we really wanted to do something like this. Seeing how it lets old EWS statuses be accessed in the GitHub UI, though, I think we should move forward with this change.

**Review by dewei-zhu — APPROVED** [review]
r=me

**Comment by JonWBedard** [comment]
Landed https://commits.webkit.org/245899@main (4ff32c7f3dc0c6c38d367a06a3bad4c61334ac7d)!

**Comment by kocsenc** [comment]
The PR is showing 0 commits now (after merging) is that expected?

**Pull request merged**
