### PR TITLE
[JSC][32bit] Enable wasm signaling memory

### PR DESCRIPTION
**Pull request by xanlpz**
#### 58f6c54799dc3a0ee86c7d6352b4f55be1bb9b73
<pre>
[JSC][32bit] Enable wasm signaling memory
<a href="https://bugs.webkit.org/show_bug.cgi?id=244843">https://bugs.webkit.org/show_bug.cgi?id=244843</a>

Reviewed by NOBODY (OOPS!).

Enable wasm signaling memory on 32bit architectures. The only thing we
need to do is to limit the &quot;fast mapped memory&quot; size to 2GB, that way
we can fit that plus the redzone pages inside a 32bit pointer. This is
OK because our memory limit was already 2GB anyway
(MAX_ARRAY_BUFFER_SIZE).

* JSTests/wasm.yaml: unskip shared memory tests on arm.
* JSTests/wasm/stress/shared-memory-errors.js: ditto.
* JSTests/wasm/stress/shared-wasm-memory-buffer.js: ditto.
* Source/JavaScriptCore/wasm/WasmMemory.cpp: use a fast memory mapped
* size of 2GB for 32bit architectures.
* (JSC::Wasm::Memory::fastMappedBytes):
* Source/WTF/wtf/PlatformEnable.h: enable wasm memory signaling on
* 32bit.
</pre>
https://github.com/WebKit/WebKit/commit/58f6c54799dc3a0ee86c7d6352b4f55be1bb9b73

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/88363 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/32795 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/19198 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/97550 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/153023 "Built successfully and passed tests") 
| | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/31298 "Hash 58f6c547 for PR 4054 does not build (failure)") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/26952 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/80562 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/92208 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/93971 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/31298 "Hash 58f6c547 for PR 4054 does not build (failure)") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/75208 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/24874 "Passed tests") | 
| | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/31298 "Hash 58f6c547 for PR 4054 does not build (failure)") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/79918 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/67838 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/80093 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/28908 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/13896 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/73856 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/28884 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/14922 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/26198 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/32089 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/37837 "Passed tests") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/76709 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/31047 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/34035 "Passed tests") | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/17022 "Passed tests") |

### CODE REVIEW

**Comment by Constellation** [comment]
EWS looks red

**Comment by guijemont** [comment]
I suspect this should allow to enable some more tests, such as JSTests/wasm/js-api/test_memory.js and JSTests/wasm/modules/wasm-imports-js-exports.js that seem to fail due to shared memory not being supported.

**Review by Constellation — CHANGES_REQUESTED** [review]
EWS is red, so please take a look.

**Comment by xanlpz** [comment]
After discussions with Justin (IIRC) we decided the approach in this patch was most likely wrong. We still want to enable this feature on 32bit though, so someone from Igalia will work on it ASAP.

**Comment by xanlpz** [comment]
Closing, we'll try to reland this elsewhere (apparently the approach might be sound after all, there was some confusion during review).

**Pull request closed without merging**
