### PR TITLE
[JSC] Update test262

### PR DESCRIPTION
**Pull request by sosukesuzuki**
#### 18daa3eb7f07cddc44e062670536f60c4d9fc776
<pre>
[JSC] Update test262
<a href="https://bugs.webkit.org/show_bug.cgi?id=272619">https://bugs.webkit.org/show_bug.cgi?id=272619</a>

Reviewed by Ross Kirsling.

update test262 to <a href="https://github.com/tc39/test262/commit/c5a80993cd96623a875dd6fa532c7d92f392f02b">https://github.com/tc39/test262/commit/c5a80993cd96623a875dd6fa532c7d92f392f02b</a>

* JSTests/test262/expectations.yaml:
* JSTests/test262/latest-changes-summary.txt:
* JSTests/test262/test262-Revision.txt:

Canonical link: <a href="https://commits.webkit.org/277491@main">https://commits.webkit.org/277491@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/e917a09c68b7f2d1fc64cf59a550a3e37eda9e92

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/47758 "2 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/26950 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/50533 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/50441 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/43813 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/32807 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/24431 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/38869 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/48340 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/24607 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/41250 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/20166 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/22086 "Passed tests") | | [✅ 🛠 wpe-skia](https://ews-build.webkit.org/#/builders/52/builds/5807 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/41044 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/44111 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/42865 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/52335 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/47251 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/22795 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/19135 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/46177 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/24067 "Built successfully") | | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/45213 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/10536 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/24856 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/54749 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/23788 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/11242 "Passed tests") |

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
I just run following commands in my local machine:

```
$ ./Tools/Scripts/test262-import
$ ./Tools/Scripts/test262-runnner --save
```

But the number of updated files is too large? did i do something wrong..?

**Review by rkirsling — APPROVED** [review]
rs=me, having discussed on Slack 🙂

**Comment by annevk** [comment]
One thing that would be good is to mention the upstream commit this is synchronized with.

**Comment by sosukesuzuki** [comment]
updated the commit message

**Pull request merged**
