### PR TITLE
Remove Preprocessor Checks for Clang Prior to Version 9

### PR DESCRIPTION
**Pull request by LumioseSil**
#### 99f4e3022fb8676139a5d58950f131dad0e2cbc0
<pre>
Remove Preprocessor Checks for Clang Prior to Version 9
<a href="https://bugs.webkit.org/show_bug.cgi?id=252351">https://bugs.webkit.org/show_bug.cgi?id=252351</a>

Reviewed by Michael Catanzaro.

Given how clang has had its respective bugs resolved and
fixed, we do not need these workarounds anymore.

*Source\WTF\wtf\Int128.cpp: Remove clang + SSE3 workaround

Canonical link: <a href="https://commits.webkit.org/260339@main">https://commits.webkit.org/260339@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/bb8e04a6ab6f1f5b2638c22c06919d31def777b5

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/108031 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/17091 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/40908 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/117161 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/116493 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/76/builds/18465 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/8403 "Built successfully") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/100281 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/113797 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/76/builds/18465 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/97148 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/41849 "layout-tests (failure)") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/76/builds/18465 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/28786 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/83518 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/1/builds/97266 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/81/builds/9994 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/30134 "Passed tests") | [  ~~🛠 jsc-armv7~~](https://ews-build.webkit.org/#/builders/38/builds/96636 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/83/builds/8084 "Built successfully and passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/10712 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/7037 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 jsc-armv7-tests~~](https://ews-build.webkit.org/#/builders/38/builds/96636 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/80/builds/16144 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/49724 "Passed tests") | [  ~~🛠 jsc-mips~~](https://ews-build.webkit.org/#/builders/37/builds/105649 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7153 "Failed to push commit to Webkit repository") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/12289 "Built successfully") | | [  ~~🧪 jsc-mips-tests~~](https://ews-build.webkit.org/#/builders/37/builds/105649 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | | | |

### CODE REVIEW

**Comment by AtariDreams** [comment]
Note: Please do not confuse this PR for https://github.com/WebKit/WebKit/pull/10145

This PR has been split from the other because this PR focuses on changes that were made upstream. Thank you!

**Comment by AtariDreams** [comment]
@geoffreygaren @Constellation Please read the PR this time.

**Comment by AtariDreams** [comment]
Screen Shot 2023-02-15 at 9 43 54 AM

These changes are safe. The one that is in despite is in the other PR.

**Comment by AtariDreams** [comment]
@cdumez Thoughts?

**Comment by mcatanzaro** [comment]
Most of these changes are in third-party code but our goal should be to minimize differences from the upstream code. You would want to first contribute these changes to abseil-cpp and libwebrtc, then eventually we'll get them here when updating to a newer version. So I would start by removing all the changes except for Int128.cpp.

**Comment by AtariDreams** [comment]
They are already up there. See abseil and libwebrtc

**Comment by AtariDreams** [comment]
> Most of these changes are in third-party code but our goal should be to minimize differences from the upstream code. You would want to first contribute these changes to abseil-cpp and libwebrtc, then eventually we'll get them here when updating to a newer version. So I would start by removing all the changes except for Int128.cpp.

https://github.com/abseil/abseil-cpp/pull/1387

**Comment by AtariDreams** [comment]
https://webrtc-review.googlesource.com/c/src/+/293060

**Comment by AtariDreams** [comment]
@mcatanzaro They are already merged basically

**Comment by mcatanzaro** [comment]
OK great! No need to land them separately here. We'll pick up your changes when updating to newer libwebrtc.

**Comment by AtariDreams** [comment]
> OK great! No need to land them separately here. We'll pick up your changes when updating to newer libwebrtc.

Ok then!

**Comment by AtariDreams** [comment]
@mcatanzaro Could you merge this then? I removed all but the WTF change.

**Review by mcatanzaro — APPROVED** [review]
OK, thanks!

**Comment by mcatanzaro** [comment]
Oh wait, one more step: the second line of your commit message should reference a new bug on WebKit Bugzilla, not the original bug. Go ahead and create a new one just for this purpose. The title of the bug should match the first line in your commit message.

**Comment by AtariDreams** [comment]
> Oh wait, one more step: the second line of your commit message should reference a new bug on WebKit Bugzilla, not the original bug. Go ahead and create a new one just for this purpose. The title of the bug should match the first line in your commit message.

Done!

**Comment by AtariDreams** [comment]
@mcatanzaro Ready!

**Comment by AtariDreams** [comment]
@mcatanzaro Do you think we could merge this or?

**Comment by mcatanzaro** [comment]
Yup.

**Comment by AtariDreams** [comment]
> Yup.

Thank you!

**Pull request merged**
