### PR TITLE
Remove parse-gc-phase-timings

### PR DESCRIPTION
**Pull request by gsnedders**
#### a1d3907991934f230f5037f36d64a87d023421ff
<pre>
Remove parse-gc-phase-timings
<a href="https://bugs.webkit.org/show_bug.cgi?id=283139">https://bugs.webkit.org/show_bug.cgi?id=283139</a>

Reviewed by Jonathan Bedard.

This script hasn&apos;t actually worked since 179778@main landed over eight
years ago, and it&apos;s the only file we have with Python 2 syntax at this
point. We may as well just remove it.

* Tools/Scripts/parse-gc-phase-timings: Removed.

Canonical link: <a href="https://commits.webkit.org/287297@main">https://commits.webkit.org/287297@main</a>
</pre>

### CODE REVIEW

**Comment by briannafan** [comment]
Unofficial r+! Is there any need to rewrite the script or move the logic elsewhere, or is the use case also obsolete?

**Comment by gsnedders** [comment]
> Unofficial r+! Is there any need to rewrite the script or move the logic elsewhere, or is the use case also obsolete?

I presume those working on GC are doing something else nowadays! There's still logging about various bits of GC timing, it's just in a very different format.

I'd mostly view a request for a script that can process the logging output to be a new feature request, rather than "fix the script that hasn't worked nearly since it was written". Having it in the repo might give the impression it actually works, which it absolutely does not.

**Review by JonWBedard — APPROVED** [review]

**Comment by ryanhaddad** [comment]
I'm not sure what happened here, but `unsafe-merge-queue` processed this in https://ews-build.webkit.org/#/builders/22/builds/12207 and it was merged as https://commits.webkit.org/287297@main.

**Comment by gsnedders** [comment]
> I'm not sure what happened here that resulted in the PR not being marked as merged, but `unsafe-merge-queue` processed this in https://ews-build.webkit.org/#/builders/22/builds/12207 and it was merged as https://commits.webkit.org/287297@main.

That was https://github.com/WebKit/WebKit/pull/36669 which did get resolved.

This was https://ews-build.webkit.org/#/builders/22/builds/12206, which _didn't_ land, and indeed this hasn't landed, as https://github.com/WebKit/WebKit/commits/main/Tools/Scripts/parse-gc-phase-timings confirms.

**Comment by gsnedders** [comment]
So let's reopen this.

**Pull request closed without merging**
