### PR TITLE
[JSC] Replace narrow no-break space and thin space with normal space in Intl.DateTimeFormat output

### PR DESCRIPTION
**Pull request by Constellation**
#### f0420f3bf5b9316e4871996ebda2a1cc0191096a
<pre>
[JSC] Replace narrow no-break space and thin space with normal space in Intl.DateTimeFormat output
<a href="https://bugs.webkit.org/show_bug.cgi?id=252147">https://bugs.webkit.org/show_bug.cgi?id=252147</a>
rdar://105375286

Reviewed by Ross Kirsling.

ICU 72 replaces normal spaces with narrow no-break spaces and thin spaces for Intl.DateTimeFormat output.
However, a lot of real world code (websites[1], Node.js modules[2] etc.) strongly assumes that this output
only contains normal spaces and these code stops working because of parsing failures. This behavior change
unfortunately caused massive web-compat problems.

As a workaround for this ICU 72 issue, we scan the output string and replace narrow no-break spaces and thin
spaces with normal spaces. This behavior is aligned to SpiderMonkey[3] and V8[4].

[1]: <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1806042">https://bugzilla.mozilla.org/show_bug.cgi?id=1806042</a>
[2]: <a href="https://github.com/nodejs/node/issues/46123">https://github.com/nodejs/node/issues/46123</a>
[3]: <a href="https://hg.mozilla.org/mozilla-central/rev/40e2c54d5618">https://hg.mozilla.org/mozilla-central/rev/40e2c54d5618</a>
[4]: <a href="https://chromium.googlesource.com/v8/v8/+/bab790f9165f65a44845b4383c8df7c6c32cf4b3">https://chromium.googlesource.com/v8/v8/+/bab790f9165f65a44845b4383c8df7c6c32cf4b3</a>

* JSTests/stress/intl-datetimeformat-en-do-not-include-special-spaces.js: Added.
(shouldBe):
(test):
(let.date2.new.Date):
(fmt.formatToParts.date1.forEach):
(date2.forEach):
* Source/JavaScriptCore/runtime/IntlDateTimeFormat.cpp:
(JSC::replaceNarrowNoBreakSpaceOrThinSpaceWithNormalSpace):
(JSC::IntlDateTimeFormat::format const):
(JSC::IntlDateTimeFormat::formatToParts const):
(JSC::IntlDateTimeFormat::formatRange):
(JSC::IntlDateTimeFormat::formatRangeToParts):
* Source/WTF/wtf/unicode/CharacterNames.h:

Canonical link: <a href="https://commits.webkit.org/260179@main">https://commits.webkit.org/260179@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/360b900aaf7653e659df7bdce4537c9f1abd7c94

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/107462 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/16524 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/40365 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/116625 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/116046 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/17949 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/7766 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/99626 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/113223 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/13550 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/96732 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/41172 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/95455 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/28358 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/82942 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/1/builds/96799 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/9530 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/29711 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 jsc-armv7~~](https://ews-build.webkit.org/#/builders/38/builds/96221 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc-arm64~~](https://ews-build.webkit.org/#/builders/83/builds/7529 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/10187 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/6609 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 jsc-armv7-tests~~](https://ews-build.webkit.org/#/builders/38/builds/96221 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/15686 "Built successfully") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/62/builds/49292 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 jsc-mips~~](https://ews-build.webkit.org/#/builders/37/builds/105069 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/11747 "Built successfully") | | [  ~~🧪 jsc-mips-tests~~](https://ews-build.webkit.org/#/builders/37/builds/105069 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/3812 "Built successfully and passed tests") | | | |

### CODE REVIEW

**Review by rkirsling — APPROVED** [review]
r=me, very interesting. Does this result in test262 failures?

**Comment by Constellation** [comment]
Caused some test262 failures. Listed up.

**Comment by justingrant** [comment]
> Caused some test262 failures. Listed up.

Interesting. On the latest Test262? I ask because the tests noted in this PR (`intl402/DateTimeFormat/prototype/formatRange/en-US.js` and `intl402/DateTimeFormat/prototype/formatRange/fractionalSecondDigits.js`) should pass in both CLDR 41 and 42 because of https://github.com/tc39/test262/pull/3765 that was merged last month. But if I messed up that Test262 PR then it'd be good to know. 

Making Test262 resilient to CLDR 42 was quite an undertaking. :-(

- https://github.com/tc39/test262/pull/3765
- https://github.com/tc39/test262/pull/3762
- https://github.com/tc39/test262/pull/3751
- https://github.com/tc39/test262/pull/3750

**Comment by rkirsling** [comment]
Seems like we haven't updated test262 in the new year, so that's probably the cause here. 😅

**Pull request merged**
