### PR TITLE
Remove getPropertyShorthand from the web exposed API.

### PR DESCRIPTION
**Pull request by darinadler**
#### 80c7a3df3ee1af77c4c3227c0b133754f90f35c5
<pre>
Remove getPropertyShorthand from the web exposed API.
<a href="https://bugs.webkit.org/show_bug.cgi?id=87129">https://bugs.webkit.org/show_bug.cgi?id=87129</a>
rdar://problem/102303976

Reviewed by Tim Nguyen.

* LayoutTests/css3/color-filters/color-filter-exposed-if-disabled-expected.txt: Updated.
* LayoutTests/css3/color-filters/color-filter-exposed-if-disabled.html: Removed call to
getPropertyShorthand.

* LayoutTests/css3/color-filters/color-filter-exposed-if-enabled-expected.txt: Updated.
* LayoutTests/css3/color-filters/color-filter-exposed-if-enabled.html: Removed call to
getPropertyShorthand.

* LayoutTests/fast/backgrounds/repeat/background-repeat-shorthand-expected.txt: Removed.
* LayoutTests/fast/backgrounds/repeat/background-repeat-shorthand.html: Removed.
* LayoutTests/fast/backgrounds/repeat/resources/background-repeat-shorthand.js: Removed.

* LayoutTests/fast/css/style-enumerate-properties-expected.txt: Updated.
* LayoutTests/fast/css/style-enumerate-properties.html: Removed getPropertyShorthand from the list
of property names expected.

* Source/WebCore/css/CSSStyleDeclaration.idl: Removed getPropertyShorthand.

* Source/WebInspectorUI/UserInterface/Models/NativeFunctionParameters.js: Removed
getPropertyShorthand and isPropertyImplicit.

Canonical link: <a href="https://commits.webkit.org/256636@main">https://commits.webkit.org/256636@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/02a8ab03c7da4c1a92359e01f4dd67400770054b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/96397 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/5651 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/29462 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/105940 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/166288 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/100380 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/5822 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/34397 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/88776 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/102666 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/102068 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/4333 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/82998 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/31316 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/86175 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/88066 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/74206 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/40127 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/19559 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/37801 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/20946 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4604 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/3106 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/43515 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/708 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/40215 "Passed tests") | |

### CODE REVIEW

**Review by nt1m — APPROVED** [review]
Looks good, thanks.

The version on CSSComputedStyleDeclaration seems pretty useless, I wonder if we could clean that up:

https://searchfox.org/wubkat/rev/5a9504aef82d929917a680a05a3fc17f7f6b4dde/Source/WebCore/css/CSSComputedStyleDeclaration.cpp#200-203

**Comment by darinadler** [comment]
We can remove the silly comment. But more importantly we just need to remove the callers and get rid of the function completely. That’s the way to clean it up.

**Comment by nt1m** [comment]
cc @karlcow here too, to check how web compatible it is (I suspect it is).

**Review by karlcow — COMMENTED** [review]
This will not break the Web indeed.

**Pull request merged**
