### PR TITLE
[CMake] Rework decision to enable -gsplit-dwarf by default

### PR DESCRIPTION
**Pull request by mcatanzaro**
#### fe4fdc28cd214d36425d861791d05d1afaee60f5
<pre>
[CMake] Rework decision to enable -gsplit-dwarf by default
<a href="https://bugs.webkit.org/show_bug.cgi?id=252679">https://bugs.webkit.org/show_bug.cgi?id=252679</a>

Reviewed by Adrian Perez de Castro.

-gsplit-dwarf breaks RPM builds due to zero-sized debug files. I could
override this with -DDEBUG_FISSION=OFF, but we&apos;re probably trying to be
_too_ helpful here by injecting debug flags into non-debug build types.
I doubt Fedora is the only distro that&apos;s not prepared for -gsplit-dwarf
so let&apos;s only inject it if the CMake build type is a debug build type,
and if ENABLE_DEVELOPER_MODE (set e.g. by build-webkit) which is a good
indication that incremental builds are desired. (The primary goal of
-gsplit-dwarf is to make incremental builds faster.) That way, we
improve CMake&apos;s default behavior for developers doing incremental
builds, but anyone manually passing CFLAGS will still get exactly what
they request without modification, and we avoid breaking find-debuginfo
scripts or other debuginfo machinery that CMake does not know about.

* Source/cmake/OptionsCommon.cmake:

Canonical link: <a href="https://commits.webkit.org/260818@main">https://commits.webkit.org/260818@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/01ec7c58788e12df402592bfc1faefcc73bd5150

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/108912 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/18015 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/41753 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/456 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/118228 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/19471 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/9299 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/101160 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/114680 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/14603 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/97826 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/42723 "Found 7 new test failures: webgl/2.0.y/conformance/glsl/bugs/character-set.html, webgl/2.0.y/conformance/glsl/misc/fragcolor-fragdata-invariant.html, webgl/2.0.y/conformance/misc/expando-loss.html, webgl/2.0.y/conformance/misc/invalid-passed-params.html, webgl/2.0.y/conformance/textures/misc/exif-orientation.html, webgl/2.0.y/conformance2/extensions/promoted-extensions-in-shaders.html, webgl/2.0.y/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html (failure)") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/96575 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/29467 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/84462 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/98004 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/10789 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/30816 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/98794 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/83/builds/8918 "Built successfully and passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/11543 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/7752 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/31008 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/16933 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/50412 "Passed tests") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/106437 "Built successfully") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7492 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/13133 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/26383 "Passed tests") | 
| | | | |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Um, @aperezdc has an alternative proposal: instead of checking build type, check `DEVELOPER_MODE`. The goal of this option is to speed up incremental builds for developers. Distro builds won't be using `DEVELOPER_MODE` so this kinda checks all the boxes. Except that will break sccache again, so we could even do both: gate it behind both the build type and the `DEVELOPER_MODE`. Opinions please? (Especially @calvaris.)

**Comment by aperezdc** [comment]
Checking both `DEVELOPER_MODE` and the build type sounds good to me, FTR.

**Comment by calvaris** [comment]
> 

I am not a fan of this. Cause sometimes you need to debug stuff without developer mode and this will totally defeat the purpose of my initial patch.

**Comment by mcatanzaro** [comment]
> I am not a fan of this. Cause sometimes you need to debug stuff without developer mode and this will totally defeat the purpose of my initial patch.

Are you doing incremental builds in this configuration?

**Comment by calvaris** [comment]
> Are you doing incremental builds in this configuration?

Yes.

**Comment by mcatanzaro** [comment]
OK, next question: if you're doing incremental builds, then presumably you're manually passing -g rather than using a distro-level build system. If so, why not just pass -gsplit-dwarf as well?

Thing is, if Fedora debuginfo broke, there's a decent chance it will break other distros too. It's real easy to work around `-DDEBUG_FISSION=OFF` but defaults should be safe. @aperezdc could you check if buildroot can handle 2.39.90 please? @bertogg how about Debian? I will check GNOME flatpak runtimes (where the build succeeded, but that doesn't necessarily indicate the debuginfo is working).

**Comment by mcatanzaro** [comment]
It looks like there is no longer any debuginfo for WebKitGTK in org.gnome.Sdk.Debug//master. Look:

```
Thread 12 (Thread 0x7fdd14ff9640 (LWP 91)):
#0  0x00007fde1c90c0cd in __GI___poll (fds=0x7fdbe8001020, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fde1d7301d9 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7fdbe8001020, timeout=<optimized out>, context=0x7fdbe8000b70) at ../glib/gmain.c:4584
#2  g_main_context_iterate (context=0x7fdbe8000b70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4271
#3  0x00007fde1d73054f in g_main_loop_run (loop=0x7fdbe8000da0) at ../glib/gmain.c:4479
#4  0x00007fde17b2ec60 in WTF::RunLoop::run() () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#5  0x00007fde17acef05 in WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#6  0x00007fde17b3184d in WTF::wtfThreadEntryPoint(void*) () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#7  0x00007fde1c88f1da in start_thread (arg=<optimized out>) at pthread_create.c:442
#8  0x00007fde1c917f44 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

```
(gdb) bt full
#0  0x00007fde1c90c0cd in __GI___poll (fds=0x7fdbe8001020, nfds=2, timeout=-1)
    at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
#1  0x00007fde1d7301d9 in g_main_context_poll
    (priority=<optimized out>, n_fds=2, fds=0x7fdbe8001020, timeout=<optimized out>, context=0x7fdbe8000b70)
    at ../glib/gmain.c:4584
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7fde1d742ce0 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x7fdbe8001020
        begin_time_nsec = 2244629846780
#2  g_main_context_iterate
    (context=0x7fdbe8000b70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4271
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x7fdbe8001020
        begin_time_nsec = 2244629846780
#3  0x00007fde1d73054f in g_main_loop_run (loop=0x7fdbe8000da0) at ../glib/gmain.c:4479
        __func__ = "g_main_loop_run"
#4  0x00007fde17b2ec60 in WTF::RunLoop::run() () at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#5  0x00007fde17acef05 in WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) ()
    at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#6  0x00007fde17b3184d in WTF::wtfThreadEntryPoint(void*) ()
    at /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-6.0.so.1
#7  0x00007fde1c88f1da in start_thread (arg=<optimized out>) at pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>

                      unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140587516794432, 8393778983924328757, 140587516794432, -128, 11, 140724470158688, 8393778983939008821, 8393198346305333557}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#8  0x00007fde1c917f44 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

So Fedora got lucky in that there was a confusing build failure and I couldn't proceed until I figured out how to deal with it. But GNOME didn't even notice that the debuginfo had disappeared. Hence, we should be more cautious with -gsplit-dwarf.

**Comment by bertogg** [comment]
> Thing is, if Fedora debuginfo broke, there's a decent chance it will break other distros too. It's real easy to work around `-DDEBUG_FISSION=OFF` but defaults should be safe. @aperezdc could you check if buildroot can handle 2.39.90 please? @bertogg how about Debian? I will check GNOME flatpak runtimes (where the build succeeded, but that doesn't necessarily indicate the debuginfo is working).

I'm debian I'm passing `-DDEBUG_FISSION=OFF` manually because `dh_dwz` does not currently support the resulting binaries, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016936 and https://sourceware.org/bugzilla/show_bug.cgi?id=27375

**Comment by aperezdc** [comment]
I have one more reason to only add `-gsplit-dwarf` for developer builds. Configure the build to use link-time optimization, for example with:

```sh
CC=gcc CXX=g++ CFLAGS='-flto' CXXFLAGS='-flto' LDFLAGS='-flto' cmake -DPORT=GTK -S. -Bbuild-gtk-lto
```

Then your build output will be littered with one line of spam for each compiler invocation:

```
...
[62/6823] Building C object Source/ThirdParty/xdgmime/CMakeFiles/xdgmime.dir/src/xdgmimeparent.c.o
cc1: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling
[63/6823] Building C object Source/ThirdParty/xdgmime/CMakeFiles/xdgmime.dir/src/xdgmimemagic.c.o
cc1: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling
[64/6823] Building C object Source/ThirdParty/xdgmime/CMakeFiles/xdgmime.dir/src/xdgmimeint.c.o
cc1: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling
[65/6823] Building C object Source/ThirdParty/xdgmime/CMakeFiles/xdgmime.dir/src/xdgmimeicon.c.o
cc1: note: ‘-gsplit-dwarf’ is not supported with LTO, disabling
[66/6823] Building C object Source/ThirdParty/xdgmime/CMakeFiles/xdgmime.dir/src/xdgmime.c.o
...
```

**Comment by aperezdc** [comment]
@calvaris Is there any reason why you cannot configure your non-developer build with `cmake -DDEBUG_FISSION=ON ...` or with `CFLAGS='-gsplit-dwarf' CXXFLAGS='-gsplit-dwarf' cmake ...`? At this point I am more than convinced that trying to mangle compiler flags to determine when it's safe to add this option is a bad idea, and that the choice is best left to the person configuring the build&mdash;I'm considering going as far as recommending to _never_ add it automatically, not even in developer builds, because this would spam the build output, too:

```bash
CFLAGS='-flto' CXXFLAGS='-flto' LDFLAGS='-flto' Tools/Scripts/build-webkit --gtk
```

🙃

**Comment by calvaris** [comment]
> @calvaris Is there any reason why you cannot configure your non-developer build with `cmake -DDEBUG_FISSION=ON ...` or with `CFLAGS='-gsplit-dwarf' CXXFLAGS='-gsplit-dwarf' cmake ...`? At this point I am more than convinced that trying to mangle compiler flags to determine when it's safe to add this option is a bad idea, and that the choice is best left to the person configuring the build—I'm considering going as far as recommending to _never_ add it automatically, not even in developer builds, because this would spam the build output, too:
> 
> ```shell
> CFLAGS='-flto' CXXFLAGS='-flto' LDFLAGS='-flto' Tools/Scripts/build-webkit --gtk
> ```
> 
> upside_down_face

I guess I could, yes. Let me check.

**Comment by mcatanzaro** [comment]
OK, thanks.

**Review by aperezdc — APPROVED** [review]

**Pull request merged**
