### PR TITLE
Add initial stubs for the Navigation API

### PR DESCRIPTION
**Pull request by TingPing**
#### dccf27374c28f944ac520ac39178abe6d1183636
<pre>
Add initial stubs for the Navigation API
<a href="https://bugs.webkit.org/show_bug.cgi?id=262906">https://bugs.webkit.org/show_bug.cgi?id=262906</a>

Reviewed by Alex Christensen.

This patch adds a runtime feature flag for and the initial bindings
for the Navigation API. It does not implement any logic.

Spec: <a href="https://html.spec.whatwg.org/#navigation-api">https://html.spec.whatwg.org/#navigation-api</a>

* LayoutTests/fast/dom/navigation-type-back-forward-expected.txt:
* LayoutTests/fast/dom/navigation-type-navigate-expected.txt:
* LayoutTests/fast/dom/navigation-type-reload-expected.txt:
* LayoutTests/fast/dom/resources/navigation-type-matches-querystring.html:
* LayoutTests/fast/dom/webtiming-expected.txt:
* LayoutTests/fast/dom/webtiming.html:
* LayoutTests/http/tests/misc/resources/webtiming-cross-origin-and-back2.html:
* LayoutTests/http/tests/misc/resources/webtiming-cross-origin-redirect.html:
* LayoutTests/http/tests/misc/resources/webtiming-one-redirect.html:
* LayoutTests/http/tests/misc/resources/webtiming-two-redirects.html:
* LayoutTests/http/tests/misc/webtiming-cross-origin-and-back1-expected.txt:
* LayoutTests/http/tests/misc/webtiming-cross-origin-redirect-expected.txt:
* LayoutTests/http/tests/misc/webtiming-no-origin-expected.txt:
* LayoutTests/http/tests/misc/webtiming-no-origin.html:
* LayoutTests/http/tests/misc/webtiming-one-redirect-expected.txt:
* LayoutTests/http/tests/misc/webtiming-two-redirects-expected.txt:
* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WebCore/CMakeLists.txt:
* Source/WebCore/DerivedSources-input.xcfilelist:
* Source/WebCore/DerivedSources-output.xcfilelist:
* Source/WebCore/DerivedSources.make:
* Source/WebCore/Sources.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/bindings/js/WebCoreBuiltinNames.h:
* Source/WebCore/dom/EventNames.h:
* Source/WebCore/dom/EventNames.in:
* Source/WebCore/dom/EventTargetFactory.in:
* Source/WebCore/page/LocalDOMWindow.cpp:
(WebCore::LocalDOMWindow::navigation):
* Source/WebCore/page/LocalDOMWindow.h:
* Source/WebCore/page/LocalDOMWindow.idl:
* Source/WebCore/page/NavigateEvent.cpp: Added.
(WebCore::NavigateEvent::NavigateEvent):
(WebCore::NavigateEvent::create):
(WebCore::NavigateEvent::intercept):
(WebCore::NavigateEvent::scroll):
(WebCore::NavigateEvent::eventInterface const):
* Source/WebCore/page/NavigateEvent.h: Added.
* Source/WebCore/page/NavigateEvent.idl: Added.
* Source/WebCore/page/Navigation.cpp: Added.
(WebCore::Navigation::Navigation):
(WebCore::createNewResult):
(WebCore::Navigation::scriptExecutionContext const):
(WebCore::Navigation::eventTargetInterface const):
(WebCore::Navigation::navigate):
(WebCore::Navigation::reload):
(WebCore::Navigation::traverseTo):
(WebCore::Navigation::back):
(WebCore::Navigation::forward):
(WebCore::Navigation::updateCurrentEntry):
* Source/WebCore/page/Navigation.h: Added.
* Source/WebCore/page/Navigation.idl: Added.
* Source/WebCore/page/NavigationCurrentEntryChangeEvent.cpp: Added.
(WebCore::NavigationCurrentEntryChangeEvent::NavigationCurrentEntryChangeEvent):
(WebCore::NavigationCurrentEntryChangeEvent::create):
(WebCore::NavigationCurrentEntryChangeEvent::eventInterface const):
* Source/WebCore/page/NavigationCurrentEntryChangeEvent.h: Added.
* Source/WebCore/page/NavigationCurrentEntryChangeEvent.idl: Added.
* Source/WebCore/page/NavigationDestination.cpp: Added.
* Source/WebCore/page/NavigationDestination.h: Added.
* Source/WebCore/page/NavigationDestination.idl: Added.
* Source/WebCore/page/NavigationHistoryEntry.cpp: Added.
(WebCore::NavigationHistoryEntry::NavigationHistoryEntry):
(WebCore::NavigationHistoryEntry::scriptExecutionContext const):
(WebCore::NavigationHistoryEntry::eventTargetInterface const):
* Source/WebCore/page/NavigationHistoryEntry.h: Added.
* Source/WebCore/page/NavigationHistoryEntry.idl: Added.
* Source/WebCore/page/NavigationInterceptHandler.h: Added.
* Source/WebCore/page/NavigationInterceptHandler.idl: Added.
* Source/WebCore/page/NavigationNavigationType.h: Added.
* Source/WebCore/page/NavigationTransition.cpp: Added.
* Source/WebCore/page/NavigationTransition.h: Added.
* Source/WebCore/page/NavigationTransition.idl: Added.
* Source/WebCore/page/NavigationNavigationType.idl: Added.
* Source/WebCore/page/Navigator.cpp:

Canonical link: <a href="https://commits.webkit.org/269937@main">https://commits.webkit.org/269937@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/6d2e93c22b12e7101a186e0612449e36b43f662c

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/23732 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/1846 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/24844 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/25885 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/21901 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/24005 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/3437 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/24253 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/22442 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/23975 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/1396 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/20528 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/26481 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/1176 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/21441 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/27698 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/20650 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/21648 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/21708 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/25475 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/23065 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/1140 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/18836 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/30459 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/1130 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/21207 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/6692 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/1552 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/30413 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/3068 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/1442 "Built successfully") | | [❌ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/6361 "Found 1 new JSC stress test failure: microbenchmarks/array-from-object-func.js.lockdown (failure)") |

### CODE REVIEW

**Comment by TingPing** [comment]
This was reverted due to a build failure on WPE.

**Comment by TingPing** [comment]
@dpino r? - I fixed the WPE build.

**Review by rwlbuis — APPROVED** [review]
LGTM.

**Comment by dpino** [comment]
LGTM too.

**Pull request merged**
