### PR TITLE
[WebIDL] Cache extended attributes of WebIDL file

### PR DESCRIPTION
**Pull request by dpino**
#### c7da26fb5135a2b9863bab32fda8ede1980183fe
<pre>
[WebIDL] Cache extended attributes of WebIDL file
<a href="https://bugs.webkit.org/show_bug.cgi?id=241960">https://bugs.webkit.org/show_bug.cgi?id=241960</a>

Reviewed by Darin Adler.

* Source/WebCore/bindings/scripts/CodeGenerator.pm:

(GetInterfaceExtendedAttributesFromName): Store results into a cache
indexeded by IDL filename, so we don&apos;t need to parse the same file
again.
(ComputeIsCallbackInterface): Use slurp function to read file contents.
(ComputeIsCallbackFunction): Use slurp function to read file contents.

Canonical link: <a href="https://commits.webkit.org/255617@main">https://commits.webkit.org/255617@main</a>
</pre>

https://github.com/False/commit/1f8c9e398af4817d65e6acf3a146a8015a4ee85c

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/84131 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/28086 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/15341 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/92120 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/146115 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/88139 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/26447 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/23698 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/76257 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/88566 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/89709 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/21515 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/71510 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/21716 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/76613 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/77253 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/64833 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/24531 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/11108 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/24435 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/12009 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3891 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/26043 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/35070 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/25976 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/31366 "Passed tests") | |

### CODE REVIEW

**Comment by weinig** [comment]
Is there a mechanism to invalidate the cache when the IDL changes?

**Comment by dpino** [comment]
> Is there a mechanism to invalidate the cache when the IDL changes?

I implemented the same mechanism used by `GetDictionaryByType` or `GetEnumByType`.

**Comment by darinadler** [comment]
> Is there a mechanism to invalidate the cache when the IDL changes?

No. But it’s an in-memory cache during the runtime of the script, not an on-disk cache.

**Review by darinadler — APPROVED** [review]
This is fine.

**Pull request merged**
