### PR TITLE
[COCOA] Add support for web-platform-tests custom domains when running layout tests

### PR DESCRIPTION
**Pull request by rreno**
#### d1a0bead6557831d3f99e787955d9c3d962e014d
<pre>
[COCOA] Add support for web-platform-tests custom domains when running layout tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=245294">https://bugs.webkit.org/show_bug.cgi?id=245294</a>
rdar://100337257

Reviewed by NOBODY (OOPS!).

Leverage CFNetwork SPI to support web-platform-tests custom domains when running
WPT tests on Cocoa ports. Glib ports already support this.

* LayoutTests/imported/w3c/web-platform-tests/*:
Rebaseline WPT tests now that they are properly run on the web-platform-tests custom
domain instead of localhost. Some more tests can be unskipped too but I&apos;ll do this
in a follow-up patch given the patch size.
</pre>
https://github.com/WebKit/WebKit/commit/d1a0bead6557831d3f99e787955d9c3d962e014d

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/100971 "2 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/10125 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/34022 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/110275 "Built successfully") | [❌ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/170535 "Hash d1a0bead for PR 7894 does not build (failure)") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/11056 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/996 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/93378 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/108111 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/106754 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/8366 "Found 60 new test failures: compositing/reflections/mask-and-reflection.html, contact-picker/contacts-select-after-dismissing-picker.html, fast/canvas/image-pattern-rotate.html, http/tests/app-privacy-report/app-attribution-beacon-isappinitiated.html, http/tests/app-privacy-report/user-attribution-cors-preflight-redirect.html, http/tests/blink/sendbeacon/beacon-cookie.html, http/tests/cache/disk-cache/disk-cache-remove-several-pending-writes.html, http/tests/workers/service/serviceworker-websocket.https.html, http/wpt/beacon/cors/crossorigin-arraybufferview-no-preflight.html, imported/w3c/web-platform-tests/content-security-policy/form-action/form-action-src-blocked.sub.html ... (failure)") | [❌ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/91622 "Found 11 new API test failures: TestWebKitAPI.Preconnect.HTTPS, TestWebKitAPI.RemoteObjectRegistry.SerializeErrorWithCertificates, TestWebKitAPI.TLSVersion.NetworkSessionNSUserDefaults, TestWebKitAPI.Challenge.ClientCertificate, TestWebKitAPI.TLSVersion.DidNegotiateModernTLS, TestWebKitAPI.Preconnect.H2PingFromWebCoreNSURLSession, TestWebKitAPI.TLSVersion.ShouldAllowDeprecatedTLS, TestWebKitAPI.WKDownload.ChallengeFailure, TestWebKitAPI.WebKit.ServerTrust, TestWebKitAPI.WKDownload.ChallengeSuccess ... (failure)") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/34970 "Found 3 new test failures: imported/w3c/web-platform-tests/content-security-policy/form-action/form-action-src-blocked.sub.html, imported/w3c/web-platform-tests/content-security-policy/worker-src/service-worker-src-child-fallback.https.sub.html, imported/w3c/web-platform-tests/html/capability-delegation/delegate-fullscreen-request-subframe-cross-origin.https.sub.tentative.html (failure)") | 
| | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/90274 "Found 13 new API test failures: TestWebKitAPI.Preconnect.HTTPS, TestWebKitAPI.RemoteObjectRegistry.SerializeErrorWithCertificates, TestWebKitAPI.TLSVersion.NetworkSessionNSUserDefaults, TestWebKitAPI.Challenge.ClientCertificate, TestWebKitAPI.TLSVersion.DidNegotiateModernTLS, TestWebKitAPI.WebKit.QuotaDelegateNavigateFragment, TestWebKitAPI.Preconnect.H2PingFromWebCoreNSURLSession, TestWebKitAPI.TLSVersion.ShouldAllowDeprecatedTLS, TestWebKitAPI.WKDownload.ChallengeFailure, TestWebKitAPI.WebKit.ServerTrust ... (failure)") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/23021 "Found 60 new test failures: http/tests/appcache/fail-on-update-2.html, http/tests/appcache/remove-cache.html, http/tests/inspector/network/getSerializedCertificate.html, http/tests/media/video-play-stall.html, http/tests/security/contentSecurityPolicy/embed-redirect-blocked3.html, http/tests/security/contentSecurityPolicy/object-redirect-blocked3.html, http/tests/security/contentSecurityPolicy/report-status-code-zero-when-using-https.html, http/tests/security/contentSecurityPolicy/userAgentShadowDOM/allow-object.html, http/tests/security/mixedContent/insecure-image-redirects-to-basic-auth-secure-image.html, http/tests/security/mixedContent/secure-redirect-to-insecure-redirect-to-basic-auth-secure-image.https.html ... (failure)") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/77956 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/3798 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/24539 "Found 60 new test failures: accessibility/mac/value-change/value-change-user-info-textfield.html, http/tests/appcache/fail-on-update-2.html, http/tests/navigation/subframe-pagehide-handler-starts-load2.html, http/wpt/beacon/cors/crossorigin-arraybufferview-no-preflight.html, http/wpt/cache-storage/cache-quota-add.any.html, http/wpt/cache-storage/cache-quota.any.html, http/wpt/fetch/response-opaque-clone.html, http/wpt/service-workers/server-trust-evaluation.https.html, http/wpt/webrtc/sframe-transform-error.html, http/wpt/webrtc/third-party-frame-ice-candidate-filtering.html ... (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/3826 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/1014 "Found 60 new test failures: animations/stop-animation-on-suspend.html, fast/images/avif-as-image.html, http/tests/eventsource/eventsource-reconnect.html, http/tests/fetch/fetch-redirect-same-origin-authorization.html, http/tests/permissions/permission-status-onchange-event-dedicated-worker.html, http/tests/workers/service/serviceworker-websocket.https.html, http/wpt/beacon/cors/crossorigin-arraybufferview-no-preflight.html, http/wpt/service-workers/server-trust-evaluation.https.html, imported/w3c/web-platform-tests/content-security-policy/gen/top.meta/script-src-wildcard/sharedworker-import.https.html, imported/w3c/web-platform-tests/content-security-policy/worker-src/service-worker-src-child-fallback.https.sub.html ... (failure)") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/9937 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/44043 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/5594 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by rreno** [comment]
This is @cdumez 's work from #4438 rebased and ready for the Ventura EWS bots.

**Comment by brentfulgham** [comment]
Is it finally happening?!? 😀

**Comment by rreno** [comment]
Style error is due to some spacing around braces in DumpRenderTree.mm but the style matches the surrounding code.

**Comment by rreno** [comment]
There are a lot of regressions even on Ventura bots :(

Many subtests which were previously passing are now failing due to promise rejections and other issues.

There's also some progressions.

**Comment by rreno** [comment]
I audited 30 of the 60 failing tests on mac-AS-debug-wk2 (the Ventura bot). There's likely more than 60 failures but we bailed out early.

I defined 4 categories of diffs:

1. Trivial to fix - things like different console output, progressions on top of what's in this PR, etc.
2. Regressions both locally and on EWS.
3. Regressions only on EWS. (vs. debug and release runs of the tests locally)
4. Regressions which are only local.

The results I got out of the 30 tests that failed:
    14 tests are trivial to fix
    5 tests regressed both locally and on EWS.
    11 tests regressed on EWS only.
    0 tests regressed locally.
    

It's not a large sample size and I really don't know how much more there would be to audit beyond these 60 tests, but this isn't promising. Over 1/3 of the tests I looked at are EWS-only regressions. The point of this work is so that EWS and local testing with custom domains are consistent.

**Comment by mdubet** [comment]
Ultra nitpick: the commit message should use `Cocoa` and not `COCOA`.

**Pull request closed without merging**
