### PR TITLE
Remove support for the hspace and vspace on table

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>

Remove support for the hspace and vspace attributes on table
<a href="https://bugs.webkit.org/show_bug.cgi?id=120133">https://bugs.webkit.org/show_bug.cgi?id=120133</a>

Reviewed by NOBODY (OOPS!).

Partial Merge - Since Webkit does not use "User Counter" - <a href="https://src.chromium.org/viewvc/blink?view=revision&revision=195601">https://src.chromium.org/viewvc/blink?view=revision&revision=195601</a>

It will align Webkit with Blink, Gecko and Web-spec.

* LayoutTests/imported/w3c/web-platform-tests/html/rendering/non-replaced-elements/tables/table-vspace-hspace-expected.txt: Updated Expectations to 'PASS'.
* LayoutTests/imported/w3c/web-platform-tests/html/rendering/non-replaced-elements/tables/table-vspace-hspace-s-expected.txt: Updated Expectations to 'PASS'.
* LayoutTests/imported/w3c/web-platform-tests/html/rendering/unmapped-attributes-expected.txt: Updated Expectations to 'PASS'.
* LayoutTests/platform/glib/tables/mozilla/bugs/bug1261-expected.txt: Rebased RenderTable.
* LayoutTests/platform/gtk/tables/mozilla/bugs/bug1261-expected.png: Updated based on new expectations.
* LayoutTests/platform/ios/tables/mozilla/bugs/bug1261-expected.txt: Rebased RenderTable.
* LayoutTests/platform/mac/tables/mozilla/bugs/bug1261-expected.png: Updated based on new expectations.
* LayoutTests/platform/mac/tables/mozilla/bugs/bug1261-expected.txt: Rebased RenderTable.
* Source/WebCore/html/HTMLTableElement.cpp
(HTMLTableElement::collectPresentationalHintsForAttribute): Removed 'hspace' and 'vspace' attributes on table to match with all other browsers.

</pre>

https://github.com/WebKit/WebKit/commit/7a8b822957edacd521f19ce9ce851704cdd927dc

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/86920 "failed check-webkit-style (failure)") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/31003 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/17788 "Built successfully") | [❌ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/95750 "Hash 7a8b8229 for PR 3573 does not build") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/149506 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/90899 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/29365 "Built successfully") | [  ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/25689 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/79065 "Hash 7a8b8229 for PR 3573 does not build") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/90971 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/92536 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/23709 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/73772 "Built successfully") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/36/builds/79065 "Hash 7a8b8229 for PR 3573 does not build") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/78706 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/78997 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/36/builds/79065 "Hash 7a8b8229 for PR 3573 does not build") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/27116 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/12840 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/27051 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/13854 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/28730 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/36717 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/28674 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/33133 "Passed tests") | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@rniwa - Is "bug1261" test case required? I fixed all other tests on local repo and can push and squash the commit? Appreciate if you can confirm and I will do the needful. Thanks!

**Review by rniwa — APPROVED** [review]
r=me

**Comment by Ahmad-S792** [comment]
@rniwa Will merge-queue and Labels be added automatically? Since I don't have access and I am not committer, so I am not sure.

**Comment by rniwa** [comment]
> @rniwa Will merge-queue and Labels be added automatically? Since I don't have access and I am not committer, so I am not sure.

No, I need to add it. I'm waiting for Mac EWS bots' results.

**Review by rniwa — APPROVED** [review]
r=me

**Comment by JonWBedard** [comment]
@Ahmad-S792 Your PR description is great, that should be your commit message, that's what `merge-queue` is complaining about

**Comment by Ahmad-S792** [comment]
> @Ahmad-S792 Your PR description is great, that should be your commit message, that's what `merge-queue` is complaining about

I messed up, I updated commit message via amend (I use GitHub Desktop, not CLI) and then when I tried to Pull Origin, it created three commits and I am unable to squash them. :-( Any suggestion or tips?

**Comment by JonWBedard** [comment]
> > @Ahmad-S792 Your PR description is great, that should be your commit message, that's what `merge-queue` is complaining about
> 
> I messed up, I updated commit message via amend (I use GitHub Desktop, not CLI) and then when I tried to Pull Origin, it created three commits and I am unable to squash them. :-( Any suggestion or tips?

You'll need to squash and then force push, this looks like GitHub's documentation on that https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits
(I don't use GitHub Desktop, so I'm just reading through documentation knowing how git works under the hood, that _should_ be the right thing)

**Comment by Ahmad-S792** [comment]
> > > @Ahmad-S792 Your PR description is great, that should be your commit message, that's what `merge-queue` is complaining about
> > 
> > 
> > I messed up, I updated commit message via amend (I use GitHub Desktop, not CLI) and then when I tried to Pull Origin, it created three commits and I am unable to squash them. :-( Any suggestion or tips?
> 
> You'll need to squash and then force push, this looks like GitHub's documentation on that https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits (I don't use GitHub Desktop, so I'm just reading through documentation knowing how git works under the hood, that _should_ be the right thing)

Damn! It is giving me same error, which I showed to @rniwa on Slack Channel. I am going to close this and create a new one. :-(

**Pull request closed without merging**
