### PR TITLE
[JHBuild] bump libsoup to 3.4.4

### PR DESCRIPTION
**Pull request by mxschmitt**
#### 65166a885bf2a95360543c7f5ebeafedcb5a7e08
<pre>
[JHBuild] bump libsoup to 3.4.4
<a href="https://bugs.webkit.org/show_bug.cgi?id=266514">https://bugs.webkit.org/show_bug.cgi?id=266514</a>

* Tools/gtk/jhbuild.modules:
* Tools/jhbuild/jhbuild-minimal.modules:
* Tools/wpe/jhbuild.modules:
</pre>
https://github.com/WebKit/WebKit/commit/65166a885bf2a95360543c7f5ebeafedcb5a7e08

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/30767 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/9445 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/32434 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/33262 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/27800 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/31513 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/11750 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/6691 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/27677 "Passed tests") | [⏳ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/31080 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/7923 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/27524 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/6794 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/6947 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/27400 "Passed tests") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/27996 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/27883 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/34599 "Built successfully") | 
| | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-1-Build-EWS "Waiting in queue, processing has not started yet") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/5078 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/33106 "Passed tests") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/30947 "Passed tests") | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/11874 "") | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | | | 
| [❌ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/8544 "") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/6987 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/8704 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/7704 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/7543 "Built successfully") | | |

### CODE REVIEW

**Comment by mxschmitt** [comment]
Turns out this patch broke cookie parsing somewhere between this range, have to bisect it first before bumping it.

**Comment by mxschmitt** [comment]
Behaviour has changed in https://gitlab.gnome.org/GNOME/libsoup/-/commit/81242200168043bd71295845df10206cd47a227a.

**Comment by TingPing** [comment]
This looks fine to me.

The behavior change is already known and documented here: https://bugs.webkit.org/show_bug.cgi?id=264804

The test expectations should already be up to date for it as the Flatpak SDK already ships this version.

**Review by carlosgcampos — APPROVED** [review]

**Comment by mxschmitt** [comment]
The problem for us in Playwright is that we are using the Inspector method [Page.setCookie](https://github.com/WebKit/WebKit/blob/41ce5164a75ae8558a06100e1969f0e9fe94ed21/Source/WebCore/inspector/agents/InspectorPageAgent.cpp#L741) which internally will end up in [NetworkStorageSession::setCookie](https://github.com/WebKit/WebKit/blob/41ce5164a75ae8558a06100e1969f0e9fe94ed21/Source/WebCore/platform/network/soup/NetworkStorageSessionSoup.cpp#L402). This calls soup's `soup_cookie_jar_add_cookie` which got [changed in soup](https://gitlab.gnome.org/GNOME/libsoup/-/commit/81242200168043bd71295845df10206cd47a227a) (regression 1).

This change would result that e.g. this test would either if we don't change anything ends up in 0 cookies being added (since soup filters them out) or if we by default add cookies as `Lax`, then there is a behaviour difference between WebKit on macOS and WebKit on Linux:

https://github.com/microsoft/playwright/blob/5752a28f877c09301b9a465fb94d8729f2750051/tests/library/browsercontext-add-cookies.spec.ts#L227-L244

(that is `Lax` on Linux while `None` on macOS)

---

It looks like also for us [`document.cookie = 'username=John Doe';`](https://github.com/microsoft/playwright/blob/821949d580eb953176d5bc38a2aa416b2707dd88/tests/library/browsercontext-cookies.spec.ts#L24-L41) should create a `sameSite: None` cookie while it does `sameSite: Lax` (regression 2). Note: Chromium e.g. does `sameSite: Lax`, but WebKit for Linux and macOS should be aligned imo. Safari/TP does also `None`. I bisected this one as well and this got broken by [efc5efba6db6478a5fcb8c938ef0dcd10b35b136](https://gitlab.gnome.org/GNOME/libsoup/-/commit/efc5efba6db6478a5fcb8c938ef0dcd10b35b136).

--- 

Will talk with our team about it, since so far I only did the investigation, so might expect an update here later today.

**Comment by mcatanzaro** [comment]
The expected behavior is for WebKit on Linux to match what WebKit does on macOS. A bug report would be appreciated.

**Comment by mxschmitt** [comment]
Thanks @mcatanzaro will do later today!

**Comment by TingPing** [comment]
> The expected behavior is for WebKit on Linux to match what WebKit does on macOS. A bug report would be appreciated.

The change in libsoup was purposeful. It is more secure and what other browsers do. I don't think we should degrade WebKitGTK to match macOS.

**Comment by TingPing** [comment]
Ah seems like some actual bugs in it anyway, I'll take a look at them.

**Pull request closed without merging**
