### PR TITLE
Re-Import html/canvas WPT

### PR DESCRIPTION
**Pull request by karlcow**
#### e566b199750f5a4633391d3425fc3ea593950a2a
<pre>
Re-Import html/canvas WPT
<a href="https://bugs.webkit.org/show_bug.cgi?id=274304">https://bugs.webkit.org/show_bug.cgi?id=274304</a>
<a href="https://rdar.apple.com/128259734">rdar://128259734</a>

Reviewed by NOBODY (OOPS!).

Re-import WPT html/canvas

Upstream commit: <a href="https://github.com/web-platform-tests/wpt/commit/ce170e706888ba461779cdd228b25ec2fbaf8793">https://github.com/web-platform-tests/wpt/commit/ce170e706888ba461779cdd228b25ec2fbaf8793</a>

* LayoutTests/imported/w3c/resources/resource-files.json:
* LayoutTests/imported/w3c/web-platform-tests/html/canvas/*:
  Re-importing, deleting, modifying a lot of the expected file in that WPT directory.

* LayoutTests/imported/w3c/web-platform-tests/html/canvas/w3c-import.log:
* LayoutTests/TestExpectations:
* LayoutTests/platform/ios/TestExpectations:
* LayoutTests/platform/mac/TestExpectations:
* LayoutTests/platform/mac-wk1/TestExpectations:
* LayoutTests/platform/mac-wk2/TestExpectations:
* LayoutTests/platform/wpe/TestExpectations:

* LayoutTests/imported/w3c/web-platform-tests/html/canvas/tools/gentestutilsunion.py:
  Fixes for the style checker which probably needs to be fixed on WPT.
  Or ignored locally.
* LayoutTests/imported/w3c/web-platform-tests/html/canvas/tools/yaml-new/text.yaml:
</pre>
https://github.com/WebKit/WebKit/commit/e566b199750f5a4633391d3425fc3ea593950a2a

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/53356 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/32707 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/5855 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/56636 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/4082 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/55662 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/40155 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/3840 "Built successfully") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/43258 "Found 2 new test failures: imported/w3c/web-platform-tests/html/canvas/offscreen/path-objects/2d.path.roundrect.1.radius.dompoint.single argument.worker.html, imported/w3c/web-platform-tests/html/canvas/offscreen/text/2d.text.measure.advances-not-defined.worker.html (failure)") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/2677 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/55454 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/30915 "Exiting early after 10 failures. 3622 tests run. 1 failures") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/46089 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/24389 "Passed tests") | 
| | [❌ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/27797 "Found 5 new test failures: imported/w3c/web-platform-tests/html/canvas/element/manual/drawing-images-to-the-canvas/image-orientation/drawImage-from-blob.tentative.html, imported/w3c/web-platform-tests/html/canvas/element/manual/filters/canvas-filter-opacity.html, imported/w3c/web-platform-tests/html/canvas/element/manual/shadows/canvas_shadows_system_colors.html, imported/w3c/web-platform-tests/html/canvas/offscreen/path-objects/2d.path.roundrect.1.radius.dompoint.single argument.worker.html, imported/w3c/web-platform-tests/html/canvas/offscreen/text/2d.text.measure.advances-not-defined.worker.html (failure)") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/3409 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/2238 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/49556 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/3576 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/58231 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/28506 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/3605 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/50658 "Found 38 new test failures: imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.w.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.worker.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.w.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.worker.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.w.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.worker.html, imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.html ... (failure)") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/29720 "Built successfully") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/46417 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/49989 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/30644 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/29484 "Built successfully") | | |

### CODE REVIEW

**Review by nt1m — APPROVED** [review]

**Comment by karlcow** [comment]
So these are the list of tests currently failing.

```
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.discrete.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.gamma.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.identity.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.linear.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.table.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.dropShadow.html
imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.gaussianBlur.html
imported/w3c/web-platform-tests/html/canvas/element/manual/filters/svg-filter-lh-rlh.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.discrete.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.discrete.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.gamma.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.gamma.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.identity.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.linear.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.linear.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.table.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.table.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.dropShadow.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.dropShadow.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.gaussianBlur.html
imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.gaussianBlur.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-layers.html
imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-layers.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-nested-layers.html
imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-nested-layers.w.html
imported/w3c/web-platform-tests/html/canvas/offscreen/path-objects/2d.path.roundrect.1.radius.dompoint.single.argument.worker.html
imported/w3c/web-platform-tests/html/canvas/offscreen/text/2d.text.measure.advances.worker.html
```

**Comment by karlcow** [comment]
The type of failures is interesting.

**Comment by karlcow** [comment]
```
7 tests ran as expected, 43 didn't:


Regressions: Unexpected image-only failures (25)
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.discrete.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.gamma.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.identity.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.linear.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.componentTransfer.table.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.dropShadow.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/element/filters/2d.filter.layers.gaussianBlur.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.discrete.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.gamma.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.linear.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.table.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.dropShadow.html [ ImageOnlyFailure ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.gaussianBlur.html [ ImageOnlyFailure ]

Regressions: Unexpected timeouts (18)
  imported/w3c/web-platform-tests/html/canvas/element/manual/filters/svg-filter-lh-rlh.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.discrete.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.gamma.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.identity.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.linear.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.componentTransfer.table.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.canvasFilterObject.gaussianBlur.tentative.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.discrete.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.gamma.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.identity.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.linear.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.componentTransfer.table.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.dropShadow.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/filters/2d.filter.layers.gaussianBlur.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-layers.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-layers.w.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-nested-layers.html [ Timeout ]
  imported/w3c/web-platform-tests/html/canvas/offscreen/manual/layers/unclosed-nested-layers.w.html [ Timeout ]
```

**Comment by karlcow** [comment]
Also opened a bug on https://github.com/web-platform-tests/wpt/issues/46508 for the python script

**Comment by karlcow** [comment]
By mistake I have forgotten to put myself in my local branch. So Let me close here. 
The story will happen now on https://github.com/WebKit/WebKit/pull/29210

**Pull request closed without merging**
