### PR TITLE
Merge WebGL2 enablement flag with WebGL flag

### PR DESCRIPTION
**Pull request by brentfulgham**
#### e3bf17995e0543582de0d43c9b8429ba2716eb2e
<pre>
Merge WebGL2 enablement flag with WebGL flag
<a href="https://bugs.webkit.org/show_bug.cgi?id=248667">https://bugs.webkit.org/show_bug.cgi?id=248667</a>
&lt;rdar://problem/102910963&gt;

Reviewed by Kimmo Kinnunen.

We&apos;ve been shipping WebGL2 for many years, and no longer need a separate WebGL2 flag. Instead, we
should merge the WebGL2 enablement flag (and compile guards) with the higher-level WebGL feature.

* LayoutTests/fast/canvas/webgl/buffer-data-subdata-dynamic-buffer.html: No need to enable WebGL2 explicitly.
* LayoutTests/fast/canvas/webgl/bufferData-offset-length.html: Ditto.
* LayoutTests/fast/canvas/webgl/copyBufferSubData.html: Ditto.
* LayoutTests/fast/canvas/webgl/getBufferSubData-webgl1.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-buffer-targets.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-buffers.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-context-creation.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-getActiveUniforms.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-getbuffersubdata.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-glsl3-compile.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-runtime-flag.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-texStorage.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2-texture-upload-enums.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2/bindings.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2/constants.html: Ditto.
* LayoutTests/fast/canvas/webgl/webgl2/sequences.html: Ditto.
* LayoutTests/inspector/canvas/create-context-webgl2.html: Ditto.
* LayoutTests/inspector/canvas/recording-webgl2-snapshots.html: Ditto.
* LayoutTests/inspector/canvas/requestContent-webgl2.html: Ditto.
* LayoutTests/inspector/canvas/resolveContext-webgl2.html: Ditto.
* LayoutTests/inspector/canvas/resources/recording-webgl2.js: Ditto.
* LayoutTests/inspector/canvas/shaderProgram-add-remove-webgl2.html: Ditto.
* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml: Remove WebGL2 flag.
* Source/WTF/wtf/PlatformEnable.h: Ditto.
* Source/WTF/wtf/PlatformEnableCocoa.h: Ditto.
* Source/WebCore/Modules/webxr/WebXROpaqueFramebuffer.cpp: Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/Modules/webxr/WebXRWebGLLayer.cpp: Ditto.
* Source/WebCore/Modules/webxr/WebXRWebGLLayer.h: Ditto.
* Source/WebCore/Modules/webxr/WebXRWebGLLayer.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/bindings/js/JSDOMConvertWebGL.cpp:
(WebCore::convertToJSValue): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/bindings/js/JSWebGL2RenderingContextCustom.cpp:
* Source/WebCore/dom/Document.cpp:
(WebCore::Document::getCSSCanvasContext): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/dom/Document.h:
* Source/WebCore/dom/Document.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/html/HTMLCanvasElement.cpp:
(WebCore::HTMLCanvasElement::getContext): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
(WebCore::HTMLCanvasElement::isWebGLType): Ditto.
(WebCore::HTMLCanvasElement::toWebGLVersion): Ditto.
* Source/WebCore/html/HTMLCanvasElement.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/html/OffscreenCanvas.cpp:
(WebCore::OffscreenCanvas::createContextWebGL): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
(WebCore::OffscreenCanvas::getContext): Ditto.
* Source/WebCore/html/OffscreenCanvas.h:
* Source/WebCore/html/OffscreenCanvas.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/html/canvas/WebGL2RenderingContext.cpp: Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/html/canvas/WebGL2RenderingContext.h: Ditto.
* Source/WebCore/html/canvas/WebGL2RenderingContext.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/html/canvas/WebGLAny.h:
* Source/WebCore/html/canvas/WebGLRenderingContextBase.cpp:
(WebCore::WebGLRenderingContextBase::create): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
(WebCore::WebGLRenderingContextBase::getBufferParameter): Ditto.
(WebCore::WebGLRenderingContextBase::getProgramParameter): Ditto.
(WebCore::WebGLRenderingContextBase::validateTexFuncFormatAndType): Ditto.
(WebCore::WebGLRenderingContextBase::useProgram): Ditto.
* Source/WebCore/html/canvas/WebGLRenderingContextBase.h:
* Source/WebCore/html/canvas/WebGLTransformFeedback.cpp: Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/html/canvas/WebGLTransformFeedback.h: Ditto.
* Source/WebCore/html/canvas/WebGLTransformFeedback.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/html/canvas/WebGLVertexArrayObject.cpp: Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/html/canvas/WebGLVertexArrayObject.h: Ditto.
* Source/WebCore/html/canvas/WebGLVertexArrayObject.idl: Switch enablement from WebGL2 to WebGL.
* Source/WebCore/inspector/InspectorCanvas.cpp:
(WebCore::InspectorCanvas::resolveContext const): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
(WebCore::shouldSnapshotWebGLAction): Ditto.
(WebCore::InspectorCanvas::recordAction): Ditto.
(WebCore::InspectorCanvas::buildObjectForCanvas): Ditto.
(WebCore::InspectorCanvas::releaseObjectForRecording): Ditto.
* Source/WebCore/inspector/InspectorCanvasCallTracer.h:
* Source/WebCore/inspector/agents/InspectorCanvasAgent.cpp:
(WebCore::InspectorCanvasAgent::startRecording): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/page/PageConsoleClient.cpp: Ditto.
(WebCore::canvasRenderingContext): Ditto.
* Source/WebCore/platform/graphics/GraphicsContextGLAttributes.h:
* Source/WebCore/platform/graphics/gbm/GraphicsContextGLFallback.cpp:
(WebCore::GraphicsContextGLFallback::platformInitializeContext): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/platform/graphics/gbm/GraphicsContextGLGBM.cpp:
(WebCore::GraphicsContextGLGBM::platformInitializeContext): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebCore/platform/graphics/texmap/GraphicsContextGLTextureMapperANGLE.cpp:
(WebCore::GraphicsContextGLTextureMapperANGLE::platformInitializeContext): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
(WebCore::GraphicsContextGLTextureMapperANGLE::platformInitialize): Ditto.
* Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in: Ditto.
* Source/WebKit/WebProcess/GPU/graphics/RemoteGraphicsContextGLProxy.cpp:
(WebKit::RemoteGraphicsContextGLProxy::isGLES2Compliant const): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebKit/WebProcess/Inspector/WebInspectorUI.cpp:
(WebKit::WebInspectorUI::enableFrontendFeatures): Move ENABLE(WEBGL2) code into ENABLE(WEBGL) block.
* Source/WebKit/WebProcess/WebPage/WebPage.cpp:
(WebKit::adjustSettingsForLockdownMode): Remove reference to WebGL2 feature flag.
* Source/WebKitLegacy/mac/WebView/WebPreferenceKeysPrivate.h:
* Source/WebKitLegacy/mac/WebView/WebPreferences.mm:
(-[WebPreferences webGL2Enabled]): Replace with stub.
(-[WebPreferences setWebGL2Enabled:]): Ditto.
* Source/WebKitLegacy/mac/WebView/WebPreferencesPrivate.h:
* Source/cmake/OptionsGTK.cmake: Remove WEBGL2 macro enablement.
* Source/cmake/OptionsMac.cmake: Ditto.
* Source/cmake/OptionsWPE.cmake: Ditto.
* Source/cmake/OptionsWin.cmake: Ditto.
* Source/cmake/WebKitFeatures.cmake: Ditto.
* Tools/DumpRenderTree/win/DumpRenderTree.cpp:
(enableExperimentalFeatures):
* Tools/Scripts/webkitperl/FeatureList.pm:

Canonical link: <a href="https://commits.webkit.org/259690@main">https://commits.webkit.org/259690@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/244ea6592cc1f03088f9709865d93e4d70eaeed1

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/105544 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/14635 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/38442 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/114797 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/174939 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/109444 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/16054 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/5858 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/97840 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/114633 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/111300 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/12207 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/95191 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/39702 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/94071 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/26827 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/81404 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/95305 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/7921 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/28183 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/93443 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/83/builds/5695 "Built successfully and passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/8332 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/4772 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/30386 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/14045 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/47726 "Passed tests") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/102153 "Built successfully") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/6698 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/9941 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/25469 "Passed tests") | 
| | | | |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
I agree that fewer build flags is good, and we should definitely land this eventually.

But right now, there's risk that `USE_ANGLE_WEBGL` will need to be reverted in WebKitGTK if we aren't able to deal with regressions like https://bugs.webkit.org/show_bug.cgi?id=248223 or https://bugs.webkit.org/show_bug.cgi?id=248221 where it's causing problems on websites that don't use any WebGL at all. And WebGL 2 is tied into `USE_ANGLE_WEBGL`. So now seems like a risky time to land this: if we're not able to ship WebGL 2 next year, we'd have to reintroduce the build guards everywhere, and that doesn't seem fun.

**Comment by brentfulgham** [comment]
@mcatanzaro Thank you for that valuable feedback. Clearly we can't land this until you have resolved that issue.

Would you mind letting me know if/when your port is ready for us to merge these two flags? Until then, I'll mark this PR as 'blocked' to avoid anyone trying to move it forward.

**Comment by mcatanzaro** [comment]
> Would you mind letting me know if/when your port is ready for us to merge these two flags?

Sure. I will add a note for myself.

**Comment by mcatanzaro** [comment]
I think after https://bugs.webkit.org/show_bug.cgi?id=250073 we will probably not need to do any reverts, so I think it's safe enough to proceed with this now.

**Review by kkinnunen-apple — APPROVED** [review]

**Comment by brentfulgham** [comment]
Thank you, Kimmo!

**Pull request merged**
