### PR TITLE
REGRESSION(263237@main): [WPE] Identifiers for touch points are not constant in multi touch

### PR DESCRIPTION
**Pull request by clopez**
#### 363198dfec40635119410647bea002f82524e4af
<pre>
REGRESSION(263237@main): [WPE] Identifiers for touch points are not constant in multi touch
<a href="https://bugs.webkit.org/show_bug.cgi?id=270516">https://bugs.webkit.org/show_bug.cgi?id=270516</a>

Reviewed by Adrian Perez de Castro.

263237@main implemented tracking of touchstart/touchend events in order to
guess when a new touchpoint was pressed and assign a unique ID to each.

The issue here is that doesn&apos;t work well in practice.
I&apos;m not sure if is because of buggy drivers or buggy devices, but it happens
that sometimes when we start a new touch event (put a new finger on the screen)
without removing the previous ones we can receive more than one touchstart event
(one for the ongoing gesture and one for the new).

There are also issues when trying to use several fingers at the same time on some
touchscreens that do not properly support that like dual-touch devices, in that
case we may receive several touchstart events (more than two) and perhaps some fake
touchend events (or missing touchend events) and that will end confusing the logic.

So instead of trying to implement in WebKit code the tracking of the touchpoints
is better that we rely on the system (the driver, libinput and the wayland-protocol)
to track the touchpoints for us.

The touch IDs that we receive from the system are already unique from the other
ones active at that moment, each active touchpoint should have a different ID.

So, there isn&apos;t really a need to assign random IDs by ourselves.

However, the IDs that we receive from the system for the touchpoints start
at 0, but IDs 0 and 1 are already reserved for the mouse and the stylus
pointer devices. So to ensure that the ID of the touchpoint will be unique
we can simply add 2 to the value from the system.

Note also what the PointerEvents spec says &lt;<a href="https://www.w3.org/TR/pointerevents/">https://www.w3.org/TR/pointerevents/</a>&gt;:
&gt; pointerId is a unique identifier for the pointer causing the event.
&gt; This identifier MUST be unique from all other active pointers in the top-level
&gt; browsing context (as defined by [HTML5]) at the time.
&gt; A user agent MAY recycle previously retired values for pointerId from previous
&gt; active pointers, if necessary.

So the ID has to be unique only between the active ones, and that is what
we get from the system.

* LayoutTests/platform/glib/TestExpectations:
* LayoutTests/platform/gtk/TestExpectations:
* LayoutTests/platform/wpe/TestExpectations:
* Source/WebCore/dom/wpe/PointerEventWPE.cpp:
* Source/WebKit/Shared/libwpe/WebEventFactory.cpp:
(WebKit::WebEventFactory::createWebTouchEvent):
* Tools/PlatformWPE.cmake:
* Tools/wpe/backends/fdo/WindowViewBackend.cpp:
* Tools/wpe/backends/fdo/WindowViewBackend.h:

Canonical link: <a href="https://commits.webkit.org/287077@main">https://commits.webkit.org/287077@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/17aef8f9fe91371a6b31337b7b28e396cb5854d4

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/78242 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/57287 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/31619 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/82900 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/29504 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/80375 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/66435 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/5569 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/61271 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/19189 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/81309 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/51264 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/68255 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/41591 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/48610 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/24872 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/27841 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/69700 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/25232 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/84264 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/5607 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/3784 "Found 1 new test failure: ipc/create-media-source-with-invalid-constraints-crash.html (failure)") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/69493 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/5764 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/67190 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/68751 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/12758 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/11014 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/12097 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/5556 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/8314 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/5545 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/8977 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/7334 "Built successfully") | | |

### CODE REVIEW

**Comment by psaavedra** [comment]
The change makes sense since the former logic is not having account the multi touch logic. To track the pointer ids instead of the single event is the right way to do it.

**Comment by clopez** [comment]
Unfortunately this is not working fine if the device is single-touch instead of multi-touch.. we need to be able to detect the number of touch points that the device can give simultaneously because in the case of single touches devices we need to go back to the behavior previous to 263969@main .. in that case we can't have multiple touchIDs because if you touch a single-touch screen with more than one finger at the same time you will receive several touch_down events and perhaps some fake touch_up events that will end confusing the logic. In that case maybe we can check how much time has passed since the previous event before deciding to create a new touchID (any event happening within 1-2 second should not create new touchID in single-touch devices).

**Comment by clopez** [comment]
After quite a lot of testing this are my conclusions:

- It is not possible to reliably detect the number of touchpoints that a device has for several reasons:
  - The Wayland protocol currently has no way to pass this information from libinput to the application. It would require plumbing a new wayland message to pass this inf. And the other option of calling libinput directly is not an option (requires privileges, etc)
  - But even if we went that way, not all touch devices (or their device drivers) provide this information. If `libinput_device_touch_get_touch_count()` returns zero that means that the number of simultaneous touches is unknown. And that happens with one of the devices that I'm testing.

- We should not try to track active touch points in the WebKit code. This is already done by the underlying system (the driver, libinput and the wayland-protocol). So we should simply forward the events that we receive instead of trying to keep our own logic tracking active touchpoints.

**Comment by psaavedra** [comment]
I've tested the patch also in a baremetal [meta-webkit](https://github.com/Igalia/meta-webkit/wiki/RPi) image based on wpewekit 2.46.2 . The multitouch is working so fine. WebKit recognizes the 2 fingers well and there are not jumps between one and the another.

zoom:

zoom-gesture

pinching:

pinch-gesture

**Review by aperezdc — APPROVED** [review]
It seems reasoanable to leave the logic for assigning identifier to the underlying layers (libinput, Wayland, etc.) so let's go ahead and land this.

@clopez You will need to rebase the patch before it can land, FWIW.

**Comment by aperezdc** [comment]
Backported into the 2.46 branch as commit bd8e4fbbde0eb00ef8d2a2ef7cb6c74f3c763d19

**Pull request merged**
