### PR TITLE
Align with HTML and remove support for external importmaps

### PR DESCRIPTION
**Pull request by yoavweiss**
#### 6c9bf5a79e0ae3933d90140445b19047b9a2bd46
<pre>
Align with HTML and remove support for external importmaps
<a href="https://bugs.webkit.org/show_bug.cgi?id=284286">https://bugs.webkit.org/show_bug.cgi?id=284286</a>

Reviewed by Yusuke Suzuki.

This PR removes support for external import maps and ensures they throw an
error instead. That would align WebKit&apos;s behavior with the HTML standard
and other browsers.

It also imports a new WPT test that validates the standard requirement
this fixes, as well as adjusts relevant WPT results. This adjustment
results in some progressions and some regressions. The regressions would
be fixed as part of
<a href="https://github.com/WebKit/standards-positions/issues/381.">https://github.com/WebKit/standards-positions/issues/381.</a>

Upstream commit: <a href="https://github.com/web-platform-tests/wpt/commit/ef413686d128045b02cfa4d8de7422c931660bdb">https://github.com/web-platform-tests/wpt/commit/ef413686d128045b02cfa4d8de7422c931660bdb</a>

* LayoutTests/imported/w3c/web-platform-tests/import-maps/external-import-map-errors-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/import-maps/external-import-map-errors.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/import-maps/w3c-import.log:
* Source/WebCore/Sources.txt: remove LoadableImportMap
* Source/WebCore/WebCore.xcodeproj/project.pbxproj: remove LoadableImportMap
* Source/WebCore/dom/LoadableClassicScript.cpp: remove LoadableImportMap
  logic
* Source/WebCore/dom/LoadableImportMap.cpp: Removed.
* Source/WebCore/dom/LoadableImportMap.h: Removed.
(WebCore::ScriptElement::prepareScript): Fire an error event if
an importmap script has a source.
(WebCore::ScriptElement::executePendingScript): remove
  loadableImportMap logic
(WebCore::ScriptElement::requestImportMap): Deleted.
* Source/WebCore/dom/ScriptElement.h: Remove `requestImportMap`.

Canonical link: <a href="https://commits.webkit.org/287725@main">https://commits.webkit.org/287725@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ee785714861198a53fe717985e7edceaed104f84

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/80244 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/59246 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/33657 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/84761 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/31220 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/82355 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/68307 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/7545 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/62726 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/20540 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/83313 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/52790 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/73078 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/43034 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/50119 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/27233 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/29681 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/71249 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/27747 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/86194 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/7464 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/5279 "Found 1 new test failure: imported/w3c/web-platform-tests/dom/observable/tentative/observable-map.any.worker.html (failure)") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/71002 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/7639 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/68918 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/70243 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/17572 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/14240 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/13187 "Passed tests") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/7428 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/12945 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/7267 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/10787 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/9072 "Built successfully") | | |

### CODE REVIEW

**Comment by yoavweiss** [comment]
It seems like there's a lot more code that needs to be removed as well. I'll look into it

**Comment by annevk** [comment]
I don't understand the test regressions. I thought the existing tests were not testing `<script type=importmap src>`?

**Comment by yoavweiss** [comment]
> I don't understand the test regressions. I thought the existing tests were not testing `<script type=importmap src>`?

The existing tests (other than the one we added yesterday) were indeed not testing `<script type=importmap src>`
But it seems the logic to ensure an import map is not loaded after a module script was intertwined with the logic for loading external import maps, and that is causing the test regressions/progressions.

I can bring back the relevant importMapPromise code, and only remove it once multiple import maps land.

**Comment by annevk** [comment]
That would be good. I don't think it would be acceptable to regress on those tests.

**Review by Constellation — APPROVED** [review]

**Comment by yoavweiss** [comment]
Removed the merge-block label as the failing test seems unrelated and flaky (as discussed on Slack)

**Pull request merged**
