### PR TITLE
Fill in/fix macros in WebKitTargetConditionals.xcconfig

### PR DESCRIPTION
**Pull request by ddkilzer**
#### 637fd114532ab3db42ffaf84888b26843e8231b9
<pre>
Fill in/fix macros in WebKitTargetConditionals.xcconfig
<a href="https://bugs.webkit.org/show_bug.cgi?id=269799">https://bugs.webkit.org/show_bug.cgi?id=269799</a>
&lt;<a href="https://rdar.apple.com/123322741">rdar://123322741</a>&gt;

Reviewed by Alexey Proskuryakov.

* Configurations/WebKitTargetConditionals.xcconfig:
- Add support for later versions.
- Fix multi-version macOS macros which were missing versions in macro
  names, had incorrect values, or where definitions were just missing.
- Remove old unsupported versions.  (More clean-up is needed in project
  *.xcconfig files to remove additional unsupported versions.)

Canonical link: <a href="https://commits.webkit.org/275122@main">https://commits.webkit.org/275122@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ed9e2efd5c69fabd3651b19edf2b0b0a70eb1020

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/40923 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/19936 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/43301 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/43482 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/37014 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/22943 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/17267 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/33913 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/41497 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/16878 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/35275 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/14536 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/14647 "Passed tests") | | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/44778 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/37132 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/36576 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/40323 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/15738 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/50/builds/12922 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/38692 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/17357 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/17408 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/5443 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/17001 "Built successfully") | | |

### CODE REVIEW

**Comment by ddkilzer** [comment]
@emw-apple We should probably trim older versions.

I was thinking that we should keep these versions or newer (delete older ones):
- macOS 12
- MacCatalyst 13
- iOS 16
- tvOS 16
- watchOS 9

Or if we wanted to be more aggressive, delete anything older than:
- macOS 12
- MacCatalyst 14
- iOS 17
- tvOS 17
- watchOS 10

Thoughts?

**Review by aproskuryakov — APPROVED** [review]
rs=me, but a lot of this should be removed, not fixed.

**Comment by ddkilzer** [comment]
> rs=me, but a lot of this should be removed, not fixed.

Thanks!  My plan was to fix first, then remove older items second.

**Comment by ddkilzer** [comment]
There are still some uses of older OS versions in other `*.xcconfig` files, so those need to be cleaned up first, but I want to do those as a separate task.

I was able to remove these, though:
```diff
diff --git a/Configurations/WebKitTargetConditionals.xcconfig b/Configurations/WebKitTargetConditionals.xcconfig
index 3bb66c2c7242..caefa28a2596 100644
--- a/Configurations/WebKitTargetConditionals.xcconfig
+++ b/Configurations/WebKitTargetConditionals.xcconfig
@@ -49,37 +49,30 @@
 // macOS
 
 WK_MACOS_BEFORE_1014 = $(WK_MACOS_BEFORE_1014_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1014_101300 = YES;
 
 WK_MACOS_BEFORE_1015 = $(WK_MACOS_BEFORE_1015_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1015_101300 = YES;
 WK_MACOS_BEFORE_1015_101400 = YES;
 
 WK_MACOS_BEFORE_1016 = $(WK_MACOS_BEFORE_1016_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1016_101300 = YES;
 WK_MACOS_BEFORE_1016_101400 = YES;
 WK_MACOS_BEFORE_1016_101500 = YES;
 
 WK_MACOS_BEFORE_1100 = $(WK_MACOS_BEFORE_1100_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1100_101300 = YES;
 WK_MACOS_BEFORE_1100_101400 = YES;
 WK_MACOS_BEFORE_1100_101500 = YES;
 
 WK_MACOS_BEFORE_1200 = $(WK_MACOS_BEFORE_1200_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1200_101300 = YES;
 WK_MACOS_BEFORE_1200_101400 = YES;
 WK_MACOS_BEFORE_1200_101500 = YES;
 WK_MACOS_BEFORE_1200_110000 = YES;
 
 WK_MACOS_BEFORE_1300 = $(WK_MACOS_BEFORE_1300_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1300_101300 = YES;
 WK_MACOS_BEFORE_1300_101400 = YES;
 WK_MACOS_BEFORE_1300_101500 = YES;
 WK_MACOS_BEFORE_1300_110000 = YES;
 WK_MACOS_BEFORE_1300_120000 = YES;
 
 WK_MACOS_BEFORE_1400 = $(WK_MACOS_BEFORE_1400_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1400_101300 = YES;
 WK_MACOS_BEFORE_1400_101400 = YES;
 WK_MACOS_BEFORE_1400_101500 = YES;
 WK_MACOS_BEFORE_1400_110000 = YES;
@@ -87,7 +80,6 @@ WK_MACOS_BEFORE_1400_120000 = YES;
 WK_MACOS_BEFORE_1400_130000 = YES;
 
 WK_MACOS_BEFORE_1500 = $(WK_MACOS_BEFORE_1500_$(TARGET_MAC_OS_X_VERSION_MAJOR));
-WK_MACOS_BEFORE_1500_101300 = YES;
 WK_MACOS_BEFORE_1500_101400 = YES;
 WK_MACOS_BEFORE_1500_101500 = YES;
 WK_MACOS_BEFORE_1500_110000 = YES;
@@ -242,17 +234,11 @@ WK_MACOS_1500_YES = _MACOS_BEFORE_1500;
 // iOSMac / MacCatalyst
 
 WK_MACCATALYST_BEFORE_13 = $(WK_MACCATALYST_BEFORE_13_$(MACOSX_DEPLOYMENT_TARGET:base));
-WK_MACCATALYST_BEFORE_13_11 = YES;
-WK_MACCATALYST_BEFORE_13_12 = YES;
 
 WK_MACCATALYST_BEFORE_14 = $(WK_MACCATALYST_BEFORE_14_$(MACOSX_DEPLOYMENT_TARGET:base));
-WK_MACCATALYST_BEFORE_14_11 = YES;
-WK_MACCATALYST_BEFORE_14_12 = YES;
 WK_MACCATALYST_BEFORE_14_13 = YES;
 
 WK_MACCATALYST_BEFORE_15 = $(WK_MACCATALYST_BEFORE_15_$(MACOSX_DEPLOYMENT_TARGET:base));
-WK_MACCATALYST_BEFORE_15_11 = YES;
-WK_MACCATALYST_BEFORE_15_12 = YES;
 WK_MACCATALYST_BEFORE_15_13 = YES;
 WK_MACCATALYST_BEFORE_15_14 = YES;
 
@@ -324,20 +310,11 @@ WK_IOS_18_YES = _IOS_BEFORE_18;
 // tvOS
 
 WK_TVOS_BEFORE_16 = $(WK_TVOS_BEFORE_16_$(TVOS_DEPLOYMENT_TARGET:base));
-WK_TVOS_BEFORE_16_13 = YES;
-WK_TVOS_BEFORE_16_14 = YES;
-WK_TVOS_BEFORE_16_15 = YES;
 
 WK_TVOS_BEFORE_17 = $(WK_TVOS_BEFORE_17_$(TVOS_DEPLOYMENT_TARGET:base));
-WK_TVOS_BEFORE_17_13 = YES;
-WK_TVOS_BEFORE_17_14 = YES;
-WK_TVOS_BEFORE_17_15 = YES;
 WK_TVOS_BEFORE_17_16 = YES;
 
 WK_TVOS_BEFORE_18 = $(WK_TVOS_BEFORE_18_$(TVOS_DEPLOYMENT_TARGET:base));
-WK_TVOS_BEFORE_18_13 = YES;
-WK_TVOS_BEFORE_18_14 = YES;
-WK_TVOS_BEFORE_18_15 = YES;
 WK_TVOS_BEFORE_18_16 = YES;
 WK_TVOS_BEFORE_18_17 = YES;
 
@@ -356,14 +333,11 @@ WK_TVOS_18_YES = _TVOS_BEFORE_18;
 // watchOS
 
 WK_WATCHOS_BEFORE_9 = $(WK_WATCHOS_BEFORE_9_$(WATCHOS_DEPLOYMENT_TARGET:base));
-WK_WATCHOS_BEFORE_9_8 = YES;
 
 WK_WATCHOS_BEFORE_10 = $(WK_WATCHOS_BEFORE_10_$(WATCHOS_DEPLOYMENT_TARGET:base));
-WK_WATCHOS_BEFORE_10_8 = YES;
 WK_WATCHOS_BEFORE_10_9 = YES;
 
 WK_WATCHOS_BEFORE_11 = $(WK_WATCHOS_BEFORE_11_$(WATCHOS_DEPLOYMENT_TARGET:base));
-WK_WATCHOS_BEFORE_11_8 = YES;
 WK_WATCHOS_BEFORE_11_9 = YES;
 WK_WATCHOS_BEFORE_11_10 = YES;
 
```

**Pull request merged**
