### PR TITLE
[WPT][WebVTT] Move some WebVTT rendering tests into the correct location

### PR DESCRIPTION
**Pull request by jernoble**
#### 25222453815607ad36719b01666f6ca52bc821b3
<pre>
[WPT][WebVTT] Move some WebVTT rendering tests into the correct location
<a href="https://bugs.webkit.org/show_bug.cgi?id=280436">https://bugs.webkit.org/show_bug.cgi?id=280436</a>
&lt;<a href="https://rdar.apple.com/problem/136782503">rdar://problem/136782503</a>&gt;

Reviewed by Eric Carlson.

Other tests inside web-platform-tests/webvtt/rendering are inside the subdirectory
cues-with-video/processing-model/, so move our own tests to that location to
prepare for upstreaming.

Additionally, make some stylistic changes to the test, and conform to WPT mechanisms
for waiting for tests to complete.

* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/basic-cue-rendering-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/basic-cue-rendering.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/basic-cue-rendering-expected.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/basic-cue-rendering.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/support/basic-cue-rendering.webvtt: Renamed from LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/basic-cue-rendering.webvtt.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/support/reference.css: Renamed from LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/resources/reference.css.
(@font-face):
(.test-diff):
(video-reference, cue):
(cue-background):
(video, video-reference):
(::cue, cue):
(::cue, cue-background):
(cue):
(video-reference[expected] &gt; cue &gt; cue-background):
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/support/webvtt-rendering-test.js: Added.
(async event):
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/support/white-space-pre-line.webvtt: Renamed from LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/white-space-pre-line.webvtt.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/white-space-pre-line-expected.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/cues-with-video/processing-model/white-space-pre-line.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/resources/webvtt-rendering-test.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/white-space-pre-line-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/webvtt/rendering/white-space-pre-line.html: Removed.

Canonical link: <a href="https://commits.webkit.org/284436@main">https://commits.webkit.org/284436@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/d0a59708d4018f94a7e1b6a9c799a628bc3a568d

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/69368 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/48768 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/22041 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/73451 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/20526 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/56569 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/20377 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/55171 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 win-tests~~](https://ews-build.webkit.org/#/builders/60/builds/13633 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/72434 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/44490 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/59889 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/41/builds/35649 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/41156 "Passed tests") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/64/builds/17319 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/18903 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/63098 "Passed tests") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/63/builds/17664 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/75162 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/13350 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/62/builds/16886 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/62838 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/13389 "Built successfully") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/59972 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/62744 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/15394 "Built successfully and passed tests") | [  ~~🧪 vision-wk2~~](https://ews-build.webkit.org/#/builders/88/builds/10761 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-intel-wk2~~](https://ews-build.webkit.org/#/builders/119/builds/4373 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/44572 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/45646 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/46841 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/45387 "Built successfully") | | |

### CODE REVIEW

**Review by eric-carlson — APPROVED** [review]

**Comment by nt1m** [comment]
Please make sure to export this change upstream

**Comment by jernoble** [comment]
> Please make sure to export this change upstream

I have been informed that the upstream process is automatic these days.

**Comment by nt1m** [comment]
> > Please make sure to export this change upstream
> 
> I have been informed that the upstream process is automatic these days.

`export-w3c-test-changes -b 280436 -g GIT_SHA -c` is how you do it nowadays. It's unfortunately not automatic (although I really wish it were).

**Comment by jernoble** [comment]
> > > Please make sure to export this change upstream
> > 
> > 
> > I have been informed that the upstream process is automatic these days.
> 
> `export-w3c-test-changes -b 280436 -g GIT_SHA -c` is how you do it nowadays. It's unfortunately not automatic (although I really wish it were).

Unfortunately, the original change wasn't upstreamed, so that tool errors out. I manually added a PR however: https://github.com/web-platform-tests/wpt/pull/48373

**Pull request merged**
