### PR TITLE
Enable CSS_SELECTORS_LEVEL4 everywhere

### PR DESCRIPTION
**Pull request by rniwa**
#### c1dc6308522c09572c237aec395a1bf72171ddb9
<pre>
Enable CSS_SELECTORS_LEVEL4 everywhere
<a href="https://bugs.webkit.org/show_bug.cgi?id=243092">https://bugs.webkit.org/show_bug.cgi?id=243092</a>

Reviewed by Tim Nguyen.

Enable this everywhere for consistency.

* Source/WTF/wtf/PlatformEnable.h:
* Source/WTF/wtf/PlatformEnableCocoa.h:

Canonical link: <a href="https://commits.webkit.org/252796@main">https://commits.webkit.org/252796@main</a>
</pre>

### CODE REVIEW

**Comment by nt1m** [comment]
I would lean towards removing this build flag altogether, and removing the `:role` pseudo-class on the way. Given the `:role` pseudo was removed from the draft standard, we should remove it too.

**Comment by rniwa** [comment]
> I would lean towards removing this build flag altogether, and removing the `:role` pseudo-class on the way. Given the `:role` pseudo was removed from the draft standard, we should remove it too.

I don't think we want to do all of that in a single patch. We can remove the build flag once all ports successfully shipped the feature enabled.

**Comment by nt1m** [comment]
I made a patch to remove `:role()`: https://github.com/WebKit/WebKit/pull/2695

I think it makes sense to at least rename the build flag after my patch.

**Review by nt1m — APPROVED** [review]
r=me but please consider removing it or at least renaming it now that the `:role()` pseudo class is gone.

**Comment by rniwa** [comment]
> r=me but please consider removing it or at least renaming it now that the `:role()` pseudo class is gone.

I'd remove the build flag in a followup

**Pull request merged**
