### PR TITLE
[WPE] Add a DisplayLink implementation

### PR DESCRIPTION
**Pull request by carlosgcampos**
#### f170513337015ac258d2937bbf9616b10e5129c3
<pre>
[WPE] Add a DisplayLink implementation
<a href="https://bugs.webkit.org/show_bug.cgi?id=261816">https://bugs.webkit.org/show_bug.cgi?id=261816</a>

Reviewed by Alejandro G. Castro.

Add a DisplayLink implementation for WPE using DRM vblank monitor. This
patch also removes the API to change display refresh rate that is no
longer needed.

* Source/WTF/wtf/PlatformHave.h:
* Source/WebKit/PlatformWPE.cmake:
* Source/WebKit/Shared/CoordinatedGraphics/threadedcompositor/ThreadedCompositor.cpp:
(WebKit::ThreadedCompositor::targetRefreshRateDidChange): Deleted.
* Source/WebKit/Shared/CoordinatedGraphics/threadedcompositor/ThreadedCompositor.h:
* Source/WebKit/SourcesWPE.txt:
* Source/WebKit/UIProcess/API/wpe/WPEView.cpp:
(WKWPE::m_backend):
* Source/WebKit/UIProcess/CoordinatedGraphics/DrawingAreaProxyCoordinatedGraphics.cpp:
(WebKit::DrawingAreaProxyCoordinatedGraphics::targetRefreshRateDidChange): Deleted.
* Source/WebKit/UIProcess/CoordinatedGraphics/DrawingAreaProxyCoordinatedGraphics.h:
* Source/WebKit/UIProcess/DrawingAreaProxy.h:
(WebKit::DrawingAreaProxy::targetRefreshRateDidChange): Deleted.
* Source/WebKit/UIProcess/glib/DisplayVBlankMonitorDRM.cpp:
(WebKit::findCrtc):
(WebKit::DisplayVBlankMonitorDRM::create):
* Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/DrawingAreaCoordinatedGraphics.cpp:
(WebKit::DrawingAreaCoordinatedGraphics::targetRefreshRateDidChange): Deleted.
* Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/DrawingAreaCoordinatedGraphics.h:
* Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/LayerTreeHost.cpp:
(WebKit::LayerTreeHost::targetRefreshRateDidChange): Deleted.
* Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/LayerTreeHost.h:
(WebKit::LayerTreeHost::sizeDidChange):
(WebKit::LayerTreeHost::targetRefreshRateDidChange): Deleted.
* Source/WebKit/WebProcess/WebPage/DrawingArea.h:
(WebKit::DrawingArea::updateBackingStoreState):
(WebKit::DrawingArea::targetRefreshRateDidChange): Deleted.

Canonical link: <a href="https://commits.webkit.org/268722@main">https://commits.webkit.org/268722@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/fae026276c3b5cb6f55e52070df4d250c4cdcf9b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/20478 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/20904 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/21548 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/22377 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/19109 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/24162 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/21079 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/20506 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/20697 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/20564 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/17804 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/23230 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/17732 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/18609 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/24896 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/17830 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/18809 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/18785 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/22836 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/19905 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/19378 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/16460 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/23886 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/18591 "Built successfully") | | [❌ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/5713 "Found 5 jsc stress test failures: stress/sampling-profiler-microtasks.js.default, stress/sampling-profiler-microtasks.js.dfg-eager, stress/sampling-profiler-microtasks.js.mini-mode, stress/sampling-profiler-microtasks.js.no-cjit-collect-continuously, stress/sampling-profiler-microtasks.js.no-llint") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/22931 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/25143 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/2531 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/19198 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/5536 "Passed tests") |

### CODE REVIEW

**Comment by hwti** [comment]
Wouldn't this affect performance when not using DRM (ie with the timer implementation) ?
The timer would be constant (not using the API), and this adds the UIProcess into the loop.
`ThreadedCompositor::frameComplete` calling `displayUpdateFired` was a feedback based on actual rendering, is there something similar with DisplayLink ?

In our case on a STB, the TV often runs at 50Hz, but the timer-based DisplayVBlankMonitor would run at 60Hz, regardless of the ThreadedCompositor being slowed down to 50fps (or less, depending on performance) by the buffer swap.

I also wonder if the DRM code would work when the rendering is done by the WebProcess (ie WPEBackend-rdk).

**Review by alexgcastro — APPROVED** [review]
LGTM! Great new addition!

**Comment by alexgcastro** [comment]
> Wouldn't this affect performance when not using DRM (ie with the timer implementation) ? The timer would be constant (not using the API), and this adds the UIProcess into the loop. `ThreadedCompositor::frameComplete` calling `displayUpdateFired` was a feedback based on actual rendering, is there something similar with DisplayLink ?
> 
> In our case on a STB, the TV often runs at 50Hz, but the timer-based DisplayVBlankMonitor would run at 60Hz, regardless of the ThreadedCompositor being slowed down to 50fps (or less, depending on performance) by the buffer swap.
> 

Great question! Adding support for a synchronization system in theory shouldn't cause performance issues and would improve all the engine synchronization, which will allow us to incrementally improve the rendering pipeline in the medium term. These are just the initial patches so we expect to add any contribution to improve the solution before activating it in the next release, that is why we started the integration after the last release.

In the case of a situation where you need to stop the rendering because of some condition of the system UI, such as the rendering stopped for some reason (window is not showed, or any other condition) we should add the condition in the timer to stop requesting frames to the WebProcess. Thanks to this patch now we can do it in a simple way and if needed in more situations, which would control all the engine, improving the performance in those cases when we have all the changes in place.

It is true that maybe in the situation you are thinking it is still not considered in the code. Please test it and report in that case.

> I also wonder if the DRM code would work when the rendering is done by the WebProcess (ie WPEBackend-rdk).

Yep, in the end, even when the frame composition is in the WebProcess the frame is sent to render from the UIProcess that handles all the resource initialization and creation.

Thanks for the feedback! Please try the patch and report any issue you can find, our goal is to make the engine more robust in the frame handling in the future, to allow to use less resources and at the right time.

**Comment by hwti** [comment]
> Great question! Adding support for a synchronization system in theory shouldn't cause performance issues and would improve all the engine synchronization, which will allow us to incrementally improve the rendering pipeline in the medium term. These are just the initial patches so we expect to add any contribution to improve the solution before activating it in the next release, that is why we started the integration after the last release.

I'm not sure to understand what you mean.
My concern is that the UIProcess will send messages at a fixed speed, regardless of the WebProcess rendering performance.
If this only causes the WebProcess to render as soon as possible, but without doing paints / layouts faster than what can be composited, it's probably fine (unless there is a scheduling priority issue like #18491).

> Yep, in the end, even when the frame composition is in the WebProcess the frame is sent to render from the UIProcess that handles all the resource initialization and creation.

With WPEBackend-rdk (for example wayland-egl or bcm-nexus), the WebProcess renders "on screen", and there is only an handshake.
`BufferCommit` sent from WebProcess to the UIProcess =>
 - `wpe_renderer_backend_egl_target_dispatch_frame_complete` in the WebProcess => `ThreadedCompositor::frameComplete`
 -  `wpe_view_backend_dispatch_frame_displayed` in the UIProcess => `WebKitWebViewClient::frameDisplayed` (only for `webkit_web_view_add_frame_displayed_callback`)

**Comment by alexgcastro** [comment]
> > Great question! Adding support for a synchronization system in theory shouldn't cause performance issues and would improve all the engine synchronization, which will allow us to incrementally improve the rendering pipeline in the medium term. These are just the initial patches so we expect to add any contribution to improve the solution before activating it in the next release, that is why we started the integration after the last release.
> 
> I'm not sure to understand what you mean. My concern is that the UIProcess will send messages at a fixed speed, regardless of the WebProcess rendering performance. If this only causes the WebProcess to render as soon as possible, but without doing paints / layouts faster than what can be composited, or skipping frames (slowing down to 30fps for example), it's probably fine (unless there is a scheduling priority issue like #18491).

Oh, ok, no worries about that, the engine handles that situation properly, it is not going to generate more frames and it keeps an statistic of the ones that did not make it to throttle the frame generation if the situations is bad. Actually with this patch we are enabling the option to use the code used in webcore to handle it.

**Comment by hwti** [comment]
> Oh, ok, no worries about that, the engine handles that situation properly, it is not going to generate more frames and it keeps an statistic of the ones that did not make it to throttle the frame generation if the situations is bad. Actually with this patch we are enabling the option to use the code used in webcore to handle it.

It depends what you mean by throttling.
With a 60Hz timer in the UIProcess, and our WebProcess limited to 50fps, there would be frames which would not "make it", but if the rendering only triggers on the next tick of the 60Hz timer, then it would cap at 30fps.
Maybe we can wire the WPE `target_refresh_rate_changed` to the `DisplayVBlankMonitorTimer`, or add a `wpe_view_backend_wait_for_vblank`, to be able to have platform-specific implementations.
Then there is the scheduling priority issue, the rendering must not prevent timers from running (but it might appear to work if it slows down just enough).
We need to try the main on our target, but it takes some time as we have to rebase our patches.

**Comment by blino** [comment]
With this PR, we still have the scheduling issues that @hwti attempted to fix in #18491 before the WPE DisplayLink implementation.

We can reproduce an application freeze, where timers can not be processed before of animations being prioritized.

**Comment by alexgcastro** [comment]
Thanks for the feedback, this PR does not try to fix that situation but we are working in this new approach with displayLInk and we plan to continue working on this in the near future, hopefully we can address that issue too. Thanks again for let us know about it.

**Pull request merged**
