### PR TITLE
[WPE] Switch to use always complex text code path

### PR DESCRIPTION
**Pull request by obyknovenius**
#### c92522eda224e1014e1493fef26f68c6402226f8
<pre>
[WPE] Switch to use always complex text code path
<a href="https://bugs.webkit.org/show_bug.cgi?id=251579">https://bugs.webkit.org/show_bug.cgi?id=251579</a>

Reviewed by Carlos Garcia Campos.

It&apos;s been a default on GTK since `<a href="https://commits.webkit.org/200076@main`.">https://commits.webkit.org/200076@main`.</a>
It fixes a lot of WPE tests and lets us reuse already existing baselines
for passing GTK tests.

Canonical link: <a href="https://commits.webkit.org/259842@main">https://commits.webkit.org/259842@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/4242a24fbe68162bce90d7c2c173e215141ffecc

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/105840 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/14908 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/38688 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/115038 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/175170 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/16327 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/6107 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/98073 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/114813 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/111589 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/12427 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/95396 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/39968 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/94286 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/27038 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/81629 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/8179 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/28390 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/8661 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/4975 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/14288 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/47938 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/6807 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/10218 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by zdobersek — COMMENTED** [review]
What are the changes outside of the LayoutTests directory? The interface doesn't load beyond 3000 files, and the changelog doesn't list them (while it's fine to avoid listing the changed baselines).

**Comment by obyknovenius** [comment]
The only change in the source code is removing `#if PLATFORM(GTK)` in `WebProcessPoolGLib.cpp`:
https://github.com/WebKit/WebKit/blob/dc9dac69fd36796e1cd101057c90b12a068ad720/Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp#L63

**Comment by obyknovenius** [comment]
Here's the diff:
```diff
diff --git a/Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp b/Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp
index 3bddcfc5d875..a9a3531a1b9b 100644
--- a/Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp
+++ b/Source/WebKit/UIProcess/glib/WebProcessPoolGLib.cpp
@@ -60,9 +60,8 @@ namespace WebKit {
 
 void WebProcessPool::platformInitialize()
 {
-#if PLATFORM(GTK)
     m_alwaysUsesComplexTextCodePath = true;
-#endif
+
     if (const char* forceComplexText = getenv("WEBKIT_FORCE_COMPLEX_TEXT"))
```

**Comment by mcatanzaro** [comment]
I think we don't need the environment variable or the platform-specific implementation code anymore.

**Comment by carlosgcampos** [comment]
The env var is still useful for debugging.

**Review by carlosgcampos — APPROVED** [review]

**Pull request merged**
