### PR TITLE
Resync web-platform-tests/{tools,websockets} from upstream of a7a594d8c03a850fd99bab1fd85bb6fe310081a2

### PR DESCRIPTION
**Pull request by fujii**
#### 7204a096e43d4a2b86dea7f22807a3474ef2af3d
<pre>
Resync web-platform-tests/{tools,websockets} from upstream of a7a594d8c03a850fd99bab1fd85bb6fe310081a2
<a href="https://bugs.webkit.org/show_bug.cgi?id=281108">https://bugs.webkit.org/show_bug.cgi?id=281108</a>

Reviewed by Anne van Kesteren.

Upstream commit: <a href="https://github.com/web-platform-tests/wpt/commit/a7a594d8c03a850fd99bab1fd85bb6fe310081a2">https://github.com/web-platform-tests/wpt/commit/a7a594d8c03a850fd99bab1fd85bb6fe310081a2</a>

This commit renamed bundled mod_pywebsocket to pywebsocket3.

* LayoutTests/imported/w3c/web-platform-tests/tools/...: Resynced.
* LayoutTests/imported/w3c/web-platform-tests/websockets/...: Resynced.
* LayoutTests/http/tests/websocket/tests/hybi/...:
* Tools/Scripts/webkitpy/layout_tests/servers/websocket_server.py:
(PyWebSocket._prepare_config):

Canonical link: <a href="https://commits.webkit.org/284890@main">https://commits.webkit.org/284890@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/4fbd4095e2b4ceeb3fc3ac6ea7c837ac1d406af8

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/70798 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/50208 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/23567 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/74895 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/21998 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/72914 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/58006 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/21819 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/56037 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/14503 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/73864 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/45640 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/61038 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/36489 "Passed tests") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/70307 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/42295 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/18471 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/20340 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/64230 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/18833 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/76609 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/15028 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/18033 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/63770 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/15072 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/61101 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/63716 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/15683 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/11791 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/5439 "Passed tests") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/46009 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/47081 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/48362 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/46823 "Built successfully") | | |

### CODE REVIEW

**Comment by annevk** [comment]
It seems that the bots haven't actually tried to run any tests. That makes me a little worried about this. Is there a way to force that to happen so that we know all is well for sure?

**Comment by fujii** [comment]
I'm seeing no problem for EWS results (except that only gtk-wk2 is still running now). Which bot are you looking?

**Comment by fujii** [comment]
For example, mac-wkl1 ran 74427 layout tests.
https://ews-build.webkit.org/#/builders/63/builds/18833

**Review by annevk — APPROVED** [review]
Thanks, I misread the results.

**Pull request merged**
