### PR TITLE
[commits.webkit.org] Treat integer as revision

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 121c1760a2ef3585e888ecd26c44b908d2ff2c7d
<pre>
[commits.webkit.org] Treat integer as revision
<a href="https://bugs.webkit.org/show_bug.cgi?id=241011">https://bugs.webkit.org/show_bug.cgi?id=241011</a>
&lt;rdar://problem/94031994&gt;

Reviewed by NOBODY (OOPS!).

* Tools/Scripts/libraries/reporelaypy/reporelaypy/__init__.py: Bump version.
* Tools/Scripts/libraries/reporelaypy/reporelaypy/checkoutroute.py:
(CheckoutRoute.commit): Convert integer to r-prefixed revision.
* Tools/Scripts/libraries/reporelaypy/reporelaypy/tests/checkoutroute_unittest.py:
(CheckoutRouteUnittest.test_json_integer): Added.
* Tools/Scripts/libraries/reporelaypy/setup.py: Bump version.
</pre>

### CODE REVIEW

**Comment by aproskuryakov** [comment]
If it’s just about “easier to write”, and not a full blocker, perhaps we don’t need this footgun?

**Comment by JonWBedard** [comment]
> If it’s just about “easier to write”, and not a full blocker, perhaps we don’t need this footgun?

This is about the perf dashboard and buildbot, specifically, both of which would have to do this conversion themselves otherwise.

**Review by aproskuryakov — CHANGES_REQUESTED** [review]
This still doesn't make sense to me. Having commits.webkit.org guess about whether a number is an SVN revision or a hash prefix seems obviously unsafe, and it seems just as obvious that it's trivial for a client to prepend "r" for revisions. Even if it's somehow not trivial, commits.webkit.org should have a custom endpoint then.

**Comment by JonWBedard** [comment]
Closing this. We ended up fixing this client side instead of server side because of @aproskuryakov's points.

**Pull request closed without merging**
