### PR TITLE
REGRESSION (269108@main): Same-origin XSLT document() loads fail

### PR DESCRIPTION
**Pull request by ddkilzer**
#### 66338748251c4f55d2b29e32e4851add3ed40f0e
<pre>
REGRESSION (269108@main): Same-origin XSLT document() loads fail
<a href="https://bugs.webkit.org/show_bug.cgi?id=273106">https://bugs.webkit.org/show_bug.cgi?id=273106</a>
&lt;<a href="https://rdar.apple.com/126897034">rdar://126897034</a>&gt;

Reviewed by Alex Christensen.

Prior to this change, all external entity loads using docLoaderFunc() in
XSLTProcessorLibxslt.cpp would fail in shouldAllowExternalLoad() because
XMLDocumentParserScope::currentCachedResourceLoader was nullptr.  This
caused both cross-origin loads and same-origin loads to fail.

The fix is to make use of XMLDocumentParserScope in docLoaderFunc() to
set XMLDocumentParserScope::currentCachedResourceLoader so that the
same-origin policy is applied.

We keep the check added to shouldAllowExternalLoad() from 269108@main in
case a load is initiated without using XMLDocumentParserScope, and this
change adds a Debug assert to catch those cases before the load fails.

Tests:
    http/tests/security/xss-ALLOWED-xsl-external-entity-xslt-docloader.html
    http/tests/security/xss-DENIED-xsl-external-entity-xslt-docloader.html

* LayoutTests/http/tests/security/resources/xss-ALLOWED-xsl-external-entity-xslt-docloader.py: Add.
* LayoutTests/http/tests/security/resources/xss-ALLOWED-xsl-external-entity-xslt-docloader.svg: Copy from LayoutTests/http/tests/security/resources/xslt-external-entity.svg.
* LayoutTests/http/tests/security/resources/xss-ALLOWED-xsl-external-entity-xslt-docloader.xml: Add.
* LayoutTests/http/tests/security/resources/xss-DENIED-xsl-external-entity-xslt-docloader.py: Rename from LayoutTests/http/tests/security/resources/xslt2.py.
* LayoutTests/http/tests/security/resources/xss-DENIED-xsl-external-entity-xslt-docloader.svg: Rename from LayoutTests/http/tests/security/resources/xslt-external-entity.svg.
* LayoutTests/http/tests/security/xss-ALLOWED-xsl-external-entity-xslt-docloader-expected.txt: Add.
* LayoutTests/http/tests/security/xss-ALLOWED-xsl-external-entity-xslt-docloader.html: Copy from LayoutTests/http/tests/security/xslt-external-entity.html.
* LayoutTests/http/tests/security/xss-DENIED-xsl-external-entity-xslt-docloader-expected.txt: Rename from LayoutTests/http/tests/security/xslt-external-entity-expected.txt.
- Update results with denied console messages.  This change is the
  result of the bug fix.
* LayoutTests/http/tests/security/xss-DENIED-xsl-external-entity-xslt-docloader.html: Rename from LayoutTests/http/tests/security/xslt-external-entity.html.
- Add xss-ALLOWED-xsl-external-entity-xslt-docloader.html to test the
  same-origin case.  This test failed before this fix.
- Rename http/tests/security/xslt-external-entity.html to
  xss-DENIED-xsl-external-entity-xslt-docloader.html to match similar
  test cases.
* LayoutTests/platform/mac-monterey/http/tests/security/xss-DENIED-xsl-external-entity-xslt-docloader-expected.txt: Rename from LayoutTests/platform/mac-monterey/http/tests/security/xslt-external-entity-expected.txt.
- Update results with denied console messages.  This change is the
  result of the bug fix.

* Source/WebCore/xml/XSLTProcessorLibxslt.cpp:
(WebCore::docLoaderFunc):
- Make use of WebCore::XMLDocumentParserScope to fix the bug.

* Source/WebCore/xml/parser/XMLDocumentParserLibxml2.cpp:
(WebCore::shouldAllowExternalLoad):
- Add Debug assert to catch failures where XMLDocumentParserScope is
  missing, or a non-WebKit, in-process libxml2 load occurs.

Canonical link: <a href="https://commits.webkit.org/277924@main">https://commits.webkit.org/277924@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ced566af85467093c15558001f804cc0041ca8aa

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/48975 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/28188 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/51942 "Built successfully") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/51663 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/45045 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/9/builds/51280 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/34151 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/25716 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/51663 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/11/builds/49899 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/47/builds/25836 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/42224 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/5/builds/51663 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/23295 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/10/builds/43393 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe-skia](https://ews-build.webkit.org/#/builders/52/builds/7030 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/45221 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/43898 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/53573 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/24026 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/50/builds/20282 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/47344 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/25289 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/42432 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/46309 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/26098 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/7004 "Built successfully and passed tests") | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/25009 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Review by achristensen07 — APPROVED** [review]
Looks like a test already covered this, and that needs updating.

Also, XMLDocumentParserScope could use some modernization.  currentCachedResourceLoader and m_oldCachedResourceLoader should be WeakPtr, m_oldErrorContext looks like it might not be needed, indentation needs reducing.

**Comment by ddkilzer** [comment]
> Also, XMLDocumentParserScope could use some modernization. currentCachedResourceLoader and m_oldCachedResourceLoader should be WeakPtr, m_oldErrorContext looks like it might not be needed, indentation needs reducing.

The `m_oldErrorContext` instance variable is still used.  I'll file a follow-up bug for this clean-up task.

**Comment by ddkilzer** [comment]
Based on [prior results](https://github.com/WebKit/WebKit/pull/27613#issuecomment-2073682363) and the current [mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/42428) build passing, this is ready to be merged without waiting for additional results.

**Comment by ddkilzer** [comment]
> > Also, `XMLDocumentParserScope` could use some modernization. `currentCachedResourceLoader` and `m_oldCachedResourceLoader` should be `WeakPtr`, `m_oldErrorContext` looks like it might not be needed, indentation needs reducing.
> 
> The `m_oldErrorContext` instance variable is still used. I'll file a follow-up bug for this clean-up task.

See:  PR https://github.com/WebKit/WebKit/pull/27703

**Pull request merged**
