### PR TITLE
Resync web-platform-tests/resources from upstream

### PR DESCRIPTION
**Pull request by cdumez**
#### 4a4574451a99cffd3197fec02b0df9437594bfd2
<pre>
Resync web-platform-tests/resources from upstream
<a href="https://bugs.webkit.org/show_bug.cgi?id=250872">https://bugs.webkit.org/show_bug.cgi?id=250872</a>

Reviewed by Tim Nguyen.

Resync web-platform-tests/resources from upstream d20c3cdbf6e91f14dda92737e.

* LayoutTests/imported/w3c/web-platform-tests/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-stack-optional.sub.window-expected.txt:
* LayoutTests/imported/w3c/web-platfrom-tests/html/user-activation/*: Updated since they would break otherwise after the resources/ folder re-sync.
* LayoutTests/imported/w3c/web-platform-tests/resources/*: Updated.

Canonical link: <a href="https://commits.webkit.org/259143@main">https://commits.webkit.org/259143@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ea21ff28fb11e5deddc8120bed5ea22a9a56a9fe

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/104057 "4 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/13152 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/36986 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/113269 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/173576 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/14212 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/4064 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/96293 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/112350 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/109827 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/10953 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/94019 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/38627 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/92800 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/25631 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/80284 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/6521 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/27007 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/6666 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/3542 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/12663 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/46542 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/8443 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/3339 "Built successfully and passed tests") | | | |

### CODE REVIEW

**Review by nt1m — APPROVED** [review]
You also synced html/user-activation, might be worth mentioning that in the commit title or splitting that part out.

**Comment by cdumez** [comment]
> You also synced html/user-activation, might be worth mentioning that in the commit title or splitting that part out.

I cannot split it out since the user-activation tests need to be updated to keep working after the resources/ update.

**Comment by nt1m** [comment]
> > You also synced html/user-activation, might be worth mentioning that in the commit title or splitting that part out.
> 
> I cannot split it out since the user-activation tests need to be updated to keep working after the resources/ update.

Worth mentioning in the commit message fwiw.

**Comment by cdumez** [comment]
> > > You also synced html/user-activation, might be worth mentioning that in the commit title or splitting that part out.
> > 
> > 
> > I cannot split it out since the user-activation tests need to be updated to keep working after the resources/ update.
> 
> Worth mentioning in the commit message fwiw.

Yes, I already did?

**Comment by nt1m** [comment]
> > > > You also synced html/user-activation, might be worth mentioning that in the commit title or splitting that part out.
> > > 
> > > 
> > > I cannot split it out since the user-activation tests need to be updated to keep working after the resources/ update.
> > 
> > 
> > Worth mentioning in the commit message fwiw.
> 
> Yes, I already did?

Ah nevermind, I missed it because it was next to the filename, sorry.

**Pull request merged**
