### PR TITLE
Remove non-standard 'incremental' attribute

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Remove non-standard 'incremental' attribute
<a href="https://bugs.webkit.org/show_bug.cgi?id=257686">https://bugs.webkit.org/show_bug.cgi?id=257686</a>

Reviewed by NOBODY (OOPS!).

This patch aligns WebKit with Gecko / Firefox by removing non-standard 'incremental' attribute on Inputs.

Issue: <a href="https://github.com/whatwg/html/issues/667">https://github.com/whatwg/html/issues/667</a>

* Source/WebCore/html/HTMLInputElement.idl: Remove 'incremental'
* Source/WebCore/html/HTMLInputElement.cpp: Remove 'incremental' usage
* Source/WebKitLegacy/mac/DOM/DOMHTMLInputElement.mm:
((BOOL) incremental): Delete function
((void)setIncremental:(BOOL)newIncremental): Ditto
* LayoutTests/imported/w3c/web-platform-tests/html/semantics/forms/historical-expected.txt: Rebaselined
* LayoutTests/fast/forms/incremental-dom-property.html: Deleted
* LayoutTests/fast/forms/incremental-dom-property-expected.txt: Deleted
</pre>

https://github.com/WebKit/WebKit/commit/a77f60e5976aa35d1f0d540ec51119b99e1d0235

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/9300 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/9581 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/9808 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/10961 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/9188 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/9309 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/11565 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/9543 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/12069 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/9449 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/10475 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/8026 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/11120 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/7672 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/8485 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/15935 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/8770 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/8636 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/11975 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/9133 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/7441 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/8349 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/12573 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/8894 "Built successfully") | | |

### CODE REVIEW

**Comment by pxlcoder** [comment]
There's more code that we can remove here – search for instances of `incrementalAttr`.

There's also the question of whether we need to keep this attribute around behind a link-check for older apps, but I don't feel that we need to.

**Comment by Ahmad-S792** [comment]
> There's more code that we can remove here – search for instances of `incrementalAttr`.
> 
> There's also the question of whether we need to keep this attribute around behind a link-check for older apps, but I don't feel that we need to.

I basically revert this [commit](https://github.com/WebKit/WebKit/commit/bd4d5f416c383acadd1c036f35fabba22b45aa31).

**Comment by Ahmad-S792** [comment]
@pxlcoder - Deleted more 'Incremental' code related to incremental, there is one in SearchInputType.cpp but that is for separate bug. :-)

**Review by annevk — COMMENTED** [review]
Unfortunately, I don't think we can consider `<input type=search>` separately from the IDL attribute. They're essentially the same API. So we should either remove it everywhere, or keep it.

**Comment by Ahmad-S792** [comment]
> Unfortunately, I don't think we can consider `<input type=search>` separately from the IDL attribute. They're essentially the same API. So we should either remove it everywhere, or keep it.

I will leave someone else to take it up. :-)

**Pull request closed without merging**
