### PR TITLE
'&nbsp;' is forced on SPACE between text nodes

### PR DESCRIPTION
**Pull request by Ahmad-S792**
#### 54804ca28d80d0d3999bb0e385ce616399b7e9e0
<pre>
&apos;&amp;nbsp;&apos; is forced on SPACE between text nodes

&apos;&amp;nbsp;&apos; is forced on SPACE between text nodes
<a href="https://bugs.webkit.org/show_bug.cgi?id=123163">https://bugs.webkit.org/show_bug.cgi?id=123163</a>

Reviewed by Ryosuke Niwa.

Merge - <a href="https://chromium.googlesource.com/chromium/src.git/+/8134eeb454ef76c72df8cd7c26f6141072c314cb">https://chromium.googlesource.com/chromium/src.git/+/8134eeb454ef76c72df8cd7c26f6141072c314cb</a>

When we rebalance white spaces, &apos;&amp;nbsp;&apos; can be added as space
under some conditions. This CL adds a condition that the next
sibling text node should not exist.

* Source/WebCore/editing/CompositeEditCommand.cpp:
(CompositeEditCommand::rebalanceWhitespaceOnTextSubstring): Extend condition for &quot;rebalanceString&quot; to ensure that nextSibling text node should not exist
* Source/WebCore/editing/Editing.cpp: Update variable name from &quot;endIsEndOfParagraph&quot; to &quot;shouldEmitNBSPbeforeEnd&quot; as needed
* Source;WebCore/editing/Editing.h: Ditto
* LayoutTests/platform/gtk/editing/pasteboard/merge-end-borders-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-endings-006-expected.png: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-006-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-010-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-010-expected.png: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-text-009-expected.png: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-text-009-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/unrendered-br-expected.txt:  Rebaselined
* LayoutTests/platform/ios-wk2/editing/pasteboard/5028447-expected.txt: Rebaselined
* LayoutTests/platform/win/editing/execCommand/find-after-replace-expected.txt: Rebaselined
* LayoutTests/platform/win/editing/execCommand/paste-1-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/find-replace-match-capitalization-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/find-replace-match-capitalization.html: Updated
* LayoutTests/accessibility/mac/select-text-145575-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/select-text/select-text-7.html: Updated
* LayoutTests/accessibility/mac/select-text/select-text-7-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/select-text/select-text-8.html: Updated
* LayoutTests/accessibility/mac/select-text/select-text-8-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/select-text/select-text-9.html: Updated
* LayoutTests/accessibility/mac/select-text/select-text-9-expected.txt: Rebaselined
* LayoutTests/editing/pasteboard/paste-text-003-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/execCommand/paste-1-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-2-expected.txt: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/unrendered-br-expected.png: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/unrendered-br-expected.txt: Rebaselined
* LayoutTests/accessibility/mac/select-text/select-text-135575.html: Updated to use &quot;js-test.js&quot;
* LayoutTests/platform/gtk/editing/pasteboard/5028447-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-endings-006-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-line-endings-010-expected.txt: Rebaselined
* LayoutTests/platform/gtk/editing/pasteboard/paste-text-009-expected.txt: Rebaselined
* LayoutTests/platform/mac/editing/execCommand/paste-1-expected.png: Rebaselined
* LayoutTests/platform/mac/editing/execCommand/paste-1-expected.txt: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/5028447-expected.txt: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/5028447-expected.png: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/merge-end-borders-expected.png: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/merge-end-borders-expected.txt: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/paste-2-expected.png: Rebaselined
* LayoutTests/platform/mac/editing/pasteboard/paste-2-expected.txt: Rebaselined
* LayoutTests/platform/ios-wk2/editing/pasteboard/paste-text-009-expected.txt: Rebaselined
* LayoutTests/platform/ios-wk2/editing/pasteboard/paste-text-at-tabspan-003-expected.txt: Rebaselined
* LayoutTests/platform/ios-wk2/editing/pasteboard/unrendered-br-expected.txt: Rebaselined
* LayoutTests/platform/ios/editing/pasteboard/paste-line-endings-006-expected.txt: Rebaselined
* LayoutTests/platform/ios/editing/pasteboard/paste-line-endings-010-expected.txt: Rebaselined
* LayoutTests/platform/ios/editing/pasteboard/paste-text-003-expected.txt: Rebaselined
* LayoutTests/platform/ios-wk2/editing/pasteboard/unrendered-br-expected.txt: Rebaselined
* LayoutTests/platform/mac-wk1/editing/execCommand/find-after-replace-expected.txt: Added Platform Specific Expectation
* LayoutTests/platform/mac-wk1/editing/mac/spelling/autocorrection-blockquote-crash-expected.txt: Added Platform Specific Expectation
* LayoutTests/platform/mac-wk1/fast/lists/drag-into-marker-expected.txt: Added Platform Specific Expectation

Canonical link: <a href="https://commits.webkit.org/257136@main">https://commits.webkit.org/257136@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/30adfa479c37b7262061fba27b24336205ee6461

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/97804 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/7042 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/30985 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/107295 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/167564 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/7477 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/35819 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/90188 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/103938 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/103442 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/5616 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/84436 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/32577 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/87487 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/89244 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/75491 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/1030 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/20672 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/1022 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/22178 "Passed tests") | | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/74/builds/4910 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/5849 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/44629 "Found 2 new test failures: imported/w3c/web-platform-tests/IndexedDB/transaction-scheduling-within-database.any.html, imported/w3c/web-platform-tests/css/css-contain/content-visibility/content-visibility-031.html (failure)") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/2443 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/2277 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/41584 "Passed tests") | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@rniwa - I am getting bitten by this [bug](https://bugs.webkit.org/show_bug.cgi?id=248137) and when I even copy "actual" result from EWS, I get same failure. I will try to copy the result of following change and let's see. [Old Commit](https://github.com/WebKit/WebKit/commit/25afdaadd4f14b3bae59b22bf07f6e405345338e)

**Comment by rniwa** [comment]
Looks like editing/execCommand/find-after-replace.html, editing/mac/spelling/autocorrection-blockquote-crash.html, and fast/lists/drag-into-marker.html still need rebaselines.

**Comment by Ahmad-S792** [comment]
> Looks like editing/execCommand/find-after-replace.html, editing/mac/spelling/autocorrection-blockquote-crash.html, and fast/lists/drag-into-marker.html still need rebaselines.

Updated them and now waiting for mac-wk1 run and it might take hours and hours, so will ping when it is done and passing, I checked other two failures and they are not related to editing.

**Comment by Ahmad-S792** [comment]
@rniwa - now ready for your review and all tests rebaselined and failing test is in IndexDB, which is not related to this change.

**Review by rniwa — APPROVED** [review]
r=me

**Pull request merged**
