### PR TITLE
[Flatpak SDK] Switch runtime to 22.08 SDK

### PR DESCRIPTION
**Pull request by philn**
#### 5918e578fd4caf841c19bb7ad36ca500ee856648
<pre>
[Flatpak SDK] Switch runtime to 22.08 SDK
<a href="https://bugs.webkit.org/show_bug.cgi?id=245049">https://bugs.webkit.org/show_bug.cgi?id=245049</a>

Reviewed by Žan Doberšek.

* LayoutTests/platform/glib/TestExpectations:
* LayoutTests/platform/glib/accessibility/aria-visible-element-roles-expected.txt:
* LayoutTests/platform/glib/accessibility/node-only-object-element-rect-expected.txt:
* LayoutTests/platform/glib/css2.1/t100801-c544-valgn-03-d-agi-expected.txt:
* LayoutTests/platform/glib/css2.1/t120401-scope-04-d-expected.txt:
* LayoutTests/platform/glib/css2.1/t120403-content-none-00-c-expected.txt:
* LayoutTests/platform/glib/css2.1/t120403-visibility-00-c-expected.txt:
* LayoutTests/platform/glib/fast/css/empty-generated-content-expected.txt:
* LayoutTests/platform/glib/fast/css/first-letter-first-line-hover-expected.txt:
* LayoutTests/platform/glib/fast/layers/overflow-scroll-auto-switch-expected.txt:
* LayoutTests/platform/glib/fast/lists/001-vertical-expected.txt:
* LayoutTests/platform/glib/fast/lists/002-expected.txt:
* LayoutTests/platform/glib/fast/lists/008-vertical-expected.txt:
* LayoutTests/platform/glib/fast/text/international/hindi-spacing-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/css/css-contain/contain-inline-size-replaced-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/css/css-scroll-snap/scroll-target-margin-005-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/html/browsers/history/the-location-interface/same-hash-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/navigation-timing/nav2_test_redirect_chain_xserver_final_original_origin-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/navigation-timing/nav2_test_redirect_chain_xserver_partial_opt_in-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/navigation-timing/nav2_test_redirect_xserver-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/navigation-timing/test_timing_xserver_redirect-expected.txt:
* LayoutTests/platform/glib/mathml/opentype/opentype-stretchy-expected.txt:
* LayoutTests/platform/gtk/compositing/backing/backing-store-columns-inside-position-fixed-expected.txt: Added.
* LayoutTests/platform/gtk/compositing/contents-opaque/body-background-painted-expected.txt: Added.
* LayoutTests/platform/gtk/compositing/contents-opaque/body-background-skipped-expected.txt: Added.
* LayoutTests/platform/gtk/compositing/no-compositing-when-fulll-screen-is-present-expected.txt: Added.
* LayoutTests/platform/gtk/compositing/tiling/tiled-layers-limit-contents-scale-expected.txt: Added.
* LayoutTests/platform/gtk/css1/box_properties/margin_right-expected.txt:
* LayoutTests/platform/gtk/css1/box_properties/padding_right-expected.txt:
* LayoutTests/platform/gtk/css2.1/t1202-counter-09-b-expected.txt:
* LayoutTests/platform/gtk/css2.1/t1202-counters-09-b-expected.txt:
* LayoutTests/platform/gtk/editing/selection/3690703-2-expected.txt:
* LayoutTests/platform/gtk/editing/selection/3690703-expected.txt:
* LayoutTests/platform/gtk/editing/selection/3690719-expected.txt:
* LayoutTests/platform/gtk/editing/selection/extend-selection-bidi-expected.txt:
* LayoutTests/platform/gtk/fast/borders/bidi-012-expected.txt:
* LayoutTests/platform/gtk/fast/borders/inline-mask-overlay-image-outset-expected.txt:
* LayoutTests/platform/gtk/fast/borders/inline-mask-overlay-image-outset-vertical-rl-expected.txt:
* LayoutTests/platform/gtk/fast/css-generated-content/012-expected.txt:
* LayoutTests/platform/gtk/fast/css-generated-content/015-expected.txt:
* LayoutTests/platform/gtk/fast/css-generated-content/after-duplicated-after-split-expected.txt:
* LayoutTests/platform/gtk/fast/css/beforeSelectorOnCodeElement-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-ellipsis-bidi-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-ellipsis-text-align-center-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-ellipsis-text-align-justify-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-ellipsis-text-align-left-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-ellipsis-text-align-right-expected.txt:
* LayoutTests/platform/gtk/fast/css/text-overflow-input-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-center-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-center-mixed-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-justify-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-justify-mixed-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-left-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-left-mixed-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-right-expected.txt:
* LayoutTests/platform/gtk/fast/css/vertical-text-overflow-ellipsis-text-align-right-mixed-expected.txt:
* LayoutTests/platform/gtk/fast/dom/HTMLElement/bdo-expected.txt:
* LayoutTests/platform/gtk/fast/encoding/utf-16-big-endian-expected.txt:
* LayoutTests/platform/gtk/fast/encoding/utf-16-little-endian-expected.txt:
* LayoutTests/platform/gtk/fast/forms/auto-fill-button/hide-auto-fill-strong-password-viewable-treatment-when-form-is-reset-expected.txt: Added.
* LayoutTests/platform/gtk/fast/forms/auto-fill-button/input-strong-password-viewable-expected.txt: Added.
* LayoutTests/platform/gtk/fast/forms/box-shadow-override-expected.txt:
* LayoutTests/platform/gtk/fast/forms/input-placeholder-visibility-1-expected.txt:
* LayoutTests/platform/gtk/fast/forms/input-placeholder-visibility-3-expected.txt:
* LayoutTests/platform/gtk/fast/forms/placeholder-position-expected.txt:
* LayoutTests/platform/gtk/fast/forms/placeholder-pseudo-style-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-circle-focus-ring-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-outline-color-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-outline-color-explicitly-inherited-from-map-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-outline-color-not-inherited-from-map-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-zero-outline-width-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-focus-ring-zoom-expected.txt:
* LayoutTests/platform/gtk/fast/images/imagemap-polygon-focus-ring-expected.txt:
* LayoutTests/platform/gtk/fast/lists/003-expected.txt:
* LayoutTests/platform/gtk/fast/lists/003-vertical-expected.txt:
* LayoutTests/platform/gtk/fast/overflow/006-expected.txt:
* LayoutTests/platform/gtk/fast/overflow/overflow-rtl-vertical-expected.txt:
* LayoutTests/platform/gtk/fast/repaint/rel-positioned-inline-with-overflow-expected.txt:
* LayoutTests/platform/gtk/fast/repaint/vertical-text-repaint-expected.txt:
* LayoutTests/platform/gtk/fast/text/complex-text-opacity-expected.txt:
* LayoutTests/platform/gtk/fast/text/emphasis-expected.txt:
* LayoutTests/platform/gtk/fast/text/text-letter-spacing-expected.txt:
* LayoutTests/platform/gtk/fast/text/whitespace/018-expected.txt:
* LayoutTests/platform/gtk/fast/text/whitespace/pre-wrap-overflow-selection-expected.txt:
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/svg/import/animate-elem-77-t-manual-expected.txt:
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/svg/import/svgdom-over-01-f-manual-expected.txt:
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/svg/import/text-tspan-01-b-manual-expected.txt:
* LayoutTests/platform/gtk/inspector/dom/getAccessibilityPropertiesForNode-expected.txt:
* LayoutTests/platform/gtk/svg/W3C-SVG-1.1-SE/text-tspan-02-b-expected.txt:
* LayoutTests/platform/gtk/svg/W3C-SVG-1.1-SE/types-dom-05-b-expected.txt:
* LayoutTests/platform/gtk/svg/custom/glyph-transformation-with-hkern-expected.txt:
* LayoutTests/platform/wpe/fast/text/khmer-lao-font-expected.txt:
* Tools/flatpak/flatpakutils.py:

Canonical link: <a href="https://commits.webkit.org/255085@main">https://commits.webkit.org/255085@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/a24921d8eafad2532b4bc15f1eefa5b4569cf486

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/91261 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/261 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/21915 "Built successfully") | [❌ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/101000 "Updated wpe dependencies (failure)") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/160912 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/274 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/29270 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/83639 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/97394 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/96918 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/234 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/78006 "Built successfully") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/27221 "Build was cancelled. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Pull request contains relevant changes; Skipped layout-tests; layout-tests (exception)") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/82160 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/81839 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/70249 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/35402 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/15862 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/33200 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/16941 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3532 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/36985 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/39760 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/38908 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/36049 "Passed tests") | |

### CODE REVIEW

**Comment by philn** [comment]
EWS failures are relevant but not sure what is the action point here... the server is not coping with incoming requests or the EWS bots are on slow network? not sure...

**Comment by philn** [comment]
cc @lauromoura

**Comment by lauromoura** [comment]
> EWS failures are relevant but not sure what is the action point here... the server is not coping with incoming requests or the EWS bots are on slow network? not sure...

Looks like it was a network issue. It was the only build that failed for such reason and the following build on the same worker fetched the SDK normally.

**Comment by philn** [comment]
> > EWS failures are relevant but not sure what is the action point here... the server is not coping with incoming requests or the EWS bots are on slow network? not sure...
> 
> Looks like it was a network issue. It was the only build that failed for such reason and the following build on the same worker fetched the SDK normally.

That was a server-side inconsistency. I've rsync'ed the repo again.

**Review by zdobersek — APPROVED** [review]

**Pull request merged**
