### PR TITLE
Align UA Stylesheet by adding default properties of 'semantics' and 'maction' section in mathml.css

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Align UA Stylesheet by adding default properties of 'semantics' and 'maction' section in mathml.css
<a href="https://bugs.webkit.org/show_bug.cgi?id=262696">https://bugs.webkit.org/show_bug.cgi?id=262696</a>

Reviewed by NOBODY (OOPS!).

This patch aligns WebKit with Web Specification [1] by adding 'UA' stylesheet rules of 'semantics' and 'maction'.

[1] <a href="https://w3c.github.io/mathml-core/#user-agent-stylesheet">https://w3c.github.io/mathml-core/#user-agent-stylesheet</a>

* Source/WebCore/css/mathml.css:

Removed following tests (they were for old MathML implementation and new behavior matches other browsers):
* LayoutTests/mathml/presentation/maction-toggle.html: Removed
* LayoutTests/mathml/presentation/maction-toggle-expected.html: Ditto
* LayoutTests/mathml/presentation/maction-toggle-href.html: Ditto
* LayoutTests/mathml/presentation/maction-toggle-href-expected.html: Ditto
* LayoutTests/mathml/presentation/maction.html: Ditto
* LayoutTests/mathml/presentation/maction-expected.html: Ditto
* LayoutTests/mathml/presentation/semantics-2.html: Ditto
* LayoutTests/mathml/presentation/semantics-2-expected.html: Ditto
* LayoutTests/mathml/presentation/semantics-3.html: Ditto
* LayoutTests/mathml/presentation/semantics-3-expected.html: Ditto
* LayoutTests/mathml/presentation/semantics-4.html: Ditto
* LayoutTests/mathml/presentation/semantics-5-expected.html: Ditto

Rebaselines:
* LayoutTests/platform/glib/accessibility/math-foreign-content-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/ignored-properties-001-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/mathml/relations/dynamic-childlist-002-expected.txt:
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/mathml/relations/css-styling/floats/not-floating-001-expected.txt:
* LayoutTests/platform/ios-wk2/imported/w3c/web-platform-tests/mathml/relations/dynamic-childlist-002-expected.txt:
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/mathml/relations/ignored-properties-001-expected.txt:
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/ignored-properties-001-expected.txt:
* LayoutTests/platform/mac/accessibility/math-foreign-content-expected.txt:
* LayoutTests/platform/mac/imported/w3c/web-platform-tests/mathml/relations/css-sty…/margin-003-expected.txt:
* LayoutTests/platform/wpe/imported/w3c/web-platform-tests/mathml/relations/css-styling/floats/not-floating-001-expected.txt:
* LayoutTests/platform/mac/imported/w3c/web-platform-tests/mathml/relations/html5-tree/dynamic-childlist-002-expected.txt:
* LayoutTests/platform/mac/imported/w3c/web-platform-tests/mathml/relations/css-styling/ignored-properties-001-expected.txt:
* LayoutTests/mathml/presentation/foreign-element-in-annotation-xml-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/mathml/relations/css-styling/writing-mode/writing-mode-002-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/mathml/relations/css-styling/floats/not-floating-001-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/mathml/relations/css-styling/default-properties-on-semantics-and-maction-expected.txt: Rebaselined
* LayoutTests/imported/w3c/web-platform-tests/mathml/presentation-markup/mrow/legacy-mrow-like-elements-001-expected.txt
</pre>

https://github.com/WebKit/WebKit/commit/caffff4595b951fb84bf00125598d456a7f0e931

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/21330 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/21654 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/22383 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/23192 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/19781 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/21569 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/24944 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/21892 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/20994 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/21553 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/21218 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/18485 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/24044 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/18386 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/19333 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/25664 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/19461 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/19540 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/23505 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/20031 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/17056 "Found 2 new test failures: imported/w3c/web-platform-tests/mathml/relations/html5-tree/dynamic-childlist-002.html, tiled-drawing/scrolling/scroll-snap/scroll-snap-mandatory-mainframe-vertical-then-horizontal.html (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/19341 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/23593 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/19929 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
If there were any more rebase needed, I will do it, once full EWS finishes.

**Review by fred-wang — COMMENTED** [review]
MathML Core changes the implementation of maction/semantics and you are effectively removing some legacy tests. Is there a consensus in the WebKit project we actually want to do that?

**Comment by fred-wang** [comment]
See also

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/maction#browser_compatibility

for things that are currently in WebKit but has been removed from or not implemented in other browsers.

**Comment by Ahmad-S792** [comment]
> MathML Core changes the implementation of maction/semantics and you are effectively removing some legacy tests. Is there a consensus in the WebKit project we actually want to do that?

Personally, I think aligning with 'BrowserCompat' and matching with Chrome and Firefox would be right approach unless if there are any internal Apple products relying on old behavior for which I would like @nt1m to give his input.

**Comment by fred-wang** [comment]
Assuming Apple is ok with removing the old implementation, I believe there is a bunch of C++ you can also removed, and make semantics/maction just behave as an mrow + extra style.

**Review by anttijk — APPROVED** [review]

**Pull request closed without merging**
