### PR TITLE
Resync WPT tests for shadow DOM

### PR DESCRIPTION
**Pull request by rniwa**
#### 37b2593a7ee32e147c98d90b99fc9cfb96a769dc
<pre>
Resync WPT tests for shadow DOM
<a href="https://bugs.webkit.org/show_bug.cgi?id=242372">https://bugs.webkit.org/show_bug.cgi?id=242372</a>

Reviewed by Chris Dumez.

Updated web platform tests for shadow DOM as of 752460399dfa1af94b0474a84746e28e58ee1004.

* LayoutTests/imported/w3c/resources/resource-files.json:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/Element-interface-attachShadow.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/declarative-shadow-dom-attachment.tentative-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/declarative-shadow-dom-attachment.tentative.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/declarative-shadow-dom-opt-in.tentative-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/declarative-shadow-dom-opt-in.tentative.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/getinnerhtml.tentative-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/getinnerhtml.tentative.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/script-access.tentative-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/declarative/script-access.tentative.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/directionality-001-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/directionality-002-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/click-focus-delegatesFocus-click-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/click-focus-delegatesFocus-click.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-autofocus-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-autofocus.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-method-delegatesFocus-nested-browsing-context-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-method-delegatesFocus-nested-browsing-context.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-method-delegatesFocus-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-method-delegatesFocus.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-pseudo-matches-on-shadow-host-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-pseudo-matches-on-shadow-host.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-tabindex-order-shadow-varying-tabindex-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-tabindex-order-shadow-varying-tabindex-2.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-tabindex-order-shadow-varying-tabindex-3-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/focus-tabindex-order-shadow-varying-tabindex-3.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/focus/w3c-import.log:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-api-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-api.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-fallback-clear-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-fallback-clear.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-initial-fallback-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-initial-fallback.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-layout-invalidation-001-expected.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-layout-invalidation-001-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/imperative-slot-layout-invalidation-001.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/resources/shadow-dom-utils.js:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/slot-dir-attach-child-crash-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/slot-dir-attach-child-crash.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/nested-shadow-trees/nested_tree_reftest-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/nested-shadow-trees/w3c-import.log:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/reprojection/reprojection-001-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/reprojection/w3c-import.log:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/shadow-root-001-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/shadow-root-002-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/upper-boundary-encapsulation/ownerdocument-002-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/upper-boundary-encapsulation/ownerdocument-002.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/upper-boundary-encapsulation/window-named-properties-003-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/upper-boundary-encapsulation/window-named-properties-003.html:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/shadow-trees/w3c-import.log:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/styles/not-apply-in-shadow-root-001-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/untriaged/styles/w3c-import.log:
* LayoutTests/imported/w3c/web-platform-tests/shadow-dom/w3c-import.log:
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/shadow-dom/focus-tabindex-order-shadow-varying-tabindex-2-expected.txt: Added.
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/shadow-dom/focus-tabindex-order-shadow-varying-tabindex-3-expected.txt: Added.
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/shadow-dom/slot-dir-attach-child-crash-expected.txt: Added.
* LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/shadow-dom/slot-dir-attach-child-crash-expected.txt: Added.

Canonical link: <a href="https://commits.webkit.org/252237@main">https://commits.webkit.org/252237@main</a>
</pre>

### CODE REVIEW

**Comment by rniwa** [comment]
Resyncing as of 752460399dfa1af94b0474a84746e28e58ee1004

**Comment by cdumez** [comment]
EWS seems unhappy.

**Comment by rniwa** [comment]
> EWS seems unhappy.

Yeah, we need some platform specific results.

**Review by cdumez — APPROVED** [review]
LGTM

**Pull request merged**
