### PR TITLE
Allow downsampling when invoking Remove Background or Copy Subject

### PR DESCRIPTION
**Pull request by whsieh**
#### 4e0a027a46cb00f262aff0db84f3d544a1428f51
<pre>
Allow downsampling when invoking Remove Background or Copy Subject
<a href="https://bugs.webkit.org/show_bug.cgi?id=242048">https://bugs.webkit.org/show_bug.cgi?id=242048</a>
rdar://95833363

Reviewed by Tim Horton.

Soft-link `vk_cgImageRemoveBackgroundWithDownsizing` from VisionKitCore, and call into it to perform
background removal when performing Remove Background or Copy Subject, if available. On recent builds
of Ventura and iOS 16, VisionKit will automatically reject hi-res (&gt; 12MP) images from running
through subject analysis; for clients such as WebKit, this new SPI allows us to opt into
downsampling these large images, instead of failing outright.

* Source/WebCore/PAL/pal/cocoa/VisionKitCoreSoftLink.h:
* Source/WebCore/PAL/pal/cocoa/VisionKitCoreSoftLink.mm:
* Source/WebCore/PAL/pal/spi/cocoa/VisionKitCoreSPI.h:
* Source/WebKit/Platform/cocoa/ImageAnalysisUtilities.h:
* Source/WebKit/Platform/cocoa/ImageAnalysisUtilities.mm:
(WebKit::requestBackgroundRemoval):

Refactor the code so that we call `vk_cgImageRemoveBackgroundWithDownsizing` if it&apos;s available, and
otherwise fall back to `vk_cgImageRemoveBackground`.

* Source/WebKit/UIProcess/ios/WKContentViewInteraction.mm:
(-[WKContentView doAfterComputingImageAnalysisResultsForBackgroundRemoval:]):
(-[WKContentView _completeImageAnalysisRequestForContextMenu:requestIdentifier:hasTextResults:]):
(-[WKContentView imageAnalysisGestureDidTimeOut:]):
* Source/WebKit/UIProcess/mac/WebContextMenuProxyMac.mm:
(WebKit::WebContextMenuProxyMac::appendMarkupItemToControlledImageMenuIfNeeded):
(WebKit::WebContextMenuProxyMac::getContextMenuFromItems):

Additionally, remove the `cropRect` completion handler argument, since the new SPI function no
longer provides this information. The `cropRect` argument was also unused after removing support for
revealing the subject, in `249582@main`.

Canonical link: <a href="https://commits.webkit.org/251921@main">https://commits.webkit.org/251921@main</a>
</pre>

### CODE REVIEW

**Comment by whsieh** [comment]
(...it just came to my attention that this version of the SPI _might_ call the completion handler on a background thread :|)

I'll need to account for that in this patch.

**Review by hortont424 — APPROVED** [review]

**Comment by whsieh** [comment]
Thanks for the review!

**Comment by saiedg** [comment]
I'm very new to this... Is it possible to use WKWebView and call this 'copy subject' function for a given image? Please any info how would be grate

**Comment by whsieh** [comment]
> I'm very new to this... Is it possible to use WKWebView and call this 'copy subject' function for a given image? Please any info how would be great

Are you looking for a way to programmatically invoke "Copy Subject", specifically in the context of a `WKWebView`? There's currently no way to do this, but you might be able to use the underlying system APIs that are used to implement this (i.e. through the Vision and VisionKit frameworks) directly.

**Comment by saiedg** [comment]
@whsieh thank you. Yes that's what i'm hoping to do but currently there is no API in vision framework for copy subject. There is person segmentation but it's not as accurate as copy subject.

**Pull request merged**
