### PR TITLE
[WPE][GTK] Share public headers

### PR DESCRIPTION
**Pull request by mcatanzaro**
#### f76a7e30e5749af897b83cc75b2534b1afa32552
<pre>
[WPE][GTK] Share public headers
<a href="https://bugs.webkit.org/show_bug.cgi?id=243809">https://bugs.webkit.org/show_bug.cgi?id=243809</a>

Reviewed by Carlos Garcia Campos.

We&apos;re soon going to have four public APIs:

* GTK 3
* GTK 4
* WPE 1.0/1.1
* WPE 2.0

To avoid having four different copies of all the public headers, let&apos;s
generate the public headers from a shared template. We&apos;ll start by
unifying the existing WPE and GTK headers without making any API
changes. Using a customized version of unifdef, we can use
PLATFORM(GTK) and PLATFORM(WPE) guards in the header templates in order
to hide platform-specific code from the generated headers. Be careful
around comments, though: the guards do not work inside comments, so if
any part of a doc comment needs to differ, the entire doc comment will
need to be duplicated.

Also note that I don&apos;t touch the DOM API. GTK 3 will just have to be
different from the other APIs.

Thanks to Adrian for proposing this solution.

I also got rid of WebKitForwardDeclarations.h. Turns out it was only
needed to break an include cycle between GTK&apos;s WebKitWebView.h and
WebKitPrintOperation.h, but that can be solved easily enough without it.

I also added WebKitVersion.h to WPE&apos;s web process API, to match GTK.

Note: the generate-api-header script and various other portions of this
commit were written by Carlos Garcia and reviewed by Michael.

* Source/WebKit/GLib.cmake: Added.
* Source/WebKit/PlatformGTK.cmake:
* Source/WebKit/PlatformWPE.cmake:
* Source/WebKit/Scripts/glib/generate-api-header.py: Added.
* Source/WebKit/UIProcess/API/glib/WebKitApplicationInfo.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitApplicationInfo.h.
* Source/WebKit/UIProcess/API/glib/WebKitAuthenticationRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitAuthenticationRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitAutocleanups.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitAutocleanups.h.
* Source/WebKit/UIProcess/API/glib/WebKitAutomationSession.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitAutomationSession.h.
* Source/WebKit/UIProcess/API/glib/WebKitBackForwardList.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitBackForwardList.h.
* Source/WebKit/UIProcess/API/glib/WebKitBackForwardListItem.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitBackForwardListItem.h.
* Source/WebKit/UIProcess/API/glib/WebKitContextMenu.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitContextMenu.h.
* Source/WebKit/UIProcess/API/glib/WebKitContextMenuActions.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitContextMenuActions.h.
* Source/WebKit/UIProcess/API/glib/WebKitContextMenuItem.h.in: Renamed from Source/WebKit/UIProcess/API/gtk3/WebKitContextMenuItem.h.
* Source/WebKit/UIProcess/API/glib/WebKitCookieManager.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitCookieManager.h.
* Source/WebKit/UIProcess/API/glib/WebKitCredential.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitCredential.h.
* Source/WebKit/UIProcess/API/glib/WebKitDefines.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitDefines.h.
* Source/WebKit/UIProcess/API/glib/WebKitDeviceInfoPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitDeviceInfoPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitDownload.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitDownload.h.
* Source/WebKit/UIProcess/API/glib/WebKitEditingCommands.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitEditingCommands.h.
* Source/WebKit/UIProcess/API/glib/WebKitEditorState.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitEditorState.h.
* Source/WebKit/UIProcess/API/glib/WebKitError.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitError.h.
* Source/WebKit/UIProcess/API/glib/WebKitFaviconDatabase.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitFaviconDatabase.h.
* Source/WebKit/UIProcess/API/glib/WebKitFileChooserRequest.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitFileChooserRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitFindController.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitFindController.h.
* Source/WebKit/UIProcess/API/glib/WebKitFormSubmissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitFormSubmissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitGeolocationManager.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitGeolocationManager.h.
* Source/WebKit/UIProcess/API/glib/WebKitGeolocationPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitGeolocationPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitHitTestResult.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitHitTestResult.h.
* Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in: Renamed from Source/WebKit/UIProcess/API/gtk3/WebKitInputMethodContext.h.
* Source/WebKit/UIProcess/API/glib/WebKitInstallMissingMediaPluginsPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitInstallMissingMediaPluginsPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitJavascriptResult.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitJavascriptResult.h.
* Source/WebKit/UIProcess/API/glib/WebKitMediaKeySystemPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitMediaKeySystemPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitMemoryPressureSettings.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitMemoryPressureSettings.h.
* Source/WebKit/UIProcess/API/glib/WebKitMimeInfo.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitMimeInfo.h.
* Source/WebKit/UIProcess/API/glib/WebKitNavigationAction.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitNavigationAction.h.
* Source/WebKit/UIProcess/API/glib/WebKitNavigationPolicyDecision.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitNavigationPolicyDecision.h.
* Source/WebKit/UIProcess/API/glib/WebKitNetworkProxySettings.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitNetworkProxySettings.h.
* Source/WebKit/UIProcess/API/glib/WebKitNotification.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitNotification.h.
* Source/WebKit/UIProcess/API/glib/WebKitNotificationPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitNotificationPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitOptionMenu.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitOptionMenu.h.
* Source/WebKit/UIProcess/API/glib/WebKitOptionMenuItem.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitOptionMenuItem.h.
* Source/WebKit/UIProcess/API/glib/WebKitPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitPlugin.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitPlugin.h.
* Source/WebKit/UIProcess/API/glib/WebKitPolicyDecision.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitPolicyDecision.h.
* Source/WebKit/UIProcess/API/glib/WebKitResponsePolicyDecision.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitResponsePolicyDecision.h.
* Source/WebKit/UIProcess/API/glib/WebKitScriptDialog.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitScriptDialog.h.
* Source/WebKit/UIProcess/API/glib/WebKitSecurityManager.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitSecurityManager.h.
* Source/WebKit/UIProcess/API/glib/WebKitSecurityOrigin.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitSecurityOrigin.h.
* Source/WebKit/UIProcess/API/glib/WebKitSettings.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitSettings.h.
* Source/WebKit/UIProcess/API/glib/WebKitURIRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitURIRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitURIResponse.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitURIResponse.h.
* Source/WebKit/UIProcess/API/glib/WebKitURISchemeRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitURISchemeRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitURISchemeResponse.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitURISchemeResponse.h.
* Source/WebKit/UIProcess/API/glib/WebKitURIUtilities.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitURIUtilities.h.
* Source/WebKit/UIProcess/API/glib/WebKitUserContent.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitUserContent.h.
* Source/WebKit/UIProcess/API/glib/WebKitUserContentFilterStore.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitUserContentFilterStore.h.
* Source/WebKit/UIProcess/API/glib/WebKitUserContentManager.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitUserContentManager.h.
* Source/WebKit/UIProcess/API/glib/WebKitUserMediaPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitUserMediaPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitUserMessage.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitUserMessage.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebContext.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitWebContext.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebResource.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitWebResource.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebView.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitWebView.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebViewSessionState.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitWebViewSessionState.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebsiteData.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitWebsiteData.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebsiteDataAccessPermissionRequest.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitWebsiteDataAccessPermissionRequest.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebsiteDataManager.h.in: Renamed from Source/WebKit/UIProcess/API/wpe/WebKitWebsiteDataManager.h.
* Source/WebKit/UIProcess/API/glib/WebKitWebsitePolicies.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitWebsitePolicies.h.
* Source/WebKit/UIProcess/API/glib/WebKitWindowProperties.h.in: Renamed from Source/WebKit/UIProcess/API/gtk/WebKitWindowProperties.h.
* Source/WebKit/UIProcess/API/gtk/WebKitApplicationInfo.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitAuthenticationRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitAutomationSession.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitBackForwardList.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitBackForwardListItem.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitContextMenu.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitDefines.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitDeviceInfoPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitDownload.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitEditingCommands.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitEditorState.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitFindController.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitForwardDeclarations.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitGeolocationManager.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitGeolocationPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitHitTestResult.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitInstallMissingMediaPluginsPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitMediaKeySystemPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitMemoryPressureSettings.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitMimeInfo.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitNavigationAction.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitNetworkProxySettings.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitNotification.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitNotificationPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitOptionMenu.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitOptionMenuItem.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitPlugin.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitPolicyDecision.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitPrintOperation.h:
* Source/WebKit/UIProcess/API/gtk/WebKitResponsePolicyDecision.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitScriptDialog.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitSecurityManager.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitSecurityOrigin.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitURIRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitURIResponse.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitURISchemeRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitURISchemeResponse.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitURIUtilities.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitUserContent.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitUserContentFilterStore.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitUserContentManager.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitUserMediaPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitUserMessage.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitWebResource.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitWebViewBase.h.in: Renamed from Source/WebKit/UIProcess/API/gtk3/WebKitWebViewBase.h.
* Source/WebKit/UIProcess/API/gtk/WebKitWebViewSessionState.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitWebsiteData.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitWebsiteDataAccessPermissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/gtk/WebKitWebsiteDataManager.h: Removed.
* Source/WebKit/UIProcess/API/gtk4/WebKitContextMenuItem.h: Removed.
* Source/WebKit/UIProcess/API/gtk4/WebKitInputMethodContext.h: Removed.
* Source/WebKit/UIProcess/API/gtk4/WebKitWebViewBase.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitAutocleanups.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitContextMenuActions.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitContextMenuItem.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitCookieManager.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitCredential.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitError.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitFaviconDatabase.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitFileChooserRequest.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitFormSubmissionRequest.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitInputMethodContext.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitJavascriptResult.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitNavigationPolicyDecision.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitSettings.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitWebContext.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitWebView.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitWebsitePolicies.h: Removed.
* Source/WebKit/UIProcess/API/wpe/WebKitWindowProperties.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitConsoleMessage.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitConsoleMessage.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitFrame.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitFrame.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitScriptWorld.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitScriptWorld.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitWebEditor.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitWebEditor.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitWebExtension.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitWebExtension.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitWebExtensionAutocleanups.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitWebExtensionAutocleanups.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitWebHitTestResult.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitWebHitTestResult.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/WebKitWebPage.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitWebPage.h.
* Source/WebKit/WebProcess/InjectedBundle/API/glib/webkit-web-extension.h.in: Renamed from Source/WebKit/WebProcess/InjectedBundle/API/gtk/webkit-web-extension.h.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitConsoleMessage.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitScriptWorld.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitWebEditor.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitWebExtension.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitWebExtensionAutocleanups.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/gtk/WebKitWebHitTestResult.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitFrame.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/wpe/WebKitWebPage.h: Removed.
* Source/WebKit/WebProcess/InjectedBundle/API/wpe/webkit-web-extension.h: Removed.
* Source/cmake/FindUnifdef.cmake: Added.
* Source/cmake/OptionsGTK.cmake:
* Source/cmake/OptionsWPE.cmake:
* Tools/gtk/dependencies/apt:
* Tools/gtk/dependencies/brew:
* Tools/gtk/dependencies/dnf:
* Tools/gtk/dependencies/pacman:
* Tools/wpe/dependencies/apt:
* Tools/wpe/dependencies/dnf:
* Tools/wpe/dependencies/pacman:

Canonical link: <a href="https://commits.webkit.org/253528@main">https://commits.webkit.org/253528@main</a>
</pre>

### CODE REVIEW

**Comment by philn** [comment]
Please, this time, coordinate with our QA folks before landing this, since it seems clean builds will be needed? Incremental WPE build failed on EWS, for instance.

CC @dpino @lauromoura

**Comment by mcatanzaro** [comment]
> Please, this time, coordinate with our QA folks before landing this, since it seems clean builds will be needed? Incremental WPE build failed on EWS, for instance.

Clean builds shouldn't be needed. It's failing because, sadly, it's actually still broken. I'm bamboozled, as usual. Will post my findings in the bug report.

**Comment by carlosgcampos** [comment]
I've pushed a commit to try a simpler approach using a script as I initially proposed. This way it's a single step and we don't need the intermediate temporary.

**Review by carlosgcampos — APPROVED** [review]
LGTM

**Comment by mcatanzaro** [comment]
Unfortunately we still have a problem with the incremental build. When the .h.in template is modified, the .h header file does not get regenerated. I'm so confused because it looks like it ought to work. :/

**Comment by mcatanzaro** [comment]
> Unfortunately we still have a problem with the incremental build. When the .h.in template is modified, the .h header file does not get regenerated. I'm so confused because it looks like it ought to work. :/

The problem was caused by unifdef not generating headers if it doesn't strip out any conditionals. What a mess. :( Carlos Garcia fixed it by changing how we use unifdef. He also improved this pull request by adding some extra manual preprocessing in the python script to allow us to use system unifdef so we don't have to bundle our own patched unifdef in Source/ThirdParty.

**Comment by mcatanzaro** [comment]
I think we should be good now except for the LTS bots that are still using jhbuild rather than flatpak. These bots need to have unifdef installed.

**Comment by mcatanzaro** [comment]
Note this will break bisects. Sorry. :/ You'll likely need to do a clean build after unapplying this patch, i.e. when going backwards from a newer commit to the older commit. This is because the generated headers will still be in the include path and they'll conflict with the original headers.

**Pull request merged**
