### PR TITLE
PC_GCRYPT_FOUND should be checked in FindLibGcrypt.cmake

### PR DESCRIPTION
**Pull request by parr0tr1ver**
PC_GCRYPT_FOUND should be checked in FindLibGcrypt.cmake
    https://bugs.webkit.org/show_bug.cgi?id=254402
    
    Reviewed by NOBODY (OOPS!).
    
    After `pkg_check_modules(PC_GCRYPT QUIET libgcrypt)` in
    FindLibGcrypt.cmake, PC_GCRYPT_FOUND will be set but PC_GCRYPT is kept
    empty. So check PC_GCRYPT_FOUND instead.
    
    * Source/cmake/FindLibGcrypt.cmake:

https://github.com/WebKit/WebKit/commit/a17d2152bdd1445df479b506f4e43c59640f8ace

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/1895 "Passed style check") | [  ~~🛠 ios~~](https://ews-build.webkit.org/#/builders/26/builds/1926 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/1988 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/2821 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/1985 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/2001 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/1971 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/1754 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/1914 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/15/builds/1704 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/1697 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/2666 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/1699 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/10/builds/1683 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/1600 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/20/builds/1585 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/1738 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/1730 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/2830 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/1815 "Built successfully and passed tests") | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/30/builds/1753 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [⏳ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-WK2-Tests-EWS "Waiting to run tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/1954 "Built successfully") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/4/builds/1678 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/1694 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/444 "Failed to checkout and rebase branch from PR 12357") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/1842 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/1999 "Built successfully") | 
| | | | [  ~~🧪 jsc-mips-tests~~](https://ews-build.webkit.org/#/builders/3/builds/558 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") |

### CODE REVIEW

**Comment by philn** [comment]
Looks good I guess but please read the PR template and follow the instructions...

**Comment by aperezdc** [comment]
@parr0tr1ver The change in the patch is fine, but you will need to use `Tools/Scripts/git-webkit` to to make the commit log follows the project guidelines. Could you please update the PR using the script? Thanks in advance!

**Comment by parr0tr1ver** [comment]
Closed by script and reopen it.

**Comment by parr0tr1ver** [comment]
> @parr0tr1ver The change in the patch is fine, but you will need to use `Tools/Scripts/git-webkit` to to make the commit log follows the project guidelines. Could you please update the PR using the script? Thanks in advance!

@aperezdc I updated the commit but messed up this PR with the script.  I'll try to update the description manually.

**Review by aperezdc — APPROVED** [review]

**Comment by aperezdc** [comment]
@parr0tr1ver I think the scripts (and the EWS builders) are confused because the work branch in your repository is called `main`. I have opened [a bug report](https://bugs.webkit.org/show_bug.cgi?id=254913) to solve that. I am afraid that the merge queue would also trip on this patch if we tried to merge it.

In the meantime, could you try submitting from a branch with a different name? For example, from your `main` branch you can use something like `git switch -c pc-gcrypt && git webkit pfr`&mdash;IIUC that should work.

**Comment by parr0tr1ver** [comment]
@aperezdc I opened a new PR #12360  with branch parr0tr1ver:dev-FindLibGcrypt.

**Comment by aperezdc** [comment]
> @aperezdc I opened a new PR #12360 with branch parr0tr1ver:dev-FindLibGcrypt.

That worked, thanks!

**Pull request closed without merging**
