### PR TITLE
Add xfail annotations to existing webkitpy scm_unittest

### PR DESCRIPTION
**Pull request by gsnedders**
#### 74b1edfb3f780f5697edf917b3a72a6929469039
<pre>
Add xfail annotations to existing webkitpy scm_unittest
<a href="https://bugs.webkit.org/show_bug.cgi?id=244292">https://bugs.webkit.org/show_bug.cgi?id=244292</a>

Reviewed by Jonathan Bedard.

* Tools/CISupport/build-webkit-org/steps.py:
(RunWebKitPyTests): Run tests with --all
* Tools/CISupport/build-webkit-org/steps_unittest.py:
* Tools/CISupport/ews-build/steps.py:
(RunWebKitPyPython2Tests): Run tests with --all
(RunWebKitPyPython3Tests): Run tests with --all
* Tools/CISupport/ews-build/steps_unittest.py:
(test_success):
(test_unexpected_failure):
* Tools/Scripts/webkitpy/common/checkout/scm/git.py:
(Git.create_patch): Add assert to make failure more obvious
* Tools/Scripts/webkitpy/common/checkout/scm/scm_unittest.py:
(SVNTest): Add various @xfail
(GitTest): Add various @xfail
(GitSVNTest): Add various @xfail

Canonical link: <a href="https://commits.webkit.org/253880@main">https://commits.webkit.org/253880@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/658cbed03b16f3ae27d97e76f3fa06360ee9aa69

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/87327 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/31415 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/18138 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/96554 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/149901 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/91302 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/29778 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/25979 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/79441 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/91328 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/92944 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/24059 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/74119 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/23906 "Passed tests") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/5/builds/90932 "Passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/79031 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/79253 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/66922 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/27495 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/13089 "Passed tests") | | 
| [✅ 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/86419 "Passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/27447 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/14104 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/2729 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/29133 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/36965 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/29065 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/33381 "Passed tests") | |

### CODE REVIEW

**Comment by gsnedders** [comment]
Oh, this didn't file a bug as expected :(

**Review by JonWBedard — APPROVED** [review]
I wonder how many of these tests we should just delete, they're mostly testing `webkit-patch` foo that we're slowly deprecating.

**Comment by JonWBedard** [comment]
Note that Services tests are still failing, need to address that.

**Comment by gsnedders** [comment]
> I wonder how many of these tests we should just delete, they're mostly testing `webkit-patch` foo that we're slowly deprecating.

Quite a lot, probably. But getting tests back into a state where they all run to their expected results seems higher priority.

**Pull request merged**
