### PR TITLE
dominant-baseline property should be inherited

### PR DESCRIPTION
**Pull request by Ahmad-S792**
#### 0ed9d940afc3aac44f07b5f0b68626972aeeb6c1
<pre>
dominant-baseline property should be inherited

<a href="https://bugs.webkit.org/show_bug.cgi?id=139258">https://bugs.webkit.org/show_bug.cgi?id=139258</a>

Reviewed by Tim Nguyen.

This patch aligns WebKit with Blink / Chromium, Gecko / Firefox
and web spec [1] by making this property inherited.

[1] <a href="https://drafts.csswg.org/css-inline/#dominant-baseline">https://drafts.csswg.org/css-inline/#dominant-baseline</a>

Merge: <a href="https://src.chromium.org/viewvc/blink?view=revision&amp">https://src.chromium.org/viewvc/blink?view=revision&amp</a>;revision=199970

* Source/WebCore/css/CSSProperties.json: Add &apos;inherited:true&apos;
* Source/WebCore/rendering/style/SVGRenderStyle.cpp:
(SVGRenderStyle::changeRequiresLayout): Change from non-inherited to inherited
* Source/WebCore/rendering/style/SVGRenderStyle.h: functions changes to make &apos;inherited&apos;
(SVGRenderStyle::setBitDefaults): Ditto
(SVGRenderStyle::InheritedFlags::opeartor==): Update for &apos;dominantBaseline&apos; (Support / Help from Antoine Quint)
* LayoutTests/svg/custom/dominant-baseline-inherit.svg: Add Test Case
* LayoutTests/svg/custom/dominant-baseline-inherit-expected.svg: Add Test Case Expectation
* LayoutTests/platform/mac/svg/custom/alignment-baseline-modes-expected.txt: Rebaselined
* LayoutTests/platform/mac/svg/custom/alignment-baseline-modes-expected.png: Rebaselined
* LayoutTests/platform/ios/svg/custom/alignment-baseline-modes-expected.txt: Rebaselined
* LayoutTests/platform/gtk/svg/custom/alignment-baseline-modes-expected.png: Rebaselined
* LayoutTests/platform/glib/svg/custom/alignment-baseline-modes-expected.txt: Rebaselined

Canonical link: <a href="https://commits.webkit.org/265525@main">https://commits.webkit.org/265525@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/b69282b4cdf0dc100f19b8a2d17e4df16b81a333

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/11124 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/11334 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/11661 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/12775 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/10614 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/11139 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/13713 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/11319 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/13526 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/11285 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/12174 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/9387 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/13179 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/9467 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/10062 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/17265 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/10538 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/10216 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/13437 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/10649 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/8735 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/9819 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/2664 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/14094 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/10501 "Built successfully") | | |

### CODE REVIEW

**Comment by nikolaszimmermann** [comment]
Looks good, why is it in draft state? 🙈

**Comment by Ahmad-S792** [comment]
> Looks good, why is it in draft state? 🙈

I think it might fail bunch of WPT and other bits, so waiting for EWS to give it a spin so I can fix them in one go. Hence, I kept it in draft. :-)

**Comment by nikolaszimmermann** [comment]
Fair enough :-)

**Comment by Ahmad-S792** [comment]
@graouts - can you help in finding cause of 'animation' tests failures due to this patch at 0 ms?

**Comment by graouts** [comment]
> @graouts - can you help in finding cause of 'animation' tests failures due to this patch at 0 ms?

Not sure. I tried your patch and `DiscreteSVGPropertyWrapper` is correctly setting the value in its `blend()` function and I can check that `destination.svgStyle().dominantBaseline()` is set correctly after it is called.

Maybe @anttijk will detect something fishy with the way the value is stored now that it's moving from non-inherited to inherited.

**Comment by graouts** [comment]
Hmm, debugging a bit I see that when `newStyle` is obtained from the `applyAnimations` lambda in `TreeResolver::createAnimatedElementUpdate()` the `dominant-baseline` bit is gone.

**Comment by graouts** [comment]
> Hmm, debugging a bit I see that when `newStyle` is obtained from the `applyAnimations` lambda in `TreeResolver::createAnimatedElementUpdate()` the `dominant-baseline` bit is gone.

Oh, I see where things go wrong. We hit this clause in the `applyAnimations()` lambda:

```c++
        if (*resolvedStyle.style == *animatedStyle && animationImpact.isEmpty())
            return { WTFMove(resolvedStyle.style), animationImpact };
```

The `RenderStyle` `==` operator does not account for `dominant-baseline` it appears and thus the animated value here is discarded.

**Comment by graouts** [comment]
> The `RenderStyle` `==` operator does not account for `dominant-baseline` it appears and thus the animated value here is discarded.

@Ahmad-S792 You'll need to update `SVGRenderStyle::InheritedFlags::operator==(const InheritedFlags& other)` to check `dominantBaseline == other.dominantBaseline`.

**Comment by Ahmad-S792** [comment]
> > The `RenderStyle` `==` operator does not account for `dominant-baseline` it appears and thus the animated value here is discarded.
> 
> @Ahmad-S792 You'll need to update `SVGRenderStyle::InheritedFlags::operator==(const InheritedFlags& other)` to check `dominantBaseline == other.dominantBaseline`.

Thanks a lot. @graouts You helped a lot more than expected. Appreciate it. It will update it and push during my lunch break and get it over the line. :-)

**Review by nt1m — APPROVED** [review]

**Pull request merged**
