### PR TITLE
input[type=date] with invalid date should return empty string for value IDL attribute of the default value

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Input[type=date] with invalid date should return empty string for value IDL attribute instead of the default value

<a href="https://bugs.webkit.org/show_bug.cgi?id=120038">https://bugs.webkit.org/show_bug.cgi?id=120038</a>

Reviewed by NOBODY (OOPS!).

Merge <a href="https://chromium.googlesource.com/chromium/blink/+/cb52052e3522824fa9ffc73cb34667492d47d976">https://chromium.googlesource.com/chromium/blink/+/cb52052e3522824fa9ffc73cb34667492d47d976</a>

* Source/WebCore/html/BaseDateAndTimeInputType.cpp
(WebCore::BaseDateAndTimeInputType::visibleValue): Modified BaseDateAndTimeInputType::sanitizeValue so it should return an empty string if the input string is invalid.
</pre>

https://github.com/WebKit/WebKit/commit/ede11974dec4b04d93f83e16783b9b76b010ba5b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/86626 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/30674 "Built successfully") | [✅ ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/43/builds/17565 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/95468 "Built successfully") | [❌ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/149194 "Found 1 new test failure: fast/forms/date-multiple-fields-keyboard-events.html") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/90611 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/29052 "Built successfully") | [✅ ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/25494 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/78801 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/90711 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/92242 "Passed tests") | [✅ ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/68/builds/23479 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/73553 "Built successfully") | [✅ ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/23544 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/78484 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/43/builds/17565 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/66550 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/78561 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/26841 "Built successfully") | [✅ ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/43/builds/17565 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/72198 "Built successfully") | 
| | [✅ ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/67/builds/26761 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/43/builds/17565 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ ~~🧪 jsc-armv7-tests~~](https://ews-build.webkit.org/#/builders/46/builds/25783 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/28438 "Built successfully") | [✅ ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/36563 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/74980 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/28382 "Built successfully") | [✅ ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/43/builds/17565 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ ~~🧪 jsc-mips-tests~~](https://ews-build.webkit.org/#/builders/45/builds/16580 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") |

### CODE REVIEW

**Comment by rniwa** [comment]
Thanks for the patch! Bug we should also merge a test!

**Comment by Ahmad-S792** [comment]
> Thanks for the patch! Bug we should also merge a test!

What is confusing are test cases talk about  - Please run this with DumpRenderTree.

I can create them and then try to add to this pull request (will be first time trying) or I can land them in separate pull request? What do you suggest?

**Comment by rniwa** [comment]
> > Thanks for the patch! Bug we should also merge a test!
> 
> What is confusing are test cases talk about - Please run this with DumpRenderTree.

Oh, DumpRenderTree is the name of WebKit's test runner. See https://github.com/WebKit/WebKit/blob/main/Introduction.md#correctness-testing-in-webkit

> I can create them and then try to add to this pull request (will be first time trying) or I can land them in separate pull request? What do you suggest?

Yes, we should include the test in this PR.

**Comment by Ahmad-S792** [comment]
@rniwa - I think I should change it to "Draft" till I figure out on how to work properly with GitHub because now with new push, I am getting quite a lot of failures. If you can guide a bit, it would be great. Thanks!

**Pull request closed without merging**
