### PR TITLE
[LBSE] Unify all SVG geometry/transform computations with CSS

### PR DESCRIPTION
**Pull request by nikolaszimmermann**
#### 5c3443a0ab7a7fdeaeeb20c104da59b55de0e265
<pre>
[LBSE] Unify all SVG geometry/transform computations with CSS
<a href="https://bugs.webkit.org/show_bug.cgi?id=247672">https://bugs.webkit.org/show_bug.cgi?id=247672</a>

Reviewed by Rob Buis.

Consistently use SVGLayerTranformComputation whenever transformations
need to be computed in the SVG render tree, utilizing &apos;TransformState&apos;
and &apos;mapLocalToContainer&apos;, which were previously extended for SVGs
needs (TransformState::TransformMatrixTracking).

This assures that the very same transformation matrices / code paths
are used for the following items:

- Query SVG CTM (e.g. from JS), via SVGLocatable interface
  getCTM() / getScreenCTM() / (getTransformToElement()).

- Painting layers for SVG renderers
  RenderLayer::paintLayerByApplyingTransform() uses the 4x4 3D aware
  m_transform matrix previously computed in RenderLayer::updateTransform().

- DOM geometry API (getBoundingClientRect / getClientRect / etc.)
...

Covered by existing tests, fixes a bunch of tests in LBSE related to
getCTM &amp; friends. One test - svg/zoom/page/zoom-zoom-coords.xhtml was
wrong in all browsers -- fix that, now legacy fails it and LBSE passes
as all others (no change in behavior for legacy, only the test changed).

* LayoutTests/platform/ios-wk2/svg/custom/getClientRects-expected.txt:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/TestExpectations:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/W3C-SVG-1.1/coords-viewattr-01-b-expected.txt:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/container-opacity-clip-viewBox-expected.png: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/getTransformToElement-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/getscreenctm-in-mixed-content-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/getscreenctm-in-scrollable-div-area-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/getscreenctm-in-scrollable-div-area-nested-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/getscreenctm-in-scrollable-svg-area-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/custom/text-ctm-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/text/selection-doubleclick-expected.txt:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/text/text-rescale-expected.txt:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/zoom/page/zoom-coords-viewattr-01-b-expected.txt:
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/zoom/page/zoom-zoom-coords-expected.txt: Copied from LayoutTests/platform/mac/svg/zoom/page/zoom-zoom-coords-expected.txt.
* LayoutTests/platform/mac-ventura-wk2-lbse-text/svg/zoom/text/zoom-coords-viewattr-01-b-expected.txt:
* LayoutTests/platform/mac/svg/zoom/page/zoom-zoom-coords-expected.txt:
* LayoutTests/svg/custom/getClientRects-expected.txt:
* LayoutTests/svg/zoom/page/zoom-zoom-coords.xhtml:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/dom/Element.cpp:
(WebCore::shouldObtainBoundsFromSVGModel):
(WebCore::shouldObtainBoundsFromBoxModel):
(WebCore::Element::boundsInRootViewSpace):
(WebCore::Element::absoluteEventBounds):
(WebCore::Element::getClientRects):
(WebCore::Element::boundingAbsoluteRectWithoutLayout const):
* Source/WebCore/rendering/RenderLayerModelObject.cpp:
(WebCore::RenderLayerModelObject::mapLocalToSVGContainer const):
(WebCore::RenderLayerModelObject::applySVGTransform const):
* Source/WebCore/rendering/RenderLayerModelObject.h:
* Source/WebCore/rendering/svg/RenderSVGBlock.cpp:
(WebCore::RenderSVGBlock::absoluteRects const):
(WebCore::RenderSVGBlock::absoluteQuads const):
(WebCore::RenderSVGBlock::mapLocalToContainer const):
(WebCore::RenderSVGBlock::offsetFromContainer const):
* Source/WebCore/rendering/svg/RenderSVGModelObject.cpp:
(WebCore::RenderSVGModelObject::absoluteRects const):
(WebCore::RenderSVGModelObject::absoluteQuads const):
* Source/WebCore/rendering/svg/RenderSVGRoot.cpp:
(WebCore::RenderSVGRoot::mapLocalToContainer const):
(WebCore::RenderSVGRoot::absoluteQuads const):
* Source/WebCore/rendering/svg/SVGBoundingBoxComputation.cpp:
(WebCore::SVGBoundingBoxComputation::handleRootOrContainer const):
* Source/WebCore/rendering/svg/SVGLayerTransformComputation.h:
(WebCore::SVGLayerTransformComputation::computeAccumulatedTransform const):
(WebCore::SVGLayerTransformComputation::calculateScreenFontSizeScalingFactor const):
* Source/WebCore/svg/SVGLocatable.cpp:
(WebCore::SVGLocatable::computeCTM):
* Source/WebCore/svg/SVGSVGElement.cpp:
(WebCore::SVGSVGElement::localCoordinateSpaceTransform const):
* Source/WebCore/svg/SVGUseElement.cpp:
(WebCore::SVGUseElement::toClipPath):

Canonical link: <a href="https://commits.webkit.org/256862@main">https://commits.webkit.org/256862@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/eaa123162392a0612fe66a001e824a67b0284d06

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/97012 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/6279 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/30127 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/106539 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/166818 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/100986 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/6509 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/35014 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/89406 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/103233 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/102683 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/4894 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/83627 "Built successfully") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/31911 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/86737 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/88605 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/74803 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/314 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/20084 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/295 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/21511 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4746 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/5088 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/44019 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/1530 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/40815 "Passed tests") | |

### CODE REVIEW

**Comment by nikolaszimmermann** [comment]
This depends on PR #6290, PR #6292, PR #6293, PR #6294 and PR #6295. I'll leave it in DRAFT as state as long as the dependencies aren't merged yet -- the actual patch can be reviewed, it's ready!

**Comment by nikolaszimmermann** [comment]
@rwlbuis finally ready for review. Ideally PR #6292 lands first, since this PR fixes some of the transform/getCTM/... tests there.

**Review by rwlbuis — APPROVED** [review]
LGTM.

**Comment by nikolaszimmermann** [comment]
Thanks!

**Comment by nikolaszimmermann** [comment]
Need to rebaseline gtk-wk2 results for the zoom-zoom-coords change. Will take care later.

**Pull request merged**
