### PR TITLE
Move RenderSVGResourceClipper into legacy

### PR DESCRIPTION
**Pull request by rwlbuis**
#### 8f89524115a09d620e5a6eb1eddbbfc949c5b0e4
<pre>
Move RenderSVGResourceClipper into legacy
<a href="https://bugs.webkit.org/show_bug.cgi?id=262114">https://bugs.webkit.org/show_bug.cgi?id=262114</a>

Reviewed by Nikolas Zimmermann.

Move RenderSVGResourceClipper into legacy and rename it in order
to introduce LBSE RenderSVGResourceClipper variant, which will
offer stateless clipping for RenderLayer.

* Source/WebCore/Sources.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/rendering/ReferencedSVGResources.cpp:
(WebCore::ReferencedSVGResources::referencedClipperRenderer):
* Source/WebCore/rendering/ReferencedSVGResources.h:
* Source/WebCore/rendering/RenderBox.cpp:
(WebCore::RenderBox::hitTestClipPath const):
* Source/WebCore/rendering/RenderElement.cpp:
(WebCore::RenderElement::layerCreationAllowedForSubtree const):
* Source/WebCore/rendering/RenderLayer.cpp:
* Source/WebCore/rendering/svg/Legacy/LegacyRenderSVGResourceClipperInlines.h: Copied from Source/WebCore/rendering/svg/RenderSVGResourceClipperInlines.h.
(WebCore::LegacyRenderSVGResourceClipper::clipPathElement const):
(WebCore::LegacyRenderSVGResourceClipper::clipPathUnits const):
* Source/WebCore/rendering/svg/RenderSVGResource.cpp:
(WebCore::requestPaintingResource):
(WebCore::removeFromCacheAndInvalidateDependencies):
* Source/WebCore/rendering/svg/RenderSVGResourceSolidColor.cpp:
(WebCore::RenderSVGResourceSolidColor::applyResource):
* Source/WebCore/rendering/svg/SVGBoundingBoxComputation.cpp:
* Source/WebCore/rendering/svg/SVGRenderSupport.cpp:
(WebCore::SVGRenderSupport::intersectRepaintRectWithResources):
(WebCore::SVGRenderSupport::pointInClippingArea):
* Source/WebCore/rendering/svg/SVGRenderTreeAsText.cpp:
(WebCore::writeSVGResourceContainer):
(WebCore::writeResources):
* Source/WebCore/rendering/svg/SVGRenderingContext.cpp:
(WebCore::SVGRenderingContext::prepareToRenderSVGContent):
* Source/WebCore/rendering/svg/SVGResources.cpp:
(WebCore::SVGResources::buildCachedResources):
(WebCore::SVGResources::setClipper):
* Source/WebCore/rendering/svg/SVGResources.h:
(WebCore::SVGResources::clipper const):
* Source/WebCore/rendering/svg/SVGResourcesCycleSolver.cpp:
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceClipper.cpp: Renamed from Source/WebCore/rendering/svg/RenderSVGResourceClipper.cpp.
(WebCore::LegacyRenderSVGResourceClipper::LegacyRenderSVGResourceClipper):
(WebCore::LegacyRenderSVGResourceClipper::removeAllClientsFromCache):
(WebCore::LegacyRenderSVGResourceClipper::removeClientFromCache):
(WebCore::LegacyRenderSVGResourceClipper::applyResource):
(WebCore::LegacyRenderSVGResourceClipper::pathOnlyClipping):
(WebCore::LegacyRenderSVGResourceClipper::computeInputs):
(WebCore::LegacyRenderSVGResourceClipper::applyClippingToContext):
(WebCore::LegacyRenderSVGResourceClipper::drawContentIntoMaskImage):
(WebCore::LegacyRenderSVGResourceClipper::calculateClipContentRepaintRect):
(WebCore::LegacyRenderSVGResourceClipper::hitTestClipContent):
(WebCore::LegacyRenderSVGResourceClipper::resourceBoundingBox):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceClipper.h: Renamed from Source/WebCore/rendering/svg/RenderSVGResourceClipper.h.
(WebCore::ClipperData::invalidate):
(isType):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceClipperInlines.h: Renamed from Source/WebCore/rendering/svg/RenderSVGResourceClipperInlines.h.
(WebCore::LegacyRenderSVGResourceClipper::clipPathElement const):
(WebCore::LegacyRenderSVGResourceClipper::clipPathUnits const):
* Source/WebCore/svg/SVGClipPathElement.cpp:
(WebCore::SVGClipPathElement::createElementRenderer):

Canonical link: <a href="https://commits.webkit.org/268500@main">https://commits.webkit.org/268500@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/6b439e6b4cbf426aaeb43aea6e5b4e3819ee95d1

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/19766 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/20189 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/20806 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/21661 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/18472 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/20002 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/23449 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/20333 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/20031 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/19986 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/19985 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/17194 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/22516 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/17158 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/17989 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/24278 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/18233 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/18163 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/22260 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/18754 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/15892 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/17917 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/4753 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/22268 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/18580 "Built successfully") | | |

### CODE REVIEW

**Review by nikolaszimmermann — APPROVED** [review]
Great, r=me.

**Comment by litherum** [comment]
There are now 2 sibling directories: one named Legacy and one named legacy. This isn't going to work for people with case-insensitive filesystems (like most Mac users)

https://github.com/WebKit/WebKit/tree/main/Source/WebCore/rendering/svg

**Comment by litherum** [comment]
Fixed in https://github.com/WebKit/WebKit/commit/6bef92cf112d35641e59053f35d99a580ec710ed

**Comment by rwlbuis** [comment]
> There are now 2 sibling directories: one named Legacy and one named legacy. This isn't going to work for people with case-insensitive filesystems (like most Mac users)
> 
> https://github.com/WebKit/WebKit/tree/main/Source/WebCore/rendering/svg

Oops, I must have done some local copy statements that went wrong and accidentally upstreamed it. Thanks for the fix!

**Pull request merged**
