### PR TITLE
[Skia] Import the Skia source code tree

### PR DESCRIPTION
**Pull request by aperezdc**
#### a69ccc8a7890bae451abc439812bba3b5ea86917
<pre>
[Skia] Import the Skia source code tree
<a href="https://bugs.webkit.org/show_bug.cgi?id=268974">https://bugs.webkit.org/show_bug.cgi?id=268974</a>

Reviewed by Michael Catanzaro, Brent Fulgham and Don Olmstead.

Import the Skia sources at commit 55e8dd4151ce562ce2e61162bf835bef16dd5162.
Follow-up changes will wire building the library and initial support in
the WPE port.

* Source/ThirdParty/skia: Added.
* Tools/Scripts/webkitpy/style/checker.py: Ignore most of the rules
for ThirdParty/skia.

Canonical link: <a href="https://commits.webkit.org/274314@main">https://commits.webkit.org/274314@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/dc1441b4110f208920fea0865454a1d1bf9dc688

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [  ~~🧪 style~~](https://ews-build.webkit.org/#/builders/38/builds/38700 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 ios~~](https://ews-build.webkit.org/#/builders/48/builds/17631 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/14/builds/41045 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/41231 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/34353 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/9/builds/41007 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/20441 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/51/builds/14977 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/41231 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/11/builds/39273 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/49/builds/20441 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/14/builds/41045 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/5/builds/41231 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/49/builds/20441 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/14/builds/41045 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/2/builds/42507 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/20/builds/32146 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/49/builds/20441 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/14/builds/41045 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/2/builds/42507 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [  ~~🛠 🧪 jsc-arm64~~](https://ews-build.webkit.org/#/builders/12/builds/38323 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/13510 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/51/builds/14977 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/2/builds/42507 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/15122 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/14/builds/41045 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 jsc-armv7~~](https://ews-build.webkit.org/#/builders/35/builds/45332 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/13968 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | [  ~~🧪 jsc-armv7-tests~~](https://ews-build.webkit.org/#/builders/35/builds/45332 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/5043 "Built successfully and passed tests") | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/14603 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Comment by donny-dont** [comment]
The GitHub PR UI is unable to handle any comments I have on this particular patch because of the size of the Skia sources. Could we maybe just land the Skia sources and then add in the build parts in a subsequent patch?

**Review by brentfulgham — COMMENTED** [review]
I am strongly in favor of this!

**Comment by aperezdc** [comment]
> The GitHub PR UI is unable to handle any comments I have on this particular patch because of the size of the Skia sources. Could we maybe just land the Skia sources and then add in the build parts in a subsequent patch?

Let's do it that way. I am reporposing this issue to land the Skia sources, and created a new Bugzilla issue for the build system integration.

**Review by donny-dont — APPROVED** [review]
Sony supports the integration of Skia into WebKit as a replacement for Cairo

**Comment by aperezdc** [comment]
Done, this now includes _only_ the Skia source and the edit to the linter rules, to avoid false style checker positives for code under `Source/ThirdParty/Skia/` 🍃

**Comment by smfr** [comment]
Should we use `Source/ThirdParty/skia` to match the capitalization of the other directories?

**Comment by aperezdc** [comment]
> Should we use `Source/ThirdParty/skia` to match the capitalization of the other directories?

Sure thing, there is no particular reason why we picked the `Skia` capitalization, so I'll update this to be `skia`.

**Comment by aperezdc** [comment]
Done, now with 25% more lowercase letters in the directory name 😄

**Review by mcatanzaro — APPROVED** [review]
On behalf of the capital letters reduction committee, I (reluctantly) approve this change. (It's too bad this needs to be imported into WebKit's source tree. Would be much nicer as an external dep. Oh well.)

**Comment by brentfulgham** [comment]
I support adopting Skia as a replacement for Cairo in Windows. This poses no issue to Apple's builds, aside from the performance hit of adding a large number of new files.

Could someone explain why this must be a full import into the tree, rather than an external dependency?

**Comment by brentfulgham** [comment]
I spoke with Don separately -- it seems like this is similar to ANGLE or BoringSSL where we don't have a stable external versioning system we can trust to have reliable cross-project versioning.

**Comment by aperezdc** [comment]
> I support adopting Skia as a replacement for Cairo in Windows. This poses no issue to Apple's builds, aside from the performance hit of adding a large number of new files.

🙌🏼 

> Could someone explain why this must be a full import into the tree, rather than an external dependency?

The aim is to provide as less disruption as possible.

During a discussion last week with some of the Skia maintainers they have made it clear to us that it is not in their radar to make guarantees about API/ABI stability, nor making releases of any kind. Therefore, it does not fulfill the packaging requirements for most GNU/Linux distributions, or BSD ports, and will not be available as a system dependency.

Importing the source in the WebKit tree is what makes development most convenient for WebKit developers and does not require any changes in the existing infrastructure (build bots, tooling, scripts, etc.). If we were to use a different distribution mechanism for the Skia sources, we may  need changes in a number of places. 

Moreover, the practice of shipping such dependencies under `Source/ThirdParty/` is not new and has been already in place for quite some time.

**Review by brentfulgham — APPROVED** [review]
Looks good.

**Pull request merged**
