### PR TITLE
[WTF] Integrate simdutf

### PR DESCRIPTION
**Pull request by Constellation**
#### 68eced08c0e300295df18f727536e0d92dfe1259
<pre>
[WTF] Integrate simdutf
<a href="https://bugs.webkit.org/show_bug.cgi?id=250112">https://bugs.webkit.org/show_bug.cgi?id=250112</a>
<a href="https://rdar.apple.com/104145576">rdar://104145576</a>

Reviewed by Michael Saboff.

Add simdutf for faster base64 processing for new Base64 features in ECMAScript.
Once it implements replacement character handling, we can also consider using it for
UTF-8 / UTF-16 conversion too. Apple OSS Approval: OSS-13396

* Source/WTF/WTF.xcodeproj/project.pbxproj:
* Source/WTF/wtf/CMakeLists.txt:
* Source/WTF/wtf/simdutf/LICENSE-simdutf.txt: Added.
* Source/WTF/wtf/simdutf/simdutf.cpp: Added.
(_mm512_set_epi8):
(simdutf::implementation::supported_by_runtime_system const):
(simdutf::get_available_implementations):
(simdutf::get_active_implementation):
(simdutf::match_system):
(simdutf::to_string):
(simdutf::BOM::check_bom):
(simdutf::BOM::bom_byte_size):
(simdutf::result::result):
* Source/WTF/wtf/simdutf/simdutf.h: Added.
(simdutf::internal::detect_supported_architectures):
(simdutf::internal::cpuid):
(simdutf::implementation::name const):
(simdutf::implementation::description const):
(simdutf::implementation::required_instruction_sets const):
(simdutf::implementation::implementation):
(simdutf::internal::available_implementation_list::available_implementation_list):
(simdutf::internal::atomic_ptr::atomic_ptr):
(simdutf::internal::atomic_ptr::operator const T* const):
(simdutf::internal::atomic_ptr::operator* const):
(simdutf::internal::atomic_ptr::operator-&gt; const):
(simdutf::internal::atomic_ptr::operator T*):
(simdutf::internal::atomic_ptr::operator*):
(simdutf::internal::atomic_ptr::operator-&gt;):
(simdutf::internal::atomic_ptr::operator=):

Canonical link: <a href="https://commits.webkit.org/281011@main">https://commits.webkit.org/281011@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/66647286a4e4c544e7927b5272e7de5b34ae9035

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/58419 "43933 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/37746 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/10903 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/62044 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/59/builds/8863 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/45382 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/9060 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/47314 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 wincairo-tests~~](https://ews-build.webkit.org/#/builders/59/builds/8863 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/60450 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/47/builds/35356 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/50506 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/41/builds/28158 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/32112 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/64/builds/7805 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/7867 "Built successfully") | 
| [  ~~🛠 🧪 jsc~~](https://ews-build.webkit.org/#/builders/20/builds/51510 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/54065 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/63/builds/8075 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/63748 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/57661 "Built successfully and passed tests") | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/2332 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/62/builds/8113 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/54634 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/2340 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/50527 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/54700 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/1973 "Passed tests") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/79421 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/8700 "Built successfully and passed tests") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/33575 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | [  ~~🧪 jsc-armv7-tests~~](https://ews-build.webkit.org/#/builders/25/builds/13212 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/34661 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/35745 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/34406 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Comment by litherum** [comment]
The transformation from 8-bit to 16-bit strings isn't very complicated; I'm surprised we couldn't just write the routine in vector assembly ourself. Is this really worth a 3rd party dependency?

**Comment by Constellation** [comment]
Making it enough in the fastest form is challenging, https://arxiv.org/pdf/2109.10433.pdf, and so far this is successfully making it super fast in all the architectures we care.

**Comment by lemire** [comment]
@Constellation  I recommend bumping the version. See https://github.com/simdutf/simdutf/releases

> The transformation from 8-bit to 16-bit strings isn't very complicated; I'm surprised we couldn't just write the routine in vector assembly ourself. Is this really worth a 3rd party dependency? Maybe I'm misunderstanding the motivation?

You definitively can do that (write the routine in vector assembly ourself). And some systems did just that... like [Oracle GraalVM](https://github.com/oracle/graal). However, the `simdutf` library has been running in production for some time (part of node.js and bun). We have thorough testing across a wide range of platforms, compilers and so forth. It is also being actively developed. I think @Jarred-Sumner can testify that it was beneficial for bun to adopt `simdutf`.
 

Our research on the topic:

* Robert Clausecker, Daniel Lemire, Transcoding Unicode Characters with AVX-512 Instructions (in preparation).
* Daniel Lemire, Wojciech Muła,  [Transcoding Billions of Unicode Characters per Second with SIMD Instructions](https://arxiv.org/abs/2109.10433), Software: Practice and Experience52 (2), 2022.
* John Keiser, Daniel Lemire, [Validating UTF-8 In Less Than One Instruction Per Byte](https://arxiv.org/abs/2010.03090), Software: Practice and Experience 51 (5), 2021.

We shall have more in the future.

**Comment by lemire** [comment]
The adoption of the simdutf library by the popular Node.js JavaScript runtime lead to a significant
performance gain:

> Decoding and Encoding becomes considerably faster than in Node.js 18. With the addition of simdutf for UTF-8 parsing the observed benchmark, results improved by 364% (an extremely impressive leap) when decoding in comparison to Node.js 16. ([State of Node.js Performance 2023](https://blog.rafaelgss.dev/state-of-nodejs-performance-2023))

**Comment by Constellation** [comment]
@lemire It seems that WebKit / JavaScriptCore needs following features for UTF-8 / UTF-16 and Base64.

1. replacement character in UTF transcoding
2. separate padding control option for base64 (base64 / base64_url +- omit-padding-control)

**Comment by litherum** [comment]
Is there a reason that ICU's conversion routines must be 364% slower than necessary?

**Comment by lemire** [comment]
@Constellation 

> replacement character in UTF transcoding

It is a critical feature that we must add next. We have an open issue and it is prioritized.

> separate padding control option for base64 (base64 / base64_url +- omit-padding-control)

That seems quite easy. Let me see if I can get it done today.

**Comment by lemire** [comment]
@Constellation I looked at how WebKit uses base64 encoding and decoding and I believe that simdutf already provides the necessary functions, without any need to do additional work.

This wasn't as clear as I'd like, but we are updated the documentation/README, please see https://github.com/simdutf/simdutf/pull/429

If you think I am wrong, it would be great if you could comment. Feel free to take the discussion to https://github.com/simdutf/simdutf/pull/429 if you prefer.

The transcoding with replacement is definitively something we have not yet published, but it will come 'soon'.

**Comment by lemire** [comment]
See also https://github.com/simdutf/simdutf/issues/147

**Comment by Constellation** [comment]
@lemire Recent ECMAScript added base conversion proposal and it can change base64 / base64_url with or without padding. So there are four variants we need to support: base64 w/ padding, base64 w/o padding, base64_url w/ padding and base64_url w/o padding. My understanding is that simdutf only supports base64 w/o padding and base64_url w/ padding, is it correct?

**Comment by lemire** [comment]
> My understanding is that simdutf only supports base64 w/o padding and base64_url w/ padding, is it correct?

It is quite easy to extend simdutf and I am doing so. I should be able to produce a new release later today.

**Comment by lemire** [comment]
@Constellation Resolved in 5.3.0: https://github.com/simdutf/simdutf/releases/tag/v5.3.0

**Comment by Constellation** [comment]
> Is there a reason that ICU's conversion routines must be 364% slower than necessary?

It is largely depending on ICU's implementation.

**Review by msaboff — APPROVED** [review]
rs=me

**Pull request merged**
