### PR TITLE
[JHBuild] Replace download.gnome.org for GitHub mirror or gitlab.gnome.org

### PR DESCRIPTION
**Pull request by dpino**
#### 09963421693e1d72cd5a9732a183138984894a28
<pre>
[JHBuild] Replace download.gnome.org for GitHub mirror or gitlab.gnome.org
<a href="https://bugs.webkit.org/show_bug.cgi?id=282528">https://bugs.webkit.org/show_bug.cgi?id=282528</a>

Reviewed by Carlos Alberto Lopez Perez.

Many times downloads of &apos;libsoup&apos;, &apos;glib&apos; or &apos;glib-networking&apos; fail
unexpectedly. This might be due to a problem on server side. Apparently,
GitHub mirrors are more reliably. Thus, it would be better to rely on
github mirrors in those modules where it&apos;s possible.

Also, for the ATK/ASPI modules use a git repository, instead of a
tarball.

* Tools/jhbuild/jhbuild-minimal.modules:

Canonical link: <a href="https://commits.webkit.org/286145@main">https://commits.webkit.org/286145@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/baae18ea75c60ad470504051194f2d3faeafe0b0

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/74778 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/54208 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/27595 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/79201 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/26016 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/76895 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/63344 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/1993 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/58733 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/17015 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/77845 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/48884 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/64257 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/39127 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/46139 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/21754 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/24349 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/67324 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/22099 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/80691 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/2096 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/1248 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/66993 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/2244 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/64275 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/66286 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/10228 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/8381 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/11567 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/2061 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/2089 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/3009 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/2096 "Built successfully") | | |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
We've been having pretty severe infrastructure problems this past week. GitLab has been especially unreliable. I don't think switching from download.gnome.org -> gitlab.gnome.org is likely to improve reliability in the long run; the download website is likely generally more reliable since it's much simpler and doesn't require regular downtime.

**Comment by dpino** [comment]
> We've been having pretty severe infrastructure problems this past week. GitLab has been especially unreliable. I don't think switching from download.gnome.org -> gitlab.gnome.org is likely to improve reliability in the long run; the download website is likely generally more reliable since it's much simpler and doesn't require regular downtime.

There are two things mixed up in this PR, one is replacing `download.gnome.org` for `github.com` for those GNOME modules that have a mirror website on GitHub (`libsoup`, `glib`, `glib-networking`). The other part is to move the repositories not having a GitHub mirror from tarballs to git repositories (download.gnome.org -> gitlab.gnome.org). Perhaps it's like you say and it doesn't improve reliability, but I still prefer to use git repositories over tarballs.

**Review by clopez — APPROVED** [review]

**Comment by aperezdc** [comment]
> [...] but I still prefer to use git repositories over tarballs.

Why? Apart from the inconveniences of being much slower to fetch than tarballs, taking more space on disk, and harder to store in a cache... Is there any advantage using Git for packages that have official releases as tarball?

**Comment by dpino** [comment]
> > [...] but I still prefer to use git repositories over tarballs.
> 
> Why? Apart from the inconveniences of being much slower to fetch than tarballs, taking more space on disk, and harder to store in a cache... Is there any advantage using Git for packages that have official releases as tarball?

JHBuid allows to fetch git repositories as shallow copies, thus it doesn't occupy more than a tarball. 

All the network errors I have seen some far in JHBuild are related to downloading tarballs. They are errors like this:

```
2024-08-29T16:07:16.4093783Z *** Checking out glib-networking *** [6/26]
2024-08-29T16:07:16.4094997Z curl --retry 5 --fail --continue-at - -L https://download.gnome.org/sources/glib-networking/2.70/glib-networking-2.70.0.tar.xz -o /home/pwuser/.cache/jhbuild/downloads/glib-networking-2.70.0.tar.xz
2024-08-29T16:07:16.4266123Z Failed to build WPE port dependencies with jhbuild
2024-08-29T16:07:16.4296215Z Died at ./Tools/Scripts/update-webkitwpe-libs line 26.
```

Which corresponds to https://gitlab.gnome.org/GNOME/jhbuild/-/blob/master/jhbuild/versioncontrol/tarball.py?ref_type=heads#L192

I have never seen a module setup as a git repostiory that fails to download, and I have been maintaining builds with JHBuild for a long time.

Another issue with tarballs, although is a minor thing, is that sometimes it happens someone updates the version of a module but forgets to refresh the SHA256 value. When that happens, the tarball download ends unsuccessfully without an error message, which makes hard to figure out what has happened. This won't happen if the repository is setup as a git repository.

**Comment by dpino** [comment]
I also forgot to mention that these network errors from `download.gnome.org` on tarballs are so common that we also switched to git repositories in the JHBuild used by WebKit Container SDK https://github.com/Igalia/webkit-container-sdk/blob/main/images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules

With this I don't mean to blame `download.gnome.org`, perhaps the `curl` or `wget` commands (it happens with both) that pulls the repositories can be improved. All I know is that this problem exist, it's common and I needed a more reliable solution.

**Comment by mcatanzaro** [comment]
There's no way curl or wget is broken. It's definitely download.gnome.org.

**Comment by mcatanzaro** [comment]
I found https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1768. Probably related.

**Comment by averi** [comment]
The new AWS infrastructure GNOME is migrating to is meant to improve resiliency and increase stability, the plan is to switch download.gnome.org away from mirrorbits to use our CDN, next steps here are for us to roll out the new GNOME Release service, remove master.gnome.org from the equation and switch download.g.o to a plain web server backed by CDN77, I'd suggest to hold off any change in this regard as major architectural changes are lined up for the upcoming weeks.

**Comment by mcatanzaro** [comment]
Well I think WebKit infrastructure needs to be reliable in the meantime and it looks like Diego prefers to build from git repos anyway, so we might not revert this, but it's great that the problem is being addressed!

**Comment by dpino** [comment]
Last week the ATK modules failed to download with the following error:

```
fatal: unable to access 'https://gitlab.gnome.org/Archive/atk.git/': The requested URL returned error: 503
```

Now I'm trying to access https://gitlab.gnome.org/Infrastructure/Infrastructure/-/issues/1768, but I'm getting a 503 error:

image

**Comment by averi** [comment]
Diego, download.gnome.org has already moved to the new infrastructure, gitlab has not (yet), there's an issue with the underlying network equipment we have escalated, it's being looked at. The plan is to finalize the migration of all GNOME services by very early Q1 2025.

**Pull request merged**
