### PR TITLE
Cleanup Apple Win Platform Layout Tests

### PR DESCRIPTION
**Pull request by stwrt**
#### 2f7ad43d0e760aeb9c5f7a13d1e903fecdb7cc38
<pre>
Cleanup Apple Win Platform Layout Tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=252254">https://bugs.webkit.org/show_bug.cgi?id=252254</a>

Reviewed by Don Olmstead.

Remove Apple Win specific layout tests.

* LayoutTests/platform/win/ Removed.
* LayoutTests/platform/win-7sp0/ Removed.
* LayoutTests/platform/win-future/ Removed.

Canonical link: <a href="https://commits.webkit.org/260279@main">https://commits.webkit.org/260279@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/b4e086016e192e0340cc5af3a1860dec92e12bce

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/107767 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/16823 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/40664 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/116912 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/116293 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/18237 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/8139 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/99946 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/113524 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/13783 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/96973 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/41466 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/95690 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/28614 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/83306 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/9787 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/29962 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/10474 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/6851 "Passed tests") | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/80/builds/15941 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/49546 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7112 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/12037 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by donny-dont — APPROVED** [review]

**Comment by brentfulgham** [comment]
I believe expected results go wincairo->win->global, so we may break WinCairo by just removing all test results.

Don: Can you confirm whether removing these directories break WinCairo test results, perhaps by running locally since EWS doesn't seem to run tests?

**Comment by brentfulgham** [comment]
I.e., we might need to move some of those expectations to the wincairo folder, rather than just deleting them outright.

**Comment by fujii** [comment]
WinCairo port doesn't seem to look at them.

> Verbose baseline search path: platform\wincairo-win10-wk2 -> platform\wincairo-win10 -> platform\wincairo-wk2 -> platform\wincairo -> platform\wk2 -> generic
> Baseline search path: platform\wincairo -> platform\wk2 -> generic

**Comment by brentfulgham** [comment]
> WinCairo port doesn't seem to look at them.

Oh, excellent! Thank you, @fujii!

**Pull request merged**
