### PR TITLE
AX: make AccessibilityNodeObject::elementRect() account for <input type=checkbox switch>

### PR DESCRIPTION
**Pull request by annevk**
#### acb887bd35a9194d58f136b8059855e7cd8b700a
<pre>
AX: make AccessibilityNodeObject::elementRect() account for &lt;input type=checkbox switch&gt;
<a href="https://bugs.webkit.org/show_bug.cgi?id=263120">https://bugs.webkit.org/show_bug.cgi?id=263120</a>
<a href="https://rdar.apple.com/116920561">rdar://116920561</a>

Reviewed by Tyler Wilcock.

As &lt;input type=checkbox switch&gt; has its own role, rely here on whether
it&apos;s a native checkbox instead (which is inclusive of switch).

* LayoutTests/accessibility/checkbox-radio-element-rect-expected.txt: Added.
* LayoutTests/accessibility/checkbox-radio-element-rect.html: Added.
* LayoutTests/platform/glib/accessibility/checkbox-radio-element-rect-expected.txt: Added.
* LayoutTests/platform/ios/TestExpectations:
* LayoutTests/platform/ios/accessibility/checkbox-radio-element-rect-expected.txt: Added.
* Source/WebCore/accessibility/AccessibilityNodeObject.cpp:
(WebCore::AccessibilityNodeObject::elementRect const):

Canonical link: <a href="https://commits.webkit.org/271855@main">https://commits.webkit.org/271855@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/78ebad62bdf39a32a4aeecafdbdcff0fd8bd00bb

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/29842 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/8505 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/31155 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/32352 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/26983 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/30498 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/10684 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/5769 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/27037 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/30132 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/7122 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/25458 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/6074 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/6244 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/26545 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/33688 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/27218 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/26970 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/32417 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/6161 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/4361 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/30200 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/7905 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/26344 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/7076 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/6913 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/6692 "Built successfully") | | |

### CODE REVIEW

**Comment by annevk** [comment]
@twilco it seems that in ac7dd8d670b156b61c63ed6c32b2308fb900ac7d you didn't add a test for this or perhaps I'm missing something? Any suggestions for how to best test this?

**Comment by twilco** [comment]
Looking into this a bit more, I think this change is unnecessary. In `main`, for non-native checkboxes and radiobuttons, this is what will happen:

1. From `elementRect`, `checkboxOrRadioRect` will be called
2. `checkboxOrRadioRect` calls `labelsForNode`
3. `labelsForNode` returns early if `HTMLElement::isLabelable` returns false, which it will for these ARIA controls

**Comment by twilco** [comment]
> This is also more future proof as HTML input elements whose type is checkbox that have the switch attribute set will also be covered, despite those using the switch role.

When `<input type="checkbox" switch>` comes to be, we should change this to include them. Maybe we add a new function titled `isCheckboxLike()` that is basically just `is checkbox || is switch`. Or we could add a new `isNativeCheckboxOrRadio` function (similar patterns already exist) that is something like:

```
bool AccessibilityObject::isNativeCheckboxOrRadio() const
{
    if (!isCheckboxOrRadio())
        return false;
    auto ariaRole = ariaRoleAttribute();
    return ariaRole != AccessibilityRole::Checkbox && ariaRole != AccessibilityRole::RadioButton;
}
```

And actually, probably even better to split these up into `isNativeCheckbox` and `isNativeRadioButton` if we decided to go this route

**Comment by annevk** [comment]
I think what might not have been clear is that `isCheckbox()` is inclusive of switch. I'm open to refactoring this though. It would be nice to get in now that `<input type=checkbox switch>` is enabled by default.

**Comment by annevk** [comment]
The iOS results probably need to be rebased one more time as I didn't realize we were not running accessibility tests on iOS by default, but otherwise I think this is good to go.

**Review by twilco — APPROVED** [review]

**Pull request merged**
