### PR TITLE
font-relative units of svg elements don't take zoom factors into account

### PR DESCRIPTION
**Pull request by fujii**
#### 4e612c4d529b93a265a140b8937551b8bc794ffa
<pre>
font-relative units of svg elements don&apos;t take zoom factors into account
<a href="https://bugs.webkit.org/show_bug.cgi?id=199236">https://bugs.webkit.org/show_bug.cgi?id=199236</a>

Reviewed by Simon Fraser.

WebKit handles zoom factor (zoom property and page zoom) differently
for SVG. WebKit multiplies internal computed CSS length values by zoom
factors for HTML elements, but for SVG elements. WebKit scales SVG
differently for zooming. Thus, internal computed font-size is zoomed
for HTML elements, but unzoomed for a SVG elements.

However, CSS length values of the root SVG element of included SVG
documents should be zoomed. font-relative units of the svg elements
didn&apos;t take zoom factor into account because font-size of them were
unzoomed. It should be zoomed.

There was another problem. Assume there was a compound HTML document
included a SVG document that included another HTML document, and
font-size property was specified to a HTML element of the outer HTML
document, and a zoom factor was applied. The computed font-size of the
HTML element was zoomed. If it was inherited to elements of the inner
HTML document, the font size of the inner HTML was zoomed twice.

font-size property should be resolved at root elements of included
documents.

Before this change, WebKit inconsitently scales texts in HTML in SVG
for text zoom. If a font-size property was specified to a element of
parent SVG document, it was unzoomed. If it was specified to a element
of inner HTML document, it was zoomed. After this change, WebKit
consitetly scales texts in HTML for text zoom even if the HTML is
included in SVG and font-size property is inherited from the parent
SVG. This change needed rebaselining of expectations for some test
cases. And, some HTML in SVG documents would have text overwrap for
text zoom.

* LayoutTests/platform/glib/svg/zoom/text/zoom-hixie-mixed-008-expected.txt:
* LayoutTests/platform/glib/svg/zoom/text/zoom-hixie-mixed-009-expected.txt:
* LayoutTests/platform/ios/svg/zoom/text/zoom-hixie-mixed-008-expected.txt:
* LayoutTests/platform/ios/svg/zoom/text/zoom-hixie-mixed-009-expected.png:
* LayoutTests/platform/ios/svg/zoom/text/zoom-hixie-mixed-009-expected.txt:
* LayoutTests/platform/mac/svg/custom/foreign-object-skew-expected.png:
* LayoutTests/platform/mac/svg/custom/foreign-object-skew-expected.txt:
* LayoutTests/platform/mac/svg/zoom/text/zoom-hixie-mixed-008-expected.png:
* LayoutTests/platform/mac/svg/zoom/text/zoom-hixie-mixed-008-expected.txt:
* LayoutTests/platform/mac/svg/zoom/text/zoom-hixie-mixed-009-expected.png:
* LayoutTests/platform/mac/svg/zoom/text/zoom-hixie-mixed-009-expected.txt:
* LayoutTests/svg/zoom/page/em-and-font-size-expected.html: Added.
* LayoutTests/svg/zoom/page/em-and-font-size.html: Added.
* LayoutTests/svg/zoom/page/zoom-foreignObject-2-expected.html: Added.
* LayoutTests/svg/zoom/page/zoom-foreignObject-2.html: Added.
* LayoutTests/svg/zoom/text/zoom-hixie-mixed-008.xml:
* LayoutTests/svg/zoom/text/zoom-hixie-mixed-009.xml:
* Source/WebCore/css/svg.css:
(*|*:not(*) &gt; svg, foreignObject &gt; *|*:not(*)):
* Source/WebCore/style/StyleBuilderState.cpp:
(WebCore::Style::BuilderState::setFontSize):

Canonical link: <a href="https://commits.webkit.org/284310@main">https://commits.webkit.org/284310@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/9294b295492e1274b346b7b1f46d8a5a6eb8cacb

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/68751 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/48143 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/21410 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/72821 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/19896 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/70868 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/55939 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/19712 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/54794 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/13229 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/71818 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/43987 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/59361 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/35259 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/40652 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/16787 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/18254 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/62601 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/17135 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/74528 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/12722 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/16380 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/62291 "Found 5 new test failures: compositing/animation/repaint-after-clearing-shared-backing.html imported/w3c/web-platform-tests/css/css-view-transitions/new-content-element-writing-modes.html imported/w3c/web-platform-tests/css/css-view-transitions/new-content-flat-transform-ancestor.html imported/w3c/web-platform-tests/css/css-view-transitions/new-content-inline-with-offset-from-containing-block-clipped.html imported/w3c/web-platform-tests/css/css-view-transitions/snapshot-containing-block-includes-scrollbar-gutter.html (failure)") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/12762 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/59443 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/62326 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/10277 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/3887 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/10544 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/43944 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/45018 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/46212 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/44760 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
We do have initialZoom for computed style in `StyleAdjuster.cpp`: https://github.com/WebKit/WebKit/blob/ed96717ba87eb2682e3ac06e5883417c1db58efc/Source/WebCore/style/StyleAdjuster.cpp#L869 , is it applicable with this?

**Comment by fujii** [comment]
> We do have initialZoom for computed style in `StyleAdjuster.cpp`:
https://github.com/WebKit/WebKit/blob/ed96717ba87eb2682e3ac06e5883417c1db58efc/Source/WebCore/style/StyleAdjuster.cpp#L869
> , is it applicable with this?

I know. We don't need to change that. Do you have any suggestion with it?

**Comment by Ahmad-S792** [comment]
> > We do have initialZoom for computed style in `StyleAdjuster.cpp`:
> > https://github.com/WebKit/WebKit/blob/ed96717ba87eb2682e3ac06e5883417c1db58efc/Source/WebCore/style/StyleAdjuster.cpp#L869
> > 
> > , is it applicable with this?
> 
> I know. We don't need to change that. Do you have any suggestion with it?

No - just wanted to check, if it impacts or not.

**Review by nikolaszimmermann — COMMENTED** [review]
Looks ok to me, however I'm not an expert on that CSS / font-size resolving area, and would prefer an additional check by @anttijk / @smfr - esepcially since this adds a custom rule to the svg.css.

**Review by smfr — APPROVED** [review]

**Comment by winzig** [comment]
(I'm the original reporter of the issue). This bug still exists for me if the SVG is styled with font-size. If you refer to the [original JS Fiddle](https://jsfiddle.net/winzig/3k6x91ha/1/) from my original report, you can still reproduce this bug today on Safari Technology Preview `Release 212 (Safari 18.2, WebKit 20621.1.10.111.2)`

**Pull request merged**
