### PR TITLE
[ews-build.webkit.org] Use twisted defer when communicating with results.webkit.org

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 0a4279f491040e274f94afd752e535777f4551cb
<pre>
[ews-build.webkit.org] Use twisted defer when communicating with results.webkit.org
<a href="https://bugs.webkit.org/show_bug.cgi?id=249026">https://bugs.webkit.org/show_bug.cgi?id=249026</a>
rdar://103184263

Rubber-stamped by Aakash Jain.

We have some evidence that requests to results.webkit.org are blocking the main thread in buildbot.
We should use Twisted&apos;s defer when making web requests to prevent this problem.

* Tools/CISupport/ews-build/results_db.py:
(ResultsDatabase.JsonPrinter): Protocol to receive the contents of a request body.
(ResultsDatabase.get_results_summary): Return a Twisted defer object which resolves into the appropriate json.
(ResultsDatabase.is_test_pre_existing_failure): Ditto.
(ResultsDatabase.is_test_expected_to): Ditto.
(ResultsDatabase.main): Resolve Twisted&apos;s defers.
* Tools/CISupport/ews-build/steps.py:
(RunWebKitTests.runCommand): Renamed from commandComplete, convert to a deferred response.
(RunWebKitTests.filter_failures_using_results_db): Convert to a deferred response.
(ReRunWebKitTests.runCommand): Renamed from commandComplete, convert to a deferred response.
(RunWebKitTestsWithoutChange.runCommand): Ditto.
(RunWebKitTests.commandComplete): Renamed to runCommand.
(ReRunWebKitTests.commandComplete): Ditto.
(RunWebKitTestsWithoutChange.commandComplete): Ditto.

Canonical link: <a href="https://commits.webkit.org/257654@main">https://commits.webkit.org/257654@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/1a16bc0262ff2ac1a6961fd157221c0c233c3b0c

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/99616 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/8791 "Built successfully") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/43/builds/32702 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/108975 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/169209 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/11/builds/103617 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/76/builds/9372 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/86086 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/92084 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/106888 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/19/builds/105389 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/76/builds/9372 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/43/builds/32702 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/92084 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/76/builds/9372 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/43/builds/32702 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/36/builds/92084 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/81/builds/2621 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/43/builds/32702 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| [✅ 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/98547 "Passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/2561 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/86086 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/80/builds/8701 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/43/builds/32702 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/4424 "Built successfully") | | |

### CODE REVIEW

**Comment by aj062** [comment]
Any sample runs on uat instance?

**Comment by JonWBedard** [comment]
> Any sample runs on uat instance?

Working on that now

**Comment by JonWBedard** [comment]
I've done the twisted foo correctly, see https://ews-build.webkit-uat.org/#/builders/15/builds/141, but we're encountering another problem when making requests this way that's giving us "User timeout caused connection failure."

**Comment by JonWBedard** [comment]
> I've done the twisted foo correctly, see https://ews-build.webkit-uat.org/#/builders/15/builds/141, but we're encountering another problem when making requests this way that's giving us "User timeout caused connection failure."

Seems like the "User timeout caused connection failure." is about the configuration of our staging instance, not the code here, given that I can reproduce the problem outside of buildbot on the staging instance, but things work locally and on the production instance.

**Review by aj062 — APPROVED** [review]
rs=me

**Pull request merged**
