### PR TITLE
[Win] Remove DLLLauncherMain.cpp

### PR DESCRIPTION
**Pull request by fujii**
#### 21785f58f0ef78badabb6ab466a888bc5399cbf2
<pre>
[Win] Remove DLLLauncherMain.cpp
<a href="https://bugs.webkit.org/show_bug.cgi?id=253812">https://bugs.webkit.org/show_bug.cgi?id=253812</a>

Reviewed by Don Olmstead.

We no longer need DLLLauncherMain.cpp since Apple Windows port was
removed. It made CMake scripts complicated and the missing required
DLL error message useless.

There are three ways to do it:

1. Copy all DLL files of WebKitRequirements to the output directory during the build process.
   This makes the size of a built product archive big.
2. Runner scripts (run-webkit-tests and run-jsc etc) set PATH.
   Apple ports do the same for DYLD_FRAMEWORK_PATH.
3. Windows port developers manually set PATH to &quot;WebKitLibraries\win\bin64&quot; before running executables.
   As well as they had to set WEBKIT_LIBRARIES env var so far.

This patch takes approach #2.

* Source/JavaScriptCore/jsc.cpp:
(jscmain):
(dllLauncherEntryPoint): Deleted.
* Source/JavaScriptCore/shell/DLLLauncherMain.cpp: Removed.
* Source/JavaScriptCore/shell/PlatformWin.cmake:
* Source/WebDriver/PlatformWin.cmake:
* Source/WebDriver/WebDriverMain.cpp:
(main):
(dllLauncherEntryPoint): Deleted.
* Source/cmake/WebKitMacros.cmake:
* Tools/ImageDiff/ImageDiff.cpp:
(main):
(dllLauncherEntryPoint): Deleted.
* Tools/ImageDiff/PlatformWin.cmake:
* Tools/MiniBrowser/win/CMakeLists.txt:
* Tools/MiniBrowser/win/Common.cpp:
(DllMain): Deleted.
* Tools/MiniBrowser/win/WinMain.cpp:
(wWinMain):
(dllLauncherEntryPoint): Deleted.
* Tools/Scripts/run-javascriptcore-tests:
* Tools/Scripts/run-jsc:
* Tools/Scripts/webkitdirs.pm:
(setupWindowsWebKitEnvironment):
* Tools/Scripts/webkitpy/port/win.py:
(WinPort.setup_environ_for_server):
* Tools/TestWebKitAPI/PlatformWin.cmake:
* Tools/TestWebKitAPI/win/main.cpp:
(main):
(dllLauncherEntryPoint): Deleted.
* Tools/WebKitTestRunner/PlatformWin.cmake:
* Tools/WebKitTestRunner/win/main.cpp:
(main):
(dllLauncherEntryPoint): Deleted.
* Tools/win/DLLLauncher/DLLLauncherMain.cpp: Removed.

Canonical link: <a href="https://commits.webkit.org/265819@main">https://commits.webkit.org/265819@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/db8951f007f69bd6b4b6a6f4a4d6df71d0e13db2

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/11751 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/11950 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/12318 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/13395 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/11195 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/11770 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/14339 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/11931 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/14058 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/11915 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/12750 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/9969 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/13816 "Built successfully") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/11848 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/10042 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/10665 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/17800 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/10002 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/11119 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/10820 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/13994 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/11155 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/11228 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/9271 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/11835 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/10404 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/3187 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/14685 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/12169 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/1332 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/11085 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/2952 "Passed tests") |

### CODE REVIEW

**Comment by donny-dont** [comment]
> Realized it'd probably be better to comment here rather than on bugzilla.
> 
> It's unclear to me by what you mean by setting the path? Do you mean that the user of the binary needs to set the path? If so, I'm not convinced that's a good tradeoff, especially not without a lot more discussion involved. Because this will break some people's setup (for example, it would break the environment I've been using for testing the JSC test script changes being proposed if I rebased past it or wanted to check it afterwards) and would seem to do so in a confusing way with no real information about how to deal with it.

Would this be ok if all the `.dll`s in `%WEBKIT_LIBRARIES%\bin` were copied over? Doing a copy at the start seems reasonable but we'd have to handle the case where the files were updated due to a new release.

**Comment by foopoiuyt** [comment]
> For prebuilt Windows WebKit binary users, there is no change. They still need to copy all DLLs. https://trac.webkit.org/wiki/BuildingCairoOnWindows#DownloadbuildartifactsfromBuildbot
> 
> For Windows WebKit developers, I don't recommend to copy DLLs because of the problem Don pointed out. I recommend them to set path in the WebKit command prompt as well as setting `WEBKIT_LIBRARIES`. `path %WEBKIT_LIBRARIES%\bin64;%path%` https://trac.webkit.org/wiki/BuildingCairoOnWindows#WebKitcommandprompt

The "The specified module could not be found" section on the above link, for example, mentions needing to set WEBKIT_LIBRARIES or the copy, but does not seem to mention changing path. My point is that people potentially have flows and scripts that do this with the WEBKIT_LIBRARIES environment that don't change path and work today. If we're going to change that, at the least it should be brought up internally and a mention of such on the mailing list.

I think the change itself is nice to avoid the wackiness, but from a process standpoint, I think there are hoops to go through before changing it.

**Comment by fujii** [comment]
I will update the document after landing this change.
I don't land this change until all WinCairo tester set the path. https://bugs.webkit.org/show_bug.cgi?id=253812#c0
I created this WIP pull request to have a discussion.

**Comment by fujii** [comment]
BTW, we will be able to remove `WEBKIT_LIBRARIES` env var entirely after this change. It was used by Apple mainly to change the library directory.

**Comment by donny-dont** [comment]
> BTW, we will be able to remove `WEBKIT_LIBRARIES` env var entirely after this change. It was used by Apple mainly to change the library directory.
> 
> Ah, PlayStation port is still using WEBKIT_LIBRARIES. we will be able to remove `WEBKIT_LIBRARIES` env var entirely from Winodws port.

I personally think `WEBKIT_LIBRARIES` should be nuked from orbit. It has caused me way too many problems over the years and it should go away for everyone.

**Comment by fujii** [comment]
Unfortunately, you will have to set path to `WebKitLibraries/win/bin64` in my plan.
Alternatively, we can set env vars in scripts (run-webkit-tests, run-minibrowser, etc).
Do you like this idea?
Personally, I don't like it very much because I often have to run WebKitTestRunner.exe directly to debug.
So I have to set all env vars by using [the WebKit command prompt](https://trac.webkit.org/wiki/BuildingCairoOnWindows#WebKitcommandprompt).

**Comment by foopoiuyt** [comment]
> > BTW, we will be able to remove `WEBKIT_LIBRARIES` env var entirely after this change. It was used by Apple mainly to change the library directory.
> > Ah, PlayStation port is still using WEBKIT_LIBRARIES. we will be able to remove `WEBKIT_LIBRARIES` env var entirely from Winodws port.
> 
> I personally think `WEBKIT_LIBRARIES` should be nuked from orbit. It has caused me way too many problems over the years and it should go away for everyone.

So do you have a reasonable plan for how to deal with where to find the libraries? Because requiring them in a fixed subdirectory of the source tree doesn't seem like a good one.

**Comment by foopoiuyt** [comment]
> I will update the document after landing this change. I don't land this change until all WinCairo tester set the path. https://bugs.webkit.org/show_bug.cgi?id=253812#c0 I created this WIP pull request to have a discussion.

I guess my related point is that we probably don't have full knowledge of what things depend on this, so the WinCairo testers are one example, but potentially we have other internal builds that would be affected, and if there are other projects using the windows WebKit builds, they might be affected. So, I feel like committing a breaking change and then changing the docs and giving a heads up may not be the best way to communicate the situation.

**Comment by rkirsling** [comment]
Why do we need an env var for a default location? Shouldn't an env var just be used for referencing a copy of WebKitRequirements stored outside of the repo root directory?

**Comment by fujii** [comment]
We can append `%WEBKIT_LIBRARIES%\bin64` to `PATH` if the environment has `WEBKIT_LIBRARIES`, `WebKitLibraries\win\bin64` otherwise.

~~~diff
diff --git a/Tools/Scripts/webkitpy/port/win.py b/Tools/Scripts/webkitpy/port/win.py
index b977a40fc047..245dc087b9b9 100644
--- a/Tools/Scripts/webkitpy/port/win.py
+++ b/Tools/Scripts/webkitpy/port/win.py
@@ -143,6 +143,11 @@ class WinPort(ApplePort):
         env = super(WinPort, self).setup_environ_for_server(server_name)
         env['PYTHONUTF8'] = '1'
         env['XML_CATALOG_FILES'] = ''  # work around missing /etc/catalog <rdar://problem/4292995>
+        if 'WEBKIT_LIBRARIES' in env:
+            lib_dir = self._filesystem.join(env['WEBKIT_LIBRARIES'], 'bin64')
+        else:
+            lib_dir = self.path_from_webkit_base('WebKitLibraries', 'win', 'bin64')
+        env['PATH'] = lib_dir + ';' + env['PATH']
         return env
 
     def environment_for_api_tests(self):
~~~

This patch is not enough. We have to modify more scripts. For example, run-jsc-stress-tests.
Apple sets `DYLD_FRAMEWORK_PATH` env var in more scripts.


I don't like this approach because we have to modify more scripts and this is not useful for me to debug. https://github.com/WebKit/WebKit/pull/11435#issuecomment-1468801185
But, I don't object if you like this approach.

**Review by donny-dont — COMMENTED** [review]
I'm fine with the changes to the files I just want to make sure of a couple things

* What does this mean for the downloaded bundles? I would assume it means the .zip comes with the requirements as well and if so is that something 🍎 is ok with from a file size standpoint? If they're there it also means the build scripts need to be modified to not include the requirement tag listing and any CI scripts need to not use that.
* Has this been tested in our CI containers so we know we don't break them?

**Comment by fujii** [comment]
This patch takes approach #2. No change for built product archives.
I haven't tested it with CI tester bots. I hope it won't break. But, if will fail, I will fix or revert.

**Review by donny-dont — APPROVED** [review]

**Pull request merged**
