### PR TITLE
Fix spelling error identifer -> identifier.

### PR DESCRIPTION
**Pull request by youssefsoli**
#### ecb9c3424f835fbcd43250769868f9072a244d4f
<pre>
Fix spelling error identifer -&gt; identifier.
<a href="https://bugs.webkit.org/show_bug.cgi?id=241787">https://bugs.webkit.org/show_bug.cgi?id=241787</a>

Patch by Youssef Soliman &lt;youssefdevelops@gmail.com&gt; on 2022-06-21
Reviewed by Jonathan Bedard and Ross Kirsling.

Across multiple files, the word &quot;identifier&quot; is misspelled as &quot;identifer&quot;

* Source/WebCore/Modules/filesystemaccess/FileSystemHandleCloseScope.h:
(WebCore::FileSystemHandleCloseScope::FileSystemHandleCloseScope):
* Source/WebCore/bindings/scripts/CodeGeneratorJS.pm:
(GenerateDeletePropertyCommon):
* Source/WebCore/bindings/scripts/test/JS/JSTestNamedDeleterNoIdentifier.cpp:
(WebCore::JSTestNamedDeleterNoIdentifier::deleteProperty):
(WebCore::JSTestNamedDeleterNoIdentifier::deletePropertyByIndex):
* Source/WebCore/bindings/scripts/test/JS/JSTestNamedDeleterThrowingException.cpp:
(WebCore::JSTestNamedDeleterThrowingException::deleteProperty):
(WebCore::JSTestNamedDeleterThrowingException::deletePropertyByIndex):
* Source/WebCore/bindings/scripts/test/JS/JSTestNamedDeleterWithIndexedGetter.cpp:
(WebCore::JSTestNamedDeleterWithIndexedGetter::deleteProperty):
* Source/WebKit/GPUProcess/graphics/RemoteRenderingBackend.cpp:
(WebKit::RemoteRenderingBackend::prepareLayerBuffersForDisplay):
* Source/WebKit/Shared/ObjectIdentifierReferenceTracker.h:
* Source/WebKit/UIProcess/API/APIContentWorld.cpp:
(API::ContentWorld::worldForIdentifier):
* Source/WebKit/WebProcess/GPU/graphics/RemoteRenderingBackendProxy.cpp:
(WebKit::RemoteRenderingBackendProxy::ensureGPUProcessConnection):
* Source/WebKit/WebProcess/Storage/WebSWContextManagerConnection.messages.in:
* Source/WebKit/webpushd/PushClientConnection.mm:
(WebPushD::ClientConnection::broadcastDebugMessage):
* Tools/MiniBrowser/mac/WK2BrowserWindowController.m:
(-[WK2BrowserWindowController updateTitle:]):
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py:
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/revert.py:
(Revert.parser):
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/squash.py:
(Squash.parser):

Canonical link: <a href="https://commits.webkit.org/251701@main">https://commits.webkit.org/251701@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@295696">https://svn.webkit.org/repository/webkit/trunk@295696</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Review by rkirsling — CHANGES_REQUESTED** [review]
Files under JSTests/test262/test don't actually belong to this repo; they are regularly imported from [test262](https://github.com/tc39/test262), so you'll have to submit a separate PR over there for those files.

**Comment by youssefsoli** [comment]
https://github.com/tc39/test262/pull/3583 PR for test262

**Review by rkirsling — APPROVED** [review]

**Review by rkirsling — APPROVED** [review]
r=me as long as bots are happy (not sure why they're not running 🤔).

**Comment by JonWBedard** [comment]
I can speak for the `Tools` part of this change (and that looks good), but I think we might want someone like @hortont424, @whsieh or @achristensen07 to verify there aren't any unintended consequences in the `WebCore` and `WebKit` bits.

**Comment by youssefsoli** [comment]
It looks like the `WebCore` and `WebKit` parts only modify local variables so hopefully it shouldn't have any side-effects.

**Review by JonWBedard — APPROVED** [review]

**Pull request merged**
