### PR TITLE
Revert [253729@main] Run all WPT tests against the web-platform.test domains

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 65a288fdc104ff56f373db734bedfc513ff0a1c0
<pre>
Revert [253729@main] Run all WPT tests against the web-platform.test domains
<a href="https://bugs.webkit.org/show_bug.cgi?id=243428">https://bugs.webkit.org/show_bug.cgi?id=243428</a>

Unreviewed.

* LayoutTests/
* Source/WebKit/NetworkProcess/NetworkProcessCreationParameters.cpp:
* Source/WebKit/NetworkProcess/NetworkProcessCreationParameters.h:
* Source/WebKit/NetworkProcess/glib/WebKitOverridingResolver.cpp: Removed.
* Source/WebKit/NetworkProcess/glib/WebKitOverridingResolver.h: Removed.
* Source/WebKit/NetworkProcess/soup/NetworkProcessSoup.cpp:
* Source/WebKit/SourcesGTK.txt:
* Source/WebKit/SourcesWPE.txt:
* Source/WebKit/UIProcess/API/C/WKContext.cpp:
* Source/WebKit/UIProcess/API/C/WKContextPrivate.h:
* Source/WebKit/UIProcess/LegacyGlobalSettings.h:
* Source/WebKit/UIProcess/Network/NetworkProcessProxy.cpp:
* Tools/Scripts/webkitpy/layout_tests/run_webkit_tests.py:
* Tools/Scripts/webkitpy/layout_tests/servers/run_webkit_httpd.py:
* Tools/Scripts/webkitpy/layout_tests/servers/web_platform_test_server.py:
* Tools/Scripts/webkitpy/port/base.py:
* Tools/Scripts/webkitpy/port/driver.py:
* Tools/Scripts/webkitpy/port/gtk.py:
* Tools/Scripts/webkitpy/port/wpe.py:
* Tools/Scripts/webkitpy/w3c/test_converter.py:
* Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.cpp:
* Tools/WebKitTestRunner/InjectedBundle/InjectedBundle.h:
* Tools/WebKitTestRunner/Options.cpp:
* Tools/WebKitTestRunner/Options.h:
* Tools/WebKitTestRunner/TestController.cpp:
* Tools/WebKitTestRunner/TestController.h:
* Tools/WebKitTestRunner/TestInvocation.cpp:

Canonical link: <a href="https://commits.webkit.org/253742@main">https://commits.webkit.org/253742@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/81588bc86341d58a85218cd460f003aefc868eaa

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/86986 "Passed style check") | [  ~~🛠 ios~~](https://ews-build.webkit.org/#/builders/69/builds/31073 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/43/builds/17837 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/8/builds/95854 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/149566 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/64/builds/29437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/25730 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/79116 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/91020 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/92602 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/64/builds/29437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/73816 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/79116 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/64/builds/29437 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/43/builds/17837 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/36/builds/79116 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/66/builds/27170 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/43/builds/17837 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/67/builds/27112 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/43/builds/17837 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/28795 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/73816 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/1048 "Built successfully and passed tests") | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/65/builds/28735 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/43/builds/17837 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | |

### CODE REVIEW

**Comment by JonWBedard** [comment]
For some reason, EWS didn't think this had relevant webkitpy changes in it (it does), which is no doubt what caused this to erroneously be landed in the first place.

**Comment by JonWBedard** [comment]
> For some reason, EWS didn't think this had relevant webkitpy changes in it (it does), which is no doubt what caused this to erroneously be landed in the first place.

cc @aj062

**Comment by TingPing** [comment]
> For some reason, EWS didn't think this had relevant webkitpy changes in it (it does),

So what needs to be done to reland this?

**Comment by TingPing** [comment]
This was reopened in #3715 with fixes for the `test-webkitpy` failures.

**Pull request merged**
