### PR TITLE
[JSC] Fix Temporal regulateTime's constraints for milliseconds, microseconds, and nanoseconds

### PR DESCRIPTION
**Pull request by Constellation**
#### 9b4ed7838982af6ad2539c1a58012e9fe832be36
<pre>
[JSC] Fix Temporal regulateTime&apos;s constraints for milliseconds, microseconds, and nanoseconds
<a href="https://bugs.webkit.org/show_bug.cgi?id=241818">https://bugs.webkit.org/show_bug.cgi?id=241818</a>
rdar://95534859

Reviewed by Ross Kirsling.

This patch fixes constraints for milliseconds, microseconds, and nanoseconds in constrainTime.
It should be from 0 to 999, not to 1000[1].

[1]: <a href="https://tc39.es/proposal-temporal/#sec-temporal-constraintime">https://tc39.es/proposal-temporal/#sec-temporal-constraintime</a>

* JSTests/stress/temporal-plaintime-tostring-1000-millisecond.js: Added.
(shouldBe):
(throw.new.Error):
* Source/JavaScriptCore/runtime/TemporalPlainTime.cpp:
(JSC::constrainTime):

Canonical link: <a href="https://commits.webkit.org/251698@main">https://commits.webkit.org/251698@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@295693">https://svn.webkit.org/repository/webkit/trunk@295693</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Review by rkirsling — APPROVED** [review]
r=me

**Comment by Constellation** [comment]
@rkirsling thank you!

**Comment by Constellation** [comment]
Runtime change, and jsc-armv7-tests pass. This is enough for this patch.

**Comment by Constellation** [comment]
mac is already built, and merge-queue is getting stuck with many patches now. Using unsafe-merge-queue.

**Pull request merged**
