### PR TITLE
[git-webkit] Prompt user for bugzilla credentials during setup

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 1957c7470eb18d40f7b32969e9146d1af91b76ad
<pre>
[git-webkit] Prompt user for bugzilla credentials during setup
<a href="https://bugs.webkit.org/show_bug.cgi?id=236659">https://bugs.webkit.org/show_bug.cgi?id=236659</a>
&lt;rdar://problem/88980650 &gt;

Reviewed by NOBODY (OOPS!).

* Tools/Scripts/libraries/webkitcorepy/webkitcorepy/credentials.py:
(credentials): Store credentials under &quot;bugs.webkit.org&quot; instead of &quot;<a href="https://bugs.webkit.org&quot">https://bugs.webkit.org&quot</a>;
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py:
(Setup.git): Prompt user for bugzilla credentials.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/setup_unittest.py:
</pre>

### CODE REVIEW

**Comment by JonWBedard** [comment]
The "how" of this patch is pretty straight forward, but the consequences might be somewhat controversial.
- This will block setup on having a valid bugzilla account
- Moving from https://<hostname> to <hostname> in keychain aligns with what Safari does, but will break folks who have already run `git-webkit setup`

**Comment by aj062** [comment]
> * This will block setup on having a valid bugzilla account

You can consider making this optional, where user has option to skip this step. If skipped git-webkit wouldn't comment on the bug automatically, but rest everything will keep working.

**Comment by aproskuryakov** [comment]
> * This will block setup on having a valid bugzilla account

This does seem very controversial indeed. Mostly because it's something that we'd ask new contributors to do preemptively, before they had a chance to hack on the code and decide if they have something to submit.

Existing contributors would almost certainly already have the credentials in Mac keychain, so we don't need to be asked again.

**Comment by JonWBedard** [comment]
> > * This will block setup on having a valid bugzilla account
> 
> This does seem very controversial indeed. Mostly because it's something that we'd ask new contributors to do preemptively, before they had a chance to hack on the code and decide if they have something to submit.
> 
> Existing contributors would almost certainly already have the credentials in Mac keychain, so we don't need to be asked again.

`webkitcorepy.credentials` is decently smart, the reason I'm making the shift from `https://<hostname>` to `<hostname>` in this PR is because we are checking the existing keychain values, if we have valid bugzilla credentials, folks won't be prompted

**Comment by JonWBedard** [comment]
Updated PR lets folks cntrl-C out of providing bugzilla credentials.

**Pull request closed without merging**
