### PR TITLE
Factorize common platform code for font variant settings

### PR DESCRIPTION
**Pull request by mdubet**
#### 5535cabfe075b7a1ad80c2d61b414f394d1fd109
<pre>
Factorize common platform code for font variant settings
<a href="https://bugs.webkit.org/show_bug.cgi?id=246856">https://bugs.webkit.org/show_bug.cgi?id=246856</a>
rdar://101426315

Reviewed by Michael Catanzaro.

* Source/WebCore/platform/graphics/cocoa/FontCacheCoreText.cpp:
(WebCore::computeFeatureSettingsFromVariants): Deleted.
* Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:
(WebCore::setFeatureSettingsFromVariants): Deleted.
* Source/WebCore/platform/text/TextFlags.cpp:
(WebCore::setFeatureSettingsFromVariants):
* Source/WebCore/platform/text/TextFlags.h:

Canonical link: <a href="https://commits.webkit.org/255842@main">https://commits.webkit.org/255842@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/a82afd03daf9611992d264739f35d72337eda0e8

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/93740 "1 style error") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/2935 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/24346 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/103384 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/163706 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/97733 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/2951 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/31189 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/86078 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/99419 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/99400 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/2101 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/80180 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/29129 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/84027 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/83755 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/72082 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/37584 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/17587 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/35433 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/18847 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4035 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/39311 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/41399 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/41245 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/38078 "Passed tests") | |

### CODE REVIEW

**Review by mcatanzaro — CHANGES_REQUESTED** [review]
Nice improvement. Unfortunately I see EWS is unhappy:

```
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:63: error: cannot bind non-const lvalue reference of type ‘WTF::HashMap<std::array<char, 4>, int, WebCore::FourCharacterTagHash, WebCore::FourCharacterTagHashTraits>&’ to an rvalue of type ‘WebCore::FeaturesMap’ {aka ‘WTF::HashMap<std::array<char, 4>, int, WebCore::FourCharacterTagHash, WebCore::FourCharacterTagHashTraits>’}
  198 |     for (auto& newFeature = computeFeatureSettingsFromVariants(font.fontDescription().variantSettings()))
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:105: error: expected ‘;’ before ‘)’ token
  198 |     for (auto& newFeature = computeFeatureSettingsFromVariants(font.fontDescription().variantSettings()))
      |                                                                                                         ^
      |                                                                                                         ;
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:105: error: expected primary-expression before ‘)’ token
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:105: error: expected ‘;’ before ‘)’ token
  198 |     for (auto& newFeature = computeFeatureSettingsFromVariants(font.fontDescription().variantSettings()))
      |                                                                                                         ^
      |                                                                                                         ;
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:199:44: error: ‘class WTF::HashMap<std::array<char, 4>, int, WebCore::FourCharacterTagHash, WebCore::FourCharacterTagHashTraits>’ has no member named ‘tag’
  199 |         featuresToBeApplied.set(newFeature.tag, newFeature.value);
      |                                            ^~~
/app/webkit/Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:199:60: error: ‘class WTF::HashMap<std::array<char, 4>, int, WebCore::FourCharacterTagHash, WebCore::FourCharacterTagHashTraits>’ has no member named ‘value’; did you mean ‘values’?
```

I also notice that you have two commits here. The merge-queue will only allow you to land one commit per pull request, so you'll have to choose between sneaking the unrelated change into this commit, or splitting it out into a second pull request.

**Comment by mdubet** [comment]
Yes I can't build the GTK port locally so I'm using EWS as my sandbox.
I will mark this PR as draft until the port builds successfully.

**Comment by mdubet** [comment]
@mcatanzaro The PR is ready now

**Review by mcatanzaro — APPROVED** [review]
Need to fix the style error:

```
ERROR: Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:  Multi line control clauses should use braces.  [whitespace/braces] [4]
```

**Comment by mdubet** [comment]
> Need to fix the style error:
> 
> ```
> ERROR: Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:  Multi line control clauses should use braces.  [whitespace/braces] [4]
> ```

I think it's a false positive ?

**Comment by nt1m** [comment]
> > Need to fix the style error:
> > ```
> > ERROR: Source/WebCore/platform/graphics/harfbuzz/ComplexTextControllerHarfBuzz.cpp:198:  Multi line control clauses should use braces.  [whitespace/braces] [4]
> > ```
> 
> I think it's a false positive ?

Seems like it, I don't see multi-line clauses there.

**Comment by mcatanzaro** [comment]
Indeed... that's strange. I wonder why the style checker is confused about that.

**Comment by mdubet** [comment]
> Indeed... that's strange. I wonder why the style checker is confused about that.

I've actually tried with braces, and it then correctly warns about useless braces around single line statement 😅

**Pull request merged**
