### PR TITLE
[WPE][GTK] Warning: WebKit2: Couldn't find 'run_async_javascript_function_in_world_finish' for the corresponding async function: 'run_async_javascript_function_in_world'

### PR DESCRIPTION
**Pull request by mcatanzaro**
#### 910ab18a82d45d05c146999c32b0c517bf78b56a
<pre>
[WPE][GTK] Warning: WebKit2: Couldn&apos;t find &apos;run_async_javascript_function_in_world_finish&apos; for the corresponding async function: &apos;run_async_javascript_function_in_world&apos;
<a href="https://bugs.webkit.org/show_bug.cgi?id=269377">https://bugs.webkit.org/show_bug.cgi?id=269377</a>

Reviewed by Adrian Perez de Castro.

We need to use the new finish-func annotation so that language bindings
can figure out how to complete the async call, due to our nonstandard
naming for the finish function. It seems trying to reuse the same finish
function for multiple async calls was not such a good idea.

Unfortunately, with older gobject-introspection, we cannot use this
new annotation or the build will fail due to the unrecognized
annotation. So we will need to conditionalize the entire doc comment.

Finally, I&apos;ve also fixed the nullability of the world_name parameter,
which was broken due to a missing colon.

* Source/WebKit/PlatformGTK.cmake:
* Source/WebKit/PlatformWPE.cmake:
* Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:
* Source/WebKit/UIProcess/API/glib/WebKitWebView.h.in:

Canonical link: <a href="https://commits.webkit.org/276012@main">https://commits.webkit.org/276012@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/fd574d760eaa0e11d18666803e4c644fadd59935

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/41570 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/20584 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/43948 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/44139 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/37662 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/23693 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/17914 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/34371 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/42144 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/17511 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/35807 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/15031 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/15225 "Passed tests") | | [⏳ 🛠 wpe-skia ](https://ews-build.webkit.org/#/builders/WPE-Skia-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/37757 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/37136 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/45510 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/16385 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/13460 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/40893 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/18004 "Built successfully") | | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/39303 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/9681 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/18060 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/17648 "Built successfully") | | |

### CODE REVIEW

**Review by aperezdc — APPROVED** [review]
Nice catch 👌🏼

**Comment by mcatanzaro** [comment]
Oh look, we cannot do it because older gobject-introspection does not recognize it.

**Comment by aperezdc** [comment]
> Oh look, we cannot do it because older gobject-introspection does not recognize it.

Dang. Any ideas?

**Comment by mcatanzaro** [comment]
Two ideas:

 * Move the doc comment from the source file to the header template. Have two different copies of the doc comment, conditionalized on `GI_CHECK_VERSION()`. Hope that the gi-scanner version matches the introspection header version. This is probably the best solution.
 * Add a new function webkit_web_view_run_async_javascript_function_in_world_finish() that just calls webkit_web_view_run_javascript_in_world_finish(). Deprecate it immediately. Probably overkill.

**Comment by aperezdc** [comment]
> Two ideas:
> 
> * Move the doc comment from the source file to the header template. Have two different copies of the doc comment, conditionalized on `GI_CHECK_VERSION()`. Hope that the gi-scanner version matches the introspection header version. This is probably the best solution.

Let's try this. The version should match, but we could even check the actual version of the scanner using `g-ir-scanner --version` if we want to be sure, in case the version of the `.pc` module wouldn't match the one of the actual program which, while rare, might happen during cross-compilation... although cross-builds typically disable introspection 🙃 

We already have a way in `Source/cmake/FindGI.cmake` for extracting the version from `g-ir-scanner --version` so something like this could be used to have add a macro to be used for guarding usage of `(finish-func ...)`:

```diff
diff --git a/Source/cmake/FindGI.cmake b/Source/cmake/FindGI.cmake
index fdc56b21b148..dfdb33624fde 100644
--- a/Source/cmake/FindGI.cmake
+++ b/Source/cmake/FindGI.cmake
@@ -36,6 +36,9 @@ command. The following variables will also be set:
   Path to the ``g-ir-scanner`` program.
 ``GI_COMPILER_EXE``
   Path to the ``g-ir-compiler`` program.
+``GI_SCANNER_VERSION``
+  Version reported by ``g-ir-scanner --version``, typically the same as
+  ``GI_VERSION``.
 ``GI_GIRDIR``
   Path where to install ``.gir`` files in the target system.
 ``GI_TYPELIBDIR``
@@ -109,19 +112,21 @@ endif ()
 set(GI_GIRDIR "${_GI_GIRDIR}" CACHE PATH "Path to installed .gir files")
 set(GI_TYPELIBDIR "${_GI_TYPELIBDIR}" CACHE PATH "Path to installed .typelib files")
 
-if (NOT GI_VERSION AND GI_SCANNER_EXE)
-    execute_process(
-        COMMAND "${GI_SCANNER_EXE}" --version
-        OUTPUT_VARIABLE GI_VERSION
-        OUTPUT_STRIP_TRAILING_WHITESPACE
-        COMMAND_ERROR_IS_FATAL ANY
-        ERROR_QUIET
-    )
-    if (GI_VERSION MATCHES "^g-ir-scanner[[:space:]]+([0-9.]+)")
-        set(GI_VERSION ${CMAKE_MATCH_1})
-    else ()
-        unset(GI_VERSION)
-    endif ()
+execute_process(
+    COMMAND "${GI_SCANNER_EXE}" --version
+    OUTPUT_VARIABLE GI_SCANNER_VERSION
+    OUTPUT_STRIP_TRAILING_WHITESPACE
+    COMMAND_ERROR_IS_FATAL ANY
+    ERROR_QUIET
+)
+if (GI_SCANNER_VERSION MATCHES "^g-ir-scanner[[:space:]]+([0-9.]+)")
+    set(GI_SCANNER_VERSION ${CMAKE_MATCH_1})
+else ()
+    unset(GI_SCANNER_VERSION)
+endif ()
+
+if (NOT GI_VERSION AND GI_SCANNER_VERSION)
+    set(GI_VERSION ${GI_SCANNER_VERSION})
 endif ()
 
 if (GI_VERSION VERSION_GREATER_EQUAL 1.59.1)
@@ -129,6 +134,11 @@ if (GI_VERSION VERSION_GREATER_EQUAL 1.59.1)
 else ()
     set(GI_HAVE_SOURCES_TOP_DIRS FALSE)
 endif ()
+if (GI_SCANNER_VERSION VERSION_GREATER 1.78.1)
+    set(GI_SCANNER_HAVE_FINISH_FUNC 1)
+else ()
+    set(GI_SCANNER_HAVE_FINISH_FUNC 0)
+endif ()
 
 include(FindPackageHandleStandardArgs)
 find_package_handle_standard_args(GI
@@ -354,6 +364,7 @@ function(GI_INTROSPECT namespace nsversion header)
             "--pkg-export=${opt_PACKAGE}-${nsversion}"
             "$<$<BOOL:${target_def}>:-D$<JOIN:${target_def},;-D>>"
             "$<$<BOOL:${target_inc}>:-I$<JOIN:${target_inc},;-I>>"
+            "-DGI_SCANNER_HAVE_FINISH_FUNC=${GI_SCANNER_HAVE_FINISH_FUNC}"
             ${scanner_flags}
             ${opt_OPTIONS}
             ${gir_srcs}
```

WDYT?

**Comment by mcatanzaro** [comment]
I suppose that's even better.

At this point, do you want to prepare a pull request (since you've already done the hard part) or you want me to copy that into this one?

**Comment by aperezdc** [comment]
> I suppose that's even better.
> 
> At this point, do you want to prepare a pull request (since you've already done the hard part) or you want me to copy that into this one?

Please go ahead, pick the diff I shared and incorporate it in this patch 👍🏼

**Comment by mcatanzaro** [comment]
```
 "-DGI_SCANNER_HAVE_FINISH_FUNC=${GI_SCANNER_HAVE_FINISH_FUNC}"
```
 
I'm not sure about this. Will gi-scanner be smart enough to respect the preprocessor definitions when parsing the source file? I'm skeptical. I had been thinking we'd move the doc comment to the header template and preprocess it with unifdef; that's how we've handled other cases where the doc comment needs to be conditionalized thus far.

**Comment by mcatanzaro** [comment]
OK, big brain moment: let's have only one doc comment annotated for newer gobject-introspection, and use `GI_SCANNER_VERSION` to decide whether the warnings should be fatal.

**Comment by mcatanzaro** [comment]
I think I have something, but I want to test it downstream first to be confident that it actually works.

**Comment by mcatanzaro** [comment]
```
if (GI_SCANNER_VERSION MATCHES "^g-ir-scanner[[:space:]]+([0-9.]+)")
```

This doesn't work.

**Comment by mcatanzaro** [comment]
Please review again.

**Comment by mcatanzaro** [comment]
> Please review again.

Just kidding. This didn't work at all. I have yet another idea...

**Comment by mcatanzaro** [comment]
Sorry for the delay. This should be ready again now.

**Review by aperezdc — APPROVED** [review]
The repeated paragraph isn't great, but it seems this the reasonable approach with the current tooling we have 👌🏼

**Comment by philn** [comment]
This broke builds with GI disabled...

```
CMake Error at Source/WebKit/PlatformWPE.cmake:279 (if):                                                                                                                                                           
  if given arguments:                                                                                                                                                                                              
                                                                                                                                                                                                                   
    "VERSION_GREATER_EQUAL" "1.79.2"                                                                                                                                                                               
                                                                                                                                                                                                                   
  Unknown arguments specified                                                                                                                                                                                      
Call Stack (most recent call first):                                                                                                                                                                               
  Source/cmake/WebKitMacros.cmake:74 (include)                                                                                                                                                                     
  Source/WebKit/CMakeLists.txt:727 (WEBKIT_INCLUDE_CONFIG_FILES_IF_EXISTS)
```

**Comment by aperezdc** [comment]
> This broke builds with GI disabled...
> 
> ```
> CMake Error at Source/WebKit/PlatformWPE.cmake:279 (if):                                                                                                                                                           
>   if given arguments:                                                                                                                                                                                              
>                                                                                                                                                                                                                    
>     "VERSION_GREATER_EQUAL" "1.79.2"                                                                                                                                                                               
>                                                                                                                                                                                                                    
>   Unknown arguments specified                                                                                                                                                                                      
> Call Stack (most recent call first):                                                                                                                                                                               
>   Source/cmake/WebKitMacros.cmake:74 (include)                                                                                                                                                                     
>   Source/WebKit/CMakeLists.txt:727 (WEBKIT_INCLUDE_CONFIG_FILES_IF_EXISTS)
> ```

I'll fix it momentarily, thanks for the heads up.

**Comment by aperezdc** [comment]
Follow-up to fix the issue with GObject-Introspection disabled: https://github.com/WebKit/WebKit/pull/25811

**Pull request merged**
