### PR TITLE
Incorrect tab stop if tab-size is a <length> and the distance to the next tab stop is less than 0.5ch

### PR DESCRIPTION
**Pull request by fujii**
#### d88306bc080b632ff421d82f64806ca1220fe9ab
<pre>
Incorrect tab stop if tab-size is a &lt;length&gt; and the distance to the next tab stop is less than 0.5ch
<a href="https://bugs.webkit.org/show_bug.cgi?id=258961">https://bugs.webkit.org/show_bug.cgi?id=258961</a>

Reviewed by Myles C. Maxfield.

FontCascade::tabWidth returns the width between the current
position and the next tab stop. If it is less than 0.5ch, it
should return the width between the current position and the next
next tab stop.
&lt;<a href="https://drafts.csswg.org/css-text-3/#white-space-phase-2">https://drafts.csswg.org/css-text-3/#white-space-phase-2</a>&gt;

The width of the next next tab stop is the sum of the width of
the next tab stop and the tab size. However, it just returned the
tab size in the case.

This change makes the following wpt tests pass.
  imported/w3c/web-platform-tests/css/css-text/tab-size/tab-min-rendered-width-1.html
  imported/w3c/web-platform-tests/css/css-text/white-space/tab-stop-threshold-004.html
  imported/w3c/web-platform-tests/css/css-text/white-space/tab-stop-threshold-002.html
  imported/w3c/web-platform-tests/css/css-text/white-space/tab-stop-threshold-006.html

* LayoutTests/TestExpectations:
* Source/WebCore/platform/graphics/FontCascade.h:
(WebCore::FontCascade::tabWidth const):

Canonical link: <a href="https://commits.webkit.org/265922@main">https://commits.webkit.org/265922@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/862855b8383e4b25bed18c0897d8e68a0c322ce1

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/12175 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/12520 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/12822 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/13920 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/11748 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/12205 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/14936 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/12535 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/14428 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/12339 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/13143 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/10310 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/14336 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/10428 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/11051 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/18164 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/11509 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/11211 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/14389 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/11703 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/9651 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/10920 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/3018 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/15246 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/11557 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@fujii - I think it will fix failing '[tab-min-rendered-width-1.html](https://wpt.fyi/results/css/css-text/tab-size/tab-min-rendered-width-1.html?label=master&label=experimental&aligned&q=css-text%2Ftab-size)' as well.

**Comment by fujii** [comment]
Wow, very good to know. I though it's a WebKit's spec. The test is exactly what I want. Thank you very much. Will revise.
https://drafts.csswg.org/css-text-3/#white-space-phase-2

**Comment by Ahmad-S792** [comment]
> Wow, very good to know. I though it's a WebKit's spec. The test is exactly what I want. Thank you very much. Will revise. https://drafts.csswg.org/css-text-3/#white-space-phase-2

It will progress all failing these tests as well. [css-text/white-space/tab-stop-threshold-](https://wpt.fyi/results/css/css-text/white-space?label=experimental&label=master&aligned&q=css-text%2Fwhite-space%2Ftab-stop-threshold-)

**Review by litherum — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
