### PR TITLE
[GLib] Import the libsysprof-capture source tree

### PR DESCRIPTION
**Pull request by aperezdc**
#### ccba8b99a8ed0395e05c3926211a713f56abd9a0
<pre>
[GLib] Import the libsysprof-capture source tree
<a href="https://bugs.webkit.org/show_bug.cgi?id=275203">https://bugs.webkit.org/show_bug.cgi?id=275203</a>

Reviewed by Carlos Garcia Campos.

Import the source for the libsysprof-capture library, which will be used
to add runtime tracing support for the GTK and WPE ports. This is a
small, plain C library with a license compatible with the rest of the
WebKit code base (BSD-2-Clause), and it is designed to be statically
linked in other projects.

By providing a copy in the WebKit tree, it will be possible to have
tracing support always built by default, even on those systems which do
not provide a packaged version of the library.

* Source/CMakeLists.txt: Include libsysprof-capture subdir when needed.
* Source/ThirdParty/libsysprof-capture: Added.
* Source/WTF/wtf/PlatformGTK.cmake: Link libsysprof-capture into WTF.
* Source/WTF/wtf/PlatformWPE.cmake: Ditto.
* Source/cmake/OptionsGTK.cmake: Set USE_SYSPROF_CAPTURE option as
enabled for the port.
* Source/cmake/OptionsWPE.cmake: Ditto.
* Source/cmake/WebKitFeatures.cmake: Add USE_SYSPROF_CAPTURE build option,
disabled by default.
* Tools/gtk/manifest.txt.in: Add libsysprof-capture directory to be
included in release tarballs.
* Tools/wpe/manifest.txt.in: Ditto.
* Tools/Scripts/webkitpy/style/checker.py: Ignore most of the rules for
ThirdParty/libsysprof-capture.

Canonical link: <a href="https://commits.webkit.org/279881@main">https://commits.webkit.org/279881@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/dde8fe55c1c32b690054cf8bbde29d3c808a99d0

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/54783 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/34215 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/7361 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/58061 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/5514 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/57083 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/41760 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/5528 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/44370 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/3732 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/56878 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/32344 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/47461 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/25494 "Passed tests") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/54609 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/29135 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/4798 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/3655 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/48150 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/50952 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/5015 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/59651 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/54288 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/30030 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/5162 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/51793 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/31171 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/47543 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/51198 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/32180 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/66584 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/8113 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/30959 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12690 "Passed tests") |

### CODE REVIEW

**Review by mcatanzaro — COMMENTED** [review]
I don't understand. This is a system library with a pkg-config file and a stable API:

```
$ pkg-config --cflags --libs sysprof-capture-4 
-I/usr/include/sysprof-6 -pthread -lsysprof-capture-4 -pthread
```

Occasional ABI breaks are handled with soname bumps. It seems like a reliable rather than a problematic dependency, so why does it need to be bundled in Source/ThirdParty?

**Comment by mcatanzaro** [comment]
OK, I see in the bug report:

> While some Linux distributions have packages for the library, some
other distributions and cross-compilation environments like Yocto or
Buildroot may not have packages -- and we *really* want to be able to
tell people to run a command to produce a trace output even for release
builds, so in order to have that possibility, we need to make sure that
WebKit can be built with libsysprof-capture enabled by default in all
cases.

But it looks simple and should be pretty easy to package, surely easier than it was to integrate it into the WebKit source tree with a custom CMake build system like you've done here? I would just package it for buildroot and yocto and wherever else you need it. It will be much better in the long run.

**Comment by aperezdc** [comment]
Updated, added the missing dummy `config.h` file and as a bonus I've added a check for `reallocarray()` and `strlcpy()`, which the library can use if present.

**Comment by aperezdc** [comment]
> Honestly it doesn't seem like a very strong argument. Packaging sysprof is straightforward. I would just add a hard dependency if you really want it to be impossible to disable the tracing support.

Correction: *technically* straightforward, but often decisions are not taken purely on technical grounds.

> The fact that Debian doesn't allow new packages is stable releases is a self-imposed problem. Other distros don't have this rule, and you probably don't really need to collect traces from Debian stable users anyway.

Debian is an example from the traditional Linux distribution. Ubuntu LTS has the package in 24.04 but we do need to support as well the previous LTS for a while longer&mdash;no package there either.

But you are also forgetting that builds for embedded devices may be stuck in somewhat old and more or less fixed build environments that may not accept adding a new package, but would be fine having a WebKit update&mdash;and we would like WebKit updates in such scenarios to have runtime tracing support.

FWIW, I didn't expect so much discussion and pushback for a 7K LoC library *designed* for being embedded in other code bases...

**Review by GeorgesStavracas — COMMENTED** [review]
I don't have strong opinions on library vs source importing. This branch definitely builds and works for the Sysprof patches I've been working on, so to me this is fine.

**Comment by mcatanzaro** [comment]
Also need to edit Tools/gtk/manifest.txt.in and Tools/wpe/manifest.txt.in to allowlist the new ThirdParty/ directory.

**Comment by aperezdc** [comment]
> Also need to edit Tools/gtk/manifest.txt.in and Tools/wpe/manifest.txt.in to allowlist the new ThirdParty/ directory.

Good point! Added and patch re-uploaded after a rebase. It should be all ready now 🙏🏼

**Review by carlosgcampos — APPROVED** [review]

**Pull request merged**
