### PR TITLE
Omit the integer value for grid-lines when it's the default value.

### PR DESCRIPTION
**Pull request by mattwoodrow**
#### fc4a525dc1504f16c392e5f6a3936f56f085e410
<pre>
Omit the integer value for grid-lines when it&apos;s the default value.
<a href="https://bugs.webkit.org/show_bug.cgi?id=245025">https://bugs.webkit.org/show_bug.cgi?id=245025</a>

Reviewed by Tim Nguyen.

As per the shortest possible serialization principle, we don&apos;t need to print the &apos;1&apos; default value.

* LayoutTests/fast/css-grid-layout/grid-item-area-get-set-expected.txt:
* LayoutTests/fast/css-grid-layout/grid-item-area-get-set.html:
* LayoutTests/fast/css-grid-layout/grid-item-column-row-get-set-expected.txt:
* LayoutTests/fast/css-grid-layout/grid-item-column-row-get-set.html:
* LayoutTests/fast/css-grid-layout/grid-item-end-after-get-set-expected.txt:
* LayoutTests/fast/css-grid-layout/grid-item-end-after-get-set.html:
* LayoutTests/fast/css-grid-layout/grid-item-start-before-get-set-expected.txt:
* LayoutTests/fast/css-grid-layout/grid-item-start-before-get-set.html:
* LayoutTests/imported/w3c/web-platform-tests/css/css-grid/grid-layout-properties.html:
* LayoutTests/imported/w3c/web-platform-tests/css/css-grid/parsing/grid-area-computed-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-grid/parsing/grid-area-computed.html:
* Source/WebCore/css/ComputedStyleExtractor.cpp:
(WebCore::valueForGridPosition):

Canonical link: <a href="https://commits.webkit.org/254821@main">https://commits.webkit.org/254821@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/3a78f1a4e91511c8012f1ee0a5ad53e253e267fd

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/90208 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/34753 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/20814 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/99519 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/157014 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/94217 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/33244 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/28574 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/82534 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/95989 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95863 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/26443 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/77041 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/26330 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/81277 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/81062 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/69329 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/34373 "Built successfully") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/15135 "Found 1 new test failure: css3/scroll-snap/scroll-snap-drag-scrollbar-thumb-with-relayouts.html (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/32214 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/16084 "Found 1 new test failure: css3/scroll-snap/scroll-snap-drag-scrollbar-thumb-with-relayouts.html (failure)") | | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/74/builds/3374 "The change is no longer eligible for processing.") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/35958 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/39039 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/1456 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/37861 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/35168 "Passed tests") | |

### CODE REVIEW

**Comment by mattwoodrow** [comment]
This was discussed and resolved here: https://github.com/w3c/csswg-drafts/issues/3448

**Comment by nt1m** [comment]
Hi Oriol, can you please check if the serialization here is correct whenever you have time?

**Comment by Loirooriol** [comment]
Serializing `1 foobar` as `foobar` seems wrong, they are not equivalent:

```html
<div style="display: inline-grid; border: solid; grid-template-rows: [foobar] 100px [foobar-start] 100px; grid-template-columns: 100px 100px">
  <div style="background: cyan; grid-row-start: 1 foobar; grid-column-start: 1"></div>
  <div style="background: orange; grid-row-start: foobar; grid-column-start: 2"></div>
</div>
```

**Review by nt1m — APPROVED** [review]

**Comment by nt1m** [comment]
Looks good to me, though it would be nice if @Loirooriol could also take a look.

**Review by Loirooriol — APPROVED** [review]

**Pull request closed without merging**
