### PR TITLE
Replace duplicated code in LLIntSlowPaths with already defined macros

### PR DESCRIPTION
**Pull request by mikhailramalho**
#### 4fc946a72c06f3c63d781b31c1f908f286ebb598
<pre>
Replace duplicated code in LLIntSlowPaths with already defined macros
<a href="https://bugs.webkit.org/show_bug.cgi?id=274984">https://bugs.webkit.org/show_bug.cgi?id=274984</a>

Reviewed by Keith Miller.

This patch removes some duplicated code in favor of using the
LLINT_BEGIN_NO_SET_PC() and LLINT_BEGIN() macros.

* Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:
(JSC::LLInt::LLINT_SLOW_PATH_DECL):
(JSC::LLInt::llint_slow_path_checkpoint_osr_exit_from_inlined_call):
(JSC::LLInt::llint_slow_path_checkpoint_osr_exit):

Canonical link: <a href="https://commits.webkit.org/279740@main">https://commits.webkit.org/279740@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/04a9cacec7f45f77c12c3356e009e3b1619cef1a

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/54373 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/33778 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/6931 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/57652 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/5104 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/41309 "Built successfully") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/5052 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/44033 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/3414 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/56466 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/47/builds/31943 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/47085 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/25169 "Passed tests") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/28751 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/4410 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/3247 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/47734 "Built successfully and passed tests") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/50515 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/4618 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/59243 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/53880 "Built successfully and passed tests") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/29592 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/5052 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/51458 "Passed tests") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/30751 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/47178 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/50821 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/11848 "Built successfully and passed tests") | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/31725 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/66179 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/30541 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12608 "Passed tests") |

### CODE REVIEW

**Review by kmiller68 — CHANGES_REQUESTED** [review]
We don't need to and shouldn't ref VM in JSC slow paths. That's almost certainly a perf regression for no gain. If the VM is destroyed inside a JSC slow path we've REALLY screwed up somewhere...

**Review by Constellation — CHANGES_REQUESTED** [review]
This is 0% ok.
1. Super costly. Caused massive performance issue
2. There is no reasonable meaning to keep VM ref/deref.

**Comment by mikhailramalho** [comment]
> We don't need to and shouldn't ref VM in JSC slow paths. That's almost certainly a perf regression for no gain. If the VM is destroyed inside a JSC slow path we've REALLY screwed up somewhere...

I see, after I spoke with Ryosuke I was under the impression that this could happen in JSC, but indeed this regresses performance:
```
a mean = 65.12966
b mean = 65.05873
pValue = 0.0041817762
(Bigger means are better.)
1.001 times worse
Results ARE significant
```

And what about the rest of JSC? Are we interested in adopting smart pointers in places like ftl and dfg (except for VM objects)? 

I'll repurpose this PR to include only the changes not related to the smart pointers

**Comment by Constellation** [comment]
Do not do these things onto VM. This does not help anything.

**Comment by mikhailramalho** [comment]
Hey Yusuke, I'm specifically asking about adopting smart pointers in jsc that are not VM objects.

Is it something that you folks are interested?

**Review by kmiller68 — APPROVED** [review]
r=me

**Pull request merged**
