### PR TITLE
Resync fetch WPT

### PR DESCRIPTION
**Pull request by rreno**
#### e9041b9ec42e1b7336f93101d7ab4df67fbea996
<pre>
Resync fetch WPT
<a href="https://bugs.webkit.org/show_bug.cgi?id=245919">https://bugs.webkit.org/show_bug.cgi?id=245919</a>
rdar://100643816

Reviewed by Brent Fulgham.

Update fetch WPT as of upstream revision 0fea3b0180a7beb02871c87bd971fb1950b04476

* LayoutTests/imported/w3c/web-platform-tests/fetch/*:
    Added and modified a huge number of tests from upstream.

* LayoutTests/TestExpectations:
* LayoutTests/platform/glib/TestExpectations:
* LayoutTests/platform/ios/TestExpectations:
* LayoutTests/platform/mac-wk1/TestExpectations:
* LayoutTests/platform/ios-wk2/TestExpectations:
* LayoutTests/platform/mac/TestExpectations:

* Tools/WebKitTestRunner/InjectedBundle/InjectedBundlePage.cpp:
(WTR::InjectedBundlePage::willSendRequestForFrame):

Canonical link: <a href="https://commits.webkit.org/256738@main">https://commits.webkit.org/256738@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/c0e1bc1bdd8fbd7439dfc52abfa3a8b956f247fe

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/96697 "120 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/5961 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/29788 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/106222 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/166535 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/6172 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/34693 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/89077 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/102932 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/102374 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/4615 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/83307 "Built successfully") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/31577 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/86455 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/88323 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/74503 "Found 1 new API test failure: /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/text/state-changed (failure)") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/40419 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/19807 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/21227 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4679 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/4473 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/43755 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/1168 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/40507 "Passed tests") | |

### CODE REVIEW

**Comment by rreno** [comment]
This was done with the following:

```
import-w3c-tests -t web-platform-tests/fetch
```

followed by a
```
run-webkit-tests --release --no-build --reset-results imported/w3c/web-platform-tests/fetch
```
w/ ToT WebKit.

**Comment by rreno** [comment]
GTK 115 new test failures. Tomorrow is going to be fun 🥳

**Comment by rreno** [comment]
I downloaded the results and am looking at them on my local machine. Many of the differences between (for example) mac-wk2 and mac-AS-debug-wk2 are due to generated keys showing up in the `Blocked access to external URL` messages. These messages are unfortunately not JS console messages so I can't just dump JS console log to stderr to get that stuff out of the test output.

There's a regex in WKTR to transform stuff like that to `GENERATED_KEY` so I'll have to try to get that to work.

**Comment by rreno** [comment]
Doing a fresh run on EWS rebased against main. From my local results, I expect mac-wk2 to be green. Hopefully there's not much else different between the ports and platforms.

**Comment by JonWBedard** [comment]
What's the sense in having all the layout tests listed in a commit message like this? Feels like I'd rather just have it be `LayoutTests/platform/glib/imported/w3c/web-platform-tests/fetch*`....

**Comment by rreno** [comment]
This is the output of the git-webkit tool. It's at the very least searchable.

**Comment by rreno** [comment]
🤞 this is hopefully the last time I need to make changes to the branch. WK1 needed some more service/shared worker tests skipped, mac-wk2 (release and debug) had an expectation changed, and I made a mistake when creating a platform expectation for ios-wk2.

Come on EWS let's see all green! (except for style because of the non-pep8 indent in Python files)

**Review by brentfulgham — APPROVED** [review]
LGTM.

**Comment by rreno** [comment]
There's a ton of shared/service worker tests in fetch/api so I just skipped that whole subdir for WK1. We kept hitting the limit of failures causing EWS to bail out early.

**Comment by rreno** [comment]
So many shared/service worker tests needed to be skipped for wk1. Here's what I did using `fd` and `rg` (can do the same with `find` and `grep`)

```
$ fd worker LayoutTests/imported/w3c/web-platform-tests/fetch | rg "\.html" | cut -d'/' -f2- > wk1-workers
```
Then copy the output into `LayoutTests/platform/mac-wk1/TestExpectations` and add `[ Skip ]` to the end of each line.

**Comment by rreno** [comment]
WK2 was all green. WK1 had >30 failures again. Skipping all of fetch for WK1 until I can figure out which features of fetch we should support and test in WK1.
https://bugs.webkit.org/show_bug.cgi?id=247981

**Pull request merged**
