### PR TITLE
Link GitHub accounts on /team/

### PR DESCRIPTION
**Pull request by annevk**
#### 8fc30703af6e1ee075e268db8148bc611749e7aa
<pre>
Link GitHub accounts on /team/
<a href="https://bugs.webkit.org/show_bug.cgi?id=246455">https://bugs.webkit.org/show_bug.cgi?id=246455</a>

Reviewed by Jonathan Bedard.

* Websites/webkit.org/wp-content/themes/webkit/team.php:

Canonical link: <a href="https://commits.webkit.org/255550@main">https://commits.webkit.org/255550@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/7c06e45e60c0209204fb8d86c3697d81ea1b0c5b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/92819 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/2033 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/23404 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/102547 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/2033 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/30373 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/85218 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/98707 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/98482 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/1383 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/79308 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/28298 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/83296 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/83014 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [⏳ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/API-Tests-GTK-EWS "Waiting to run tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/36777 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/16923 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/34577 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/18113 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/38447 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/40717 "Passed tests") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/1769 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/40362 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/37285 "Passed tests") | |

### CODE REVIEW

**Comment by annevk** [comment]
I didn't have a way to test this so hopefully someone can verify this locally.

**Review by JonWBedard — APPROVED** [review]

**Comment by JonWBedard** [comment]
> I didn't have a way to test this so hopefully someone can verify this locally.

There is a staging instance, I believe, which @lingcherd and @jdatapple are familiar with...I've used it before, but don't remember the details.

**Comment by lingcherd** [comment]
I've uploaded your patch to the UAT server https://www.webkit-uat.org.

**Comment by JonWBedard** [comment]
> I've uploaded your patch to the UAT server https://www.webkit-uat.org.

@annevk r+ still stands, but maybe could we put the nicks on a new line? Line wrap is a bit weird.

**Comment by annevk** [comment]
I cannot see that website unfortunately, but I believe I have addressed your optional feedback. Note I'm not a committer so someone else will have to do that I think.

(Also, apologies for making a mess. I didn't realize you had to squash locally.)

**Comment by JonWBedard** [comment]
> I cannot see that website unfortunately, but I believe I have addressed your optional feedback. Note I'm not a committer so someone else will have to do that I think.
> 
> (Also, apologies for making a mess. I didn't realize you had to squash locally.)

Looks good! Sending to `merge-queue` now! :)

**Pull request merged**
