### PR TITLE
[LBSE] Rename RenderSVGResource -> LegacyRenderSVGResource

### PR DESCRIPTION
**Pull request by nikolaszimmermann**
#### 82d4fe5d16c8fa17f5960a7f1c8f29fd2f462bc5
<pre>
[LBSE] Rename RenderSVGResource -&gt; LegacyRenderSVGResource
<a href="https://bugs.webkit.org/show_bug.cgi?id=263595">https://bugs.webkit.org/show_bug.cgi?id=263595</a>

Reviewed by Rob Buis.

Begin reworking SVG resource system for LBSE. The goal is to handle invalidations
of resources, without (ab-)using the layout() system of the render tree for this.

Begin by renaming RenderSVGResource to LegacyRenderSVGResource.

Covered by existing tests.

* Source/WebCore/Sources.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/rendering/RenderLayer.cpp:
(WebCore::RenderLayer::setupClipPath):
* Source/WebCore/rendering/svg/RenderSVGBlock.cpp:
* Source/WebCore/rendering/svg/RenderSVGForeignObject.cpp:
* Source/WebCore/rendering/svg/RenderSVGImage.cpp:
(WebCore::RenderSVGImage::imageChanged):
* Source/WebCore/rendering/svg/RenderSVGInline.cpp:
* Source/WebCore/rendering/svg/RenderSVGModelObject.cpp:
* Source/WebCore/rendering/svg/RenderSVGResourceClipper.h:
* Source/WebCore/rendering/svg/RenderSVGResourceContainer.h:
* Source/WebCore/rendering/svg/RenderSVGResourceFilter.h:
(isType):
* Source/WebCore/rendering/svg/RenderSVGResourceLinearGradient.h:
* Source/WebCore/rendering/svg/RenderSVGResourceMarker.h:
* Source/WebCore/rendering/svg/RenderSVGResourceMasker.h:
* Source/WebCore/rendering/svg/RenderSVGResourcePattern.h:
* Source/WebCore/rendering/svg/RenderSVGResourceRadialGradient.h:
* Source/WebCore/rendering/svg/RenderSVGResourceSolidColor.h:
* Source/WebCore/rendering/svg/RenderSVGRoot.cpp:
* Source/WebCore/rendering/svg/RenderSVGShape.cpp:
(WebCore::RenderSVGShape::fillContains):
(WebCore::RenderSVGShape::strokeContains):
(WebCore::RenderSVGShape::fillShape):
(WebCore::RenderSVGShape::strokeShapeInternal):
* Source/WebCore/rendering/svg/RenderSVGShape.h:
* Source/WebCore/rendering/svg/RenderSVGText.cpp:
* Source/WebCore/rendering/svg/SVGInlineTextBox.cpp:
(WebCore::SVGInlineTextBox::acquirePaintingResource):
* Source/WebCore/rendering/svg/SVGInlineTextBox.h:
* Source/WebCore/rendering/svg/SVGRenderTreeAsText.cpp:
(WebCore::writeSVGPaintingResource):
(WebCore::writeSVGFillPaintingResource):
(WebCore::writeSVGStrokePaintingResource):
(WebCore::writeSVGPaintingFeatures):
* Source/WebCore/rendering/svg/SVGResourcesCache.cpp:
(WebCore::hasPaintResourceRequiringRemovalOnClientLayoutChange):
(WebCore::SVGResourcesCache::clientStyleChanged):
(WebCore::SVGResourcesCache::clientWasAddedToTree):
(WebCore::SVGResourcesCache::clientWillBeRemovedFromTree):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGForeignObject.cpp:
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGImage.cpp:
(WebCore::LegacyRenderSVGImage::imageChanged):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGModelObject.cpp:
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResource.cpp: Renamed from Source/WebCore/rendering/svg/RenderSVGResource.cpp.
(WebCore::inheritColorFromParentStyleIfNeeded):
(WebCore::requestPaintingResource):
(WebCore::LegacyRenderSVGResource::removeAllClientsFromCache):
(WebCore::LegacyRenderSVGResource::fillPaintingResource):
(WebCore::LegacyRenderSVGResource::strokePaintingResource):
(WebCore::LegacyRenderSVGResource::sharedSolidPaintingResource):
(WebCore::removeFromCacheAndInvalidateDependencies):
(WebCore::LegacyRenderSVGResource::markForLayoutAndParentResourceInvalidation):
(WebCore::LegacyRenderSVGResource::markForLayoutAndParentResourceInvalidationIfNeeded):
(WebCore::LegacyRenderSVGResource::fillAndStrokePathOrShape const):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResource.h: Renamed from Source/WebCore/rendering/svg/RenderSVGResource.h.
(WebCore::LegacyRenderSVGResource::postApplyResource):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceClipper.h:
(isType):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceContainer.cpp:
(WebCore::LegacyRenderSVGResourceContainer::markAllClientsForInvalidationIfNeeded):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGResourceContainer.h:
(WebCore::getRenderSVGResourceById):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGRoot.cpp:
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGShape.cpp:
(WebCore::LegacyRenderSVGShape::fillContains):
(WebCore::LegacyRenderSVGShape::strokeContains):
(WebCore::LegacyRenderSVGShape::fillShape):
(WebCore::LegacyRenderSVGShape::strokeShapeInternal):
* Source/WebCore/rendering/svg/legacy/LegacyRenderSVGShape.h:
* Source/WebCore/rendering/updating/RenderTreeUpdater.cpp:
(WebCore::RenderTreeUpdater::updateSVGRenderer):
* Source/WebCore/svg/SVGAnimateMotionElement.cpp:
* Source/WebCore/svg/SVGCircleElement.cpp:
* Source/WebCore/svg/SVGEllipseElement.cpp:
* Source/WebCore/svg/SVGFEImageElement.cpp:
(WebCore::SVGFEImageElement::notifyFinished):
* Source/WebCore/svg/SVGFELightElement.cpp:
* Source/WebCore/svg/SVGFEMergeNodeElement.cpp:
* Source/WebCore/svg/SVGForeignObjectElement.cpp:
* Source/WebCore/svg/SVGGElement.cpp:
* Source/WebCore/svg/SVGGeometryElement.cpp:
* Source/WebCore/svg/SVGGraphicsElement.cpp:
* Source/WebCore/svg/SVGImageElement.cpp:
* Source/WebCore/svg/SVGLineElement.cpp:
* Source/WebCore/svg/SVGPathElement.cpp:
* Source/WebCore/svg/SVGPolyElement.cpp:
* Source/WebCore/svg/SVGRectElement.cpp:
* Source/WebCore/svg/SVGSVGElement.cpp:
(WebCore::SVGSVGElement::scrollToFragment):
(WebCore::SVGSVGElement::resetScrollAnchor):
* Source/WebCore/svg/SVGStopElement.cpp:
* Source/WebCore/svg/SVGTRefElement.cpp:
* Source/WebCore/svg/SVGTextContentElement.cpp:
* Source/WebCore/svg/SVGTextElement.cpp:
* Source/WebCore/svg/SVGTextPathElement.cpp:
* Source/WebCore/svg/SVGTextPositioningElement.cpp:
* Source/WebCore/svg/SVGUseElement.cpp:
* Source/WebCore/svg/SVGViewElement.cpp:

Canonical link: <a href="https://commits.webkit.org/269784@main">https://commits.webkit.org/269784@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/380f1b450af3afe16b8ee0188226ce20593b8ce3

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/23573 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/1689 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/24694 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/25732 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/21763 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/23840 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/3252 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/24113 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/22346 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/23816 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/1236 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/20396 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/26328 "Built successfully") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/1033 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/21295 "Passed tests") | [⏳ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/GTK-WK2-Tests-EWS "Waiting to run tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/21493 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/21560 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/25337 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/1010 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/17/builds/18722 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/981 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/5626 "Built successfully and passed tests") | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/1422 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/1291 "Built successfully") | | |

### CODE REVIEW

**Review by rwlbuis — APPROVED** [review]
LGTM.

**Comment by nikolaszimmermann** [comment]
Thanks @rwlbuis - not ready yet, going to need a bit more time to update it.

**Comment by rwlbuis** [comment]
> Thanks @rwlbuis - not ready yet, going to need a bit more time to update it.

Accepted because I agree it is the right thing to do.

**Comment by nikolaszimmermann** [comment]
Oops, this already contained parts of the follow-up patch, updating...

**Comment by nikolaszimmermann** [comment]
@shallawa - I'll land this one separated, and @rwlbuis will take care of renaming the other renderers, in one-go, as per your request.

**Review by rwlbuis — APPROVED** [review]
LGTM.

**Pull request merged**
