### PR TITLE
[WPE][GTK] Rename `python-gi` apt dependency to `python3-gi`

### PR DESCRIPTION
**Pull request by obyknovenius**
#### 133de55cdecb497068ee01a6f7f3a8d4258eab26
<pre>
[WPE][GTK] Rename `python-gi` apt dependency to `python3-gi`
<a href="https://bugs.webkit.org/show_bug.cgi?id=258727">https://bugs.webkit.org/show_bug.cgi?id=258727</a>

Reviewed by Carlos Alberto Lopez Perez.

`python-gi` doesn&apos;t exist on modern Ubuntu and Debian.

* Tools/glib/dependencies/apt:

Canonical link: <a href="https://commits.webkit.org/265683@main">https://commits.webkit.org/265683@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/71388e4da5583ed830801d41bf699f626da44533

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/11550 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/11754 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/12166 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/13195 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/11010 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/11571 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/14140 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/11734 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/13884 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/11714 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/12577 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/9837 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/13617 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/9869 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/10532 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/17630 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/10941 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/10686 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/13823 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/11035 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/9097 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/10212 "Built successfully") | | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/2776 "") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/14489 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/1301 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/10892 "Built successfully") | | |

### CODE REVIEW

**Review by dpino — APPROVED** [review]
I think the patch is fine as it is, since the oldest distributions we need to support are Ubuntu 20.04 (unofficially) and Debian 11. Both systems feature `python3-gi`.

Alternatively, you could have use `$(aptIfElse python3-gi python-gi)`, but as I said the patch is fine since we don't need to support systems where `python3-gi` is not present.

LGTM.

**Comment by dpino** [comment]
I'm not a reviewer so you need a review from a reviewer in order to land the patch.

**Review by clopez — APPROVED** [review]

**Review by dpino — COMMENTED** [review]
Removed review 'approve' so patch can land.

**Comment by dpino** [comment]
@obyknovenius I'm afraid you'll need to edit the commit message and directly write `Reviewed by Carlos Alberto Lopez Perez.`, then push the patch again and add label `merge-queue`.

Sorry for the mess.

**Comment by clopez** [comment]
This gave a weird error, looks like it tried to push to the fork instead of to main
```
git push -f obyknovenius HEAD:dependencies/apt/python3-dev
 in dir /Volumes/Data/worker/Merge-Queue/build (timeout 300 secs)
 watching logfiles {}
 argv: [b'git', b'push', b'-f', b'obyknovenius', b'HEAD:dependencies/apt/python3-dev']
 using PTY: False
Pushing to obyknovenius, which is classified as a public remote
Verifying commits in 'no-radar' mode
Attempting to push 1 batch of commits to obyknovenius...
Verified 2 novel commits to obyknovenius are safe to push
Checkout too out-of-date to check bug status of novel commits
```

le'ts try again

**Pull request merged**
