### PR TITLE
[Wasm-GC] Make GC tests more maintainable

### PR DESCRIPTION
**Pull request by takikawa**
#### 52534d6449a475bcddf06f60d9a409d03d7f7e8d
<pre>
[Wasm-GC] Make GC tests more maintainable
<a href="https://bugs.webkit.org/show_bug.cgi?id=243078">https://bugs.webkit.org/show_bug.cgi?id=243078</a>

Reviewed by Yusuke Suzuki.

Change Wasm GC tests to use text format modules that are encoded to
binary format using a compiled-to-JS version of the Wasm reference
interpreter.

The interpreter is built from the following GC spec repo commit:

  8bc37d910feb5351d2d218d36af67f79281a447d

It will be updated in the future as the GC spec evolves.

The RTT tests are not updated in this patch as they will be removed when
RTT support is removed (to match the current spec).

* JSTests/wasm/gc/i31.js:
(testI31Type):
(testI31New):
(testI31Get):
(module): Deleted.
* JSTests/wasm/gc/structs.js:
(testStructDeclaration):
* JSTests/wasm/gc/wast-wrapper.js: Added.
(export.compile):
(export.instantiate):
* JSTests/wasm/gc/wast.js: Added.
(b):
(ady):
(ga):
(f1):
(cm):
(bY):
(bs):
(h):
(aek):
(dx):
(cJ):
(wP):
(jl):
(bC):
(bC.prototype.toString):
(bC.prototype.toUtf16):
(bC.prototype.slice):
(ww):
(a):
(jj):
(ax):
(cH):
(wv):
(wK):
(f_):
(y):
(y.prototype.copy):
(y.prototype.ucompare):
(y.prototype.compare):
(y.prototype.neg):
(y.prototype.add):
(y.prototype.sub):
(y.prototype.mul):
(y.prototype.isZero):
(y.prototype.isNeg):
(y.prototype.and):
(y.prototype.or):
(y.prototype.xor):
(y.prototype.shift_left):
(y.prototype.shift_right_unsigned):
(y.prototype.shift_right):
(y.prototype.lsl1):
(y.prototype.lsr1):
(y.prototype.udivmod):
(y.prototype.div):
(y.prototype.mod):
(y.prototype.toInt):
(y.prototype.toFloat):
(y.prototype.toArray):
(y.prototype.lo32):
(y.prototype.hi32):
(dr):
(adF):
(W):
(bZ):
(adI):
(hn):
(dw):
(i8):
(b0):
(em):
(bt):
(adJ):
(bu):
(aeu):
(f3):
(P):
(cK):
(wt):
(wr):
(adB):
(f4):
(cL):
(i7):
(ad1):
(jc):
(jd):
(cl):
(cl.prototype.offset):
(cl.prototype):
(cl.prototype.fill):
(cl.prototype.compare):
(dn):
(dn.prototype.offset):
(dn.prototype):
(dn.prototype.fill):
(wp):
(aL):
(wq):
(wo):
(b3):
(aM):
(adW):
(ja):
(ws):
(adZ):
(aee):
(ad9):
(ad5):
(ad0):
(ad2):
(get b):
(eo.string_appeared_here.deserialize):
(i9):
(wx):
(eq):
(f7):
(wy):
(jh):
(wu):
(s):
(cI):
(adK):
(adL):
(ak):
(dp):
(O):
(adN):
(adO):
(ji):
(i_):
(c.j):
(i):
(ep):
(aT):
(f8):
(et):
(aew.a):
(aew.b):
(aew):
(wN):
(ad):
(aeq):
(adH):
(a6):
(cR):
(cQ):
(adG):
(X):
(aei):
(adE):
(bb):
(wn):
(aA):
(aA.prototype.truncate):
(aA.prototype.length):
(aA.prototype.write):
(aA.prototype.read):
(aA.prototype.read_one):
(aA.prototype.close):
(aS):
(aS.prototype.nm):
(aS.prototype.create_dir_if_needed):
(aS.prototype.slash):
(aS.prototype.lookup):
(aS.prototype.exists):
(aS.prototype.mkdir):
(aS.prototype.rmdir):
(aS.prototype.readdir):
(aS.prototype.is_dir):
(aS.prototype.unlink):
(aS.prototype.open):
(aS.prototype.register):
(t):
(aU):
(adA):
(adz):
(bD):
(bD.prototype.truncate):
(bD.prototype.length):
(bD.prototype.write):
(bD.prototype.read):
(bD.prototype.read_one):
(bD.prototype.close):
(aB):
(aB.prototype.nm):
(aB.prototype.exists):
(aB.prototype.mkdir):
(aB.prototype.rmdir):
(aB.prototype.readdir):
(aB.prototype.is_dir):
(aB.prototype.unlink):
(aB.prototype.open):
(aB.prototype.rename):
(aB.prototype.stat):
(aB.prototype.lstat):
(aB.prototype.symlink):
(aB.prototype.readlink):
(aB.prototype.raise_nodejs_error):
(aB.prototype.stats_from_js):
(wA):
(wQ):
(adM):
(wO):
(adQ):
(adR):
(b1):
(f2):
(jb):
(adX):
(adU):
(aea):
(adT):
(adV):
(adS):
(adY):
(dq):
(ba):
(wB):
(ad4):
(aN):
(a5):
(ad3):
(f5):
(wC):
(ad6):
(je):
(jg):
(wJ):
(f9):
(ad7):
(cM):
(cn):
(dv):
(jf):
(ad8):
(f6):
(fL):
(wE):
(cN):
(j):
(co):
(er):
(wM):
(aer):
(aes):
(gc):
(aez):
(aeb.a.a.0.et.d):
(aeb):
(wF):
(aec):
(aH):
(aed):
(wG):
(wH):
(cO):
(e):
(aef):
(es):
(b2):
(aeh):
(bi):
(jk):
(adD):
(cp):
(aem):
(E):
(d):
(aen):
(aeo):
(aep):
(aej):
(gb):
(ay):
(x):
(aI):
(wL):
(ar):
(ad_):
(adP):
(wz):
(ael):
(f):
(G):
(hJ):
(adx):
(am):
(aO):
(aC):
(ag):
(ge):
(gf):
(gg):
(g):
(wS):
(r):
(dz):
(jq):
(gh.b.a):
(gh):
(jr):
(cT):
(a7):
(ev):
(w5):
(jt):
(dB):
(gi):
(ju):
(cU):
(jv):
(Y):
(jw):
(ew):
(cq):
(bF):
(dC):
(ex):
(ey):
(gj):
(w):
(jx):
(cr):
(gk):
(dD):
(ez):
(gl):
(fN):
(jy):
(bG):
(dE):
(b4):
(bc):
(jz):
(jA):
(xh):
(jB):
(eA):
(jC):
(eB):
(gn):
(eF):
(cs):
(xn):
(gp):
(jH):
(b5):
(jJ):
(jL):
(e.catch.a.xt.1):
(gq):
(c):
(xD.d.p):
(xD.d.e):
(xD.d.g):
(xD.d.a):
(xD.d.h):
(xD.d.B):
(xD.d.C):
(xD.d.c):
(xD.d.l):
(xD.d.D):
(xD.d.E):
(xD.d.N):
(xD.d.r):
(xD.d.m):
(xD.d.i):
(xD.d.O):
(xD.d.P):
(xD.d.t):
(xD.d.j):
(xD.d.n):
(xD.d.u):
(xD.d.F):
(xD.d.o):
(xD.d.k):
(xD.d.G):
(xD.d.Q):
(xD.d.q):
(xD.d.H):
(xD.d.I):
(xD.d.J):
(xD.d.K):
(xD.d.v):
(xD.d.w):
(xD.d.x):
(xD.d.L):
(xD.d.R):
(xD.d.S):
(xD.d.T):
(xD.d.U):
(xD.d.V):
(xD.d.W):
(xD.d.X):
(xD.d.y):
(xD.d.Y.c.c.k.l.n.p.p.2.x):
(xD.d.Y.c.c.k.l.n.p.p.2.m):
(xD.d.Y.c.c.k.l.n.p.p.2.j):
(xD.d.Y):
(xD.d.M):
(xD.d.Z):
(xD.d.z):
(xD.d._):
(xD):
(xM.g.h):
(xM.g.c):
(xM.g.p):
(xM.g.a):
(xM.g.M):
(xM.g.l):
(xM.g.N):
(xM.g.O):
(xM.g.P):
(xM.g.Q):
(xM.g.R):
(xM.g.S):
(xM.g.T):
(xM.g.m):
(xM.g.B):
(xM.g.U):
(xM.g.V):
(xM.g.q):
(xM.g.C):
(xM.g.r):
(xM.g.s):
(xM.g.D):
(xM.g.t):
(xM.g.u):
(xM.g.E):
(xM.g.F):
(xM.g.H):
(xM.g.I):
(xM.g.J):
(xM.g.d):
(xM.g.n):
(xM.g.o):
(xM.g.i):
(xM.g.j):
(xM.g.k):
(xM.g.v):
(xM.g.w):
(xM.g.e):
(xM.g.W):
(xM.g.X):
(xM.g.x):
(xM.g.K):
(xM.g.Y):
(xM.g.L):
(xM.g.Z):
(xM.g.y):
(xM.g._):
(xM):
(ct):
(cW):
(gr):
(bd):
(dF):
(a0):
(gs):
(jM):
(jN):
(cX):
(aE):
(jO):
(gt):
(gu):
(at):
(aF.a.typeof.a.string_appeared_here.s):
(aF.a.typeof.a.string_appeared_here.t):
(aF.a.typeof.a.string_appeared_here.u):
(aF.a.else.switch.a.0.z):
(aF.a.else.switch.a.0.E):
(aF.a.else.switch.a.0.J):
(aF.a.else.switch.a.0.O):
(aF.a.else.switch.a.0.T):
(aF.a.else.switch.a.0.Y):
(aF.a.else.switch.a.0.ab):
(aF.a.else.switch.a.0.ag):
(aF.a.else.switch.a.0.al):
(aF.a.else.switch.a.0.ay):
(aF.a.else.switch.a.0.az):
(aF.a.else.switch.a.0.aA):
(aF.a.else.switch.a.0.aG):
(aF.a.else.switch.a.0.aL):
(aF.a.else.switch.a.0.aQ):
(aF.a.else.switch.a.0.aV):
(aF.a.else.switch.a.0.aW):
(aF.a.else.switch.a.0.aX):
(aF.a.else.switch.a.0.a2):
(aF.a.else.switch.a.0.a3):
(aF.a.else.switch.a.0.a4):
(aF):
(av):
(eH):
(dG):
(aV):
(Z):
(a1):
(a2):
(cY):
(yv):
(jP):
(a.13.m.d):
(eI):
(zl):
(zm):
(zn):
(zo):
(a.f):
(a.k):
(bI):
(y.else.switch.d.0.typeof.k.string_appeared_here):
(y.else.switch.d.0.else.0.k.0):
(y.else.switch.d.0.else):
(y.else.switch.d.0.0.m.0.c):
(y.else.switch.d.0.c):
(d0):
(hz):
(V):
(hy):
(N):
(a8):
(zt):
(gv):
(a.typeof.h.string_appeared_here):
(a.else.0.h.0):
(a.else):
(eJ):
(bJ):
(b6):
(b7):
(jQ):
(jR):
(zH):
(an):
(gy):
(jS):
(zW.a.q):
(zW):
(r.g.0.f):
(z6):
(jT):
(try.try.catch):
(try.catch):
(catch):
(z):
(Af):
(Ah):
(Aj):
(dH):
(jY):
(jZ):
(cZ):
(j0):
(j1):
(j3):
(j4):
(gA):
(c0):
(dI):
(j5):
(c1):
(eK):
(dJ):
(j6):
(j7.a.K):
(j7.a.L):
(j7.a.x):
(j7.a.d):
(j7.a.q):
(j7.a.m):
(j7.a.o):
(j7.a.h):
(j7.a.p):
(j7.a.N):
(j7.a.P):
(j7.a.Q):
(j7.a.R):
(j7.a.S):
(j7.a.T):
(j7.a.U):
(j7.a.V):
(j7.a.W):
(j7.a.X):
(j7.a.Y):
(j7.a.l):
(j7.a.r):
(j7.a.Z):
(j7.a._):
(j7.a.aa):
(j7.a.ab):
(j7.a.ac):
(j7.a.ad):
(j7.a.k):
(j7.a.y):
(j7.a.n):
(j7.a.s):
(j7.a.ae):
(j7.a.u):
(j7.a.z):
(j7.a.B):
(j7.a.a.k):
(j7.a.F):
(j7.a.G):
(j7.a.H):
(j7):
(AW):
(AX):
(eL.a.i):
(eL.a.s):
(eL.a.M):
(eL.a.N):
(eL.a.d):
(eL.a.S):
(eL.a.T):
(eL.a.U):
(eL.a.V):
(eL.a.C):
(eL.a.W):
(eL.a.D):
(eL.a.X):
(eL.a.v):
(eL.a.l):
(eL.a.Z):
(eL.a.h):
(eL.a.p):
(eL.a.G):
(eL.a.aa):
(eL.a.ab):
(eL.a.ac):
(eL.a.ad):
(eL.a.ae):
(eL.a.af):
(eL.a.H):
(eL.a.w):
(eL.a.al):
(eL.a.an):
(eL.a.q):
(eL.a.x):
(eL.a.I):
(eL.a.J):
(eL.a.ao):
(eL.a.ap):
(eL.a.ar):
(eL.a.as):
(eL.a.at):
(eL.a.av):
(eL.a.ax):
(eL.a.c):
(eL.a.y.d.h):
(eL.a.y):
(eL.a.az):
(eL.a.aA):
(eL.a.r):
(eL.a.aB):
(eL.a.aD):
(eL):
(Bg):
(Bh):
(Bi):
(Bj):
(Bk):
(Bl):
(Bm):
(Bn):
(Br):
(Bs):
(BU):
(gE):
(B0):
(B4):
(B5):
(B6):
(B7):
(B8):
(B9):
(B_):
(B):
(Cd):
(Ce):
(Ch):
(Cl):
(Cm):
(Cn):
(Co):
(Cp):
(Cq):
(Cr):
(Cs):
(Cw):
(Cx):
(kg):
(dK):
(Cz):
(gF):
(kh):
(ki):
(gG):
(gH):
(gI):
(gJ):
(dL):
(gK):
(gL):
(gM):
(kj):
(kk):
(kl):
(gN):
(eP):
(km):
(kn):
(CA):
(switch):
(typeof.a.string_appeared_here.switch):
(else.switch):
(fO):
(i.d):
(i.c):
(i.g):
(i.l):
(i.m):
(i.a.f):
(i.n):
(i.p):
(i.q):
(i.s):
(i.t):
(i.v):
(i.w):
(i.y):
(i.z):
(i.B):
(i.C):
(i.E):
(i.F):
(i.H):
(i.J):
(i.L):
(i.N):
(i.P):
(i.R):
(i.T):
(i.V):
(i.X):
(i._):
(i.aa):
(i.ac):
(i.ae):
(i.af):
(i.ag):
(i.ah):
(ko):
(Di):
(l):
(n):
(m):
(o):
(p):
(q):
(u):
(v):
(A):
(C):
(D):
(F):
(H):
(I):
(J):
(K):
(L):
(M):
(Q):
(R):
(S):
(T):
(U):
(aa):
(ac):
(ae):
(af):
(ah):
(ai):
(aj):
(al):
(Dk):
(Dm):
(Dp):
(kp):
(kq):
(kr):
(ks):
(eR):
(ab):
(bj):
(ku):
(cu):
(dM):
(gO):
(gP):
(gQ):
(gR):
(kv.a.c):
(kv):
(kw):
(aG):
(gT):
(kx):
(ky):
(c4):
(kz):
(DJ):
(kA):
(kB):
(kC):
(gU):
(kD):
(c5):
(DK):
(gV):
(DL):
(kE):
(DM):
(DN):
(kF):
(DO):
(DP):
(kG):
(DQ):
(DR):
(DS):
(kH.c.b):
(kH):
(dN):
(kK):
(dO):
(dP):
(kL):
(kM):
(kN):
(kO):
(kS):
(kT):
(kU):
(kV):
(kW):
(kX):
(kY):
(kZ):
(k0):
(k1):
(k2):
(k3):
(k7):
(k8):
(k9):
(k_):
(k):
(la):
(lb):
(lc):
(ld):
(le):
(lf):
(lg):
(lh):
(li):
(lj):
(lk):
(ll):
(lm):
(ln):
(lo):
(lp):
(lq):
(lr):
(lB):
(lH):
(lM):
(lN):
(lO):
(lP):
(lQ):
(lR):
(lS):
(lT):
(lU):
(lV):
(n5):
(n6):
(n7):
(n8):
(n9):
(n_):
(oa):
(ob):
(oc):
(od):
(oe):
(of):
(og):
(oh):
(oi):
(oj):
(ok):
(ol):
(om):
(on):
(oo):
(ox):
(oz):
(oA):
(oB):
(pa):
(pb):
(pc):
(pQ):
(pR):
(qu):
(qv):
(qV):
(qW):
(rk):
(rl):
(bM):
(rK):
(gX):
(rL):
(dQ):
(E7):
(rN):
(rO):
(gY):
(as):
(a3):
(eS):
(rP):
(gZ.b.a):
(gZ):
(g0.a.b):
(g0):
(eT):
(rQ):
(dR):
(g1):
(dS):
(aW):
(c6):
(Fe):
(rR):
(Ff):
(Fg):
(Fh):
(Fi):
(g2):
(eU):
(rS):
(rT):
(eV):
(eW):
(rU):
(rV):
(g3):
(g4):
(dT):
(c7):
(rW):
(rX):
(rY):
(rZ):
(FC):
(r0):
(r1):
(r2):
(r3):
(cv):
(c8):
(eX):
(FI):
(r4):
(cw):
(FM):
(cx):
(r5):
(bf):
(FW):
(FX):
(FZ):
(F0):
(F1):
(F2):
(F3):
(F5):
(F6):
(F7):
(g5):
(g6):
(g7):
(r6):
(eY):
(g8):
(F_):
(Gc):
(Ge):
(Gf):
(a9):
(a_):
(Gh.a.i):
(Gh.a.m):
(Gh.a.o):
(Gh.a.s):
(Gh.a.v):
(Gh.a.y):
(Gh.a.C):
(Gh.a.F):
(Gh.a.I):
(Gh.a.J):
(Gh.a.L):
(Gh):
(b9.1):
(Gq):
(r8):
(r9):
(bK.1):
(b_.1):
(GS):
(r_):
(sa):
(sb):
(dV):
(cy):
(bg):
(sc):
(aX):
(b.h):
(sd):
(e1):
(se):
(g_):
(sf):
(ha):
(bx):
(cz):
(hb):
(hc):
(sg):
(e2):
(hd):
(ca):
(sh):
(si):
(bN):
(he):
(hf):
(sj):
(sk):
(sl):
(dW):
(hg):
(sm):
(sn):
(so):
(hh):
(hq):
(sp):
(sq):
(sr):
(dX):
(hr):
(ss):
(bO):
(cb):
(HR):
(HS):
(HT):
(HU):
(HV):
(HW):
(HX):
(HY):
(HZ):
(H0):
(H1):
(H3):
(H5):
(H7):
(H9):
(Ib):
(Id):
(If):
(Ig):
(Ij):
(Ik):
(Il):
(Im):
(Io):
(Ip):
(Iq):
(Ir):
(Is):
(It):
(Iu):
(Iv):
(Iw):
(Ix):
(Iy):
(Iz):
(IA):
(IB):
(IC):
(ID):
(IE):
(IF):
(IG):
(IH):
(II):
(IJ):
(IK):
(IL):
(IM):
(IN):
(IO):
(IP):
(IQ):
(IR):
(IS):
(IU):
(IW):
(IX):
(IY):
(IZ):
(I0):
(I1):
(I2):
(I3):
(I4):
(I5):
(I6):
(I8):
(I9):
(I_):
(Ja):
(Jc):
(Je):
(Jg):
(Jh):
(Ji):
(Jj):
(Jk):
(Jl):
(Jm):
(Jn):
(Jo):
(Jp):
(Jr):
(Js):
(Jt):
(Ju):
(Jv):
(Jw):
(Jx):
(Jy):
(Jz):
(JA):
(JB):
(JC):
(JD):
(JE):
(JF):
(JG):
(JH):
(JI):
(JJ):
(JK):
(JL):
(JM):
(JN):
(JO):
(JP):
(JQ):
(JR):
(JS):
(JT):
(JU):
(JV):
(JW):
(JX):
(JY):
(J0):
(J1):
(J2):
(J3):
(J4):
(J5):
(J6.a.d):
(J6):
(J7):
(J8):
(J9):
(J_):
(Kb):
(Kc):
(Kd):
(Ke):
(Kf):
(Kg):
(Kh):
(Ki):
(Kj):
(Kl.a.g):
(Kl):
(Km.a.g):
(Km):
(Kn):
(Ko):
(Kp):
(Kr):
(Ks):
(Kt):
(Ku):
(Kv):
(Kw):
(Kx):
(Ky):
(Kz):
(KA):
(KB):
(KC):
(KD):
(KE):
(KF):
(KG):
(KH):
(KI):
(KJ):
(KK):
(KL):
(KN):
(KO):
(KP):
(KR):
(KS):
(KT):
(KU):
(KV):
(KW):
(KX):
(KY):
(KZ):
(K0):
(K1):
(K2):
(K3):
(K4):
(K5):
(K6):
(K7):
(K8):
(K9):
(K_.a.g):
(K_):
(La):
(Lb):
(Lc):
(Ld.a.else.i):
(Ld):
(Lh):
(Li):
(Lk):
(Ll):
(Lm):
(Lo):
(Lp):
(Lq):
(Ls):
(Lt):
(Lu):
(Lw):
(Lx):
(Ly):
(Lz):
(LA):
(LB):
(LC):
(LD):
(LE):
(LF):
(LG):
(LH):
(LI):
(LJ):
(LK):
(LL):
(LM):
(LN):
(LO):
(LP):
(LQ):
(LR):
(LS):
(LT):
(LU):
(LV):
(LW):
(LX):
(LZ):
(L0):
(L1):
(L2):
(L3):
(L4):
(L6):
(L7):
(L8):
(L9):
(L_):
(Ma):
(Mb):
(Mc):
(Md):
(Me):
(Mf):
(Mg):
(Mh):
(Mi):
(Mj):
(Mk):
(Ml):
(Mm):
(Mn):
(Mo):
(Mp):
(Mq):
(Mr):
(Ms):
(Mt):
(Mu):
(Mv):
(Mw):
(Mx):
(My):
(Mz):
(MA):
(MB):
(MC):
(MD):
(ME):
(MF):
(MG):
(MH):
(MI):
(MJ):
(MK):
(ML):
(MM):
(MN):
(MO):
(MP):
(MQ):
(MR):
(MS):
(MT):
(MU):
(MV):
(MW):
(MX):
(MY):
(MZ):
(M0):
(M1):
(M2):
(M3):
(M4):
(M5):
(M6):
(M7):
(M8):
(M9):
(M_):
(Na):
(Nb):
(Nc):
(Nd):
(Ne):
(Nf):
(Ng):
(Nh):
(Ni):
(Nj):
(Nk):
(Nl):
(Nm):
(Nn):
(Nr):
(Ns):
(Nt):
(Nu):
(Nv):
(Nw):
(Nz):
(NB):
(NC):
(ND):
(NE):
(NF):
(NG):
(NH):
(NI):
(NJ):
(NK):
(NL):
(NM):
(NN):
(NO):
(NP):
(NQ):
(NR):
(NS):
(NT):
(NU):
(NV):
(NW):
(NX):
(NY):
(NZ):
(N0):
(N1):
(N2):
(N3):
(N4):
(N5):
(N7):
(N9):
(N_):
(Oa):
(Ob):
(Oc):
(Od):
(Oe):
(Of):
(Og.a.g):
(Og):
(Oh):
(Oi):
(Oj):
(Ok):
(Ol):
(On):
(Op):
(Or):
(Ot):
(Ov):
(Ox):
(Oz):
(OB):
(OC):
(OD):
(OE):
(OF):
(OG):
(OH):
(OI):
(OJ):
(OK):
(OL):
(OM):
(ON):
(OO):
(OQ):
(OT):
(OU):
(OV):
(e3):
(cA):
(st):
(sx):
(c_):
(fP):
(hI):
(hH):
(su):
(OW):
(sw):
(e4):
(OY):
(sv):
(OX):
(hG):
(hF):
(sy):
(OZ):
(O0):
(ap):
(O1):
(hE):
(d7):
(d6):
(d5):
(d4):
(d3):
(d2):
(d1):
(au):
(O2):
(O3):
(O4):
(O5):
(O6):
(O7):
(O8):
(O9):
(O_):
(hD):
(hC):
(sz):
(hB):
(hA):
(sA):
(Pa):
(Pb):
(sB):
(Pc):
(Yj):
(ht):
(sC):
(sD):
(sE):
(aY):
(sF):
(sG):
(Yy):
(sH):
(YA):
(hu):
(sI):
(aJ):
(sJ):
(sK):
(aK):
(sL):
(da):
(dY):
(sM):
(YJ):
(YK):
(YL):
(a.c):
(db):
(sN):
(sO):
(sP):
(sQ):
(sR):
(dc):
(dd):
(Y4):
(Y6):
(Zf):
(Zl):
(ZB):
(ZO):
(ZQ):
(ZX):
(Z5):
(_b):
(bk):
(sS):
(hv):
(sT):
(sU):
(_C):
(sV):
(sW):
(sX):
(sY):
(sZ):
(9):
(aab):
(aag):
(hw):
(aaj):
(s0):
(hx):
(dZ):
(e5):
(by):
(cc):
(s1):
(s2):
(e6):
(e7):
(bP):
(s3):
(s4):
(s5):
(acQ):
(acT):
(acU):
(s6):
(acY):
(h.c):
(ac2):
(ac5):
(adg):
(adl):
(string_appeared_here.wE.switch.P.0.h):
(string_appeared_here.wE.switch.P.0.V):
(string_appeared_here.wE.switch.P.0.x):
(string_appeared_here.wE.switch.P.0.X):
(string_appeared_here.wE.switch.P.0.T):
(string_appeared_here.wE.switch.P.0.k):
(string_appeared_here.wE.switch.P.0.d):
(string_appeared_here.wE.switch.P.0.G):
(string_appeared_here.wE.switch.P.0.C):
(string_appeared_here.wE.switch.P.0.D):
(string_appeared_here.wE.switch.P.0.H):
(string_appeared_here.wE.switch.P.0.r):
(string_appeared_here.wE.switch.P.0.Y):
(string_appeared_here.wE.switch.P.0.l):
(string_appeared_here.wE.switch.P.0.Z):
(string_appeared_here.wE.switch.P.0.c):
(string_appeared_here.wE.switch.P.0.ac):
(string_appeared_here.wE.switch.P.0.ad):
(string_appeared_here.wE.switch.P.0.L):
(string_appeared_here.wE.switch.P.0.W):
(string_appeared_here.wE.switch.P.0.w):
(string_appeared_here.wE.switch.P.0.s):
(string_appeared_here.wE.switch.P.0.ae):
(string_appeared_here.wE.switch.P.0.ag):
(string_appeared_here.wE.switch.P.0.ah):
(string_appeared_here.wE.switch.P.0.ai):
(string_appeared_here.wE.switch.P.0.ak):
(string_appeared_here.wE.switch.P.0.al):
(string_appeared_here.wE.switch.P.0.am):
(string_appeared_here.wE.switch.P.0.a):
(string_appeared_here.wE.switch.P.0.y):
(string_appeared_here.wE.switch.P.0.i):
(string_appeared_here.wE.switch.P.0.g):
(string_appeared_here.wE.switch.P.0.U):
(string_appeared_here.wE.switch.P.0.a3):
(string_appeared_here.wE.switch.P.0.ao):
(string_appeared_here.wE.switch.P.0.u):
(string_appeared_here.wE.switch.P.0.q):
(string_appeared_here.wE.switch.P.0.p):
(string_appeared_here.wE.switch.P.0.a8):
(string_appeared_here.wE.switch.P.0.a_):
(string_appeared_here.wE.switch.P.0.bb):
(string_appeared_here.wE.switch.P.0.bd):
(string_appeared_here.wE.switch.P.0.bf):
(string_appeared_here.wE.switch.P.0.bi):
(string_appeared_here.wE.switch.P.0.bk):
(string_appeared_here.wE.switch.P.0.bm):
(string_appeared_here.wE.switch.P.0.bo):
(string_appeared_here.wE.switch.P.0.M):
(string_appeared_here.wE.switch.P.0.N):
(string_appeared_here.wE.switch.P.0.br):
(string_appeared_here.wE.switch.P.0.E):
(string_appeared_here.wE.switch.P.0.bs):
(string_appeared_here.wE.switch.P.0.bu):
(string_appeared_here.wE):

Canonical link: <a href="https://commits.webkit.org/252823@main">https://commits.webkit.org/252823@main</a>
</pre>

### CODE REVIEW

**Comment by takikawa** [comment]
The commit message has a giant changelog entry for the compiled-to-JS `wast.js` file currently. These entries don't provide any useful info but I kept them in because the changelog tool generated them. I'd be happy to revise to remove the entries below the file name if that's better.

Also as the message mentions, I didn't convert the RTT tests as they should be removed in https://bugs.webkit.org/show_bug.cgi?id=243079

The `wast.js` file is built from a fork of the GC spec repo that integrates some pending upstream spec changes: https://github.com/takikawa/gc/tree/wast (`make wast.js` in the `interpreter` directory there can replicate the build)

**Comment by Constellation** [comment]
Can we use the existing libwabt.js? We already have a test using it. If update is necessary, can you update it instead of adding a new one?

**Comment by takikawa** [comment]
@Constellation That's a good question. The issue with using libwabt.js is that wabt is currently far behind on the GC proposal and doesn't support the current semantics.

I've looked into updating wabt's support of the GC proposal, but it requires some non-trivial work, starting with fully implementing the typed function references proposal. The reference interpreter, on the other hand, is kept mostly up-to-date and is synced with the spec test suite.

**Comment by justinmichaud** [comment]
This looks much nicer to me, although I think we still have yet to find the optimal way to write these tests. We have like 5 different ways of writing WASM tests now. Ideally, we would avoid re-compiling the WASM each time we run to make debug tests run faster.

I wonder if we could add a build step for this? Anyway, this is definitely an improvement. I'll let @Constellation handle the review once he's satisfied, but LGTM.

**Review by Constellation — APPROVED** [review]
OK, r=me

**Pull request merged**
