### PR TITLE
Computed display of form inside table elements should be display:none

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Computed display of form inside table elements should be display:none
<a href="https://bugs.webkit.org/show_bug.cgi?id=252541">https://bugs.webkit.org/show_bug.cgi?id=252541</a>

Reviewed by NOBODY (OOPS!).

This patch is to align WebKit with Blink / Chromium and Gecko / Firefox and web-specification.

Web-Spec: <a href="https://html.spec.whatwg.org/multipage/rendering.html#tables-2">https://html.spec.whatwg.org/multipage/rendering.html#tables-2</a>

The patch adds UA stylesheet rule as expected from the web-specification to change display
type of form inside table elements to "display: none".

* Source/WebCore/css/html.css: As above
* LayoutTests/imported/w3c/web-platform-tests/html/rendering/non-replaced-elements/tables/form-in-tables-expected.txt: Rebaselined
</pre>

https://github.com/WebKit/WebKit/commit/638925875327fc651c2b0ecf1bb9b29f3e5c1fdd

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/108562 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/17660 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/41413 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/117669 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/117867 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/112445 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/19111 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/8937 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/100791 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/114329 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/14321 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/97550 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/42290 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/96298 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/29191 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/84002 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/10470 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/30540 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/11226 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/7452 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/16617 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/50135 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/12815 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
NOTE - I am still trying to fix locally where we don't regress XHTML based test. Would appreciate any help.

**Comment by nt1m** [comment]
> NOTE - I am still trying to fix locally where we don't regress XHTML based test. Would appreciate any help.

Thanks for looking into this!

Chrome & Firefox both have special selectors to target HTML documents.

Firefox: https://searchfox.org/mozilla-central/rev/0e3779abe6ad44feb787a295fbb67bc9fe4e927a/layout/style/res/html.css#476-482
Chrome: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/html/resources/html.css;l=376-378?q=internal-is-html&ss=chromium


It wouldn't be hard to add a similar one for WebKit, here's how to add one to WebKit: https://github.com/WebKit/WebKit/commit/a8c4c541c214613828e3fe9ce6524f9dde72a7f5 (not all parts are relevant)

Your matching function would look like this:

```cpp
ALWAYS_INLINE bool matchesIsHTMLPseudoClass(const Element& element) {
    return element.document().isHTMLDocument();
};
```

`CSSSelector::PseudoClassIsHtml` should be the generated one.

**Comment by nt1m** [comment]
Alternatively an other approach you can use is create a special UA stylesheet that's only appended for HTML documents, though I'm not sure how performant that will be, since HTML documents are the majority of documents.

**Comment by Ahmad-S792** [comment]
Thanks @nt1m for your guidance and reference links. I manage to have local build with all related changes, I will close this PR since my Git setup does not work properly with 'rebase', I will do PR with all changes to get it over the line. Thanks again for your support.

**Pull request closed without merging**
