### PR TITLE
AVAudioSession is not available in public macOS SDK

### PR DESCRIPTION
**Pull request by saagarjha**
#### 5d58c1c6fae24c8e96449b72ab79ecf8e8237c65
<pre>
AVAudioSession is not available in public macOS SDK
<a href="https://bugs.webkit.org/show_bug.cgi?id=264079">https://bugs.webkit.org/show_bug.cgi?id=264079</a>

Reviewed by NOBODY (OOPS!).

This adds checks for the internal SDK on macOS.

* Source/WTF/wtf/PlatformHave.h: Check for internal SDK
</pre>

### CODE REVIEW

**Comment by aproskuryakov** [comment]
Thank you for the PR. Could you please clarify what it is intended to fix?

WebKit already builds against open source macOS Sonoma SDK without trouble: https://build.webkit.org/#/builders/Apple-Sonoma-Release-Build?numbuilds=50

**Comment by saagarjha** [comment]
Hmm, interesting. I reviewed that and it seems like I misunderstood the problem: availability checks are ignored in command-line builds, because there's an SDK in place to patch them out. There's something different about Xcode that causes this to not be included, which is probably the actual bug. I'll update this pull request with that instead.

**Comment by aproskuryakov** [comment]
Are you perhaps building for macOS Ventura using Xcode 15? That is a configuration that should be supported in theory, but we don't actively maintain it. The canonical way to build for older OSes is with aligned Xcode/SDK versions. 

Cf. discussion https://bugs.webkit.org/show_bug.cgi?id=226235 and related.

**Comment by emw-apple** [comment]
> Hmm, interesting. I reviewed that and it seems like I misunderstood the problem: availability checks are ignored in command-line builds, because there's an SDK in place to patch them out.

Right, we have `WebKitLibraries/SDKs/macosx14.0-additions.sdk/usr/local/include/AvailabilityProhibitedInternal.h` which effectively disables availability checks, because WebKit on macOS uses some private APIs which are marked unavailable in system headers. (`AVAudioSession` is one of them.) 

>  There's something different about Xcode that causes this to not be included, which is probably the actual bug.

Makes sense to me. SDK additions are set in xcconfigs, and we don't do anything special to use them in command-line Xcode builds vs. IDE Xcode builds.

**Comment by saagarjha** [comment]
Sorry for keeping this open–I've been busy with other stuff and haven't looked into this as deeply as I would have liked. I'm going to keep this open for a little bit until I figure it out but I suspect this might actually be a bug in Xcode, in which case I'll close this and file it as appropriate. Not quite sure yet.

To be clear, WebKit definitely does not build on my computer with Xcode (currently 15.1 beta 3), so *something* is wrong:
image

PAL does set additional SDKs for this target and configuration though:
image

But it isn't actually show up in the compiler invocation at all:

```
CompileC /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/Objects-normal/arm64/OutputContext.o /tmp/WebKit/Source/WebCore/PAL/pal/avfoundation/OutputContext.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'PAL' from project 'PAL')
    cd /tmp/WebKit/Source/WebCore/PAL
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /tmp/WebKit/DerivedData/SDKStatCaches.noindex/macosx14.2-23C5047d-351270cdc94707120a7f59c917d9d2ec.sdkstatcache -target arm64-apple-macos14.2 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -std\=c++2a -stdlib\=libc++ -fobjc-weak -Wno-trigraphs -fno-exceptions -fno-rtti -fno-sanitize\=vptr -fpascal-strings -O0 -fno-common -Werror -Wno-missing-field-initializers -Wmissing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wnon-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility\=hidden -fno-threadsafe-statics -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -index-store-path /tmp/WebKit/DerivedData/WebKit/Index.noindex/DataStore -iquote /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/PAL-generated-files.hmap -I/tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/PAL-own-target-headers.hmap -I/tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/PAL-all-target-headers.hmap -iquote /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/PAL-project-headers.hmap -I/tmp/WebKit/DerivedData/WebKit/Build/Products/Debug/include -I/tmp/WebKit/DerivedData/WebKit/Build/Products/Debug/usr/local/include -isystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/include -I/tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/DerivedSources-normal/arm64 -I/tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/DerivedSources/arm64 -I/tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/DerivedSources -Wall -Wconditional-uninitialized -Wextra -Wformat\=2 -Wundef -Wcast-qual -Wchar-subscripts -Wextra-tokens -Winit-self -Wmissing-noreturn -Wpacked -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wexit-time-destructors -Wglobal-constructors -Wtautological-compare -Wimplicit-fallthrough -Wvla -Wno-unknown-warning-option -Wliteral-conversion -Wthread-safety -F/tmp/WebKit/DerivedData/WebKit/Build/Products/Debug -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/PrivateFrameworks -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/PrivateFrameworks -D_LIBCPP_ENABLE_ASSERTIONS\=1 -MMD -MT dependencies -MF /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/Objects-normal/arm64/OutputContext.d --serialize-diagnostics /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/Objects-normal/arm64/OutputContext.dia -c /tmp/WebKit/Source/WebCore/PAL/pal/avfoundation/OutputContext.mm -o /tmp/WebKit/DerivedData/WebKit/Build/Intermediates.noindex/PAL.build/Debug/PAL.build/Objects-normal/arm64/OutputContext.o -index-unit-output-path /PAL.build/Debug/PAL.build/Objects-normal/arm64/OutputContext.o
```

Mostly just dumping stuff here to provide context; I'll keep looking into it more myself. But if any of this looks familiar and you know what might be wrong off the top of your head, I'm all ears.

**Comment by saagarjha** [comment]
Closing this pull request, as I believe this is a bug in Xcode itself when you set a workspace-relative DerivedData location. In that case ADDITIONAL_SDKS does not seem to function correctly, causing the build to fail. If you'd like to track this internally, see FB13455607.

**Comment by emw-apple** [comment]
Most WebKit developers (at least at Apple) use a workspace-relative derived data location, so I would be surprised if there is an Xcode bug here.

If you're having problems loading the SDK additions from the repo, one thing you could look at is how your system is deriving `$(WK_WORKSPACE_DIR)`, which is declared in `WebKitProjectPaths.xcconfig`. You would expect to see "can't find additional SDK" warnings if something is being computed wrong.

Also, I'm happy to look at a full build log if you've got one handy.

**Comment by saagarjha** [comment]
I am seeing those warnings, yes. Here's a build log from my machine: 
[Build Everything up to MiniBrowser_2023-12-15T07-46-53.txt](https://github.com/WebKit/WebKit/files/13682095/Build.Everything.up.to.MiniBrowser_2023-12-15T07-46-53.txt)

That being said, I tested this on other machines of mine and it doesn't seem to fail there, so perhaps there are multiple things that need to be true before this reproduces.

**Comment by emw-apple** [comment]
Strange indeed. It might be worth confirming that `/tmp/WebKit/WebKitLibraries/SDKs/macosx14.0-additions.sdk/SDKSettings.plist` exists? macOS is allowed to remove files from `/tmp` automatically, though I don't think it would delete anything that had been recently created.

**Comment by emw-apple** [comment]
I hit an issue like this today while working on the public build from within Xcode. I believe I've found the root cause: https://bugs.webkit.org/show_bug.cgi?id=268205 ([Xcode] Additions SDKs need to have platform-specific names)

**Comment by saagarjha** [comment]
Hi, sorry for dropping the ball on this and not following up. Thank you for diagnosing this correctly! With that change I am able to build again.

**Pull request closed without merging**
