### PR TITLE
Text selection doesn't appear correct for partially rotated text

### PR DESCRIPTION
**Pull request by rr-codes**
#### a8619910b2256e29f8a4e63ea3d9542b2561f415
<pre>
Text selection doesn&apos;t appear correct for partially rotated text
<a href="https://bugs.webkit.org/show_bug.cgi?id=257301">https://bugs.webkit.org/show_bug.cgi?id=257301</a>
rdar://109173149

Reviewed by Wenson Hsieh.

In 263159@main, a mechanism was added to detect if two quads are overlapping. This mechanism
turned out to return false positives, resulting in some quads being erroneously coalesced.

Upon further investigation, this mechanism isn&apos;t actually needed. Rather, simply expanding the
threshold for the existing `areCloseEnoughToCoalesce` mechanism is sufficient to cover this, and
does not give false positives.

* LayoutTests/fast/images/resources/text-with-rotated-text.png: Added.
* LayoutTests/fast/images/text-recognition/ios/do-not-coalesce-non-adjacent-selection-rects-in-image-overlay-expected.txt: Added.
* LayoutTests/fast/images/text-recognition/ios/do-not-coalesce-non-adjacent-selection-rects-in-image-overlay.html: Added.
* Source/WebCore/rendering/RenderObject.cpp:
(WebCore::coalesceSelectionGeometryWithAdjacentQuadsIfPossible):

Canonical link: <a href="https://commits.webkit.org/264556@main">https://commits.webkit.org/264556@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/9b26627e1621b822f4e272974cbe17cadf73db28

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/7992 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/8276 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/8488 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/9643 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/8098 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/7996 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/10262 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/8187 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/10962 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/8136 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/9218 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/7301 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/9762 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/6519 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/7308 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/14889 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/7642 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/7429 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/10790 "6 api tests failed or timed out") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/7904 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/6425 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/7218 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/7221 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/1903 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/11426 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/7645 "Built successfully") | | |

### CODE REVIEW

**Comment by whsieh** [comment]
Is it possible to write a test for this? (I imagine we might be able to do something similar to `fast/images/text-recognition/ios/coalesce-selection-rects-in-image-overlay.html`, or even augment that existing test case).

**Comment by rr-codes** [comment]
> Is it possible to write a test for this? (I imagine we might be able to do something similar to `fast/images/text-recognition/ios/coalesce-selection-rects-in-image-overlay.html`, or even augment that existing test case).

ah, I was trying to find an existing test I could base mine on. Thanks!

**Review by whsieh — APPROVED** [review]
r=mEWS

**Review by aprotyas — APPROVED** [review]
Optional nit: add a trailing new line in the layout test?

**Pull request merged**
