### PR TITLE
[GLIB] Remove libsoup2 codepaths

### PR DESCRIPTION
**Pull request by dpino**
#### 4e205427e73872e9e48092447c6f364254f5dba2
<pre>
[GLIB] Remove libsoup2 codepaths
<a href="https://bugs.webkit.org/show_bug.cgi?id=276256">https://bugs.webkit.org/show_bug.cgi?id=276256</a>

Reviewed by NOBODY (OOPS!).

Since we&apos;re no longer supporting builds with libsoup2, remove all code wrapped within USE(SOUP2).

* Source/WTF/wtf/Platform.h:
* Source/WebCore/platform/Soup.cmake:
* Source/WebCore/platform/network/soup/AuthenticationChallenge.h:
* Source/WebCore/platform/network/soup/AuthenticationChallengeSoup.cpp:
(WebCore::protectionSpaceFromSoupAuthAndURL):
(WebCore::AuthenticationChallenge::AuthenticationChallenge):
(WebCore::AuthenticationChallenge::platformCompare):
* Source/WebCore/platform/network/soup/CookieSoup.cpp:
(WebCore::Cookie::Cookie):
(WebCore::Cookie::toSoupCookie const):
(WebCore::msToSoupDate): Deleted.
* Source/WebCore/platform/network/soup/GUniquePtrSoup.h:
* Source/WebCore/platform/network/soup/NetworkStorageSessionSoup.cpp:
(WebCore::NetworkStorageSession::setCookiesFromDOM const):
* Source/WebCore/platform/network/soup/ResourceErrorSoup.cpp:
(WebCore::ResourceError::httpError):
(WebCore::ResourceError::authenticationError):
* Source/WebCore/platform/network/soup/ResourceRequest.h:
* Source/WebCore/platform/network/soup/ResourceRequestSoup.cpp:
(WebCore::ResourceRequest::updateSoupMessageBody const):
(WebCore::ResourceRequest::createSoupURI const):
* Source/WebCore/platform/network/soup/ResourceResponseSoup.cpp:
* Source/WebCore/platform/network/soup/SoupNetworkSession.cpp:
(WebCore::SoupNetworkSession::setupLogger):
(WebCore::SoupNetworkSession::clearHSTSCache):
* Source/WebCore/platform/network/soup/SoupVersioning.h: Removed.
* Source/WebCore/platform/network/soup/URLSoup.cpp:
(WebCore::urlToSoupURI):
* Source/WebCore/platform/network/soup/URLSoup.h:
* Source/WebDriver/soup/HTTPServerSoup.cpp:
(WebDriver::HTTPServer::listen):
* Source/WebKit/NetworkProcess/soup/NetworkDataTaskSoup.cpp:
(WebKit::NetworkDataTaskSoup::NetworkDataTaskSoup):
(WebKit::NetworkDataTaskSoup::createRequest):
(WebKit::NetworkDataTaskSoup::clearRequest):
(WebKit::NetworkDataTaskSoup::resume):
(WebKit::NetworkDataTaskSoup::cancel):
(WebKit::NetworkDataTaskSoup::didSendRequest):
(WebKit::NetworkDataTaskSoup::preconnectCallback):
(WebKit::NetworkDataTaskSoup::dispatchDidCompleteWithError):
(WebKit::NetworkDataTaskSoup::acceptCertificateCallback):
(WebKit::NetworkDataTaskSoup::authenticateCallback):
(WebKit::NetworkDataTaskSoup::completeAuthentication):
(WebKit::NetworkDataTaskSoup::cancelAuthentication):
(WebKit::NetworkDataTaskSoup::authenticate):
(WebKit::NetworkDataTaskSoup::continueAuthenticate):
(WebKit::NetworkDataTaskSoup::continueHTTPRedirection):
(WebKit::tlsProtocolVersionToString):
(WebKit::NetworkDataTaskSoup::didGetHeaders):
(WebKit::NetworkDataTaskSoup::requestCertificatePasswordCallback):
(WebKit::NetworkDataTaskSoup::wroteBodyDataCallback):
(WebKit::NetworkDataTaskSoup::didWriteBodyData):
(WebKit::NetworkDataTaskSoup::hstsEnforced):
(WebKit::NetworkDataTaskSoup::didStartRequest):
(WebKit::NetworkDataTaskSoup::didRestart):
(WebKit::NetworkDataTaskSoup::tlsConnectionAcceptCertificateCallback): Deleted.
(WebKit::addHeaderSizes): Deleted.
(WebKit::NetworkDataTaskSoup::networkEventCallback): Deleted.
(WebKit::NetworkDataTaskSoup::networkEvent): Deleted.
* Source/WebKit/NetworkProcess/soup/NetworkDataTaskSoup.h:
* Source/WebKit/NetworkProcess/soup/NetworkSessionSoup.cpp:
(WebKit::NetworkSessionSoup::createWebSocketTask):
(WebKit::webSocketAcceptCertificateCallback): Deleted.
(WebKit::webSocketMessageNetworkEventCallback): Deleted.
* Source/WebKit/NetworkProcess/soup/WebSocketTaskSoup.cpp:
(WebKit::isConnectionError):
(WebKit::WebSocketTask::WebSocketTask):
* Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorHTTPServer.cpp:
(WebKit::RemoteInspectorHTTPServer::start):
* Source/cmake/OptionsGTK.cmake:
* Tools/PlatformWPE.cmake:
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestAuthentication.cpp:
(Tunnel::Tunnel):
(Tunnel::connect):
(serverCallback):
(testWebViewAuthenticationProxy):
(testWebViewAuthenticationProxyHTTPS):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestBackForwardList.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestCookieManager.cpp:
(testCookieManagerLongExpires):
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestDownloads.cpp:
(addContentDispositionHTTPHeaderToResponse):
(writeNextChunk):
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestLoaderClient.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestNetworkProcessMemoryPressure.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestResources.cpp:
(addCacheHTTPHeadersToResponse):
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestSSL.cpp:
(WebSocketTest::serverWebSocketCallback):
(testWebSocketClientSideCertificate):
(httpsServerCallback):
(httpServerCallback):
(beforeAll):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitFaviconDatabase.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitPolicyClient.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitSettings.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitUserContentManager.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebContext.cpp:
(serverCallback):
(ProxyTest::webSocketProxyServerCallback):
(webSocketServerCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebsiteData.cpp:
(serverCallback):
* Tools/TestWebKitAPI/Tests/WebKitGtk/TestContextMenu.cpp:
(writeNextChunk):
(serverCallback):
* Tools/TestWebKitAPI/glib/WebKitGLib/WebKitTestServer.cpp:
(WebKitTestServer::run):
</pre>
https://github.com/WebKit/WebKit/commit/4e205427e73872e9e48092447c6f364254f5dba2

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/70417 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/49823 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/23182 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/74506 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/21595 "Failed to checkout and rebase branch from PR 30520") 
| [❌ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/72534 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/57623 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/21435 "Failed to checkout and rebase branch from PR 30520") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/46462 "Passed tests") | [❌ 🧪 win-tests](https://ews-build.webkit.org/#/builders/59/builds/21595 "Failed to checkout and rebase branch from PR 30520") 
| [❌ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/73483 "Failed to checkout and rebase branch from PR 30520") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/34440 "Found 2 new test failures: compositing/overflow/overflow-compositing-descendant.html compositing/self-painting-layers.html (failure)") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/49549 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/27326 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/31222 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/6860 "Passed tests") | [❌ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/19956 "Failed to checkout and rebase branch from PR 30520") | 
| [❌ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/63538 "Failed to checkout and rebase branch from PR 30520") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/53233 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/7131 "Passed tests") | [❌ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/76225 "Failed to checkout and rebase branch from PR 30520") | 
| [❌ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/69664 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/14643 "Failed to checkout and rebase branch from PR 30520") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/7222 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/53722 "Passed tests") | 
| | [❌ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/14685 "Failed to checkout and rebase branch from PR 30520") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/49583 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/53809 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/1097 "Passed tests") | [❌ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/23182 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/91447 "Failed to checkout and rebase branch from PR 30520") | 
| | [❌ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/45625 "Failed to checkout and rebase branch from PR 30520") | [❌ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/392 "Failed to checkout and rebase branch from PR 30520") | [❌ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12983 "Found 12 new JSC stress test failures: stress/proxy-get-and-set-recursion-stack-overflow.js.eager-jettison-no-cjit, stress/proxy-get-and-set-recursion-stack-overflow.js.no-cjit-collect-continuously, stress/proxy-get-and-set-recursion-stack-overflow.js.no-cjit-validate-phases, stress/proxy-set.js.bytecode-cache, stress/proxy-set.js.default, stress/proxy-set.js.dfg-eager, stress/proxy-set.js.dfg-eager-no-cjit-validate, stress/proxy-set.js.eager-jettison-no-cjit, stress/proxy-set.js.mini-mode, stress/proxy-set.js.no-cjit-collect-continuously ... (failure)") | 
| | [❌ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/46699 "Failed to checkout and rebase branch from PR 30520") | | | 
| | [❌ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/47976 "Failed to checkout and rebase branch from PR 30520") | | | 
| | [❌ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/46441 "Failed to checkout and rebase branch from PR 30520") | | |

### CODE REVIEW

**Comment by carlosgcampos** [comment]
The GTK port still supports building with soup2

**Comment by dpino** [comment]
> The GTK port still supports building with soup2

I thought that since now all supported distros feature libsoup3 we wanted to remove libsoup2 support, including codepaths.

**Comment by aperezdc** [comment]
@dpino @carlosgcampos I am going to close this for now, we have to discuss first when/if the libsoup2 support can be dropped from the GTK port.

**Comment by dpino** [comment]
> @dpino @carlosgcampos I am going to close this for now, we have to discuss first when/if the libsoup2 support can be dropped from the GTK port.

If I understand correctly, the only obstacle to remove libsoup2 was Debian 11 support, which reached its end of life on 14th August. It's becoming overly difficult to build WebKitGTK for Debian 11, and until very recently that was only possible applying downstream patches. The recent ICU upgrade to ICU 70 has broken the build again, and the only work around is going to be to build WebKitGTK using the JHBuild minimal dependencies moduleset, which also includes libsoup3. All in all, I think that if the only obstacle to remove libsoup2 codepaths was Debian 11 support, we can go ahead.

**Comment by bertogg** [comment]
> If I understand correctly, the only obstacle to remove libsoup2 was Debian 11 support, which reached its end of life on 14th August.

That's not correct, Debian 12 (bookworm) still ships `libsoup2` and `libwebkit2gtk-4.0-37`. It was removed from Debian 13 (trixie, currently in testing). We need libsoup2 support for all security releases.

**Comment by dpino** [comment]
> > If I understand correctly, the only obstacle to remove libsoup2 was Debian 11 support, which reached its end of life on 14th August.
> 
> That's not correct, Debian 12 (bookworm) still ships `libsoup2` and `libwebkit2gtk-4.0-37`. It was removed from Debian 13 (trixie, currently in testing). We need libsoup2 support for all security releases.

Debian 12 also features libsoup3. Right now, there are not bots building with libsoup2. Should the Debian 12 bot build with libsoup2? (to catch build breaks on libsoup2 codepaths).

**Comment by bertogg** [comment]
> Debian 12 also features libsoup3. Right now, there are not bots building with libsoup2. Should the Debian 12 bot build with libsoup2? (to catch build breaks on libsoup2 codepaths).

Yes, in Debian 12 WebKitGTK with libsoup2 is used by plenty of projects, including Liferea, GnuCash and Shotwell.

**Comment by dpino** [comment]
Since now it's clear until when libsoup2 should be supported in the codebase, I'm going to close this PR. I also updated WebKit Docs' DependenciesPolicy.md to document this agreement https://github.com/WebKit/Documentation/pull/106

**Pull request closed without merging**
