### PR TITLE
Recognize CSSUnitType::CSS_X as a resolution calc unit category

### PR DESCRIPTION
**Pull request by rreno**
#### 310f6772fe38734a6592e9ed1fa2f068556e4500
<pre>
Recognize CSSUnitType::CSS_X as a resolution calc unit category
<a href="https://bugs.webkit.org/show_bug.cgi?id=252627">https://bugs.webkit.org/show_bug.cgi?id=252627</a>
rdar://105700660

Reviewed by Tim Nguyen.

We will fail to parse an expression like calc(1x * 2) because we are expecting a Resolution
calculation category due to the first token in the expression being a Dimenson token. However,
&apos;x&apos; is not recognized by the mapping and is given the category Other.
This causes us to bail and not perform the calculation.

* Source/WebCore/css/calc/CSSCalcCategoryMapping.cpp:
(WebCore::calcUnitCategory):

* LayoutTests/imported/w3c/web-platform-tests/css/css-images/image-set/image-set-parsing-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-images/image-set/image-set-parsing.html:

Canonical link: <a href="https://commits.webkit.org/260678@main">https://commits.webkit.org/260678@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/a93f1874fd9f6c0a2d55213aec999a4ded52fde2

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/108892 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/17997 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/41735 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/436 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/118211 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/112773 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/19454 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/9279 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/101137 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/114662 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/14596 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/97807 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/42699 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/96568 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/29448 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/84433 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/10770 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/30797 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/11525 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/7734 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/16915 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/50393 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7371 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/13113 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by nt1m** [comment]
Looks fine, but are there any tests for this?

**Comment by darinadler** [comment]
Can we add a test that fails before and passes after? Preferably in web platform tests

**Comment by rreno** [comment]
I found this while working on parsing for `image-set`. I can add tests there for `calc` expressions - currently only literal values are used for resolution for testing.

A test case might be something like:
```CSS
html {
--base-resolution: 1x;
}
div {
background-image: image-set('img.png' calc(var(--base-resolution) * 2) type('image/png'));
}
```

**Comment by rreno** [comment]
I added some test cases to the image set parsing WPT. They all pass on main except the case where `calc` has a value with units of `x`.

Export here: https://github.com/web-platform-tests/wpt/pull/38624

**Review by nt1m — APPROVED** [review]

**Pull request merged**
