### PR TITLE
[WTF] RELEASE_ASSERT_NOT_REACHED should allow a message

### PR DESCRIPTION
**Pull request by jjgriego**
#### c4574f31334dd38adc9962e34b195ef364d1eb7f
<pre>
[WTF] RELEASE_ASSERT_NOT_REACHED should allow a message
<a href="https://bugs.webkit.org/show_bug.cgi?id=259526">https://bugs.webkit.org/show_bug.cgi?id=259526</a>

Reviewed by Mark Lam.

The asserts-enabled and asserts-not-enabled implementations of this macro don&apos;t
agree about whether or not it allows a message--allow one for the sake of
form. Since revision f0224c3ac4969 it&apos;s used in at least one place with a
message.

* Source/WTF/wtf/Assertions.h:

Canonical link: <a href="https://commits.webkit.org/266516@main">https://commits.webkit.org/266516@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/67449f099bed2a83da861d385fba24b7a8b6ac32

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/13544 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/13858 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/14189 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/15281 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/12883 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/16366 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/13936 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/15565 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/13711 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/14355 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/11467 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/15985 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/11643 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/12222 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/19269 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/11544 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/12718 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/12390 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/15604 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/12825 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/12905 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/10789 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/13588 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/12173 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/3547 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/3398 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/16501 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/13973 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/12748 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/3348 "Passed tests") |

### CODE REVIEW

**Comment by jjgriego** [comment]
Note that this fixes debug builds on armv7 and mips due to this use of RELEASE_ASSERT_NOT_REACHED: https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/wasm/WasmSlowPaths.cpp#L863

**Comment by aproskuryakov** [comment]
Release asserts are sometimes more limited in functionality, because it is important to keep register values intact for crash log analysis. I don't know if this is one of those cases, or an accidental omission - CC'ed JSC reviewers who will know.

**Comment by emw-apple** [comment]
For what it's worth, we already have a `RELEASE_ASSERT_NOT_REACHED_WITH_MESSAGE` macro. Not sure if they are intentionally named differently.

**Comment by jjgriego** [comment]
oh, I missed that :S maybe better to switch the problematic usage in WasmSlowPaths.cpp and fix the `!ASSERT_ENABLED` implementation of `RELEASE_ASSERT_NOT_REACHED` to not have varargs?

**Review by MenloDorian — APPROVED** [review]
r=me.  I think this change is fine and makes it consistent with the `#if !ASSERT_ENABLED` implementation.

**Pull request merged**
