### PR TITLE
Do not CFRelease a CFSTR constant.

### PR DESCRIPTION
**Pull request by LumioseSil**
#### 3f8639874e31f01d2d8ad8221f0b6803e5e2162d
<pre>
Do not CFRelease a CFSTR constant.
<a href="https://bugs.webkit.org/show_bug.cgi?id=253160">https://bugs.webkit.org/show_bug.cgi?id=253160</a>

Reviewed by Elliott Williams.

There is no need to CFRelease a CFSTR-created string. This is a constant
and CFRelease has no effect.

* Source\JavaScriptCore\API\tests\testapi.c: Remove CFRelease call

Canonical link: <a href="https://commits.webkit.org/261024@main">https://commits.webkit.org/261024@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/4f0d5a7f6625cab416ef6a81e371ecb6aa13bef6

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/110299 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/19393 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/42938 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/1704 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/119262 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/20850 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/10575 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/102553 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/116043 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/15527 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/98724 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/43737 "Passed tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/97488 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/30388 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/85594 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/99050 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/12073 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/31725 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/100036 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/83/builds/10123 "Built successfully and passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/12673 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/8696 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/31231 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/18039 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/51342 "Passed tests") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/108058 "Built successfully") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/7637 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/14500 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/26641 "Passed tests") | 
| | | | |

### CODE REVIEW

**Comment by AtariDreams** [comment]
@mcatanzaro Can we merge this quickie?

**Comment by mcatanzaro** [comment]
You need an Apple reviewer for this, because I don't want to learn how CoreFoundation works. :)

**Comment by AtariDreams** [comment]
@emw-apple Could you review this please?

**Review by emw-apple — APPROVED** [review]
There is no harm in what we do now, but AFAICT the CFRelease is indeed superfluous.

From https://developer.apple.com/documentation/corefoundation/cfstr?language=objc#, "You can retain and release values returned from CFSTR in a balanced fashion, like any other CFString, but you are not required to do so."

**Comment by AtariDreams** [comment]
> There is no harm in what we do now, but AFAICT the CFRelease is indeed superfluous.
> 
> From https://developer.apple.com/documentation/corefoundation/cfstr?language=objc#, "You can retain and release values returned from CFSTR in a balanced fashion, like any other CFString, but you are not required to do so."

So can we please merge this then?

**Pull request merged**
