### PR TITLE
[WPE] Disable FTP directory support by default

### PR DESCRIPTION
**Pull request by blino**
#### 0655304c01f9e8533798d3182b12563a216fe03e
<pre>
[WPE] Disable FTP directory support by default
<a href="https://bugs.webkit.org/show_bug.cgi?id=241094">https://bugs.webkit.org/show_bug.cgi?id=241094</a>

Reviewed by Adrian Perez de Castro.

* Source/cmake/OptionsWPE.cmake:
FTP directory support is disabled by default in the GTK port, and has
been removed in major browsers (Firefox, Chrome).
Disabling it also saves 24 kB on the library size for an ARMv7 build.

Canonical link: <a href="https://commits.webkit.org/251865@main">https://commits.webkit.org/251865@main</a>
</pre>

### CODE REVIEW

**Review by aperezdc — COMMENTED** [review]
I have no strong opinion about changing the default, but I suppose it's not much of a hassle to disable it by hand when doing a custom build either.

Opinions @philn, @zdobersek, @magomez?

**Comment by blino** [comment]
> I have no strong opinion about changing the default, but I suppose it's not much of a hassle to disable it by hand when doing a custom build either.

This change is mostly to align with the GTK port defaults, and with other browsers which removed FTP support in the past year because of poor protocol security.

And for WPE which mostly targets embedded targets, printing the content of a FTP directory is not really useful.

**Comment by philn** [comment]
No objection. BTW unrelated, the API tests are broken (webkit-settings, java stuff).

**Comment by blino** [comment]
> No objection. BTW unrelated, the API tests are broken (webkit-settings, java stuff).

Maybe related to https://github.com/WebKit/WebKit/pull/1098 ?
cc @lauromoura

**Comment by aperezdc** [comment]
> > No objection. BTW unrelated, the API tests are broken (webkit-settings, java stuff).
> 
> Maybe related to #1098 ? cc @lauromoura

Yes, that was the patch shuffling around the API tests for the Java setting. The failures are independent from the change introduced by this patch.

**Review by aperezdc — APPROVED** [review]

**Pull request merged**
