### PR TITLE
Use Exif orientation when creating ImageBitmap from Blob

### PR DESCRIPTION
**Pull request by lexaknyazev**
#### 8758b1b9f85526f462e6edb74d5c85228e15d90d
<pre>
Use Exif orientation when creating ImageBitmap from Blob
<a href="https://bugs.webkit.org/show_bug.cgi?id=223326">https://bugs.webkit.org/show_bug.cgi?id=223326</a>

Reviewed by Kenneth Russell and Kimmo Kinnunen.

Do not ignore embedded Exif orientation metadata
when creating ImageBitmap from Blob.

* LayoutTests/TestExpectations:
* LayoutTests/imported/w3c/web-platform-tests/html/canvas/element/manual/imagebitmap/imagebitmap-replication-exif-orientation-expected.txt:
* Source/WebCore/html/ImageBitmap.cpp:
(WebCore::ImageBitmap::createFromBuffer):

Canonical link: <a href="https://commits.webkit.org/253004@main">https://commits.webkit.org/253004@main</a>
</pre>

### CODE REVIEW

**Review by kkinnunen-apple — APPROVED** [review]

**Review by kenrussell — COMMENTED** [review]
What's the status of this pull request? Did the merge-queue fail, and are more code owners' reviews needed?

**Comment by lexaknyazev** [comment]
Yes, looks like the merge queue requires an approval from code owners.

**Comment by kenrussell** [comment]
I'm a WebKit reviewer and committer, and applying the merge-queue label has worked for other PRs, so am confused why it's not working here.

**Comment by lexaknyazev** [comment]
Probably because of recent updates here: https://github.com/WebKit/WebKit/commits/main/.github/CODEOWNERS.

**Review by kenrussell — APPROVED** [review]
For the record, these changes look good to me too.

**Comment by kenrussell** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=243353 asking why `merge-queue` appears to not be working for this PR.

**Comment by kenrussell** [comment]
cc @JonWBedard .

**Comment by kenrussell** [comment]
Thanks for your help getting this processed.

@lexaknyazev , one of the Web Platform Tests (wpt) is failing:
`imported/w3c/web-platform-tests/html/canvas/element/manual/imagebitmap/imagebitmap-replication-exif-orientation.html`

https://ews-build.webkit.org/#/builders/74/builds/2068

If the test's incorrect, please follow the instructions on https://trac.webkit.org/wiki/WPTExportProcess for updating it and ping me or others on Slack if you need help. Thanks.

**Comment by lexaknyazev** [comment]
@kenrussell 
- This is a new test added a few days ago.
- Without this PR, it passes 2/8 assertions; with this PR, it passes 6/8.
- The `merge-queue` failed because of expectations mismatch.
- The PR was rebased and now includes updated expectations.

**Review by kenrussell — APPROVED** [review]
Great work @lexaknyazev . Let's try merge-queue again.

**Pull request merged**
