### PR TITLE
[LBSE] Fix dynamic-updates/SVGTextElement-svgdom-lengthAdjust-prop.html expectation

### PR DESCRIPTION
**Pull request by rwlbuis**
#### a7b6dd402d17c3661feb46b50a4a92436ba371d6
<pre>
[LBSE] Fix dynamic-updates/SVGTextElement-svgdom-lengthAdjust-prop.html expectation
<a href="https://bugs.webkit.org/show_bug.cgi?id=268752">https://bugs.webkit.org/show_bug.cgi?id=268752</a>

Reviewed by NOBODY (OOPS!).

Fix dynamic-updates/SVGTextElement-svgdom-lengthAdjust-prop.html expectation, the
old expectation has a strange artefact in the scrollbar.

* LayoutTests/platform/mac-sonoma-wk2-lbse-text/svg/dynamic-updates/SVGTextElement-svgdom-lengthAdjust-prop-expected.png:
</pre>
https://github.com/WebKit/WebKit/commit/a7b6dd402d17c3661feb46b50a4a92436ba371d6

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [  ~~🧪 style~~](https://ews-build.webkit.org/#/builders/38/builds/37881 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 ios~~](https://ews-build.webkit.org/#/builders/48/builds/16790 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/14/builds/40141 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/40425 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/32/builds/33705 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") 
| | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/19475 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/51/builds/14087 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/40425 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/11/builds/38452 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/49/builds/19475 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/14/builds/40141 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/5/builds/40425 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/49/builds/19475 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/14/builds/40141 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/2/builds/41696 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/49/builds/19475 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/14/builds/40141 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/2/builds/41696 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/12886 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/51/builds/14087 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/2/builds/41696 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/14465 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/14/builds/40141 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/13322 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/13917 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Comment by rwlbuis** [comment]
@nikolaszimmermann do you know if you had any setting to cause the scrollbar issue?

**Comment by Ahmad-S792** [comment]
> @nikolaszimmermann do you know if you had any setting to cause the scrollbar issue?

@rwlbuis - We don't need to fix it. I am getting rid of it in favor of WPT tests with PR: https://github.com/WebKit/WebKit/pull/23797

**Comment by rwlbuis** [comment]
> > @nikolaszimmermann do you know if you had any setting to cause the scrollbar issue?
> 
> @rwlbuis - We don't need to fix it. I am getting rid of it in favor of WPT tests with PR: #23797

Nice! Do you know the WPT equivalent? I am guessing i passes since the correct expected png was generated without the artefact.

**Comment by rwlbuis** [comment]
> > > > @nikolaszimmermann do you know if you had any setting to cause the scrollbar issue?
> > 
> > 
> > > 
> > 
> > 
> > > @rwlbuis - We don't need to fix it. I am getting rid of it in favor of WPT tests with PR: #23797
> > 
> > 
> > Nice! Do you know the WPT equivalent? I am guessing i passes since the correct expected png was generated without the artefact.
> 
> Yes - I listed it in commit message. It is with name 'lengthadjust'.
> 
> https://wpt.fyi/results/svg/text/scripted/lengthadjust.html?label=master&label=experimental&aligned&q=lengthadjust

Great, that one passes indeed (probably no scrollbar involved) so I will close this PR.

**Comment by nikolaszimmermann** [comment]
Ahmad, unfortunately, the scrollbar problems in those layout tests are known for a long while when pixel tests are used…Am 05.02.2024 um 18:52 schrieb Rob Buis ***@***.***>:﻿




@nikolaszimmermann do you know if you had any setting to cause the scrollbar issue?





@rwlbuis - We don't need to fix it. I am getting rid of it in favor of WPT tests with PR: #23797

Nice! Do you know the WPT equivalent? I am guessing i passes since the correct expected png was generated without the artefact.

Yes - I listed it in commit message. It is with name 'lengthadjust'.
https://wpt.fyi/results/svg/text/scripted/lengthadjust.html?label=master&label=experimental&aligned&q=lengthadjust

Great, that one passes indeed (probably no scrollbar involved) so I will close this PR.

**Comment by Ahmad-S792** [comment]
> Ahmad, unfortunately, the scrollbar problems in those layout tests are known for a long while when pixel tests are used…Am 05.02.2024 um 18:52 schrieb Rob Buis ***@***.***>:﻿ @nikolaszimmermann do you know if you had any setting to cause the scrollbar issue? @rwlbuis - We don't need to fix it. I am getting rid of it in favor of WPT tests with PR: #23797 Nice! Do you know the WPT equivalent? I am guessing i passes since the correct expected png was generated without the artefact. Yes - I listed it in commit message. It is with name 'lengthadjust'. https://wpt.fyi/results/svg/text/scripted/lengthadjust.html?label=master&label=experimental&aligned&q=lengthadjust Great, that one passes indeed (probably no scrollbar involved) so I will close this PR. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

I will see whatever I can delete or update. :-)

**Pull request closed without merging**
