### PR TITLE
[GTK] Bump GTK 4 API version to -6.0

### PR DESCRIPTION
**Pull request by mcatanzaro**
#### cd4c7d74bfbdcce1b21ceff5f5fbf773278a158a
<pre>
[GTK] Bump GTK 4 API version to -6.0
<a href="https://bugs.webkit.org/show_bug.cgi?id=245296">https://bugs.webkit.org/show_bug.cgi?id=245296</a>

Reviewed by Carlos Garcia Campos.

* Source/cmake/OptionsGTK.cmake:

Canonical link: <a href="https://commits.webkit.org/255953@main">https://commits.webkit.org/255953@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/2138d2d9ff5f474309a0067a474f972e5b194f1f

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/89882 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/34429 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/20548 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/99213 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/32920 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/28343 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/82218 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/93541 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95529 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/26145 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/76687 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/26070 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/81021 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/80853 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/69073 "Found 1 new API test failure: /WebKit2Gtk/TestWebViewEditor:/webkit/WebKitWebView/cut-copy-paste/non-editable (failure)") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/1/builds/81523 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/30668 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/14936 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/76400 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/30408 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/15877 "Passed tests") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/26461 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4113 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/33868 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/38834 "Passed tests") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/78986 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/32583 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/34961 "Passed tests") | [❌ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/17308 "Found 1 new JSC stress test failure: stress/call-apply-exponential-bytecode-size.js.mini-mode (failure)") |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Ping reviewers

**Comment by mcatanzaro** [comment]
@carlosgcampos do you still want to do this?

**Comment by carlosgcampos** [comment]
Yes, but maybe we should wait until we are sure we will be able to release the new API this cycle

**Comment by mcatanzaro** [comment]
> Yes, but maybe we should wait until we are sure we will be able to release the new API this cycle

I've been thinking about this... since all major distros have packaged this API already, it would be nice to avoid doing a double rename webkit2gtk-5.0 -> webkitgtk-5.0 -> webkitgtk-6.0. A single rename is bad enough. I suggest we merge this now and just try really hard to finish the API changes this cycle. (I think we can. It's going a lot slower than I expected, but at least I've made _some_ progress.)

**Comment by carlosgcampos** [comment]
Ok, let's try then.

**Review by carlosgcampos — APPROVED** [review]

**Pull request merged**
