### PR TITLE
Remove SVG1.1 `kerning` property

### PR DESCRIPTION
**Pull request by Ahmad-S792**
<pre>
Remove SVG1.1 `kerning` property
<a href="https://bugs.webkit.org/show_bug.cgi?id=262847">https://bugs.webkit.org/show_bug.cgi?id=262847</a>

Reviewed by NOBODY (OOPS!).

This patch is to align WebKit with Gecko / Firefox, Blink / Chromium and SVG2 Web Specification [1].

[1] <a href="https://svgwg.org/svg2-draft/single-page.html#text-KerningProperty">https://svgwg.org/svg2-draft/single-page.html#text-KerningProperty</a>

W3C Mailing List: <a href="https://lists.w3.org/Archives/Public/www-svg/2012May/0101.html">https://lists.w3.org/Archives/Public/www-svg/2012May/0101.html</a>

Inspired by: <a href="https://src.chromium.org/viewvc/blink?revision=171393&view=revision">https://src.chromium.org/viewvc/blink?revision=171393&view=revision</a>

* Source/WebCore/css/CSSProperties.json: Removed 'kerning'
* Source/WebCore/css/ComputedStyleExtractor.cpp:
(ComputedStyleExtractor::valueForPropertyInStyle):
* Source/WebCore/animation/CSSPropertyAnimation.cpp:
(CSSPropertyAnimation::CSSPropertyAnimationWrapperMap):
* Source/WebCore/css/SVGCSSComputedStyleDeclaration.cpp:
(ComputedStyleExtractor::svgPropertyValue):
* Source/WebCore/rendering/style/SVGRenderStyle.cpp:
(SVGRenderStyle::createDefaultStyle):
(SVGRenderStyle::SVGRenderStyle):
(SVGRenderStyle::operator==):
(SVGRenderStyle::inheritedEqual):
(SVGRenderStyle::inheritedFrom):
(SVGRenderStyle::changeRequiresLayout):
(SVGRenderStyle::conservativelyCollectChangedAnimatableProperties):
* Source/WebCore/rendering/style/SVGRenderStyle.h:
(SVGRenderStyle::setKerning):
* Source/WebCore/rendering/style/SVGRenderStyleDefs.cpp:
(StyleTextData):
* Source/WebCore/rendering/style/SVGRenderStyleDefs.h:
* Source/WebCore/rendering/svg/SVGTextLayoutEngine.cpp:
(SVGTextLayoutEngine::layoutTextOnLineOrPath):
* Source/WebCore/rendering/svg/SVGTextLayoutEngineSpacing.cpp:
(SVGTextLayoutEngineSpacing::calculateCSSKerningAndSpacing): Renamed to 'calculateCSSSpacing'
* Source/WebCore/rendering/svg/SVGTextLayoutEngineSpacing.h:
* Source/WebCore/svg/properties/SVGPropertyAnimatorFactory.h:
* Source/WebCore/svg/svgattrs.in:
* Source/WebCore/svg/SVGElement.cpp:
(SVGElement::cssPropertyIdForSVGAttributeName):

Test Rebaselines:

* LayoutTests/fast/css/getComputedStyle/resources/property-names.js: Rebaselined
* LayoutTests/svg/batik/text/textLayout-expected.txt: Ditto
* LayoutTests/svg/batik/text/textOnPathSpaces-expected.txt: Ditto
* LayoutTests/svg/css/getComputedStyle-basic-expected.txt: Ditto
* LayoutTests/svg/css/parse-calc-length-expected.txt: Ditto
* LayoutTests/imported/w3c/web-platform-tests/css/css-variables/variable-presentation-attribute-expected.txt: Ditto
* LayoutTests/imported/w3c/web-platform-tests/css/css-cascade/all-prop-revert-layer-expected.txt: Ditto
* LayoutTests/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/fast/css/getComputedStyle/resources/property-names.js: Ditto
* LayoutTests/fast/css/getComputedStyle/computed-style-without-renderer-expected.txt: Ditto
* LayoutTests/svg/css/parse-calc-length.html: Ditto
* LayoutTests/fast/css/getComputedStyle/computed-style-expected.txt: Ditto
* LayoutTests/svg/W3C-SVG-1.1/metadata-example-01-b-expected.txt: Ditto
* LayoutTests/platform/glib/svg/batik/text/textLayout-expected.txt: Ditto
* LayoutTests/platform/glib/svg/batik/text/textOnPathSpaces-expected.txt: Ditto
* LayoutTests/platform/gtk/svg/batik/text/textLayout-expected.png: Ditto
* LayoutTests/platform/gtk/svg/batik/text/textOnPathSpaces-expected.png: Ditto
* LayoutTests/platform/ios/svg/batik/text/textLayout-expected.txt: Ditto
* LayoutTests/platform/ios/svg/batik/text/textOnPathSpaces-expected.txt: Ditto
* LayoutTests/platform/mac/svg/batik/text/textLayout-expected.png: Ditto
* LayoutTests/platform/mac/svg/batik/text/textLayout-expected.txt: Ditto
* LayoutTests/platform/mac/svg/batik/text/textOnPathSpaces-expected.png: Ditto
* LayoutTests/platform/mac/svg/batik/text/textOnPathSpaces-expected.txt: Ditto
* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/platform/ios-wk2/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/platform/ipad/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/platform/wpe/imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml-expected.txt: Ditto
* LayoutTests/platform/mac-wk1/imported/w3c/web-platform-tests/css/css-cascade/all-prop-revert-layer-expected.txt: Ditto
</pre>

https://github.com/WebKit/WebKit/commit/55d502d4720c6748da7d2610b2a770b8cc7eff0b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/21482 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/21786 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/22536 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/23346 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/19908 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/21724 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/25091 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/22036 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/21102 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/21709 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/21343 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/18623 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/24197 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/18526 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/19473 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/25784 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/19613 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/19680 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/23633 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/20162 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/17169 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/19481 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/19290 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/23720 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/20068 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
If there will be any missing rebaselines, I will do it once EWS finishes tomorrow morning. :-)

**Review by nikolaszimmermann — COMMENTED** [review]
Thanks @Ahmad-S792 - technically the patch is fine. But this needs review by Apple, I'm not familiar with the procedure to remove already shipped features.

**Comment by shallawa** [comment]
In https://github.com/WebKit/WebKit/pull/13851, we discussed removing some other SVG features. And we agreed on placing these  features behind a preference analogues to what is done in https://commits.webkit.org/266068@main. I think we worry about iOS apps that may use these features.

Is there a problem in putting these features behind a preference? Or is the `kerning` property different from the `views` properties?

**Comment by Ahmad-S792** [comment]
> In #13851, we discussed removing some other SVG features. And we agreed on placing these features behind a preference analogues to what is done in https://commits.webkit.org/266068@main. I think we worry about iOS apps that may use these features.
> 
> Is there a problem in putting these features behind a preference? Or is the `kerning` property different from the `views` properties?

Personal Opinion: I think we should just delete it right away and revert if something broke. It is just 114 line of code and this feature was removed by Blink in 2014 and never implemented by Gecko. Plus it was broken implementation as per Blink notes (like incorrect letter spacing issue) and we have alternative in form of 'font-kerning'.

As for adding flag, last I checked with Aditya for totally different bug (focus on label related), the 'SDK' flag needs to be done by Apple developer so I will close this PR and leave reference to this PR for someone else to follow-up.

**Comment by annevk** [comment]
@Ahmad-S792 everything in the referenced commit can be done by a non-Apple developer and that will already disable it in STP. Making sure it's disabled in a future OS release for embedded applications requires an additional change that does need to be made by an Apple developer, but a follow-up issue can be filed for that. It might make sense to combine a couple SVG features.

**Pull request closed without merging**
