### PR TITLE
[GLib] Modernize Tools/glib/apply-build-revision-to-files.py

### PR DESCRIPTION
**Pull request by aperezdc**
#### d22439347db4083c729de2a07ebbd6b17797fc29
<pre>
[GLib] Modernize Tools/glib/apply-build-revision-to-files.py
<a href="https://bugs.webkit.org/show_bug.cgi?id=242191">https://bugs.webkit.org/show_bug.cgi?id=242191</a>

Reviewed by Jonathan Bedard and Philippe Normand.

* Tools/glib/apply-build-revision-to-files.py: Add Python 3 shebang,
  change imports to use webkitscmpy.
(get_revision_from_most_recent_git_commit): Deleted.
(get_build_revision): Use webkitscmpy instead of executing Git directly,
remove the cases which handled Subversion checkouts.

Canonical link: <a href="https://commits.webkit.org/252012@main">https://commits.webkit.org/252012@main</a>
</pre>

### CODE REVIEW

**Review by philn — COMMENTED** [review]
For the SDK build I ended up using `git webkit find HEAD -j | jq -r .identifier` to get the HEAD version. Maybe something similar can be done here?

**Comment by aperezdc** [comment]
> For the SDK build I ended up using `git webkit find HEAD -j | jq -r .identifier` to get the HEAD version. Maybe something similar can be done here?

Not a bad idea at all! I can make the output be piped back to Python, then use `json.loads()` there to grab the identifier so we don't even need to rely piping through `jq`.

**Comment by aperezdc** [comment]
> > For the SDK build I ended up using `git webkit find HEAD -j | jq -r .identifier` to get the HEAD version. Maybe something similar can be done here?
> 
> Not a bad idea at all! I can make the output be piped back to Python, then use `json.loads()` there to grab the identifier so we don't even need to rely piping through `jq`.

Even better: I ended up using `webkitscmpy` in the same way `git-webkit find` does.

**Review by philn — APPROVED** [review]
Nice!

**Review by JonWBedard — APPROVED** [review]

**Pull request merged**
