### PR TITLE
Potential crash fix by bailing from DeleteSelectionCommand::doApply when selection isn't editable

### PR DESCRIPTION
**Pull request by Ahmad-S792**
#### b83027e6d7d01b7ec451b6086430aed994c2ed12
<pre>
Potential crash fix by bailing from DeleteSelectionCommand::doApply when selection isn&apos;t editable

Potential crash fix by bailing from DeleteSelectionCommand::doApply when selection isn&apos;t editable
<a href="https://bugs.webkit.org/show_bug.cgi?id=248486">https://bugs.webkit.org/show_bug.cgi?id=248486</a>

Reviewed by Ryosuke Niwa.

Merge - <a href="https://src.chromium.org/viewvc/blink?view=revision&amp">https://src.chromium.org/viewvc/blink?view=revision&amp</a>;revision=190121

This patch is to harden the function doApply() by bailing early by ensuring the selection to delete is not editable.

* Source/WebCore/editing/DeleteSelectionCommand.cpp:
(DeleteSelectionCommand::doApply): Add condition about selection being non-editable
* LayoutTests/editing/execCommand/delete-non-editable-range-crash.html: Add Test Case
* LayoutTests/editing/execCommand/delete-non-editable-range-crash-expected.txt: Add Test Case Expectations

Canonical link: <a href="https://commits.webkit.org/257203@main">https://commits.webkit.org/257203@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/3f512d567b9722c6440da1d350e6f14eaa696dee

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/98026 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/7244 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/31185 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/107492 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/167770 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/101964 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/7723 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/36013 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/90694 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/104115 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/103678 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/5814 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/84634 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/32993 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/87683 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/89396 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/75927 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/1224 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/20828 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/1196 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/22334 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4960 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/6044 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/44787 "Found 1 new test failure: fast/images/animated-heics-draw.html (failure)") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/2488 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/41737 "Passed tests") | |

### CODE REVIEW

**Comment by rniwa** [comment]
I think we need a test for this.

**Comment by Ahmad-S792** [comment]
> I think we need a test for this.

I added the test from Blink's / Chromium's patch.

**Comment by rniwa** [comment]
> Add Test Case Expectations

You're adding the expected result for the test case, not test expectation. The latter has a specific meaning with regards to TestExpectations file.

**Review by rniwa — APPROVED** [review]
r=me

**Comment by Ahmad-S792** [comment]
> > Add Test Case Expectations
> 
> You're adding the expected result for the test case, not test expectation. The latter has a specific meaning with regards to TestExpectations file.

Noted. Thanks! Should I do updated pushed with new commit message?

**Pull request merged**
