### PR TITLE
[GLIB] Build fix for Debian 11 after 277538@main

### PR DESCRIPTION
**Pull request by dpino**
#### 9a65a6e43674a9e8c47de9cb48dc5dda0aab830b
<pre>
[GLIB] Build fix for Debian 11 after 277538@main
<a href="https://bugs.webkit.org/show_bug.cgi?id=272667">https://bugs.webkit.org/show_bug.cgi?id=272667</a>

Reviewed by NOBODY (OOPS!).

Function &apos;drmGetDeviceFromDevId&apos; is not available in libdrm version featured
in Debian 11 (2.4.104). The function is only available since 2.4.109.

* Source/WebKit/WPEPlatform/wpe/wayland/WPEDisplayWayland.cpp:
* Source/WebKit/WPEPlatform/wpe/wayland/WPEViewWayland.cpp:
(DMABufFeedback::drmDeviceForUsage):
* Source/cmake/OptionsGTK.cmake:
* Source/cmake/OptionsWPE.cmake:
</pre>
https://github.com/WebKit/WebKit/commit/9a65a6e43674a9e8c47de9cb48dc5dda0aab830b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/48093 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/27300 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/51026 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/50780 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/44156 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/33195 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/24798 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/39305 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/48676 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/24973 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/41584 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/20425 "Passed tests") | 
| | [⏳ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/iOS-17-Simulator-WPT-WK2-Tests-EWS "Waiting to run tests") | | [✅ 🛠 wpe-skia](https://ews-build.webkit.org/#/builders/52/builds/6148 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/41390 "Built successfully and passed tests") | [⏳ 🧪 api-ios](https://ews-build.webkit.org/#/builders/API-Tests-iOS-Simulator-EWS "Waiting to run tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/43195 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/52679 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/47587 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/23142 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/19494 "Found 1 new test failure: imported/w3c/web-platform-tests/html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/location-setter-during-load.html (failure)") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/46649 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/24406 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/41752 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/45515 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/25208 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/55082 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/24129 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/11328 "Passed tests") |

### CODE REVIEW

**Comment by carlosgcampos** [comment]
hmm, in this case since wpe-platform is new library, maybe it's better to require newer DRM (only for wpe-platform lib, not for all wpe). This is an important feature that we always want to be available, not silently disabled. Or maybe we can add an alternative code to get the device path, using udev for example. What do you think @alexgcastro ?

**Comment by dpino** [comment]
@carlosgcampos This is the patch that introduced `drmGetDeviceFromDevId` https://gitlab.freedesktop.org/mesa/drm/-/commit/57e0b0552. It renames `drmGetDevice2` to `drmGetDeviceFromDevId`. Function `drmGetDevice2` still exists but it fetches a deviceID from a file descriptor. I don't know if would be possible to use `drmGetDevice2` always.

**Comment by aperezdc** [comment]
Given that we do not need to support Debian 11 after June 2024, I think it's reasonable to just bump the required libdrm version to `>=2.4.109`&mdash;all other distributions we want to support already have a newer version of the library.

**Comment by dpino** [comment]
Now the Debian 11 build bot uses JHBuild minimal moduleset, which features `libdrm` 2.4.113, so this PR is no longer necessary.

**Pull request closed without merging**
