### PR TITLE
[WTF] Rename WTF::HashMap to WTF::UncheckedKeyHashMap (1/3)

### PR DESCRIPTION
**Pull request by zakariaridouh**
#### 6cf3bfbd01ba8185860895a44b724f0232e6b330
<pre>
[WTF] Rename WTF::HashMap to WTF::UncheckedKeyHashMap (1/3)
<a href="https://bugs.webkit.org/show_bug.cgi?id=281266">https://bugs.webkit.org/show_bug.cgi?id=281266</a>
&lt;<a href="https://rdar.apple.com/137717460">rdar://137717460</a>&gt;

Reviewed by Chris Dumez.

This is the first of 3 subsequent PRs to introduce a distinction between checked and unchecked key HashMaps in the WTF library.

This PR simply renames WTF::HashMap to WTF::UncheckedKeyHashMap.

* Source/JavaScriptCore/API/JSCallbackObject.h:
* Source/JavaScriptCore/API/JSClassRef.h:
* Source/JavaScriptCore/API/JSValue.mm:
* Source/JavaScriptCore/API/JSWrapperMap.mm:
(allocateConstructorForCustomClass):
* Source/JavaScriptCore/API/glib/JSCVirtualMachine.cpp:
* Source/JavaScriptCore/API/glib/JSCWrapperMap.h:
* Source/JavaScriptCore/assembler/AssemblyComments.h:
* Source/JavaScriptCore/assembler/JITOperationList.h:
* Source/JavaScriptCore/assembler/ProbeStack.h:
* Source/JavaScriptCore/b3/B3CanonicalizePrePostIncrements.cpp:
(JSC::B3::canonicalizePrePostIncrements):
* Source/JavaScriptCore/b3/B3DuplicateTails.cpp:
* Source/JavaScriptCore/b3/B3EliminateCommonSubexpressions.cpp:
* Source/JavaScriptCore/b3/B3FixSSA.cpp:
(JSC::B3::demoteValues):
* Source/JavaScriptCore/b3/B3FoldPathConstants.cpp:
* Source/JavaScriptCore/b3/B3LowerInt64.cpp:
* Source/JavaScriptCore/b3/B3LowerToAir.cpp:
* Source/JavaScriptCore/b3/B3LowerToAir32_64.cpp:
* Source/JavaScriptCore/b3/B3MoveConstants.cpp:
* Source/JavaScriptCore/b3/B3PureCSE.h:
* Source/JavaScriptCore/b3/B3ReduceStrength.cpp:
* Source/JavaScriptCore/b3/B3SSACalculator.h:
* Source/JavaScriptCore/b3/B3Validate.cpp:
* Source/JavaScriptCore/b3/air/AirAllocateRegistersAndStackAndGenerateCode.cpp:
(JSC::B3::Air::GenerateAndAllocateRegisters::insertBlocksForFlushAfterTerminalPatchpoints):
(JSC::B3::Air::GenerateAndAllocateRegisters::generate):
* Source/JavaScriptCore/b3/air/AirAllocateRegistersAndStackAndGenerateCode.h:
* Source/JavaScriptCore/b3/air/AirAllocateRegistersByGraphColoring.cpp:
* Source/JavaScriptCore/b3/air/AirDisassembler.h:
* Source/JavaScriptCore/b3/air/AirEmitShuffle.cpp:
(JSC::B3::Air::emitShuffle):
* Source/JavaScriptCore/b3/air/AirLowerAfterRegAlloc.cpp:
(JSC::B3::Air::lowerAfterRegAlloc):
* Source/JavaScriptCore/b3/air/AirSpecial.h:
* Source/JavaScriptCore/b3/air/testair.cpp:
* Source/JavaScriptCore/bytecode/CodeBlock.h:
* Source/JavaScriptCore/bytecode/DirectEvalCodeCache.h:
* Source/JavaScriptCore/bytecode/ExpressionInfo.h:
* Source/JavaScriptCore/bytecode/ICStatusMap.h:
* Source/JavaScriptCore/bytecode/LazyValueProfile.cpp:
* Source/JavaScriptCore/bytecode/LazyValueProfile.h:
* Source/JavaScriptCore/bytecode/PreciseJumpTargetsInlines.h:
(JSC::jumpTargetForInstruction):
* Source/JavaScriptCore/bytecode/PutByStatus.h:
* Source/JavaScriptCore/bytecode/SharedJITStubSet.h:
* Source/JavaScriptCore/bytecode/StructureStubInfo.h:
* Source/JavaScriptCore/bytecode/UnlinkedCodeBlock.h:
* Source/JavaScriptCore/bytecode/UnlinkedCodeBlockGenerator.cpp:
(JSC::UnlinkedCodeBlockGenerator::applyModification):
* Source/JavaScriptCore/bytecode/UnlinkedCodeBlockGenerator.h:
* Source/JavaScriptCore/bytecompiler/BytecodeGenerator.h:
* Source/JavaScriptCore/bytecompiler/NodesCodegen.cpp:
(JSC::PropertyListNode::emitBytecode):
* Source/JavaScriptCore/bytecompiler/StaticPropertyAnalyzer.h:
* Source/JavaScriptCore/debugger/Debugger.h:
* Source/JavaScriptCore/dfg/DFGArgumentsEliminationPhase.cpp:
* Source/JavaScriptCore/dfg/DFGAtTailAbstractState.cpp:
(JSC::DFG::AtTailAbstractState::forNode):
* Source/JavaScriptCore/dfg/DFGAvailabilityMap.cpp:
(JSC::DFG::AvailabilityMap::pruneHeap):
* Source/JavaScriptCore/dfg/DFGAvailabilityMap.h:
* Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:
* Source/JavaScriptCore/dfg/DFGCSEPhase.cpp:
* Source/JavaScriptCore/dfg/DFGClobberSet.cpp:
(JSC::DFG::ClobberSet::add):
(JSC::DFG::ClobberSet::addAll):
(JSC::DFG::ClobberSet::contains const):
* Source/JavaScriptCore/dfg/DFGClobberSet.h:
* Source/JavaScriptCore/dfg/DFGCommonData.cpp:
* Source/JavaScriptCore/dfg/DFGConstantHoistingPhase.cpp:
* Source/JavaScriptCore/dfg/DFGCriticalEdgeBreakingPhase.cpp:
(JSC::DFG::CriticalEdgeBreakingPhase::run):
* Source/JavaScriptCore/dfg/DFGDesiredIdentifiers.h:
* Source/JavaScriptCore/dfg/DFGDesiredWatchpoints.h:
* Source/JavaScriptCore/dfg/DFGDisassembler.cpp:
(JSC::DFG::Disassembler::createDumpList):
* Source/JavaScriptCore/dfg/DFGDisassembler.h:
* Source/JavaScriptCore/dfg/DFGForAllKills.h:
(JSC::DFG::forAllKilledNodesAtNodeIndex):
* Source/JavaScriptCore/dfg/DFGGraph.cpp:

remainder of files excluded from commit message.

Canonical link: <a href="https://commits.webkit.org/285277@main">https://commits.webkit.org/285277@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/bc009efa5fd753cce24a7594c3fddda77d5ff609

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/72075 "4 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/51495 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/24860 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/76240 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/23284 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/74190 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/59296 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/23104 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/56865 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 win-tests~~](https://ews-build.webkit.org/#/builders/60/builds/15373 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/75142 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/46688 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/62096 "Passed tests") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/41/builds/37303 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/71582 "Passed tests") | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/43351 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/19570 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/21634 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/65203 "Built successfully and passed tests") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/65256 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/19930 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/77920 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/71327 "Built successfully and passed tests") | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/16315 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/62/builds/19095 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/65340 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/16362 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/62119 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/64597 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/15927 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/12793 "Passed tests") | [  ~~🧪 mac-intel-wk2~~](https://ews-build.webkit.org/#/builders/119/builds/6442 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/93110 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/47293 "Built successfully") | [  ~~🛠 mac-safer-cpp~~](https://ews-build.webkit.org/#/builders/120/builds/2078 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/20502 "Found 3 new JSC stress test failures: stress/json-stringify-inspector-check.js.no-llint, stress/verbose-failure-dont-graph-dump-availability-already-freed.js.default, wasm.yaml/wasm/stress/cc-int-to-int-cross-module-with-exception.js.default-wasm (failure)") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/48362 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/49649 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/48106 "Built successfully") | | |

### CODE REVIEW

**Comment by mcatanzaro** [comment]
Huh, that looks like it was a huge endeavor. But why is this better than not renaming?

What will the new checked key hash map be called?

When developers want a hash map, the class they reach for should surely still be called `HashMap`, yes?

**Comment by cdumez** [comment]
> Huh, that looks like it was a huge endeavor. But why is this better than not renaming?
> 
> What will the new checked key hash map be called?

HashMap, it will be the default / safe HashMap, used in most places (eventually). UncheckedKeyHashMap will only be used in a few places that really require it for performance.

**Comment by mcatanzaro** [comment]
Well that's a good plan, but in that case I don't see the point in renaming everything now and then just renaming it all right back again later.

**Comment by cdumez** [comment]
> Well that's a good plan, but in that case I don't see the point in renaming everything now and then just renaming it all right back again later.

We need to progressively adopt the safer HashMap while monitoring perf. We had an earlier plan where we did the adoption in the other direction (keep HashMap and slowly adopt SafeHashMap) but then people complained about the name and the fact that "HashMap" should be safe by default. So now we're doing it the "hard" way. Yes, it is code churn but we need to improve our code safety and I don't wish to delay marking progress on this.

**Review by cdumez — APPROVED** [review]

**Pull request merged**
