### PR TITLE
TZone: Use TZone Allocation in WebKit Processes

### PR DESCRIPTION
**Pull request by msaboff**
#### ef13ba196f4d02aa6e40234ec54f06c4008e84d5
<pre>
TZone: Use TZone Allocation in WebKit Processes
<a href="https://bugs.webkit.org/show_bug.cgi?id=269418">https://bugs.webkit.org/show_bug.cgi?id=269418</a>
<a href="https://rdar.apple.com/122978759">rdar://122978759</a>

Reviewed by Justin Michaud.

Add TZone initialization to JSC ObjC API, JSC test tools and WebKit Processes.
Adds one TZone allocate class to WebKit, WebProcess.

Added new compile time flag USE_WK_TZONE_MALLOC, to separately control WebKit TZone allocation.
This patch has TZone allocation turned off via BUSE_TZONE in bmalloc/BPlatform.h and USE_TZONE_MALLOC in wtc/PlatformUse.h

* Source/JavaScriptCore/API/tests/testapi.c:
(main):
* Source/JavaScriptCore/API/tests/testapi.cpp:
(WTFTZoneInit): Deleted.
* Source/JavaScriptCore/JavaScriptCore.xcodeproj/project.pbxproj:
* Source/JavaScriptCore/Sources.txt:
* Source/JavaScriptCore/runtime/InitializeThreading.cpp:
(JSC::initialize):
* Source/JavaScriptCore/API/TZoneInit.cpp.
(TZoneInit):
(TZoneRegisterTypes):
(TZoneRegisterationDone):
* Source/JavaScriptCore/API/TZoneInit.h.
* Source/WTF/wtf/PlatformUse.h:
* Source/WTF/wtf/TZoneMalloc.h:
* Source/WTF/wtf/TZoneMallocInitialization.h:
* Source/WTF/wtf/TZoneMallocInlines.h:
* Source/WebKit/Shared/API/Cocoa/WKMain.h:
* Source/WebKit/Shared/API/Cocoa/WKMain.mm:
(WKXPCServiceMain):
* Source/WebKit/Shared/API/RegisterTZoneTypes.cpp: Added.
(WebKit::registerTZoneTypes):
* Source/WebKit/Shared/API/RegisterTZoneTypes.h: Added.
* Source/WebKit/Shared/EntryPointUtilities/Cocoa/AuxiliaryProcessMain.cpp:
(main):
* Source/WebKit/Sources.txt:
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Source/WebKit/WebProcess/WebProcess.cpp:
* Source/WebKit/WebProcess/WebProcess.h:
* Source/bmalloc/bmalloc/TZoneHeapManager.cpp:
(bmalloc::api::TZoneHeapManager::init):
(bmalloc::api::TZoneHeapManager::isReady):
(bmalloc::api::TZoneHeapManager::heapRefForTZoneType):
* Source/bmalloc/bmalloc/TZoneHeapManager.h:

Canonical link: <a href="https://commits.webkit.org/274825@main">https://commits.webkit.org/274825@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/5626de682c919843b8852aca6815f8ff6014e4f4

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/40096 "2 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/19108 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/42473 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/42641 "Built successfully") | [loading 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/36185 "Build is in progress. Recent messages:") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/22091 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/16437 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/33357 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/40670 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/16151 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/34634 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/13914 "Passed tests") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/14000 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/35583 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/43919 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/33549 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/36432 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/35918 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/39686 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/39722 "Built successfully and passed tests") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/14911 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/12236 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/37965 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/16530 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/46730 "Built successfully") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/9003 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/16579 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/9617 "Passed tests") | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/16174 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Comment by msaboff** [comment]
Need to fix non-Darwin builds.

**Comment by msaboff** [comment]
Posted updated PR with speculative build fix.

**Review by justinmichaud — APPROVED** [review]
r=me

**Comment by msaboff** [comment]
Pushed PR for landing

**Review by kmiller68 — CHANGES_REQUESTED** [review]
TZoneInit.h is marked public in this PR and included in the public JSC umbrella header but uses bmalloc types which is private. That can't be right.

**Comment by msaboff** [comment]
Testing changes that make TZoneInit.h private.  Will post new PR soon.

**Pull request merged**
