### PR TITLE
Update ANGLE to 2022-05-24 (8291f2d3e72eca3a25826b689a013c292ef4ba94)

### PR DESCRIPTION
**Pull request by kenrussell**
#### ea0448dfc61f8792116ce8e91b859a1d40d628ef
<pre>
Update ANGLE to 2022-05-24 (8291f2d3e72eca3a25826b689a013c292ef4ba94)
<a href="https://bugs.webkit.org/show_bug.cgi?id=240894">https://bugs.webkit.org/show_bug.cgi?id=240894</a>

Patch by Kenneth Russell &lt;kbr@chromium.org &gt; on 2022-05-25
Reviewed by Kimmo Kinnunen.

Contains upstream commits:
8291f2d3e Fix ValidCompressedSubImageSize for 3D uploads
84a0b462d Vulkan: Bug fix in GL_QCOM_shading_rate
1afb80587 Add Vulkan backend support for texture labels
7a243dbe2 Capture/Replay: Allow repeated Gen-on-Bind for resources
7df1f5816 GN: Add angle_build_tests.
11e9c8351 Vulkan: Dump graphics pipeline cache graph
2f0b6429b Revert &quot;util/X11Window: Set PMinSize and PMaxSize hints.&quot;
cd48eedd9 Roll Chromium from 99a468a0505d to d624307d6d25 (438 revisions)
35e54dbb6 Vulkan: Fix EXT_texture_buffer support condition
f6c149339 dEQP: Support Wayland
6e2588639 Vulkan: Use packed enum for present modes
9e0a7be6c Traces: Update restricted_trace_perf.py
2ae8bdb3a Roll vulkan-deps from 880c9e0050c6 to 82a65519c521 (5 revisions)
80be1bb38 Roll SwiftShader from 73679602bc0b to b5cb037f0292 (2 revisions)
2db4297ad Roll Chromium from f0d8ec07c77f to 99a468a0505d (698 revisions)
e4a517c92 Vulkan: Rearrange GraphicsPipelineDesc to reduce footprint
f52c629b9 Capture/Replay: Make sure replay tests build libEGL
0b808c746 Silence all std::iterator deperecation warnings
bb3afdf42 Drop support for 64xMSAA+
688553c03 Vulkan: Dynamic state for primitive restart enable
c76fb2d82 Enable EXT_texture_norm16 on ES2/D3D11
3b78e0d56 Vulkan: Dynamic state for depth bias enable
7c83a3635 Vulkan: Dynamic state for rasterizer discard enable
2faabfe5e Vulkan: Optimize pipeline desc w.r.t dynamic state
ee1894e5f Account for GL_ANGLE_yuv_internal_format when setting yuv state
3da24b5cd Move trace loader code to a common location.
52c42e5a8 Temporarily disable deprecation warnings for VK-GL-CTS
88f582f6a D3D: fix whole-array assignment to SSBOs.
f8e8b7cc3 Roll vulkan-deps from c37d1e2ab98c to 880c9e0050c6 (19 revisions)
8af51b7ef Roll SwiftShader from 2933d3126969 to 73679602bc0b (4 revisions)
c3687f079 Roll Chromium from 170d12460fd5 to f0d8ec07c77f (430 revisions)
58fd31577 Vulkan: Dynamic state for vertex stride
e71a3e5fa Insert Metal polyfill for Matrix /= Scalar when needed
78ea85213 Suppress Flaky Tests
af869f4ac Update capture replay expectation file
118a6484c Metal: Upstream buffer cache fix from WebKit
f674e501f Tests: Add Bridge Constructor Portal trace
728dea2be Suppress Vulkan Validation Error
40269f91c Fix trigger.py to run mb.py with python3
c7182af2b Vulkan: Reserve varying for xfb if pre-rotation is enabled
86074fc77 Roll Chromium from dbb1f3a2b2f7 to 170d12460fd5 (586 revisions)
54a6b76f6 Roll third_party/rapidjson/src/ 7484e06c5..781a4e667 (156 commits)
2fd7444bc Fetch gn binary for the correct architecture on linux.
06fa297b6 Roll SwiftShader from cb4fc6d02fe4 to 2933d3126969 (1 revision)
6ae0c3214 Vulkan: clamp dynamic line width to supported values
d3eb61d4a D3D11: fix SSBO load in a return statement.
28dfa45d6 Spawn via vpython when old module detected.
b7474d0ae D3D11: Add GL_EXT_texture_buffer support
87ea0c7df Vulkan: SPIR-V Gen: Apply Flat to gl_Layer in FS
8701f53a4 Vulkan: Fix clear value for incomplete MS textures
dbeba9004 Reland &quot;CGL, MTL: pbuffer for IOSurface fails for some formats&quot;
b4ec8eac5 D3D11: implement image load/store for non-compute shaders.
2fdd7bfd1 Vulkan: Support binding 2D slice of a 3D texture to an image unit
14ca09bcf Metal: Remove the long type from program preludes
ff011779c Vulkan: Let texture buffer handle BufferVk&apos;s storage change
3d430f5f3 Vulkan: Add test for texture buffer and buffer data interaction
2abf9adf6 Vulkan: Bug fix in YUV descriptor pool allocation
78b8f5467 Roll SwiftShader from 89eb09307fbc to cb4fc6d02fe4 (1 revision)
428cd884e Tests: Add Stardew Valley trace
5e34541a1 Roll SwiftShader from 4011ab35f3d8 to 89eb09307fbc (3 revisions)
4dc9c79e0 Roll Chromium from 73ffbbeac851 to dbb1f3a2b2f7 (503 revisions)
c649979b7 Create EGLImage from VkImage correctly with non sized format
cd4cce3f8 Add more tips about recovering the qpa file.
957a44f41 Clarify that angle_debug_package is necessary to load the apk
93c0c90db Suppress the failing egl test to unblock roller
a277f1bce Vulkan: Fix Wayland surface size queries
6136ba273 D3D: minor cleanup of gl::RangeUI usage.
4ece3b08f Vulkan: Multiple DRM formats
d75bf9ad0 Capture/Replay: Also limit the number of per shader SSBOs
552b01d15 Roll vulkan-deps from 131de3fd9ec7 to c37d1e2ab98c (2 revisions)
7d7ed2538 Roll Chromium from 11b60f867851 to 73ffbbeac851 (445 revisions)
807c94ea8 Capture/Replay: Adjust tests do adhere to capture limits
891a46820 Vulkan: Dynamic state for stencil test/op
66dcca5e5 Vulkan: Dynamic state for depth test/write/op
bedb3075b Do not call RendererVK::handleDeviceLost() for device lost
15ecf068e Vulkan: Dynamic state for depth bounds
20820bb4b Make BitSetArray constexpr
36f5e6ce5 Vulkan: Fix DRM to GL format conversion
1cbcc1da1 Roll vulkan-deps from c6a60f3cc711 to 131de3fd9ec7 (22 revisions)
459c367ed D3D: Initialize storage after generating mipmap images.
ed909ee8a Roll SwiftShader from f1c2c0b07281 to 4011ab35f3d8 (1 revision)
7f14dd79b Roll Chromium from 3aa3e39b0aca to 11b60f867851 (666 revisions)
48b1f07b0 Vulkan: Dynamic state for front face
4e5da2d28 Vulkan: Dynamic state for cull mode
62fe36d3b Vulkan: Emulate YUV built-ins
4b95ac7df Vulkan: Don&apos;t invalidate pipeline on dynamic state change
81c84292f Do not do cleanup for Vulkan device lost
808192a74 Code Cleanup
87058cb8a Re-skip flaky test un-skipped by crrev.com/c/3641181
1b434e96b Skip flaky test on Mac NVIDIA.
4a7dd9429 Metal: Fix dangling pointer warning in IntermRebuild.cpp
e56f227d6 Vulkan: Add case: TextureSampleByDrawDispatchDraw
ece8fb5df Roll vulkan-deps from b768d03422ea to c6a60f3cc711 (1 revision)
03ccd9cc9 Revert &quot;Vulkan: Flush texture updates more often&quot;
21ad9b3c8 Vulkan: Add generic descriptors for DS cache.
d8d396dbc Vulkan: Add shared descriptor set caches.
0f2fc7664 TracePerfTest: Add ability to screenshot after reset.
7dc316c8f Roll Chromium from 65b23f3c9e05 to 3aa3e39b0aca (497 revisions)
8bb7c35c2 Vulkan: Flush texture updates more often
addfab1f7 Update docs for SwANGLE triage process.
8e844d0ff Tests: Add Black Desert Mobile trace.
389ae6b9a Add extension for read-only DS feedback loops.
40583b0f9 Tests: Skip pubg_mobile_skydive on Nvidia
4df8ca04f Remove angle_util from restricted traces.
580f90c7d Test Runner: Accept Chromium bot mode flag.
73cb1e6e2 Vulkan: Tag dynamic dirty bits with DYNAMIC
4ffab3bf5 Vulkan: Dynamic state for stencil reference
3d55cf0c0 Vulkan: Optimize the vkImage layout when used as GL_image
7e9e597ea Roll SwiftShader from e0a1188d7652 to f1c2c0b07281 (2 revisions)
8ec7b8b87 Roll Chromium from 693c7419bd5c to 65b23f3c9e05 (580 revisions)
1d8227dab Vulkan: Dynamic state for stencil write mask
c3def6fab Vulkan: Dynamic state for stencil compare mask
e9dc0f86d Cleanup from glBlitFramebuffer() 3D texture fix.
dcaa18b9c Vulkan: Dynamic state for blend color
536d6f57e Vulkan: Dynamic state for depth bias
42789b630 Use GLTexture in TextureTest for RAII goodness.
780f1a41b Vulkan: Dynamic state for line width
9b15e1c23 D3D11: clean up ES31 test expectations.
f6610106f Add a draw call perf test for changing a single uniform.
e73121b19 Vulkan: Fix VulkanPipelineCachePerfTest
dd9b4afe5 D3D: minor cleanup for image load/store.
1fa4442ba Vulkan: Set dynamic state after binding pipeline
089f2871b PerfTests: Add support for eglCreateImage and eglDestroyImage
5b623dd4b D3D9: Enable OES_fbo_render_mipmap
25ebc3b86 Roll vulkan-deps from 27ef4a0d9701 to b768d03422ea (7 revisions)
eea6366c7 Roll SwiftShader from e4a6f2d74d3c to e0a1188d7652 (1 revision)
029a4c948 util: Add calls for createImage* and destroyImage* to GLWindow
486ae89e4 Roll Chromium from 46c13be19f0f to 693c7419bd5c (567 revisions)
a8ebdf2b5 Basis Universal Texture Experiment
6ddbfa397 Metal: Log the shader source when a shader fails to translate
52904367d D3D: Mark images clean after syncing from storage
f1640db8c Fix crash when calling certain gl APIs before initialization.
66b9214fb Capture/Replay: rename ANGLE_CAPTURE to ANGLE_CAPTURE_GL
2fb58a95b Re-land: &quot;Vulkan: GBM platform&quot;
4ecb1e3e6 Vulkan: Support wide lines
18089dff2 Vulkan: Clean up flag passing in ImageView init.
8e1215716 D3D11: fix 3D texture blits.
464f30f4e Vulkan: Refactor UtilsVk dynamic state handling
86d9d66dc Vulkan: Determined sized-ness of format in initImageViews.
9872c1d63 Switch deqp merge to python3
5fa8f9045 Roll vulkan-deps from 626b2fd72bde to 27ef4a0d9701 (2 revisions)
c8c2664af Roll SwiftShader from 1dd93361b1d9 to e4a6f2d74d3c (2 revisions)
6bf0e620a Roll Chromium from 7f78f00fdc5c to 46c13be19f0f (273 revisions)
2b8172b9b Vulkan: Add missing initialization for mTotalMemorySize
31321cb73 Vulkan: Remove suppressions and workarounds for old AMD/Windows
0db4c39b5 Revert &quot;Vulkan: GBM platform&quot;
26a2e1471 Roll Chromium from bc117969dbb5 to 7f78f00fdc5c (162 revisions)
d4442f538 Reset the program executable if async linking fails.
825d5b2c5 Vulkan: GBM platform
0b0744f3e Vulkan: Fix VVL error for black desert mobile
b51bbe246 Add CopyTextureTest.ClearAfterCopySubTexture
b54b11460 Vulkan: Use ImageView layer count functions in TextureVk.
c8c4109cd HLSL: Disambiguate functions that have int/uint parameters.
e1de0950d Vulkan: Always init image views using image format.
8b4e74127 Roll SwiftShader from 74e34ab97aeb to 1dd93361b1d9 (3 revisions)
78d88796b Roll Chromium from 333c8248b125 to bc117969dbb5 (506 revisions)
e316203a6 Vulkan: add forceContinuousRefreshOnSharedPresent feature
225d8f83a Tests: Add Mortal Kombat App Trace
fa4523cf2 Roll vulkan-deps from 4ca7acf89869 to 626b2fd72bde (22 revisions)
cadb933fd Roll Chromium from 3bc34dd4d819 to 333c8248b125 (124 revisions)
1d073482a Tests: Add Basemark GPU trace
38a53d654 Revert &quot;Remove limit_max_texture_size_to_4096 workaround&quot;
bec809fe9 [Fuchsia] Download the gn sdk instead of core
5f2ad1537 Tests: Add Puzzles and Survival trace
b33d15556 Roll VK-GL-CTS from 106df4122297 to acf70aaf3fdb (12 revisions)
950db602b Roll SwiftShader from 643179694ec7 to 74e34ab97aeb (7 revisions)
dbbfac650 Tests: Add Monument Valley trace
b365a6069 Tests: Add Dead Cells trace
72cc8cbca Migrate Fuchsia sdk checkout from using script to CIPD
e0d00563f Vulkan: Simplify external format Chroma code.
51d6a1d96 Roll Chromium from 617cd3226543 to 3bc34dd4d819 (40 revisions)
a78eca2ca util/X11Window: Set PMinSize and PMaxSize hints.
332c9ad04 Roll Chromium from 7a60295b6324 to 617cd3226543 (278 revisions)
1d5d09e41 Vulkan: Prefer MAILBOX over IMMEDIATE present mode
d075dfe25 Vulkan: Reduce kMaxBufferToImageCopySize to 64M
333da2cf1 Vulkan: Limit the total bytes of suballocation garbages in flight
98488a196 FramebufferTest: Add FramebufferChangeTest test.
b79178a3e Scripts: Strip prebuilt debug APK from AOSP roll
8dcba9ae6 Roll Chromium from 1c301e690de1 to 7a60295b6324 (184 revisions)
51dc3c3e6 Vulkan: Force prune when there are lots of suballocations destroyed
bcc03bd62 Remove limit_max_texture_size_to_4096 workaround
2fae9482c Vulkan: Use heuristic to decide how many empty buffers to keep
0afa5b9f9 Tests: Add Alto&apos;s Odyssey trace.
2ce60b52a Fixes for C++20 support.
3f216ee74 Vulkan: Set timeout for MultiContextDrawWithSwap*
bd44b29d2 Roll Chromium from 6db3a94387ed to 1c301e690de1 (550 revisions)
d73468673 Decommission win7-x86-amd and win7-x64-nvidia
9865ed8b8 Check in //build files needed.
9053a641b Vulkan: Wayland dmabuf extensions
77cd0b5a3 Re-land: &quot;Vulkan: Cache ImageView serials on texture changes.&quot;
b72cff8c0 Fix build flags not in declare_args when angle_has_build is true
14c483f1c Presubmit: Verify comment before new tests
dc1ab34c9 Roll SwiftShader from cdf43bd816d7 to 643179694ec7 (4 revisions)
34fb4f790 Roll Chromium from 55c89a3a09ac to 6db3a94387ed (508 revisions)
edd331ebe Traces: Add a device arg to restricted_trace_perf
a7238b525 Consolidate handle list before pushing to mReleasedList
064fc64aa infra: Remove some slow *SAN tests.
9ab470749 D3D11: fix BufferToTexture copy when UNPACK_ROW_LENGTH is set.
9ad43bdd2 Re-land: &quot;Vulkan: Support Wayland&quot;
5c9f676d3 Basis Universal Texture Experiment
84e42c3b0 Fix validation cache when deleting a Transform Feedback.
b5f0fd1bd Skip flaky tests on Win ASAN
c0942c2d4 Roll vulkan-deps from 1cde45b8d7aa to 4ca7acf89869 (6 revisions)
c92d69d7d Roll SwiftShader from adef92e7b4c6 to cdf43bd816d7 (8 revisions)
4bbc55f4c Revert &quot;Re-land: &quot;Vulkan: Support Wayland&quot;&quot;
58526dea2 Roll Chromium from 929311ac6298 to 55c89a3a09ac (470 revisions)
5113ae8ef Vulkan: Explicitly enable per-sample shading if `sample` used
9200ba537 Reland &quot;Make SPIRV optional for Metal backend&quot;
802504add Vulkan: Add log for buffer pool stats
4d26c66d0 Vulkan: Call cleanupGarbage only if mLastCompletedQueueSerial changed
527557b9c Fix ValidateFramebufferTextureLayer for cubemap arrays
e6662832a Re-land fixing of commit ID for Android builds.
3e05b93af Vulkan: MSAA swapchain resolve based on renderArea
c6e6e284e Update Android deqp and end2end sharding
237479a27 Fix presubmit following <a href="https://crrev.com/c/3611486">https://crrev.com/c/3611486</a>
bc929e6e5 D3D11: recompile all shaders using 10.0.20348.0 toolchain.
b953bc13e Tests: Add GFXBench Tessellation trace
f7615d0ad OpenGL: Add allow_astc_formats workaround
4dc4c0f05 Remove whitespace from features json files
df163d714 Test both MSL translators in APPLEClipDistanceTest
06fa7e39a Expand Intel GPU detection
e0dd196a0 Re-land: &quot;Vulkan: Support Wayland&quot;
ea9a2dbea Capture/Replay: handle glGetVertexAttrib parameter value
41adabc48 Use app data dir instead of /sdcard for writing qpa file
5b4f180cd Fix formatting
f1c5e2b11 Roll vulkan-deps from 7b51f5f85aad to 1cde45b8d7aa (4 revisions)
fd57d8f0c Roll Chromium from 3a1ff9044aec to 929311ac6298 (541 revisions)
e55990e35 Capture/Replay: Handle arrays with uniform block indices
1aa4c120d gl_tests: Fix formatting
c7a9f0c6c Vulkan: Remove syncval suppressions no longer triggering
e39dfe0fe Roll VK-GL-CTS from a22069b4e3b7 to 106df4122297 (1 revision)
3eb2bcf77 Vulkan: Fix syncval errors with DONT_CARE for unused attachments
3eb891960 Roll Chromium from 1e97e6cd1c3c to 3a1ff9044aec (639 revisions)
31f841386 Add option for Metal output to angle_shader_translator
394fb0d34 Vulkan: Don&apos;t take lock for getLastCompletedQueueSerial
5e4c141c2 Tests: Add GFXBench Driver Overhead 2 trace
7184fe38c Tests: Add Jetpack Joyride trace.
8b26c14c0 Roll SwiftShader from b92f7acb7e81 to adef92e7b4c6 (4 revisions)
2d3ad8ec6 Roll vulkan-deps from 1963b94c99e8 to 7b51f5f85aad (4 revisions)
1c4c9fe95 Capture/Replay: Fix formatting
2c58e7a5b Reduce console spam from Metal shader translation
437053a16 Revert &quot;Make SPIRV optional for Metal backend&quot;
f9729598a Revert &quot;Fix commit ID gathering on Android builds.&quot;
c1d0e139d Roll vulkan-deps from 4f93dbdc6060 to 1963b94c99e8 (2 revisions)
d5ceba0b4 Roll SwiftShader from f88fc3b53c52 to b92f7acb7e81 (3 revisions)
3e4069290 Roll Chromium from c7e51a124fab to 1e97e6cd1c3c (915 revisions)
2a6e123b1 Vulkan: Move pruneOrphanedBufferBlocks to last
266111a55 Vulkan: Fix SemaphoreCount best practice warning
1ef90012b Vulkan: Remove API access for mTotalBufferToImageCopySizen
454efd1d5 Add forceDepthAttachmentInitOnClear frontend workaround
29287e1fc Make SPIRV optional for Metal backend
3b65b8037 Vulkan: Work around Qualcomm imprecision with dithering
6c2486918 Enable SINGLE_BUFFER with eglCreateWindowSurface
1835e5d89 Fix commit ID gathering on Android builds.
c9794d6c0 Run a smoke test in each shard and crash on timeouts.
80d50b992 Add build arg to automatically attach renderdoc
7d31a47fc Vulkan: Optimize away eglSwapBuffers for single buffer surfaces
5c756bc1a Perf Tests: Compute GPU time periodically
c402f002b Android perf tests shards 20- &gt;6 (only --smoke-test-mode)
6930184ef Log runTests so that it shows up in logcat dumps.
c45aff4f2 Roll SwiftShader from 5f5faa3a2aad to f88fc3b53c52 (4 revisions)
cc834907f Roll vulkan-deps from f685346e2e51 to 4f93dbdc6060 (2 revisions)
95c1ff52b EGL: Fix EGL_KHR_mutable_render_buffer
0c59b5d90 Log debuggerd $PID output when instrumentation gets stuck.
fe2c82ad3 check integer overflow in Texture copyImage
cdcf17153 Add missing result_skip and result_fail.
1a144edfe Metal:ReadPixels AMD Copy Texture to Buffer optimization
6b9c5c8d1 Vulkan: Improve GetStorageMemoryType logic
cbdefd933 Roll chromium_revision 192db13f85..c7e51a124f (995097:996181)
d0c8363e0 Dump logcat if instrumentation doesn&apos;t finish in 10 minutes.
ebfb9b9f0 Configure logging in perf and gold tests to include time.
7555a1590 DEPS: Remove deprecated chromium dep
fc8282875 Tests for Nvidia/Vulkan bugs with tessellation control

Canonical link: <a href="https://commits.webkit.org/250984@main">https://commits.webkit.org/250984@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@294834">https://svn.webkit.org/repository/webkit/trunk@294834</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by kenrussell** [comment]
Please note that the style failures are expected; the compiled shaders in ANGLE's D3D backend have Windows line endings. We don't want to change these from upstream, as doing so introduces merge conflicts during every ANGLE update into WebKit.

**Comment by kenrussell** [comment]
Note also that Kyle points out he has another critical bug fix incoming in https://bugs.webkit.org/show_bug.cgi?id=240896 , so maybe I should redo this roll after he's landed that.

**Comment by kenrussell** [comment]
cc @greggman

**Review by kkinnunen-apple — APPROVED** [review]
Let's try to merge even with the style errors

**Comment by kenrussell** [comment]
We're going to deliberately bypass the style check, as changing the line endings in the noted files is problematic for future ANGLE rolls, and the test failure on win is unrelated. Landing.

**Comment by kenrussell** [comment]
Not clear to me whether the merge-queue label had no effect because of the style failures we've agreed we want to bypass, and the only layout test failure is unrelated. Adding unsafe-merge-queue.

**Pull request merged**
