### PR TITLE
Always use percentages for computed values of font-stretch, never keywords

### PR DESCRIPTION
**Pull request by darinadler**
#### b724d37d49cae06de4633efc4b468500f40f0ce3
<pre>
Always use percentages for computed values of font-stretch, never keywords
<a href="https://bugs.webkit.org/show_bug.cgi?id=247008">https://bugs.webkit.org/show_bug.cgi?id=247008</a>
rdar://problem/101546363

Reviewed by Tim Nguyen.

<a href="https://drafts.csswg.org/css-fonts/#propdef-font-stretch">https://drafts.csswg.org/css-fonts/#propdef-font-stretch</a>

Current CSS Fonts Module Level 4 says computed values are always serialized as a percentage.
This is a change since CSS Fonts Module Level 3 which said they should be computed &quot;as specified&quot;.
Web Platform Tests currently has a mix; this updates tests to consistently expect the new form.

* LayoutTests/fast/css/getComputedStyle/computed-style-font-family-expected.txt:
Updated to expect &quot;100%&quot; instead of &quot;normal&quot;.

* LayoutTests/fast/text/font-stretch-parse-expected.txt: Updated.
* LayoutTests/fast/text/font-stretch-parse.html: Updated to expect percentages.

* LayoutTests/fast/text/variations/out-of-bounds-selection-properties-expected.txt:
* LayoutTests/fast/text/variations/out-of-bounds-selection-properties.html:
Updated to expect &quot;100%&quot; instead of &quot;normal&quot;.

* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/animations/font-stretch-interpolation-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/animations/font-stretch-interpolation.html:
Updated to expect percentages instead of keywords.

* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/animations/system-fonts-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/inheritance-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/parsing/font-stretch-computed-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/variations/font-stretch-expected.txt:
Updated for more PASS.

* LayoutTests/imported/w3c/web-platform-tests/css/css-variables/variable-presentation-attribute-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-variables/variable-presentation-attribute.html:
Updated to expect percentages instead of keywords.

* LayoutTests/platform/gtk/imported/w3c/web-platform-tests/css/css-fonts/animations/system-fonts-expected.txt:
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/css/css-fonts/animations/system-fonts-expected.txt:
* LayoutTests/platform/wpe/imported/w3c/web-platform-tests/css/css-fonts/animations/system-fonts-expected.txt:
Updated for more PASS.

* Source/WebCore/css/ComputedStyleExtractor.cpp:
(WebCore::fontStretch): Removed code path that checks for and uses keywords.

Canonical link: <a href="https://commits.webkit.org/256094@main">https://commits.webkit.org/256094@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/1cfaa6432f9025ec10fc7726fe034d17409cec1b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/94513 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/3691 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/27418 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/104167 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/164439 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/98511 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/3743 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/31887 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/86841 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/100138 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/100183 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/2689 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/80904 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/29719 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/84614 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/84183 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/72613 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/38288 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/18007 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/36152 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/19280 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4207 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/40051 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/41923 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/42004 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/38510 "Passed tests") | |

### CODE REVIEW

**Review by nt1m — APPROVED** [review]
Looks good, would have been nice to include the spec reference in the commit message.

**Comment by darinadler** [comment]
> Looks good, would have been nice to include the spec reference in the commit message.

OK, did that.

**Comment by darinadler** [comment]
@nt1m This includes some fixes for erroneous Web Platform Tests. Could you remind me again how to create a WPT pull request for them? I tried using the `export-w3c-test-changes` but couldn’t remember exactly how to use it. Do we have any webpages with instructions?

**Comment by nt1m** [comment]
> @nt1m This includes some fixes for erroneous Web Platform Tests. Could you remind me again how to create a WPT pull request for them? I tried using the `export-w3c-test-changes` but couldn’t remember exactly how to use it. Do we have any webpages with instructions?

If you're on the right WebKit branch locally, you can run `export-w3c-test-changes -g HEAD -b BUGZILLA_ID -c --no-linter`. There is https://trac.webkit.org/wiki/WPTExportProcess, but some of it is out of date since the Github transition.

**Comment by darinadler** [comment]
https://github.com/web-platform-tests/wpt/pull/36714

**Pull request merged**
