### PR TITLE
[GTK] Layout tests with ANGLE backend require to use GLX to make Xvfb and software rasterization work

### PR DESCRIPTION
**Pull request by alexgcastro**
#### 7edb06686319c608d0b996e1ad391534a27fe653
<pre>
[GTK] Layout tests with ANGLE backend require to use GLX to make Xvfb and software rasterization work
<a href="https://bugs.webkit.org/show_bug.cgi?id=245288">https://bugs.webkit.org/show_bug.cgi?id=245288</a>

Reviewed by NOBODY (OOPS!).

Gtk layout tests are using Xvfb and software rasterization, this is detected and uses the X11
backends and GLX in WebKit, we need to make sure we have the GLX backend compiled for ANGLE and
we use it in GTK for the GraphicsContextGLFallback class. That solves crashes in the Layout tests
for WebGL with ANGLE.

* Source/ThirdParty/ANGLE/CMakeLists.txt: Compile GLX backend when using
  gtk if x11 is enabled.
* Source/ThirdParty/ANGLE/PlatformGTK.cmake: Add compilation options for
  x11, use platform types in that case.
* Source/WebCore/platform/graphics/gbm/GraphicsContextGLFallback.cpp:
(WebCore::GraphicsContextGLFallback::platformInitializeContext): In case
of gtk and x11 enabled we configure the display to use the ANGLE GLX backend.
</pre>
https://github.com/WebKit/WebKit/commit/7edb06686319c608d0b996e1ad391534a27fe653

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/90056 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/34603 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/20685 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/99384 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/156888 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/94062 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/33094 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/28463 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/82388 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/93680 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95704 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/26307 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/76862 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/26208 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/81160 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/80957 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/69209 "Found 4 new API test failures: /WebKit2Gtk/TestLoaderClient:/webkit/WebKitWebPage/redirect-to-data-uri, /TestWTF:WTF_WordLock.ManyContendedLongSections, /WebKit2Gtk/TestWebKitVersion:/webkit/WebKitVersion/version, /WebKit2Gtk/TestWebKitAccessibility:/webkit/WebKitAccessibility/accessible/children-changed (failure)") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/66/builds/34286 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/15039 "Passed tests") | | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/67/builds/32127 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/15980 "Passed tests") | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/63/builds/35871 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/38942 "Passed tests") | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/65/builds/37772 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/35064 "Passed tests") | |

### CODE REVIEW

**Review by mcatanzaro — CHANGES_REQUESTED** [review]
Hm, it's OK for some things to be different in developer mode, but forcing GLX is pretty extreme. It means we'll have a different set of graphics bugs in developer mode than our users will encounter. And frankly, we have a lot of graphics bugs. This seems like too much: if developers get forced into a legacy graphics mode, we'll fail to notice bugs before users complain, and will have increased difficulty reproducing bugs that users report.

It's also moving backwards. GLX is a legacy technology, and I understand that nowadays using EGL instead of GLX is recommended even under X11, right?

Ideally, we'd stop using Xvfb for layout tests and use Weston instead, but I understand that would probably require a bunch of rebaselining.

**Comment by alexgcastro** [comment]
> Hm, it's OK for some things to be different in developer mode, but forcing GLX is pretty extreme. It means we'll have a different set of graphics bugs in developer mode than our users will encounter. And frankly, we have a lot of graphics bugs. This seems like too much: if developers get forced into a legacy graphics mode, we'll fail to notice bugs before users complain, and will have increased difficulty reproducing bugs that users report.
> 

I agree, but in this case we are choosing using GLX inside ANGLE because WebKit is already using GLX for rendering, that is the problem,  we are using GLX already and ANGLE was forcing EGL backend, I mean we need to use GLX for ANGLE because tests were already using it. It is not that we are changing that.

> It's also moving backwards. GLX is a legacy technology, and I understand that nowadays using EGL instead of GLX is recommended even under X11, right?
> 
> Ideally, we'd stop using Xvfb for layout tests and use Weston instead, but I understand that would probably require a bunch of rebaselining.

Exactly I would love we stop using Xvfb but that is a different task, I don't think we should block bugs waiting for that.

**Comment by mcatanzaro** [comment]
> I agree, but in this case we are choosing using GLX inside ANGLE because WebKit is already using GLX for rendering, that is the problem, we are using GLX already and ANGLE was forcing EGL backend, I mean we need to use GLX for ANGLE because tests were already using it. It is not that we are changing that.

Are you sure that your changes are limited to the case where we are using GLX already? It doesn't look like they are?

`DEVELOPER_MODE` does not mean we're running layout tests, and it certainly doesn't mean we're running under X11.

**Comment by mcatanzaro** [comment]
> I agree, but in this case we are choosing using GLX inside ANGLE because WebKit is already using GLX for rendering, that is the problem, we are using GLX already and ANGLE was forcing EGL backend, I mean we need to use GLX for ANGLE because tests were already using it. It is not that we are changing that.

So does this affect more than just layout tests?

If not, I think the next step is: find another way to do what you need for layout tests without looking at `DEVELOPER_MODE`. The test runner could configure WebKit using a special C API, for example.

**Comment by zdobersek** [comment]
Far-sighted solution would be to just remove GLX support throughout.

**Comment by alexgcastro** [comment]
> > I agree, but in this case we are choosing using GLX inside ANGLE because WebKit is already using GLX for rendering, that is the problem, we are using GLX already and ANGLE was forcing EGL backend, I mean we need to use GLX for ANGLE because tests were already using it. It is not that we are changing that.
> 
> Are you sure that your changes are limited to the case where we are using GLX already? It doesn't look like they are?
> 
> `DEVELOPER_MODE` does not mean we're running layout tests, and it certainly doesn't mean we're running under X11.

Yeah, you are right, but this is the fallback class used when we do not have dmabuf support in a platform, we have it here just for the testing platforms, it is not something we want anyone to use because it copies memory. Currently layout tests is the first thing we want to use it until we solve the mess with EGL and nvidia drivers.

Anyway, a good addition I can add is to add the same check we use to choose GLX in other classes in that case, it is not something we know it is there but it can be a good improvement, that way it can pick EGL or GLX because we know in developer mode we are going to compile it.

I'll do the modification, but remember this is the fallback class for dmabuf support that is even causing a big warning because it is used for testing and making sure everyone knows we don't want you to use it.

**Comment by alexgcastro** [comment]
> > I agree, but in this case we are choosing using GLX inside ANGLE because WebKit is already using GLX for rendering, that is the problem, we are using GLX already and ANGLE was forcing EGL backend, I mean we need to use GLX for ANGLE because tests were already using it. It is not that we are changing that.
> 
> So does this affect more than just layout tests?
> 
> If not, I think the next step is: find another way to do what you need for layout tests without looking at `DEVELOPER_MODE`. The test runner could configure WebKit using a special C API, for example.

It affects any platform that does not support dmabuf, wants to use ANGLE and WebKit decides GLX is the way to go for all the GL rendering, this is not something we want applications to use. We don't know if there is going to be anyone using it like that in the future for testing purposes, because the fallback is not for production, so we don't think it makes sense to spend more effort trying to support this situation. At least for the moment.

**Comment by mcatanzaro** [comment]
Since this is only a fallback that you don't want applications to ever wind up in, how about just making the changes unconditionally, instead of looking at `DEVELOPER_MODE`?

**Comment by alexgcastro** [comment]
> Since this is only a fallback that you don't want applications to ever wind up in, how about just making the changes unconditionally, instead of looking at `DEVELOPER_MODE`?

We didn't want to compile GLX backend in the release versions for the gtk port because we just wanted to solve a problem with Xvfb testing, we would like to avoid that backend and remove GLX support at some point as Zan explained. I guess we can add it to GTK and avoid it in WPE, if that is something acceptable for everyone I'm ok with it.

**Comment by mcatanzaro** [comment]
> I guess we can add it to GTK and avoid it in WPE, if that is something acceptable for everyone I'm ok with it.

That sounds much better than varying graphics behavior based on `DEVELOPER_MODE`.

**Review by mcatanzaro — COMMENTED** [review]
OK thanks, this looks better.

I'll let graphics reviewers handle final review.

**Comment by alexgcastro** [comment]
> OK thanks, this looks better.
> 
> I'll let graphics reviewers handle final review.

Thanks for your comments when reviewing the patch.

**Comment by zdobersek** [comment]
I think this needs a solution in the form of removing GLX support. Until that can be done, I'm not the best to review such patches.

**Comment by alexgcastro** [comment]
After https://commits.webkit.org/254751@main this is not a problem anymore because we prefer EGL, so we go in the good directorion to remove GLX. I'm closing this PR.

**Pull request closed without merging**
