### PR TITLE
Introduction.md: HTTP => HTTPS

### PR DESCRIPTION
**Pull request by Schweinepriester**
Since
1. this is only a non-substantial documentation change
2. `Tools/Scripts/git-webkit` didn't work in GitHub Codespaces (want me to open a ticket for that?)
3. commits without a ticket aren't strickly prohibited, for example recently https://github.com/WebKit/WebKit/commit/7177e2715da5b49087012a9285c6200bb20af383

I've taken this open approach. I hope this is acceptable.

The change itself: Checked the links, skipping the redirect HTTP => HTTPS this way.

The Pull Request Template is only commented out.

### CODE REVIEW

**Comment by JonWBedard** [comment]
Changes without an issue are ok, although we do need a correctly formatted commit message, basically something like:
```
Change title

Reviewed by NOBODY (OOPS!).

* Introduction.md:
```

Not familiar with GitHub code spaces, would be curious why `git-webkit` doesn't work there.

**Comment by Schweinepriester** [comment]
Okay, apologies, not sure what happend there oO
Guess I'll open another one, with a proper message from the start ¯\\\_(ツ)_/¯

**Comment by JonWBedard** [comment]
You can just edit the commit with 'git commit --amend' and the force-push to your branch with 'git push <remote> patch-1', no need to close the PR

**Comment by Schweinepriester** [comment]
That is what I tried, technically using `git push --force-with-lease`, but somehow I/it managed to mark every file in the repo as changed, hence the "Files changed ∞" oO
For me this PR is now very sluggish as well… and also I'm sure I didn't manually close this PR :o

**Pull request closed without merging**
