### PR TITLE
drawImage(detachedOffscreenCanvas) is supposed to throw https://bugs.webkit.org/show_bug.cgi?id=266918

### PR DESCRIPTION
**Pull request by Kaiido**
#### 5dbd0444ac2e6b126ff88e34c7cf2a785f984cf2
<pre>
drawImage(detachedOffscreenCanvas) is supposed to throw <a href="https://bugs.webkit.org/show_bug.cgi?id=266918">https://bugs.webkit.org/show_bug.cgi?id=266918</a>

Reviewed by @mattwoodrow.

Explanation of why this fixes the bug.

By setting the OffscreenCanvas&apos;s `size()` after the DetachedCanvas has been created we ensure that the DetachedCanvas has the correct size to later create the new OffscreenCanvas, and that any method checking the size of the previous OffscreenCanvas, including `drawImage()`, gets the expected `0` width and height.

Also deletes the custom `width` and `height` getters from OffscreenCanvas since these were only used to return a &quot;fake&quot; `0` in case the OffscreenCanvas got detached, and that they are now truly `0`. The special handling in `setWidth` and `setHeight` is still required though.

Tests are not yet published at <a href="https://github.com/web-platform-tests/wpt/pull/43835">https://github.com/web-platform-tests/wpt/pull/43835</a>

* Source/WebCore/html/OffscreenCanvas.cpp:
(WebCore::OffscreenCanvas::detach):
(WebCore::OffscreenCanvas::width const): Deleted.
(WebCore::OffscreenCanvas::height const): Deleted.
* Source/WebCore/html/OffscreenCanvas.h:

import new WPT tests

Manually imported since while <a href="https://github.com/web-platform-tests/wpt/pull/43835">https://github.com/web-platform-tests/wpt/pull/43835</a> has been approved, it still hasn&apos;t been merged.

drawImage(detachedOffscreenCanvas) is supposed to throw <a href="https://bugs.webkit.org/show_bug.cgi?id=266918">https://bugs.webkit.org/show_bug.cgi?id=266918</a>

Reviewed by @Ahmad-S792.

Since the previous change this method was failing to trigger the proper exception type when
called on a detached OffscreenCanvas, because now the size is actually empty for detached
OffscreenCanvas. We need to separate the case &apos;detached&apos; and &apos;no buffer&apos;, because zero size
OffscreenCanvas will match &apos;no buffer&apos; and we&apos;d throw an InvalidStateError instead of an
IndexSizeError for zero-sized OffscreenCanvas.

* Source/WebCore/html/OffscreenCanvas.cpp:
(WebCore::OffscreenCanvas::convertToBlob):

Canonical link: <a href="https://commits.webkit.org/274534@main">https://commits.webkit.org/274534@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/7314cf09e22cac047623d0346f776377aaa41db7

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/39338 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/18317 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/41691 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/41872 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/35238 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/41644 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/21178 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/15646 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/32893 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/39912 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/15408 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/34068 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/13391 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/13359 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/35008 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/43150 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/35702 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/35337 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/39160 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/14150 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/11662 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/37401 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/15756 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/34286 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/8802 "Built successfully and passed tests") | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/15804 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/15411 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Review by mattwoodrow — APPROVED** [review]
Looks good!

You'll need to squash the two commits into a single one with a single description for the merge bot to be happy.

Looks like the test changes got approved, so please import them (either using the import-w3c-tests script, or manually) into this change too.l

**Comment by Ahmad-S792** [comment]
@Kaiido - Do you have committers right or do you want me to merge it?

**Comment by Kaiido** [comment]
Yes please merge. I don't have committers right.

**Comment by Ahmad-S792** [comment]
> Yes please merge. I don't have committers right.

Just noticed in commit message that you have two `OOPS!` - can you update commit message because I know our merge script will fail because of additional `OOPS`.

**Comment by Kaiido** [comment]
I did amend the commit message. Hope it's fine now.

**Pull request merged**
