### PR TITLE
Move macOS BigSur and Monterey test expectations that will be impacted by custom WPT domains

### PR DESCRIPTION
**Pull request by rreno**
#### b7047a1cbe71dec029e5c9ed6e6669e29a5f396f
<pre>
Move macOS BigSur and Monterey test expectations that will be impacted by custom WPT domains
<a href="https://bugs.webkit.org/show_bug.cgi?id=248635">https://bugs.webkit.org/show_bug.cgi?id=248635</a>
rdar://problem/102880092

Reviewed by NOBODY (OOPS!).

LayoutTests/platform/mac-*/:
   Copied expectations from their current locations
   (either the base expectations next to the tests or pre-existing
   platform-specific expectations).
</pre>
https://github.com/WebKit/WebKit/commit/b7047a1cbe71dec029e5c9ed6e6669e29a5f396f

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/98383 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/7588 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/31512 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/107821 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/168090 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/8097 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/84968 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/90944 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/104481 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/104038 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/6156 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/89721 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/33156 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/87969 "Passed tests") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/21083 "Found 30 new test failures: accessibility/aria-keyshortcuts.html, compositing/no-compositing-when-fulll-screen-is-present.html, css3/supports-dom-api.html, fast/css/css-typed-om/style-property-map-set-CSSMathSum-value.html, fast/text/text-edge-property-parsing.html, imported/w3c/web-platform-tests/css/css-grid/masonry/tentative/masonry-grid-template-columns-computed-withcontent.html, imported/w3c/web-platform-tests/css/css-scroll-snap/scroll-target-margin-003.html, imported/w3c/web-platform-tests/css/css-typed-om/the-stylepropertymap/properties/animation-delay.html, imported/w3c/web-platform-tests/css/css-typed-om/the-stylepropertymap/properties/background.html, imported/w3c/web-platform-tests/css/css-typed-om/the-stylepropertymap/properties/baseline-shift.html ... (failure)") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/76103 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/1536 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/22611 "Found 30 new test failures: accessibility/aria-keyshortcuts.html, compositing/no-compositing-when-fulll-screen-is-present.html, css3/supports-dom-api.html, fast/css/css-typed-om/style-property-map-set-CSSMathSum-value.html, fast/rendering/render-style-null-optgroup-crash.html, fast/text/text-edge-property-parsing.html, http/tests/appcache/fail-on-update-2.html, http/wpt/fetch/response-opaque-clone.html, imported/w3c/web-platform-tests/css/css-cascade/all-prop-initial-xml.html, imported/w3c/web-platform-tests/css/css-grid/masonry/tentative/masonry-grid-template-columns-computed-withcontent.html ... (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/1470 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/45099 "Found 30 new test failures: accessibility/aria-keyshortcuts.html, compositing/no-compositing-when-fulll-screen-is-present.html, css3/supports-dom-api.html, fast/css/css-typed-om/style-property-map-set-CSSMathSum-value.html, fast/rendering/render-style-null-optgroup-crash.html, fast/text/text-edge-property-parsing.html, http/tests/navigation/fragment-navigation-policy-ignore.html, http/wpt/service-workers/fetch-service-worker-preload-changing-request.https.html, http/wpt/service-workers/fetch-service-worker-preload-download.https.html, http/wpt/service-workers/fetch-service-worker-preload.https.html ... (failure)") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/6378 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/42020 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/2830 "Built successfully") | | |

### CODE REVIEW

**Comment by rreno** [comment]
These are tests that will be affected by #4438

**Comment by rreno** [comment]
Maybe reproduction steps will help verify the change is what I claim it is?

Checkout `rreno:support_wpt_custom_domains` which is a rebased and merge-conflict free version of @cdumez s branch.

switch back to `main`

For all the changes that didn't already have platform-specific expectations:

```
$ git diff --name-only support_wpt_custom_domains | grep -E "expected.txt$" | grep -Ev "platform/"
```


And all changes that already had platform-specific expectations:

```
$ git diff --name-only support_wpt_custom_domains | grep -E "mac.+expected.txt$"
```

In order to do the actual copy:

```sh
#!/bin/zsh

# I changed out the platform for each run of the script. Probably a nicer way to do this with args.
target=LayoutTests/platform/mac-bigsur-wk2
export target

# Like the hard-coded platform above, the grep part of the pipeline I just manually changed for each platform.
#     * mac
#     * mac-wk1
#     * mac-wk2
# Additionally, the non-platform-specific pipeline needs to be substituted here too.
git diff --name-only support_wpt_custom_domains | grep -E "mac-wk2/.+expected.txt$" | xargs -I % sh -c '
for f; do
    newfile=${target}/${f#*/*/*/}
    mkdir -p "$(dirname $newfile)"
    cp "$f" "$newfile"
done' sh %

```

In all, I ran that script 7 times. One for the non-platform specific expectations and one each for the three mac platforms x 2 OS versions.

**Review by brentfulgham — APPROVED** [review]
rs=me. This patch is a set of copies to platform-specific sub-directories. If git provided a history-preserving copy operation like svn does, this would be a much smaller/simpler patch to review.

**Comment by rreno** [comment]
Closing this.

The motivation for platform-specific expectations was to maintain as much test coverage as we can on downlevels. Many of the tests that fail with custom domains on BigSur and Monterey only fail subtests and so skipping the whole thing discards coverage of the passing subtests.

 It's not clear the trade-off between maintaining platform-specific test expectations and test coverage on downlevels is worth it.

**Pull request closed without merging**
