### PR TITLE
git-webkit broke webkitbot

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 8f37a9ae8521648e65fd8393087bdce7abdbba4b
<pre>
git-webkit broke webkitbot
<a href="https://bugs.webkit.org/show_bug.cgi?id=241824">https://bugs.webkit.org/show_bug.cgi?id=241824</a>
&lt;rdar://95642497&gt;

Reviewed by Yusuke Suzuki and Alexey Proskuryakov.

* Tools/WebKitBot/src/WebKitBot.mjs: Use pure-git tools to update checkout.

Canonical link: <a href="https://commits.webkit.org/252078@main">https://commits.webkit.org/252078@main</a>
</pre>

### CODE REVIEW

**Review by aproskuryakov — APPROVED** [review]
Are we performing adequate cleanup in between? Somewhat surprised that changes are needed here, but not in cleanup.

**Review by Constellation — APPROVED** [review]
r=me

**Comment by JonWBedard** [comment]
> Are we performing adequate cleanup in between? Somewhat surprised that changes are needed here, but not in cleanup.

This basically is the cleanup step. The big issue right now is that we're leaving around an entire commit. Force-moving the `main` branch to `origin/main` fixes that. Although you can only do that in detached HEAD state, so there is one more change needed.

**Comment by aproskuryakov** [comment]
> This basically is the cleanup step. 

It is very different from what EWS does to clean up. Should be be striving to standardize on one set of steps?

**Comment by JonWBedard** [comment]
> > This basically is the cleanup step.
> 
> It is very different from what EWS does to clean up. Should be be striving to standardize on one set of steps?

That's a good point, making our steps here more similar. That being said, EWS has to deal with quite a bit more that webkitbot, namely, failed rebases or failed patch application.

**Pull request merged**
