### PR TITLE
Store securityOrigin of topDocument with each document

### PR DESCRIPTION
**Pull request by chirags27**
#### ea7cc1e302185a6c9e7b95a83e39da761ced6ae9
<pre>
Store securityOrigin of topDocument with each document
<a href="https://bugs.webkit.org/show_bug.cgi?id=251231">https://bugs.webkit.org/show_bug.cgi?id=251231</a>
rdar://104716458

Reviewed by NOBODY (OOPS!).

With this change, we start storing the security origin of top document
at creation time of a document.

* Source/WebCore/dom/Document.cpp:
* Source/WebCore/dom/Document.h:
</pre>
https://github.com/WebKit/WebKit/commit/e8d99c61ecc08c3b76ba8edcebf2561cb810f040

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/106118 "11 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/15171 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/38946 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/115302 "Built successfully") | [❌ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/175379 "Found 60 new test failures: accessibility/aria-roles.html, css3/filters/change-filter-style.html, editing/execCommand/insert-list-nested-with-orphaned-live-range.html, editing/inserting/insert-paragraph-separator-with-html-elements-crash.html, fast/canvas/canvas-inside-viewport-timer-throttling.html, fast/dom/focus-style-resolution-attribute-change.html, fast/dom/repeating-timer-element-overflow-throttling.html, fast/dom/repeating-timer-element-overflowing-child-own-layer-throttling.html, fast/dom/repeating-timer-mixed-visible-display-none-elements-throttling.html, fast/dom/repeating-timer-visible-element-throttling.html ... (failure)") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/110023 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/16659 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/6387 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/98326 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/114998 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/111874 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/12676 "Found 60 new test failures: compositing/backing/backing-store-attachment-empty-keyframe.html, compositing/backing/transition-extent.html, compositing/reflections/mask-and-reflection.html, crypto/workers/subtle/aes-cbc-import-key-decrypt.html, crypto/workers/subtle/aes-cbc-import-key-encrypt.html, crypto/workers/subtle/aes-cbc-import-key-unwrap-key.html, crypto/workers/subtle/aes-cbc-import-key-wrap-key.html, crypto/workers/subtle/aes-cfb-import-key-decrypt.html, crypto/workers/subtle/aes-cfb-import-key-encrypt.html, crypto/workers/subtle/aes-cfb-import-key-unwrap-key.html ... (failure)") | [❌ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/95605 "Found 115 new API test failures: TestWebKitAPI.WebKit.ApplicationCacheDirectories, TestWebKitAPI.WebKit.InvalidDeviceIdHashSalts, TestWebKitAPI.WebKit2.CaptureMuteAPI, TestWebKitAPI.WebKit2.ConnectedToHardwareConsole, TestWebKitAPI.WebKit2.CrashGPUProcessWhileCapturing, TestWebKitAPI.WebKit.NavigateDuringDeviceEnumeration, TestWebKitAPI.WebKit2.EnumerateDevicesAfterMuting, TestWebKitAPI.ServiceWorkers.NonDefaultSessionID, TestWebKitAPI.IndexedDB.IndexedDBFileNameV1, TestWebKitAPI.WebKit.MigrateLocalStorageDataToGeneralStorageDirectory ... (failure)") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/40176 "Found 397 new test failures: accessibility/scroll-to-make-visible-iframe.html, crypto/workers/subtle/aes-cbc-import-key-decrypt.html, crypto/workers/subtle/aes-cbc-import-key-encrypt.html, crypto/workers/subtle/aes-cbc-import-key-unwrap-key.html, crypto/workers/subtle/aes-cbc-import-key-wrap-key.html, crypto/workers/subtle/aes-ctr-import-key-decrypt.html, crypto/workers/subtle/aes-ctr-import-key-encrypt.html, crypto/workers/subtle/aes-ctr-import-key-unwrap-key.html, crypto/workers/subtle/aes-ctr-import-key-wrap-key.html, crypto/workers/subtle/aes-gcm-import-key-decrypt.html ... (failure)") | 
| | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/94549 "Found 120 new API test failures: TestWebKitAPI.ApplePay.ApplePayAvailableInFrame, TestWebKitAPI.WebKit.ApplicationCacheDirectories, TestWebKitAPI.WebKit.InvalidDeviceIdHashSalts, TestWebKitAPI.WebKit2.CaptureMuteAPI, TestWebKitAPI.AppPrivacyReport.AppInitiatedRequestWithServiceWorker, TestWebKitAPI.WebKit2.CrashGPUProcessWhileCapturing, TestWebKitAPI.WebKit.NavigateDuringDeviceEnumeration, TestWebKitAPI.WebKit2.EnumerateDevicesAfterMuting, TestWebKitAPI.ServiceWorkers.NonDefaultSessionID, TestWebKitAPI.PasteImage.RevealSelectionAfterPastingImage ... (failure)") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/27248 "Found 60 new test failures: accessibility/mac/wk1-set-selected-text-marker-range-input-element.html, accessibility/scroll-to-global-point-iframe.html, accessibility/scroll-to-make-visible-iframe.html, compositing/backing/backing-store-attachment-empty-keyframe.html, compositing/backing/transition-extent.html, crypto/workers/subtle/aes-cbc-import-key-decrypt.html, crypto/workers/subtle/aes-cbc-import-key-encrypt.html, crypto/workers/subtle/aes-cbc-import-key-unwrap-key.html, crypto/workers/subtle/aes-cbc-import-key-wrap-key.html, crypto/workers/subtle/aes-cfb-import-key-decrypt.html ... (failure)") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/81855 "5 api tests failed or timed out") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/8422 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/28600 "Found 60 new test failures: accessibility/scroll-to-global-point-iframe.html, accessibility/scroll-to-make-visible-iframe.html, compositing/backing/backing-store-attachment-empty-keyframe.html, compositing/backing/transition-extent.html, crypto/workers/subtle/aes-cbc-import-key-decrypt.html, crypto/workers/subtle/aes-cbc-import-key-encrypt.html, crypto/workers/subtle/aes-cbc-import-key-unwrap-key.html, crypto/workers/subtle/aes-cbc-import-key-wrap-key.html, crypto/workers/subtle/aes-cfb-import-key-decrypt.html, crypto/workers/subtle/aes-cfb-import-key-encrypt.html ... (failure)") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/8916 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/5182 "Found 60 new test failures: compositing/backing/transition-extent.html, crypto/workers/subtle/aes-cbc-import-key-decrypt.html, crypto/workers/subtle/aes-cbc-import-key-encrypt.html, crypto/workers/subtle/aes-cbc-import-key-unwrap-key.html, crypto/workers/subtle/aes-cbc-import-key-wrap-key.html, crypto/workers/subtle/aes-cfb-import-key-decrypt.html, crypto/workers/subtle/aes-cfb-import-key-encrypt.html, crypto/workers/subtle/aes-cfb-import-key-unwrap-key.html, crypto/workers/subtle/aes-cfb-import-key-wrap-key.html, crypto/workers/subtle/aes-ctr-import-key-decrypt.html ... (failure)") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/14535 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/48144 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/10461 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by lauromoura** [comment]
The `gtk-wk2` layout test queue failed with the bot filled with related crash dumps before finishing to repeat the tests. Here's the link for the first round of results:

https://ews-build.s3-us-west-2.amazonaws.com/GTK-WK2-Tests-EWS/6a141c0a-39849/results.html

And the crashing thread from test accessibility/accessibility-crash-focused-element-change.html, similar to the other tests:

```
Thread 1 (Thread 0x7f14e7a56ec0 (LWP 1582)):
#0  0x00007f14f4c6736c in WebCore::NavigationRequester::from(WebCore::Document&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#1  0x00007f14f4c69648 in WebCore::NavigationAction::NavigationAction(WebCore::Document&, WebCore::ResourceRequest const&, WebCore::InitiatedByMainFrame, WebCore::FrameLoadType, bool, WebCore::Event*, WebCore::ShouldOpenExternalURLsPolicy, WTF::AtomString const&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#2  0x00007f14f4c49a78 in WebCore::FrameLoader::loadWithDocumentLoader(WebCore::DocumentLoader*, WebCore::FrameLoadType, WTF::RefPtr<WebCore::FormState, WTF::RawPtrTraits<WebCore::FormState>, WTF::DefaultRefDerefTraits<WebCore::FormState> >&&, WebCore::AllowNavigationToInvalidURL, WTF::CompletionHandler<void ()>&&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#3  0x00007f14f4c4d4e0 in WebCore::FrameLoader::load(WebCore::DocumentLoader&, WebCore::SecurityOrigin const*) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#4  0x00007f14f4c4e0b0 in WebCore::FrameLoader::load(WebCore::FrameLoadRequest&&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#5  0x00007f14f54cf06f in WebCore::UserInputBridge::loadRequest(WebCore::FrameLoadRequest&&, WebCore::InputSource) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#6  0x00007f14f3150902 in WebKit::WebPage::loadRequest(WebKit::LoadParameters&&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#7  0x00007f14f2a72810 in void IPC::handleMessage<Messages::WebPage::LoadRequest, WebKit::WebPage, WebKit::WebPage, void (WebKit::LoadParameters&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebPage*, void (WebKit::WebPage::*)(WebKit::LoadParameters&&)) [clone .isra.0] () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#8  0x00007f14f2a76586 in WebKit::WebPage::didReceiveWebPageMessage(IPC::Connection&, IPC::Decoder&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#9  0x00007f14f2caf56a in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#10 0x00007f14f2f9cf46 in WebKit::WebProcess::didReceiveMessage(IPC::Connection&, IPC::Decoder&) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#11 0x00007f14f2ca7d25 in IPC::Connection::dispatchMessage(std::unique_ptr<IPC::Decoder, std::default_delete<IPC::Decoder> >) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#12 0x00007f14f2ca98c1 in IPC::Connection::dispatchOneIncomingMessage() () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#13 0x00007f14f01fa97a in WTF::RunLoop::performWork() () at /app/webkit/WebKitBuild/Release/lib/libjavascriptcoregtk-4.1.so.0
#14 0x00007f14f0273999 in WTF::RunLoop::RunLoop()::{lambda(void*)#1}::_FUN(void*) () at /app/webkit/WebKitBuild/Release/lib/libjavascriptcoregtk-4.1.so.0
#15 0x00007f14f027440f in WTF::RunLoop::{lambda(_GSource*, int (*)(void*), void*)#1}::_FUN(_GSource*, int (*)(void*), void*) () at /app/webkit/WebKitBuild/Release/lib/libjavascriptcoregtk-4.1.so.0
#16 0x00007f14ec21ec37 in g_main_dispatch (context=0x55738948c0c0) at ../glib/gmain.c:3419
#17 g_main_context_dispatch (context=0x55738948c0c0) at ../glib/gmain.c:4137
#18 0x00007f14ec275028 in g_main_context_iterate.constprop.0 (context=0x55738948c0c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4213
#19 0x00007f14ec21e2af in g_main_loop_run (loop=0x5573894bae50) at ../glib/gmain.c:4413
#20 0x00007f14f0274540 in WTF::RunLoop::run() () at /app/webkit/WebKitBuild/Release/lib/libjavascriptcoregtk-4.1.so.0
#21 0x00007f14f3181e4e in int WebKit::AuxiliaryProcessMain<WebKit::WebProcessMainGtk>(int, char**) () at /app/webkit/WebKitBuild/Release/lib/libwebkit2gtk-4.1.so.0
#22 0x00007f14ebbb954a in __libc_start_call_main (main=main@entry=0x557387f40920 <main>, argc=argc@entry=4, argv=argv@entry=0x7ffeda248478) at ../sysdeps/nptl/libc_start_call_main.h:58
#23 0x00007f14ebbb960b in __libc_start_main_impl (main=0x557387f40920 <main>, argc=4, argv=0x7ffeda248478, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:389
#24 0x0000557387f40855 in _start () at ../sysdeps/x86_64/start.S:115
```

Full trace: https://ews-build.s3-us-west-2.amazonaws.com/GTK-WK2-Tests-EWS/6a141c0a-39849/accessibility/accessibility-crash-focused-element-change-crash-log.txt

**Comment by aj062** [comment]
I cancelled api-ios and api-mac runs (https://ews-build.webkit.org/#/builders/9/builds/94255 and https://ews-build.webkit.org/#/builders/3/builds/95363) as they were failing and taking too long. Please check

**Comment by cdumez** [comment]
I am personally not 100% sure this is a the way to go. This seems inefficient memory-wise to duplicate the top origin for every frame. You might think it is acceptable as long as it's only the top origin but odds are will need more information later on (maybe COOP/COEP, CSP, ...).

Odds are, in the long run, we could be better off with an object (e.g. probably SecurityContext which already exists) that contains those members. The LocalFrame would get it from its SecurityContext from its document (document currently subclasses SecurityContext). A RemoteFrame would store it locally since it doesn't have a document.

Thoughts @achristensen07? I don't mind trying Chirag's approach but I suspect it won't scale well.

**Comment by achristensen07** [comment]
Chris, I think that's a better approach.

**Comment by chirags27** [comment]
Closing this based on conversation as the new change will look quite different when it's time for that.

**Pull request closed without merging**
