### PR TITLE
REGRESSION (248723@main): Videos on bbc.co.uk fail to load when content filtering is enabled

### PR DESCRIPTION
**Pull request by whsieh**
#### 5d11f0377c180c6fb87a0d60f84082c75753eac1
<pre>
REGRESSION (248723@main): Videos on bbc.co.uk fail to load when content filtering is enabled
<a href="https://bugs.webkit.org/show_bug.cgi?id=249811">https://bugs.webkit.org/show_bug.cgi?id=249811</a>
rdar://103247851

Reviewed by Brent Fulgham and Alex Christensen.

On articles on bbc.co.uk, video elements are embedded inside subframes, and are only interactive
once the containing subframe has finished loading (i.e. dispatched the &quot;load&quot; event). In the case
where:

1.  Content filtering is enabled, and also happens in the network process via the
    `CONTENT_FILTERING_IN_NETWORKING_PROCESS` codepath new in iOS 16/macOS Ventura.

2.  The subframe is loaded from a disk cache entry (as opposed to over the network, or in memory
    cache).

...we end up never dispatching the load event on the subframe, due to the fact that the
corresponding `WebCore::SubresourceLoader` driving the subframe load never gets notified that
loading finished. This is because, in following code within the network process (in the codepath
marked below), we exit early after delivering the cached data to the content filter, before either
sending `WebResourceLoader::DidReceiveResource` or `WebResourceLoader::DidFinishResourceLoad` (the
latter of which we use in the case where we don&apos;t already have a shareable resource handle). To fix
this, we simply pull the logic to dispatch `WebResourceLoader::DidFinishResourceLoad` out into a
separate callback, and invoke it from both places.

```
    #if ENABLE(SHAREABLE_RESOURCE)
        if (!entry-&gt;shareableResourceHandle().isNull()) {
    #if ENABLE(CONTENT_FILTERING_IN_NETWORKING_PROCESS)
            if (m_contentFilter &amp;&amp; !m_contentFilter-&gt;continueAfterDataReceived(entry-&gt;buffer()-&gt;makeContiguous(), entry-&gt;buffer()-&gt;size())) {
                m_contentFilter-&gt;continueAfterNotifyFinished(m_parameters.request.url());
                m_contentFilter-&gt;stopFilteringMainResource();               // &lt;-------
                return;
            }
    #endif
            send(Messages::WebResourceLoader::DidReceiveResource(entry-&gt;shareableResourceHandle()));
            return;
        }
    #endif
```

Note that we prefer dispatching `DidFinishResourceLoad` over `DidReceiveResource` below (which we
would normally use in this shareable resource handle codepath), since the resource loader in the web
process would already have received the data when content filtering is enabled, so sending the
entire cached resource handle again is redundant.

Test: http/tests/contentfiltering/load-event-in-allowed-subframe.html

* LayoutTests/http/tests/contentfiltering/load-event-in-allowed-subframe-expected.txt: Added.
* LayoutTests/http/tests/contentfiltering/load-event-in-allowed-subframe.html: Added.
* LayoutTests/http/tests/contentfiltering/resources/lots-of-text.html: Added.

Add a new test resource that consists of an HTML page that contains a large amount of text. This
ensures that we&apos;ll attempt to store it in disk cache, which is a necessary part of reproducing this
bug.

* Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp:
(WebKit::NetworkResourceLoader::sendResultForCacheEntry):

Dispatch `WebResourceLoader::DidFinishResourceLoad` in both content filtering codepaths when
`CONTENT_FILTERING_IN_NETWORKING_PROCESS` is enabled.

Canonical link: <a href="https://commits.webkit.org/258394@main">https://commits.webkit.org/258394@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/4fb2487c19a6d88640e1c26f8f588667f3079139

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/101398 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/10555 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/34456 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/110669 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/170936 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/11506 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/1408 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/93792 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/108495 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/107180 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/8747 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/91988 "Passed tests") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/35274 "Found 1 new test failure: imported/w3c/web-platform-tests/file-system-access/sandboxed_FileSystemBaseHandle-postMessage-Error.https.window.html (failure)") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/90645 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/23395 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/78271 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/4167 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/24907 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/4222 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/1329 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/10317 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/44395 "Passed tests") | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/5749 "Failed to push commit to Webkit repository") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/5986 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@whsieh Is this [bug](https://bugs.webkit.org/show_bug.cgi?id=249556) similar by any change?

**Comment by whsieh** [comment]
> @whsieh Is this [bug](https://bugs.webkit.org/show_bug.cgi?id=249556) similar by any change?

I suspect that's a different issue, since this bug (1) only reproduces when you have content filtering enabled (i.e. Content Restrictions > Web Content > Limit Adult Websites), and (2) the symptoms of the bug are such that you'd only see a blank space where the video would normally be (instead of the video or content above the video being clipped).

**Comment by Ahmad-S792** [comment]
> > @whsieh Is this [bug](https://bugs.webkit.org/show_bug.cgi?id=249556) similar by any change?
> 
> I suspect that's a different issue, since this bug (1) only reproduces when you have content filtering enabled (i.e. Content Restrictions > Web Content > Limit Adult Websites), and (2) the symptoms of the bug are such that you'd only see a blank space where the video would normally be (instead of the video or content above the video being clipped).

Fair enough, I just thought it might be same, so just wanted to ask. Thanks for your input.

**Review by brentfulgham — APPROVED** [review]
Looks good.

**Review by achristensen07 — APPROVED** [review]

**Review by pvollan — APPROVED** [review]
R=me.

**Pull request merged**
