### PR TITLE
[build.webkit.org] Use GitHub checkouts

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 91e76ff30d923951dcf180aca7eb6c93c95825b9
<pre>
[build.webkit.org] Use GitHub checkouts
<a href="https://bugs.webkit.org/show_bug.cgi?id=239072">https://bugs.webkit.org/show_bug.cgi?id=239072</a>
&lt;rdar://problem/91567092 &gt;

Reviewed by Ryan Haddad.

* Tools/CISupport/build-webkit-org/config.json: Convert schedulers to GitHub based branch names.
* Tools/CISupport/build-webkit-org/loadConfig.py: Ditto.
* Tools/CISupport/build-webkit-org/master.cfg: Enable incoming hooks from GitHub.
(load_password): Added.
* Tools/CISupport/build-webkit-org/steps.py:
(CheckOutSource): Replace with GitHub based checkout.
(CleanUpGitIndexLock): Replaced SVNCleanup.
(SVNCleanup): Replace with CleanUpGitIndexLock.
(ShowIdentifier.start): `got_revision` will bet hash, not subversion revision.
* Tools/CISupport/build-webkit-org/steps_unittest.py:
(TestShowIdentifier.test_success):
(TestShowIdentifier.test_failure):

Canonical link: <a href="https://commits.webkit.org/249946@main">https://commits.webkit.org/249946@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@293323">https://svn.webkit.org/repository/webkit/trunk@293323</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by JonWBedard** [comment]
I think I'm missing something, that's why this is a draft. Will be doing some work on the staging instance today to iron out any wrinkles.

**Comment by JonWBedard** [comment]
> I think I'm missing something, that's why this is a draft. Will be doing some work on the staging instance today to iron out any wrinkles.

Verified this on our dev instance, everything works!

**Review by ryanhaddad — APPROVED** [review]
LGTM

**Comment by JonWBedard** [comment]
I need to delay landing this until we fix the bot watchers dashboard, which relies on revisions still.

**Comment by JonWBedard** [comment]
I'm planning on landing and deploying this on the morning of April 25th

**Pull request merged**
