### PR TITLE
[ iOS ] imported/w3c/web-platform-tests/css/css-backgrounds/border-image-repeat-round.html is a constant ImageOnly Failure (254356)

### PR DESCRIPTION
**Pull request by brentfulgham**
#### fbcfc6b54320d38d1fa997225db714c645469502
<pre>
[ iOS ] imported/w3c/web-platform-tests/css/css-backgrounds/border-image-repeat-round.html is a constant ImageOnly Failure (254356)
<a href="https://bugs.webkit.org/show_bug.cgi?id=254356">https://bugs.webkit.org/show_bug.cgi?id=254356</a>
&lt;rdar://107145200&gt;

Reviewed by NOBODY (OOPS!).

Import the correct reference file for this test from upstream wpt (431f4f6eb006c4f79e991d9a1913931005e2f566).

The current reference file shows gaps between the individual images, which is incorrect for a test
that does a repeat (not a space).

* LayoutTests/imported/w3c/web-platform-tests/css/css-backgrounds/reference/border-image-repeat-round-ref.html: Added.
</pre>
https://github.com/WebKit/WebKit/commit/fbcfc6b54320d38d1fa997225db714c645469502

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/1009 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/1037 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/1073 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/1549 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/893 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/1086 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/1118 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/1097 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/1017 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/947 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/944 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/1446 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/991 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/940 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/934 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/919 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/968 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/1987 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/963 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/905 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/906 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/949 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/978 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by nt1m — CHANGES_REQUESTED** [review]
Not sure how this fixes the issue, `-ref.html` files are not used by WebKit test runner (though we should definitely have it around to keep the import in sync).

**Comment by brentfulgham** [comment]
> Not sure how this fixes the issue, `-ref.html` files are not used by WebKit test runner (though we should definitely have it around to keep the import in sync).

Ah, I see the issue. There is an `-expected.html` file that references a bad PNG with the spacing present. It must have been generated long ago.

**Comment by nt1m** [comment]
> > Not sure how this fixes the issue, `-ref.html` files are not used by WebKit test runner (though we should definitely have it around to keep the import in sync).
> 
> Ah, I see the issue. There is an `-expected.html` file that references a bad PNG with the spacing present. It must have been generated long ago.

We should reimport the support files then!

**Comment by brentfulgham** [comment]
> We should reimport the support files then!

I think the file `support/border-image-round-result.png` that we use is old and outdated. They switched to the `-ref.html` file for the test, so I'm not sure how to fix our local tests.

Maybe I can find the old file in `wpt` GitHub (more recent than the ancient "with space" version).

**Comment by brentfulgham** [comment]
I'm going to do a full import of the css-backgrounds test suite, since they have fixed this upstream.

**Pull request closed without merging**
