### PR TITLE
Move StyleAppearance to Source/WebCore/platform

### PR DESCRIPTION
**Pull request by Andrew-Fryer**
#### 9d4f5af97cec1f9bb63e9fe1eae5b7cbf26437e1
<pre>
Move StyleAppearance to Source/WebCore/platform
<a href="https://bugs.webkit.org/show_bug.cgi?id=276025">https://bugs.webkit.org/show_bug.cgi?id=276025</a>
<a href="https://rdar.apple.com/130800233">rdar://130800233</a>

Reviewed by Tim Nguyen.

StyleAppearance is used in Source/WebCore/platform to render form controls.
We&apos;re moving it from .../style to .../platform to avoid a layering violation.

* Source/WebCore/Headers.cmake:
* Source/WebCore/Sources.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/platform/StyleAppearance.cpp: Renamed from Source/WebCore/style/StyleAppearance.cpp.
(WebCore::operator&lt;&lt;):
* Source/WebCore/platform/StyleAppearance.h: Renamed from Source/WebCore/style/StyleAppearance.h.

Canonical link: <a href="https://commits.webkit.org/280713@main">https://commits.webkit.org/280713@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/72fa3888d7409568678e0712b862fa7f6d95d3ac

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/57376 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/36704 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/9851 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/60998 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/7821 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/59504 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/44328 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/8009 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/46467 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/5537 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/59406 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/34444 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/49553 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/27331 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/31226 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/6865 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/6824 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/53237 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/7136 "Found 2 new test failures: imported/w3c/web-platform-tests/svg/import/metadata-example-01-t-manual.svg svg/custom/use-on-symbol-inside-pattern.svg (failure)") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/62677 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/1289 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/7227 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/53727 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/1295 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/49588 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/53818 "Passed tests") | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/19/builds/12683 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/1101 "Passed tests") | | | 
| [❌ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/8563 "Failed to push commit to Webkit repository") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/32533 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/33618 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/34703 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/33364 "Built successfully") | | |

### CODE REVIEW

**Comment by weinig** [comment]
If this lives in platform, I am not sure the Style prefix makes sense. 

Can you expand on why this move is something you want to make?

**Comment by nt1m** [comment]
> If this lives in platform, I am not sure the Style prefix makes sense.
> 
> Can you expand on why this move is something you want to make?

StyleAppearance is used in Source/WebCore/platform to render form controls. We should just do the move to avoid a layering violation.

The name `StyleAppearance` makes it clear it's tied to the CSS `appearance` property.

**Comment by nt1m** [comment]
Headers.cmake needs updating too to fix the GTK/WPE build: https://searchfox.org/wubkat/rev/e08a72c3d292c1ef4fd66f9c2efb96581ec7ca87/Source/WebCore/Headers.cmake#2505

**Comment by stwrt** [comment]
> #### [731099f](https://github.com/WebKit/WebKit/commit/731099f20daad5f70af3c99760fd59a2975dd904)
> Move StyleAppearance to Source/WebCore/platform
> https://bugs.webkit.org/show_bug.cgi?id=276025
> [rdar://130800233](https://rdar.apple.com/130800233)
> 
> Reviewed by NOBODY (OOPS!).
> 
> Explanation of why this fixes the bug (OOPS!).
> 
> * Source/WebCore/Sources.txt:

Please add a commit message here on the purpose of this commit.

**Comment by Andrew-Fryer** [comment]
> Headers.cmake needs updating too to fix the GTK/WPE build: https://searchfox.org/wubkat/rev/e08a72c3d292c1ef4fd66f9c2efb96581ec7ca87/Source/WebCore/Headers.cmake#2505

Thanks!
(I just spent an hour figuring this out and then saw msgs here... I don't think I got a notification about comments on this PR 😖 .)

**Comment by Andrew-Fryer** [comment]
@stwrt 
Do I need to update the PR description or do anything else to play nicely with EWS etc?

May I add `merge-queue`?
(If so, how do I perms to do that; I think it's blocked.)

**Comment by stwrt** [comment]
> @stwrt Do I need to update the PR description or do anything else to play nicely with EWS etc?
> 
> May I add `merge-queue`? (If so, how do I perms to do that; I think it's blocked.)

You need to get approval from a reviewer before we can put the PR in merge-queue.

**Review by nt1m — APPROVED** [review]

**Comment by Andrew-Fryer** [comment]
> > @stwrt Do I need to update the PR description or do anything else to play nicely with EWS etc?
> > May I add `merge-queue`? (If so, how do I perms to do that; I think it's blocked.)
> 
> You need to get approval from a reviewer before we can put the PR in merge-queue.

I think I can't add the label because I'm not a committer.
Could someone please add the `merge-queue` label if this is good to go?

**Comment by stwrt** [comment]
> > > @stwrt Do I need to update the PR description or do anything else to play nicely with EWS etc?
> > > May I add `merge-queue`? (If so, how do I perms to do that; I think it's blocked.)
> > 
> > 
> > You need to get approval from a reviewer before we can put the PR in merge-queue.
> 
> I think I can't add the label because I'm not a committer. Could someone please add the `merge-queue` label if this is good to go?

Added safe-merge-queue, so it will merge once the tests pass.

**Comment by Andrew-Fryer** [comment]
I just looked through the failures.
I can't imagine they are related to my patch.
A lot of them look like flaky tests (timeout, new line unexpected at EOF, etc).
Can I trigger a re-run somehow?
Should I ping someone?


In case it's helpful, here are the ones that look like real issues to me:
- https://ews-build.s3-us-west-2.amazonaws.com/macOS-Ventura-Release-WK2-Tests-EWS/72fa3888-7136-rerun/imported/w3c/web-platform-tests/page-visibility/unload-pretty-diff.html
- https://ews-build.s3-us-west-2.amazonaws.com/macOS-Ventura-Release-WK2-Tests-EWS/72fa3888-7136-rerun/media/media-source/media-source-rendering-update-count-pretty-diff.html
- https://ews-build.s3-us-west-2.amazonaws.com/macOS-Ventura-Release-WK2-Tests-EWS/72fa3888-7136-rerun/media/video-transformed-pretty-diff.html
- https://ews-build.s3-us-west-2.amazonaws.com/macOS-Ventura-Release-WK2-Tests-EWS/72fa3888-7136-rerun/scrollingcoordinator/mac/fixed-backgrounds/fixed-background-in-overflow-in-iframe-pretty-diff.html
- https://ews-build.s3-us-west-2.amazonaws.com/macOS-Ventura-Release-WK2-Tests-EWS/72fa3888-7136-rerun/svg/stroke/non-scaling-stroke-gradient-text-diff.png

**Comment by nt1m** [comment]
None of these look related to this change, merge-queue will probably end up going ahead and land this

**Comment by Andrew-Fryer** [comment]
I thought `unsafe-merge-queue` would have merge by now; do I need to do anything here?

**Comment by whsieh** [comment]
> I thought `unsafe-merge-queue` would have merge by now; do I need to do anything here?

The repo is closed at the moment for maintenance, through noontime today.

**Pull request merged**
