### PR TITLE
Remove duplicated SVG clip path tests

### PR DESCRIPTION
**Pull request by rwlbuis**
#### 649d511f93de1d6e06acbd1d00286fd18388afb0
<pre>
Remove duplicated SVG clip path tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=266574">https://bugs.webkit.org/show_bug.cgi?id=266574</a>

Reviewed by Nikolas Zimmermann.

Remove duplicated SVG clip path tests (and expectations), these tests are
mostly old and before wpt, but by now imported into the wpt repository.

* LayoutTests/platform/glib/TestExpectations:
* LayoutTests/platform/mac-sonoma-wk2-lbse-text/TestExpectations:
* LayoutTests/svg/clip-path/clip-path-clip-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-nested-twice-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-nested-twice.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-005.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-006-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-006.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-007-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-007.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-008-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-008.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-009-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-009.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-010-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip-rule-010.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-clip.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-clip-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-invisible-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-invisible.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-005.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-006-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-006.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-007-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-content-use-007.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-css-transform-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-child-changes-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-child-changes.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-clippathunits-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-clippathunits.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-href-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-href.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-id-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-dom-id.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-invalid-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-invalid.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-negative-scale-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-negative-scale.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-no-content-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-objectboundingbox-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-g-005.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-marker-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-svg-005.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-use-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-use-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-use-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-on-use-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-001.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-002.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-003.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-004.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-text-005.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-userspaceonuse-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/clip-path-userspaceonuse-001.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-001.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-002.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-003-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-003.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-004-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-004.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-005-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-005.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-006-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-006.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-007-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-007.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-008-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-008.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-009-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-009.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-010-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-010.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-panning-001-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-panning-001.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-panning-002-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-nested-clip-path-panning-002.svg: Removed.
* LayoutTests/svg/clip-path/mask-objectboundingbox-content-clip-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-objectboundingbox-content-clip-transform-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-objectboundingbox-content-clip-transform.svg: Removed.
* LayoutTests/svg/clip-path/mask-objectboundingbox-content-clip.svg: Removed.
* LayoutTests/svg/clip-path/mask-userspaceonuse-content-clip-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-userspaceonuse-content-clip-transform-expected.svg: Removed.
* LayoutTests/svg/clip-path/mask-userspaceonuse-content-clip-transform.svg: Removed.
* LayoutTests/svg/clip-path/mask-userspaceonuse-content-clip.svg: Removed.

Canonical link: <a href="https://commits.webkit.org/273931@main">https://commits.webkit.org/273931@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/3666f589c0cacf70d8d25672160e06f8743465e0

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/37184 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/16085 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/39481 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/39755 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/33185 "Built successfully") 
| | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/18762 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/13228 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/31675 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/37747 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/13579 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/32728 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/11823 "Passed tests") | 
| | [❌ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/11818 "Unexpected infrastructure issue, retrying build") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/33374 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/41012 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/33676 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/33749 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/37724 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/12153 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/9946 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/35869 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/13772 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/8410 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/12509 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/13036 "Built successfully") | | |

### CODE REVIEW

**Review by nikolaszimmermann — COMMENTED** [review]
While I agree with the change, it makes it harder to run tests right now for LBSE, since we only run tests in svg/ right now. That would need to change, to at least include `imported/w3c/...css-masking/clip-path-svg-content/`? Anything else?

We should think about extending the LBSE baselines outside of svg/, if we merge this.

**Comment by rwlbuis** [comment]
> While I agree with the change, it makes it harder to run tests right now for LBSE, since we only run tests in svg/ right now. That would need to change, to at least include `imported/w3c/...css-masking/clip-path-svg-content/`? Anything else?
> 
> We should think about extending the LBSE baselines outside of svg/, if we merge this.

I think the wpt svg tests likely have unique, useful tests not in WebKit svg tests, so I am trying to locally run both when testing LBSE, I think the test runs do not take that long.

**Comment by nikolaszimmermann** [comment]
No doubt, just please update the instructions in the TestExpectations file in a follow-up PR - so I won't forget to run any directories for further testing.

**Review by nikolaszimmermann — APPROVED** [review]
rs=me

**Pull request merged**
