### PR TITLE
[Python3] Migrate Tools/CISupport to Python3

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 4510bdae57343552b89fc9be070d28836c37d3f0
<pre>
[Python3] Migrate Tools/CISupport to Python3
<a href="https://bugs.webkit.org/show_bug.cgi?id=237148">https://bugs.webkit.org/show_bug.cgi?id=237148</a>
&lt;rdar://problem/89430395 &gt;

Reviewed by Aakash Jain.

* Tools/CISupport/build-webkit-org/committer_auth_unittest_old.py: Removed.
* Tools/CISupport/build-webkit-org/loadConfig_unittest.py: Change shebang to Python 3.
* Tools/CISupport/build-webkit-org/make_passwords_json.py: Change shebang to Python 3,
make Python 3 compatible.
* Tools/CISupport/ews-build/email_unittest.py: Change shebang to Python 3.
* Tools/CISupport/ews-build/loadConfig_unittest.py: Ditto.
* Tools/CISupport/win/kill-old-processes: Ditto.

Canonical link: <a href="https://commits.webkit.org/247754@main">https://commits.webkit.org/247754@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@290453">https://svn.webkit.org/repository/webkit/trunk@290453</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by aj062** [comment]
Most of it looks fine. Just little worried about moving `kill-old-processes` to python3. Is that well tested? If not, might consider testing it separately (and maybe moving it to another PR, so that it doesn't block rest of the changes)

**Comment by JonWBedard** [comment]
> Most of it looks fine. Just little worried about moving `kill-old-processes` to python3. Is that well tested? If not, might consider testing it separately (and maybe moving it to another PR, so that it doesn't block rest of the changes)

`kill-old-processes` is not a complicated script. It's simple enough that I can run it on Mac to check for Python 3 compatibility.

**Comment by aj062** [comment]
Actually we are already invoking it with python3 in ews/build.webkit.org, since http://trac.webkit.org/changeset/281673/webkit

**Review by aj062 — APPROVED** [review]

**Comment by JonWBedard** [comment]
Landed https://commits.webkit.org/247754@main (4510bdae5734)!

**Pull request merged**
