### PR TITLE
Remove few `css3/filters` local tests in favor of WPT

### PR DESCRIPTION
**Pull request by Ahmad-S792**
#### 407efa0c74c72a22984add7e24b40c76645b7e1a
<pre>
Remove few `css3/filters` local tests in favor of WPT

<a href="https://bugs.webkit.org/show_bug.cgi?id=278089">https://bugs.webkit.org/show_bug.cgi?id=278089</a>
<a href="https://rdar.apple.com/133827167">rdar://133827167</a>

Reviewed by Brent Fulgham.

This patch removes local tests in favor of WPT tests.

effect-reference-after.html -&gt; effect-reference-after-001.html
bug419429.html -&gt; filter-url-to-non-existent-filter-001.html
effect-drop-shadow-clip-abspos.html -&gt; filters-drop-shadow-002.html
effect-reference-add-hw.html -&gt; effect-reference-add-hw-001.html
effect-reference-on-span-crash.html -&gt; effect-reference-on-span.html
effect-reference-on-transparent-element.html -&gt; same name
effect-reference-source-alpha-hw.html -&gt; effect-reference-source-alpha-002.html
effect-reference-source-alpha-not-first.html -&gt; effect-reference-source-alpha-001.html
effect-reference-external.html -&gt; svg-relative-urls-002.html
effect-reference-local-url-with-base.html -&gt; effect-reference-local-url-with-base-001.html
effect-reference-rename.html -&gt; effect-reference-rename-001.html
effect-reference-reset-style-delete-crash.html -&gt; same name
reference-filter-update-on-attribute-change.html -&gt; reference-filter-update-on-attribute-change-001.html
remove-filter-repaint.html -&gt; same name

* LayoutTests/css3/filters/effect-reference-after-expected.html: Removed.
* LayoutTests/css3/filters/effect-reference-after.html: Removed.
* LayoutTests/imported/blink/css3/filters/bug419429-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/bug419429.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-drop-shadow-clip-abspos-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-drop-shadow-clip-abspos.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-add-hw-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-add-hw.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-span-crash-expected.txt: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-span-crash.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-transparent-element-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-transparent-element.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-hw-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-hw.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-not-first-expected.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-not-first.html: Removed.
* LayoutTests/css3/filters/effect-reference-external-expected.txt: Removed.
* LayoutTests/css3/filters/effect-reference-external.html: Removed.
* LayoutTests/css3/filters/effect-reference-local-url-with-base-expected.html: Removed.
* LayoutTests/css3/filters/effect-reference-local-url-with-base.html: Removed.
* LayoutTests/css3/filters/effect-reference-rename-expected.html: Removed.
* LayoutTests/css3/filters/effect-reference-rename.html: Removed.
* LayoutTests/css3/filters/effect-reference-reset-style-delete-crash-expected.txt: Removed.
* LayoutTests/css3/filters/effect-reference-reset-style-delete-crash.html: Removed.
* LayoutTests/css3/filters/reference-filter-update-on-attribute-change-expected.html: Removed.
* LayoutTests/css3/filters/reference-filter-update-on-attribute-change.html: Removed.
* LayoutTests/css3/filters/remove-filter-repaint-expected.html: Removed.
* LayoutTests/css3/filters/remove-filter-repaint.html: Removed.
* LayoutTests/platform/glib/TestExpectations:

Canonical link: <a href="https://commits.webkit.org/282307@main">https://commits.webkit.org/282307@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/eac4196021d721349a8bf4a8cd16b8370b11a16e

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/62558 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/41913 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/15153 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/66542 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/13110 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/49600 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/13446 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/50408 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/9036 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/65627 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/38949 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/54181 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/31150 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/35669 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/11515 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/12038 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/57262 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/11831 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/68271 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/6504 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/11516 "Found 1 new test failure: workers/worker-user-gesture.html (failure)") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/57781 "Found 3 new test failures: imported/w3c/web-platform-tests/content-security-policy/reporting/report-preload-and-consume.https.html imported/w3c/web-platform-tests/fetch/private-network-access/fetch.https.window.html imported/w3c/web-platform-tests/server-timing/server_timing_header-parsing.https.html (failure)") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/6533 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/54227 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/57979 "Passed tests") | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/13927 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/5423 "Passed tests") | | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/37713 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/38798 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/39895 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/38542 "Built successfully") | | |

### CODE REVIEW

**Comment by brentfulgham** [comment]
I think this is a good idea in general, but I'm not familiar enough with the details of our filter tests to know if the WPT tests cover the precise range of behavior of our internal tests. I'm particularly nervous about `LayoutTests/imported/blink/css3/filters/bug419429.html` which may have exercised some old crash bug or other problem that might not be covered in WPT.

I think Said or another graphics expert should give these a double-check. I'll also try to look more closely myself in case the WPT test are obvious dupes of the internal ones.

**Comment by Ahmad-S792** [comment]
> I think this is a good idea in general, but I'm not familiar enough with the details of our filter tests to know if the WPT tests cover the precise range of behavior of our internal tests. I'm particularly nervous about `LayoutTests/imported/blink/css3/filters/bug419429.html` which may have exercised some old crash bug or other problem that might not be covered in WPT.
> 
> I think Said or another graphics expert should give these a double-check. I'll also try to look more closely myself in case the WPT test are obvious dupes of the internal ones.

Blink converted all these tests to WPT here - https://issues.chromium.org/issues/40123422 , I already checked our repo has equivalent WPT tests and also these tests are present on wpt.fyi as well.

**Comment by brentfulgham** [comment]
> Blink converted all these tests to WPT here - https://issues.chromium.org/issues/40123422 , I already checked our repo has equivalent WPT tests and also these tests are present on wpt.fyi as well.

Ah! That is indeed strong evidence that it is safe to remove those. That leaves us with these webkit-specific tests:

```
* LayoutTests/css3/filters/effect-reference-after.html: Removed.
* LayoutTests/imported/blink/css3/filters/bug419429.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-drop-shadow-clip-abspos.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-add-hw.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-span-crash.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-on-transparent-element.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-hw.html: Removed.
* LayoutTests/imported/blink/css3/filters/effect-reference-source-alpha-not-first.html: Removed.
* LayoutTests/css3/filters/effect-reference-external.html: Removed.
* LayoutTests/css3/filters/effect-reference-local-url-with-base.html: Removed.
* LayoutTests/css3/filters/effect-reference-rename.html: Removed.
* LayoutTests/css3/filters/effect-reference-reset-style-delete-crash.html: Removed.
* LayoutTests/css3/filters/reference-filter-update-on-attribute-change.html: Removed.
* LayoutTests/css3/filters/remove-filter-repaint.html: Removed.
```

We need to confirm that we have identical coverage in WPT for these items. That's what I'm hoping to get @shallawa 's feedback about.

**Comment by brentfulgham** [comment]
> We need to confirm that we have identical coverage in WPT for these items. That's what I'm hoping to get @shallawa 's feedback about.

And if we do not have this coverage, we should create WPT tests so that we DO get the coverage, and migrate them to WPT (but that would be a follow-up task).

**Review by brentfulgham — APPROVED** [review]
I have now reviewed all of the tests and agree that these seem to have been accurately converted to WPT tests, and that those tests are already in the local WebKit copy of these WPT directories. Therefore it is indeed safe to remove these duplicate tests.

**Comment by brentfulgham** [comment]
I also confirmed that we are not skipping any of these tests, so we should not lose any coverage relying on the WPT locations.

**Pull request merged**
