### PR TITLE
[LBSE] Outermost <svg> elements are not device-pixel aligned

### PR DESCRIPTION
**Pull request by nikolaszimmermann**
#### de2323d7e2c84bdeb40158ec03bf6130ed7584e6
<pre>
[LBSE] Outermost &lt;svg&gt; elements are not device-pixel aligned
<a href="https://bugs.webkit.org/show_bug.cgi?id=244966">https://bugs.webkit.org/show_bug.cgi?id=244966</a>

Reviewed by Rob Buis.

RenderLayer::paintLayerByApplingTransform() already contains all the code necessary to place
outer &lt;svg&gt; elements on device-pixel aligned boundaries. The subpixelOffset is applied as
transformation once for the outermost &lt;svg&gt; and thus to all descendants, since the
outermost &lt;svg&gt; establishes a stacking context. The subpixelOffset is not relevant below
RenderSVGRoot, since the rest of the SVG render tree is not applying device-pixel alignment.

This fixes a few rendering differences between LBSE / legacy, as indicated by the LBSE
specific expected.png removal.

Add two new tests covering inline SVG positioning non non-integer coordinates, probing the
sub-pixel / device-pixel alignment is done correctly.

A follow-up patch will revisit this topic, considering also composited elements, testing
their behaviour with respect to sub-pixel positioning + SVG + overflow + 3D transforms...

* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/absolute-sized-svg-in-xhtml-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/createImageElement2-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/embedding-external-svgs-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/image-parent-translation-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/junk-data-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/path-bad-data-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/custom/rootmost-svg-xy-attrs-expected.png:
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/hixie/error/012-expected.png: Removed.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/transforms/animated-path-inside-transformed-html-expected.png: Added.
* LayoutTests/platform/mac-monterey-wk2-lbse-text/svg/transforms/svg-css-transforms-expected.png: Removed.
* LayoutTests/svg/compositing/outermost-svg-with-border-padding.html: Allow 1px more difference (seen by ews-mac-debug-wk2).
* LayoutTests/svg/in-html/inline-svg-non-integer-position-display-block-expected.html: Added.
* LayoutTests/svg/in-html/inline-svg-non-integer-position-display-block.html: Added.
* LayoutTests/svg/in-html/inline-svg-non-integer-position-display-inline-expected.html: Added.
* LayoutTests/svg/in-html/inline-svg-non-integer-position-display-inline.html: Added.
* Source/WebCore/rendering/RenderLayerBacking.cpp:
(WebCore::snappedGraphicsLayer):
(WebCore::RenderLayerBacking::computeParentGraphicsLayerRect const):
(WebCore::RenderLayerBacking::updateGeometry):
(WebCore::RenderLayerBacking::adjustOverflowControlsPositionRelativeToAncestor):
(WebCore::RenderLayerBacking::updateMaskingLayerGeometry):
(WebCore::RenderLayerBacking::updateContentsRects):
(WebCore::RenderLayerBacking::updateClippingStackLayerGeometry):
(WebCore::RenderLayerBacking::setContentsNeedDisplayInRect):
* Source/WebCore/rendering/svg/RenderSVGRoot.cpp:
(WebCore::RenderSVGRoot::paintingAffectedByExternalOffset const):
(WebCore::RenderSVGRoot::updateFromStyle):
* Source/WebCore/rendering/svg/RenderSVGRoot.h:

Canonical link: <a href="https://commits.webkit.org/254558@main">https://commits.webkit.org/254558@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/c983d0b58b16afb24edebcfcd48631ee06ce3b62

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/89445 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/33999 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/20186 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/98765 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/155071 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/93453 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/32504 "Built successfully") | [  ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/27996 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/81802 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/93177 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95092 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/25817 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/76347 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/25748 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/80693 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/80596 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/68735 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/30263 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/14667 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/30001 "Built successfully") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/15607 "Found 1 new test failure: imported/w3c/web-platform-tests/html/browsers/history/the-history-interface/history_forward_cross_realm_method.html (failure)") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3198 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/33448 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/38568 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/32158 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/34698 "Passed tests") | |

### CODE REVIEW

**Comment by nikolaszimmermann** [comment]
This depends on PR #4157.

**Comment by nikolaszimmermann** [comment]
> This depends on PR #4157.
It is in -- rebased this branch, ready for review.

**Review by rwlbuis — APPROVED** [review]
LGTM.

**Comment by nikolaszimmermann** [comment]
mac-AS-debug-wk2 shows one test with 1px more in fuzziness 852 -> 853 pixels (it was already a range, so it's fine to raise).

**Pull request merged**
