### PR TITLE
WebCore and WebKit project files are missing some generated files, also stale items and overly complex paths

### PR DESCRIPTION
**Pull request by darinadler**
#### ff73fb7bddf6d7da0132154a3e2ac4dfb642c53f
<pre>
WebCore and WebKit project files are missing some generated files, also stale items and overly complex paths
<a href="https://bugs.webkit.org/show_bug.cgi?id=249276">https://bugs.webkit.org/show_bug.cgi?id=249276</a>
rdar://problem/103326681

Reviewed by Elliott Williams and David Kilzer.

* Source/WebCore/WebCore.xcodeproj/project.pbxproj: Removed duplicate entries for files that were
moved to the PAL project: TextEncodingDetector.h, TextEncodingDetectorICU.cpp,
TextEncodingRegistry.h/cpp, OpenGLSoftLinkCocoa.h/mm. Removed entries for many deleted files such
as WHLSLStandardLibraryFunctionMap.cpp. Updated many source files to use group-relative paths
rather than more complicated setups such as using BUILT_PRODUCTS_DIR, as part of this fixed paths
of some groups to make group-relative paths simpler.

* Source/WebKit/CMakeLists.txt: Removed WebAuthnProcess.

* Source/WebKit/WebKit.xcodeproj/project.pbxproj: Removed entries for deleted files related to
WebAuthn process. Updated many source files to use group-relative paths rather than more
complicated setups such as using BUILT_PRODUCTS_DIR, as part of this fixed the paths of some groups
to make group-relative paths simpler.

Canonical link: <a href="https://commits.webkit.org/258004@main">https://commits.webkit.org/258004@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/1496f0426f418a6fd4cdfa0ba5cdb0759f95d54b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/100600 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/9740 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/33639 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/109903 "Built successfully") | [❌ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/170184 "Found 1 new test failure: js/dom/Promise-reject-large-string.html (failure)") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/104585 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/10675 "Built successfully") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/85/builds/286 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/92997 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/107753 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/106379 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/8069 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/91321 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/34682 "Passed tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/89981 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/22710 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/77651 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/3454 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/24237 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/3469 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/85/builds/286 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/9580 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/43731 "Passed tests") | | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/74/builds/5474 "The change is no longer eligible for processing.") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/5261 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/2866 "Built successfully and passed tests") | | | |

### CODE REVIEW

**Review by ddkilzer — APPROVED** [review]
r=me

**Review by emw-apple — APPROVED** [review]

**Comment by ddkilzer** [comment]
GitHub says there are merge conflicts in `Source/WebCore/WebCore.xcodeproj/project.pbxproj`.  (Wish that was a little more visible when scrolling down the page.)

**Comment by darinadler** [comment]
Yes I will resolve those before landing. They are new conflicts that arose while this awaited review.

**Comment by darinadler** [comment]
I will have to resolve the new conflicts and upload again. This one is hard to merge!

**Pull request merged**
