### PR TITLE
ITP treats client injected JavaScript as user interaction

### PR DESCRIPTION
**Pull request by charliewolfe**
#### e2a9577bb29b17921ccf6a419b67566f69d77de9
<pre>
ITP treats client injected JavaScript as user interaction
<a href="https://bugs.webkit.org/show_bug.cgi?id=260807">https://bugs.webkit.org/show_bug.cgi?id=260807</a>
rdar://113989281

Reviewed by Brent Fulgham and John Wilander.

JavaScript evaluated by the client app is treated as if it was from a user gesture, so ITP
currently logs this as a user interaction. This leads to cases where a page can be granted
storage privileges without a meaningful user interaction.

The enum ProcessInteractionStyle already exists to indicate that logging user interaction
for a key press should be delayed until the key press is actually handled. Add another value
to this enum to indicate that a user gesture should never be logged as user interaction by ITP.

* Source/WebCore/bindings/js/ScriptController.cpp:
(WebCore::ScriptController::executeScriptInWorld):
* Source/WebCore/dom/UserGestureIndicator.h:
* Tools/TestWebKitAPI/Tests/WebKitCocoa/ResourceLoadStatistics.mm:
(TEST):

Canonical link: <a href="https://commits.webkit.org/267381@main">https://commits.webkit.org/267381@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/db27d217b176585f3bf099b08cc2118ad06da640

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/16426 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/16747 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/17182 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/18202 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/15404 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/16617 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/19977 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/16890 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/17772 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/16622 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/17049 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/14205 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/18998 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/14295 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/14889 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/21700 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/15281 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/15054 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/19380 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/15642 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/13285 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/14845 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/3938 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/19214 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/15467 "Built successfully") | | |

### CODE REVIEW

**Review by brentfulgham — APPROVED** [review]
Looks good, and safe. r=me

**Comment by johnwilander** [comment]
It looks like the new test only checks that evaluating JS does not count as a user gesture. Is there a corresponding test that checks that a real user interaction still counts? I'm especially thinking of for touch devices.

**Comment by charliewolfe** [comment]
> It looks like the new test only checks that evaluating JS does not count as a user gesture. Is there a corresponding test that checks that a real user interaction still counts? I'm especially thinking of for touch devices.

I don't see an existing test for this. I added a test to verify other user gestures still log user interaction.

**Review by johnwilander — APPROVED** [review]
r=me

**Pull request merged**
