### PR TITLE
Update ANGLE to 2022-08-01 (7399fc7f6606f3b30de3f1113002a2c73d36968b))

### PR DESCRIPTION
**Pull request by kkinnunen-apple**
#### a7f8eacef337cb6691dca0b742d00f80d4f3dd0f
<pre>
Update ANGLE to 2022-08-01 (7399fc7f6606f3b30de3f1113002a2c73d36968b))

Reviewed by Kenneth Russell.

Contains upstream commits:
git log --oneline 2a5193f6ceca4c8a7f27b324ad7da4aa60f968b3..7399fc7f6606f3b30de3f1113002a2c73d36968b --pretty=%h %s
7399fc7f6 infra: Update wrangling docs with Sheriff-o-Matic.
9af3ae0dc Roll vulkan-deps from 2d409ca4e3b6 to 73766817e984 (5 revisions)
a0eff7297 Vulkan: Reduce descriptorSets usage from UtilsVk
8f9e15cc9 Vulkan: avoid excessive log for FORMAT_IMPLEMENTATION_DEFINED
427086a9c Vulkan: remove SpirvVaryingPrecisionFixer
a629fb0a0 Roll VK-GL-CTS from e3066ef682d7 to 0170b4a25e36 (10 revisions)
cbab97d40 Remove needless IOSurface alignment validation
9c6c072c9 Roll vulkan-deps from d28e244d3e12 to 2d409ca4e3b6 (5 revisions)
326441d0a Roll SwiftShader from e8c074d7684b to 80aaa8a74b74 (6 revisions)
3ccaddf92 Vulkan: EXT_YUV_target: layout(yuv) support
f000215dd Vulkan: Optimize transform feedback buffer tracking
6142b8397 Vulkan: EXT_YUV_target: add vk feature
3dd6f5f74 Reland &quot;Disable share context lock for Chromium&quot;
5db09e9b9 Vulkan: Try allocate from existing DescriptorPool before create new
c48cfa02e Revert &quot;Disable share context lock for Chromium&quot;
08df7ce44 Test Runner: Disable --bot-mode on Fuchsia.
39c5f3219 Roll vulkan-deps from 7158d6e8eaad to d28e244d3e12 (3 revisions)
6fb8d909e Roll SwiftShader from 1739966fee2a to e8c074d7684b (4 revisions)
a04f8c58a Roll Chromium from 85c57e6023c8 to e810ac85e1c8 (442 revisions)
e7affd555 d3d11: allow selecting render device by PCI vendor/device ID
e3701f90e Remove WARN() in getPixelFormatInfo()
80022b96c Vulkan: Fix xfb buffer redefine to smaller size
fb97cfcd6 Roll chromium_revision 1201dfbc62..85c57e6023 (1027387:1028671)
b8e741d25 Vulkan: allow selecting render device by PCI device/vendor IDs
e1741f4ba Disable share context lock for Chromium
0dc29af95 Context: Also disable ASTC on mState when emulation is disabled.
630e50c31 Roll SwiftShader from b6ddcf331865 to 1739966fee2a (1 revision)
255893f63 Roll vulkan-deps from 03d4f8e01303 to 7158d6e8eaad (3 revisions)
b968b6c99 Test Utils: Get executable path from command line.
3f59c2856 D3D11: implement image load/store format reinterpretation.
83dfd8398 dEQP: Allow running against system GL.
a78c01b27 [Cast Convergence] Remove is_chromecast in ANGLE.
5c5a14c30 Tests: Add Battle Of Polytopia trace.
4e0462563 Translator: Fix deep copy of loops and branches
313884ce5 Vulkan: Move dmabuf extensions support
39119a8b3 Roll vulkan-deps from 50a58c2a73cb to 03d4f8e01303 (3 revisions)
54da29525 Remove suppressions added due to VK_ATTACHMENT_UNUSED bug
a3cda6071 Roll SwiftShader from 16e026a959f1 to b6ddcf331865 (2 revisions)
88dd868f2 FrameCapture: Fix and optimize multi-context reset
be7084466 Vulkan: Remove the bindEmptyForUnusedDescriptorSets workaround
673a41ae6 dEQP: Isolate headers in tcuANGLEPlatform.h.
8e63c6e8f Remove suppressions for tests which pass with Intel Mesa 20.0.8
df879d491 Return INVALID_VALUE for online BC compression
4a14030d3 Avoid streaming a wide string to a (narrow) ostringstream.
8d2988f70 infra: Add sheriff_rotations to luci properties.
da2d1e0a9 Update extension support (July 25, 2022).
3b020cc17 Roll VK-GL-CTS from cb1dc55bc044 to e3066ef682d7 (11 revisions)
4fdc37545 Roll vulkan-deps from f00ffae9c319 to 50a58c2a73cb (6 revisions)
e3933465d Vulkan: Allow dither for some color blend modes
fd89020c2 FrameCapture: Reset VertexArray state
00e48c135 Vulkan: Destroy DescriptorPoolHelper when its unused.
b23ea6802 Vulkan: Re-enable multisample framebuffer fetch
6d6b99673 Roll Chromium from d2f8d8516036 to 1201dfbc6265 (220 revisions)
2b43d630a Remove unused (and incorrect on Android) mTestSuiteName.
c2aaeadb9 Vulkan: Skip nonexistent attachments when calculating samples
72795eb0f Roll Chromium from 9d88fd8904e8 to d2f8d8516036 (510 revisions)
788c5454e Roll VK-GL-CTS from 692df061716d to cb1dc55bc044 (1 revision)
90fa855b4 Suppress the early_fragment_tests PLS test on Pixel 6
adeb750d7 Validate that skipped tests are skipped by suite.
08df2000c Roll vulkan-deps from 5cb0a31b27bf to f00ffae9c319 (7 revisions)
7d6f3d94e glValidateProgramPipelines: Skip draw state error check
c95e2b7d2 Remove a few cases that are skipped by end2end.
d57ce8150 Use &quot;readwrite&quot; PLS images when possible
aa7e6751a Automatically enable early_fragment_tests when PLS is declared
77aa34ae1 Add support for PLS as function arguments
3a0d7249f Ignore tests skipped by the suite.
d0fe12db8 Vulkan: Disable Multisample Framebuffer Fetch
b78d471ae Add angle_enable_share_context_lock build flag
115d83618 Switch Linux Intel testing to UHD 630 GPU
c460c2991 Implement GLSL additions for ANGLE_shader_pixel_local_storage
25f7d39fc Roll vulkan-deps from c42337d9ef75 to 5cb0a31b27bf (10 revisions)
dba01bdc8 Roll Chromium from 16ae342caefb to 9d88fd8904e8 (515 revisions)
992018c7b Suppress VUID-VkGraphicsPipelineCreateInfo-pStages-06896.
1e6195033 Skip TracePerfTest vulkan_car_chase on Linux Intel
84bfb6cef Roll Chromium from 806fa2d991d9 to 16ae342caefb (283 revisions)
fc97b2da2 Vulkan: Always use depth&lt;=256 AHB image siblings
b860fa453 Vulkan: account for yuvCscStandard in switch validation
be24acbde Vulkan: Support GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES
bd82a5e4a Vulkan: __samplerExternal2DY2YEXT-aware ProgramExecutableVk
6c418f8c5 Vulkan: __samplerExternal2DY2YEXT-aware TextureVk
53d40aed3 Vulkan: Destroy descriptorSet cache when BufferHelper destroyed
c7459a465 Vulkan: Destroy descriptorSet cache when BufferBlock destroyed
3fbd4e40d Roll Chromium from a1cfdbdf4c3b to 806fa2d991d9 (256 revisions)
8df0c53ef Vulkan: Split suballocation out into it&apos;s own file
45e5cf014 Vulkan: Implement ASTC emulation.
3d369ac6d Roll vulkan-deps from b22fee44bf09 to c42337d9ef75 (4 revisions)
861602360 Roll Chromium from 14dcb8bf5432 to a1cfdbdf4c3b (455 revisions)
a3899c532 Capture/Replay: drop context capture call in EGL capture templ
645ee1943 Vulkan: Only modify input attachment images for FF MSAA fix up
d4e54b819 Vulkan: Clean up garbage of last completed submission too
5f7e0e505 Translator: Remove early fragment tests transformation
f1dac70d5 Remove platform skips for cookie_run and real_cricket
3baa867c4 Vulkan: Fix image arguments passed to functions in GLSL
2c3c45ee6 Roll VK-GL-CTS from ef9a6635208b to 692df061716d (12 revisions)
466fc0c61 Add new prerequisite type for GL_ENUM integers
bf3692851 Suppress SYNC-HAZARD-WRITE_AFTER_READ in vulkan_car_chase
e72694905 Remove python version check in presubmit
68879b81b Minor fixes: typos, links.
b569fc1a6 Roll vulkan-deps from 3204c0c798d3 to b22fee44bf09 (5 revisions)
c210f8812 Roll Chromium from d19b3e76906e to 14dcb8bf5432 (534 revisions)
c4004751b Metal: texture allocation failures handled incorrectly
496bddf31 Skip mutable texture upload tests through feature
15cc00130 Add a GL_ANGLE_shader_pixel_local_storage extension
1ae7a56c9 Vulkan: Fix double clear of AHBs
8f2fbbebb Inline all metal command buffer decoder methods
ebf14fe37 Return EXIT_FAILURE from run_perf_tests.py if any test failed
a4606f62a Roll vulkan-deps from 07a6dec37162 to 3204c0c798d3 (8 revisions)
47e424034 Roll Chromium from 3840fb1fefb2 to d19b3e76906e (447 revisions)
ea1382365 Remove suppression for passing dEQP tests
d9763c60d Disable mutable texture upload on Win/Intel devs
5911243cd Fix linkValidateTransformFeedback for glLinkProgram
c8ba755a2 Update version of lucicfg for angle repo and regen config
01092c48c Vulkan: Destroy descriptorSet cache when shader image is destroyed
e25137c00 Vulkan: Move DescriptorSet cache to DynamicDescriptorPool
6cbf0c012 Vulkan: Only apply MSAA FF fix up if executable has FF
eaf77ef32 Metal fails to compile uniform blocks in ternary statements
5d59c0eb1 Skip EGLBufferAgeTest.QueryBufferAge on Linux Intel Vulkan
4b20c309f Roll Chromium from f224faaabcd0 to 3840fb1fefb2 (566 revisions)
9a086ec7d Roll vulkan-deps from 50b3fdf7ad7d to 07a6dec37162 (2 revisions)
eb88a2ac8 Capture/Replay: Handle the case when there is no context
16e7226da Propagate device type in ReuseUnterminatedDisplay.
b038605c2 Fix test dependency on EGL initialization elsewhere.
32c5fd8ac Reland &quot;Vulkan: Flush texture updates more often&quot;
b6d463308 Add MB config for linux-exp-test
0d3ecf463 Vulkan: Multisample Framebuffer Fetch
12efe5b27 Cleanup invalid EGL handles only if app called eglTermiate
5897d6f59 GL: Add emulateCopyTexImage2D workaround
8056a5ee4 Add Linux Intel experimental standalone bot
b47603e04 Implement GL_NV_read_depth_stencil
da9c06780 Revert &quot;Spawn via vpython when old module detected.&quot;
062788fa6 Roll vulkan-deps from 4d09ee266d3c to 50b3fdf7ad7d (3 revisions)
a04d6c3ee Roll Chromium from 2b7014d6e622 to f224faaabcd0 (511 revisions)
a2f64b81d Roll vulkan-deps from c119749eff1f to 4d09ee266d3c (17 revisions)
d88f79063 Extra buffer logging/checking on Android Cuttlefish
4f7d2d028 Vulkan: SPIR-V Gen: Apply Flat to gl_ViewID_OVR in FS
3622f1474 D3D: Fix compile after CreateTemporaryFile changes
61e014832 Roll Chromium from eb8af3adeed3 to 2b7014d6e622 (496 revisions)
c525ccf7d Vulkan: SPIR-V Gen: Apply Flat to int inputs in FS
82ff27bff Add Metal to the perf tests
3b5b7a29e Caps: Check if ANGLE_texture_multisample is enabled
056c6c7c2 Metal: Skip invalidation of emulated formats
659fb3c50 Roll Chromium from 14abb4e33fdf to eb8af3adeed3 (542 revisions)
adcc64539 Roll VK-GL-CTS from 867b77cee987 to ef9a6635208b (14 revisions)
bf52137bc Roll SwiftShader from 1d6a1036bdb3 to 16e026a959f1 (1 revision)
ac838109a Roll Chromium from 84d7af71045d to 14abb4e33fdf (505 revisions)
94bbb40a4 GL: Enable pack skip emulation on all Apple drivers
a1f8049ab Vulkan: Remove VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT
9931dfd51 D3D9: Implement float sources for Image9::copyFromRTInternal
925ec6b5a Clamp viewport dimensions on store
fb3e2def8 Extend labelObject functionality
929a37520 Roll SwiftShader from 7987bda077c8 to 1d6a1036bdb3 (2 revisions)
a4e00c645 Expose EXT_compressed_ETC1_RGB8_sub_texture on Metal and GL
cd1b22eec Roll vulkan-deps from 34e0281e9664 to c119749eff1f (5 revisions)
3a52a7967 Roll Chromium from 0820cef93768 to 84d7af71045d (436 revisions)
afcca86c6 Fix ValidateCompressedTexSubImage3D compressed format check
0f688d620 Metal: Allow Surfaces to be created without depth &amp; stencil
053d152da Vulkan: Resolve GoogleX MSRTSS conflict with EXT
81a69da60 Vulkan: min/mag filters follow chroma filter value
916a35dd0 Merge getTempPath and CreateTemporaryFile
39e88e6e5 Handle OOM in SwapChain11::getRenderTargetShaderResource
5a65a2b1c Fix samples&apos; arguments to SampleApplication
007a4f061 Vulkan: Wayland resize callback
3e5de4acc Add a test that passes image2D handles as function args
a29353f09 Roll SwiftShader from d1116fa9e9dc to 7987bda077c8 (1 revision)
514abb060 Roll vulkan-deps from 24ed8b7a6bd7 to 34e0281e9664 (9 revisions)
2437b73b6 Roll Chromium from 532c25a8e2ac to 0820cef93768 (270 revisions)
9070e279a Vulkan: Handle platforms that have imprecise float division issues
5ef62fa19 Roll chromium_revision b1ab0fbd60..532c25a8e2 (1020158:1020841)
1154cc46d Vulkan: Fix round-after-dither logic
06bd0c114 angle: set $build/goma[&quot;use_luci_auth&quot;] = True
4a5c1e1f2 Roll vulkan-deps from 8e3184380881 to 24ed8b7a6bd7 (2 revisions)
86c735bfe pls: Rename GL_DISABLED_ANGLE -&gt; GL_DISABLE_ANGLE
44d8bf760 Vulkan: Support EGL_EXT_platform_wayland
0c46c2d9f Vulkan: Support DRM_FORMAT_MOD_LINEAR
2a941833c Roll vulkan-deps from cf47f3e49a61 to 8e3184380881 (2 revisions)
da984303f Add a pls test for in-shader coherency
85b056015 Add a pls test for load-only storage
bd6d1e175 Roll VK-GL-CTS from e22ec5fc4cbf to 867b77cee987 (1 revision)
8e79a2226 Roll Chromium from 8bf3474ad33a to b1ab0fbd602a (1173 revisions)
723cc8802 Reland &quot;Reland &quot;Vulkan: Destroy DescriptorSet cache when it becomes invalid&quot;&quot;
3b107ee1f Roll vulkan-deps from 863435cf0898 to cf47f3e49a61 (19 revisions)
4a5fe6fb5 Roll SwiftShader from 90fdde382489 to d1116fa9e9dc (13 revisions)
7cb0622cb BlitGL: Fix LUMAWorkaround for half-float copies
defd99dc4 Update MSRTSS vulkan struct to final version
4b745c2bf Revert &quot;Reland &quot;Vulkan: Destroy DescriptorSet cache when it becomes invalid&quot;&quot;
6cd08bc23 Vulkan: Don&apos;t optimize away flush after clear for single buffer
ac1af3881 Add presubmit check for .gclient file
2d5defc71 Roll vulkan-deps from 1fe7a0ab555e to 863435cf0898 (7 revisions)
90edbd94e Metal: Support GL_ANGLE_provoking_vertex
c66e16521 Roll vulkan-deps from 470172656108 to 1fe7a0ab555e (1 revision)
1e96beb9f Suppress the new BestPractice VVL Error
c7fe43489 Roll SwiftShader from ec31f547750c to 90fdde382489 (6 revisions)
551a26aee Reland &quot;Vulkan: Destroy DescriptorSet cache when it becomes invalid&quot;
4884e9de1 Add a pls test for maximum capacity
785353fd3 Support Desktop OpenGL context creation in end2end tests
61bcba898 Roll vulkan-deps from 20ef3c4c476b to 470172656108 (3 revisions)
45def3d4d Remove non-negative offsets restriction in D3D extension
4298a54ea Clean up OWNERS files
fd9301c1d Capture/Replay: Capture egl surface related calls
1fcfe3bbc Roll vulkan-deps from 137b026580e5 to 20ef3c4c476b (5 revisions)
3224b16a4 Roll Chromium from 1bfae54dd233 to 8bf3474ad33a (639 revisions)
d50b22764 Reland &quot;Vulkan: Support EGL_ANDROID_front_buffer_auto_refresh&quot;
fd256b0d9 Tests: Add Uber trace
ba737f47a Vulkan: Don&apos;t sync pipeline cache if warm up is effective
bb373176c Roll vulkan-deps from 11ad77222bfe to 137b026580e5 (1 revision)
b2683a3c2 Document angle_restricted_traces
26a314b45 Fix typos in multi-draw extension specs
1dc3385af libstdc++: move FramebufferHelper to cache utils
3a799ba5b Fix ValidateES3TexImageParametersBase for glTexImage*D
ce4e11d3c libANGLE: Add a unique ID to the Surface

Canonical link: <a href="https://commits.webkit.org/253206@main">https://commits.webkit.org/253206@main</a>
</pre>

### CODE REVIEW

**Review by kenrussell — APPROVED** [review]
Looks good to me. I specifically reviewed all changes in `src/libANGLE/renderer/metal` and `changes.diff`.

There are some merge conflicts (surprising) in some of ANGLE's test expectations files which will need to be resolved, ideally in favor of the ones coming from upstream ANGLE.

**Review by djg — APPROVED** [review]
:shipit:

**Comment by kenrussell** [comment]
For the record @kkinnunen-apple did you want one of us to apply `merge-queue`?

**Comment by djg** [comment]
> For the record @kkinnunen-apple did you want one of us to apply `merge-queue`?

I usually leave that to the author if they have committer privileges, so they can land it when they're happy.

**Pull request merged**
