### PR TITLE
[CMake][GTK][WPE] Make Thunder optional

### PR DESCRIPTION
**Pull request by obyknovenius**
#### 22eed5e8c7baaf0a58427f6d7ae63bddbb6c85b7
<pre>
[CMake][GTK][WPE] Make Thunder optional
<a href="https://bugs.webkit.org/show_bug.cgi?id=257116">https://bugs.webkit.org/show_bug.cgi?id=257116</a>

Reviewed by NOBODY (OOPS!).

Currently, Thunder is required when building WebKit using developer mode.
But the only environment where we have it preinstalled is Flatpak.

It is possible to disable it by setting `ENABLE_THUNDER` to `OFF`.
But it would be nice to make CMake autodetect if Thunder is available
at build time.

* Source/cmake/OptionsGTK.cmake:
* Source/cmake/OptionsWPE.cmake:
</pre>
https://github.com/WebKit/WebKit/commit/22eed5e8c7baaf0a58427f6d7ae63bddbb6c85b7

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/7399 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/7657 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/7832 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/9028 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/7604 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/9518 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/7582 "Built successfully") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/10489 "4 flakes 99 failures") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/7528 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/8586 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/6849 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/9137 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/5900 "Passed tests") | | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/14458 "2 flakes 115 failures") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/6294 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/7199 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/6845 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/10101 "1 api test failed or timed out") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/6982 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/7333 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/5996 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/7544 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/6684 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/1741 "Passed tests") | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/19/builds/1741 "The change is no longer eligible for processing.") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/10891 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/7749 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/7069 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/1881 "Passed tests") |

### CODE REVIEW

**Review by nikolaszimmermann — APPROVED** [review]
Makes sense -- especially since it is not available in any  distribution :-)

**Review by nikolaszimmermann — COMMENTED** [review]
We need to discuss this first, @clopez reminded me that we need Thunder for some multimedia tests -- I was not aware of that.

**Comment by clopez** [comment]
Think about this in this way: if the user is explicit about disabling the feature he can reason better about unexpected failures on layout tests or about some feature not working.
On the other hand if we allow CMake to auto-detect features that can be enabled then this can become a foot-gun.

**Review by mcatanzaro — CHANGES_REQUESTED** [review]
I agree with Carlos Lopez. We should not consider Thunder_FOUND when deciding whether it should be enabled by default or not. [I wrote a blog post about this](https://blogs.gnome.org/mcatanzaro/2022/07/15/best-practices-for-build-options/) (see rule 3).

- I think it's find for thunder to default to either `OFF` or `${ENABLE_EXPERIMENTAL_FEATURES}`. Maybe we could go a little above and beyond with the error message, since if you search Google for "thunder" you will never find https://github.com/Sparkle-CDM/sparkle-cdm
- But actually, we don't seem to need `ENABLE_THUNDER` at all. It does nothing if `ENABLE_ENCRYPTED_MEDIA` is not enabled, and for WPE/GTK you need it to do anything with encrypted media (I think?). So the option should just be removed.

**Comment by philn** [comment]
Ah sorry I misunderstood what you meant, nevermind.

**Review by calvaris — CHANGES_REQUESTED** [review]
This really needs discussion.

**Comment by huanghaiyang** [comment]
how to install thunder?

**Comment by philn** [comment]
https://github.com/Sparkle-CDM/sparkle-cdm

**Pull request closed without merging**
