### PR TITLE
WPT Re-import css/css-color

### PR DESCRIPTION
**Pull request by mdubet**
#### 10d2ed1d8cb56cecb3a780cbadf72a25f4ce969a
<pre>
WPT Re-import css/css-color
<a href="https://bugs.webkit.org/show_bug.cgi?id=250416">https://bugs.webkit.org/show_bug.cgi?id=250416</a>
rdar://104095501

Reviewed by Tim Nguyen.

WPT 89f67a0

* LayoutTests/TestExpectations:
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/color-resolving-expected.txt: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/deprecated-sameas-018.html:
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/nested-color-mix-with-currentcolor-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/nested-color-mix-with-currentcolor.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/parsing/color-computed-lab-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/parsing/color-computed-lab.html:
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t32-opacity-offscreen-with-alpha-c.xht:
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-b-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-b-ref.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-b.xht: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-multiple-boxes-c-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-multiple-boxes-c-ref.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t422-rgba-onscreen-multiple-boxes-c.xht: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t425-hsla-onscreen-b-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t425-hsla-onscreen-b.xht: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t425-hsla-onscreen-multiple-boxes-c-expected.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/t425-hsla-onscreen-multiple-boxes-c.xht: Removed.
* LayoutTests/imported/w3c/web-platform-tests/css/css-color/w3c-import.log:
* LayoutTests/platform/gtk/TestExpectations:

Canonical link: <a href="https://commits.webkit.org/259182@main">https://commits.webkit.org/259182@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/db9b36d352ed67a0263e4564192485cddc877f91

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/104291 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/13378 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/37199 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/113504 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/173793 "Built successfully and passed tests") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/14463 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/4293 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/96513 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/112549 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/110060 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/11133 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/94201 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/38789 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/92995 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/25812 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/80457 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/6738 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/70/builds/27169 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/6872 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/3726 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/12887 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/46727 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/6325 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/8658 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by nt1m — COMMENTED** [review]
Can we do a directory wide sync of css-color? (also can the commit message metadata be completed?)

**Comment by maattdd** [comment]
Updated to sync the whole css-color folder

**Comment by mdubet** [comment]
Changed to sync the entire css-color folder

**Review by nt1m — APPROVED** [review]

**Comment by nt1m** [comment]
@mdubet I went ahead and fixed the failure (due to now supporting currentColor + color-mix) along with updating 1 test to latest upstream.

**Pull request merged**
