### PR TITLE
[JSC] Remove useWasmTypedFunctionReferences and useWasmExtendedConstantExpressions

### PR DESCRIPTION
**Pull request by Constellation**
#### 760c07823975ffd394576c368a7757728013489a
<pre>
[JSC] Remove useWasmTypedFunctionReferences and useWasmExtendedConstantExpressions
<a href="https://bugs.webkit.org/show_bug.cgi?id=278173">https://bugs.webkit.org/show_bug.cgi?id=278173</a>
<a href="https://rdar.apple.com/133960341">rdar://133960341</a>

Reviewed by Yijia Huang.

Remove already shipped feature flags useWasmTypedFunctionReferences and useWasmExtendedConstantExpressions.
In particular, our code was messed up so much with useWasmTypedFunctionReferences flag on/off. Removing
this flag significantly simplifies our code base, easier to maintain.

* JSTests/wasm.yaml:
* JSTests/wasm/extended-const/extended-const.js:
* JSTests/wasm/extended-const/flag-turned-off.js: Removed.
* JSTests/wasm/function-references/block_signature.js:
* JSTests/wasm/function-references/br_on_null.js:
* JSTests/wasm/function-references/bug243265.js:
* JSTests/wasm/function-references/call_ref.js:
* JSTests/wasm/function-references/local_init.js:
* JSTests/wasm/function-references/ref_as_non_null.js:
* JSTests/wasm/function-references/ref_types.js:
* JSTests/wasm/function-references/table.js:
* JSTests/wasm/function-references/table_init.js:
* JSTests/wasm/gc/any.js:
* JSTests/wasm/gc/array_new_data.js:
* JSTests/wasm/gc/array_new_elem.js:
* JSTests/wasm/gc/array_new_fixed.js:
* JSTests/wasm/gc/array_new_fixed_long.js:
* JSTests/wasm/gc/arrays.js:
* JSTests/wasm/gc/block.js:
* JSTests/wasm/gc/br_on_cast.js:
* JSTests/wasm/gc/bug247874.js:
* JSTests/wasm/gc/bug250613.js:
* JSTests/wasm/gc/bug252299.js:
* JSTests/wasm/gc/bug252538.js:
* JSTests/wasm/gc/bug252719.js:
* JSTests/wasm/gc/bug254226.js:
* JSTests/wasm/gc/bug254412.js:
* JSTests/wasm/gc/bug254413.js:
* JSTests/wasm/gc/bug254414.js:
* JSTests/wasm/gc/bug258127.js:
* JSTests/wasm/gc/bug258128.js:
* JSTests/wasm/gc/bug258499.js:
* JSTests/wasm/gc/bug258795.js:
* JSTests/wasm/gc/bug258796.js:
* JSTests/wasm/gc/bug258801.js:
* JSTests/wasm/gc/bug258804.js:
* JSTests/wasm/gc/bug258805.js:
* JSTests/wasm/gc/bug260516.js:
* JSTests/wasm/gc/bug262862.js:
* JSTests/wasm/gc/bug262863.js:
* JSTests/wasm/gc/bug265721.js:
* JSTests/wasm/gc/bug265742.js:
* JSTests/wasm/gc/bug265927.js:
* JSTests/wasm/gc/bug266043.js:
* JSTests/wasm/gc/bug266056.js:
* JSTests/wasm/gc/bug266127.js:
* JSTests/wasm/gc/bug266167.js:
* JSTests/wasm/gc/bug266249.js:
* JSTests/wasm/gc/bug267381.js:
* JSTests/wasm/gc/bulk-array.js:
* JSTests/wasm/gc/call_indirect.js:
* JSTests/wasm/gc/call_ref.js:
* JSTests/wasm/gc/casts.js:
* JSTests/wasm/gc/const-exprs-flag-off.js: Removed.
* JSTests/wasm/gc/const-exprs.js:
* JSTests/wasm/gc/eq.js:
* JSTests/wasm/gc/exception.js:
* JSTests/wasm/gc/extern.js:
* JSTests/wasm/gc/i31.js:
* JSTests/wasm/gc/js-api.js:
* JSTests/wasm/gc/limits.js:
* JSTests/wasm/gc/linking.js:
* JSTests/wasm/gc/packed-arrays.js:
* JSTests/wasm/gc/rec.js:
* JSTests/wasm/gc/simd.js:
* JSTests/wasm/gc/structs.js:
* JSTests/wasm/gc/sub.js:
* JSTests/wasm/gc/subtyping.js:
* JSTests/wasm/gc/table_init.js:
* JSTests/wasm/js-api/type-reflection-concrete-types.js:
* JSTests/wasm/references/element_active_mod.js:
(refNullExternInElemsSection):
* JSTests/wasm/references/func_ref.js:
(assert.eq.instance.exports.fix):
(assert.throws.fun): Deleted.
(assert.throws): Deleted.
(string_appeared_here.End.End.Function.End.Code.End.WebAssembly.imp.ref): Deleted.
(string_appeared_here.End.End.Function.End.Code.End.WebAssembly): Deleted.
(GetLocal.0.I32Const.0.TableSet.0.End.End.WebAssembly.fun): Deleted.
(GetLocal.0.I32Const.0.TableSet.0.End.End.WebAssembly.assert.throws): Deleted.
(GetLocal.0.I32Const.0.TableSet.0.End.End.WebAssembly): Deleted.
(assert.throws.doTest): Deleted.
(let.importedFun.of): Deleted.
(makeFuncrefIdent.fun): Deleted.
(b.b.GetLocal.0.End.End.End.WebAssembly): Deleted.
(foo): Deleted.
* JSTests/wasm/references/is_null.js:
(checkRefNullWithI32ImmType):
* JSTests/wasm/references/table_misc.js:
(GetLocal.0.GetLocal.1.TableGrow.0.End.End.WebAssembly): Deleted.
* JSTests/wasm/references/validation.js:
(assert.throws.new.WebAssembly.Module.bin):
(assert.throws): Deleted.
* JSTests/wasm/stress/funcref-types.js:
* JSTests/wasm/v8/regress/regress-1364036.js:
* Source/JavaScriptCore/runtime/Options.cpp:
(JSC::disableAllWasmOptions):
* Source/JavaScriptCore/runtime/OptionsList.h:
* Source/JavaScriptCore/wasm/WasmBBQJIT.cpp:
(JSC::Wasm::BBQJITImpl::BBQJIT::addRefFunc):
* Source/JavaScriptCore/wasm/WasmConstExprGenerator.cpp:
(JSC::Wasm::parseExtendedConstExpr):
(JSC::Wasm::evaluateExtendedConstExpr):
* Source/JavaScriptCore/wasm/WasmFormat.h:
(JSC::Wasm::isValueType):
(JSC::Wasm::isRefType):
(JSC::Wasm::isExternref):
(JSC::Wasm::isFuncref):
(JSC::Wasm::funcrefType):
(JSC::Wasm::externrefType):
(JSC::Wasm::isRefWithTypeIndex):
(JSC::Wasm::isTypeIndexHeapType):
(JSC::Wasm::isSubtype):
* Source/JavaScriptCore/wasm/WasmFunctionParser.h:
(JSC::Wasm::FunctionParser::pushLocalInitialized):
(JSC::Wasm::FunctionParser::resetLocalInitStackToHeight):
(JSC::Wasm::FunctionParser::typeToStringModuleRelative const):
(JSC::Wasm::FunctionParser&lt;Context&gt;::parse):
(JSC::Wasm::FunctionParser&lt;Context&gt;::checkLocalInitialized):
(JSC::Wasm::FunctionParser&lt;Context&gt;::parseExpression):
(JSC::Wasm::FunctionParser&lt;Context&gt;::parseUnreachableExpression):
* Source/JavaScriptCore/wasm/WasmOperations.cpp:
(JSC::Wasm::JSC_DEFINE_JIT_OPERATION):
(JSC::Wasm::JSC_DEFINE_NOEXCEPT_JIT_OPERATION):
* Source/JavaScriptCore/wasm/WasmParser.h:
(JSC::Wasm::ParserBase::parseBlockSignature):
(JSC::Wasm::ParserBase::parseHeapType):
(JSC::Wasm::ParserBase::parseValueType):
* Source/JavaScriptCore/wasm/WasmSectionParser.cpp:
(JSC::Wasm::SectionParser::parseTableHelper):
(JSC::Wasm::SectionParser::parseElement):
(JSC::Wasm::SectionParser::parseInitExpr):
* Source/JavaScriptCore/wasm/WasmTable.cpp:
(JSC::Wasm::FuncRefTable::FuncRefTable):
* Source/JavaScriptCore/wasm/js/JSWebAssemblyHelpers.h:
(JSC::defaultValueForReferenceType):
* Source/JavaScriptCore/wasm/js/WasmToJS.cpp:
(JSC::Wasm::wasmToJS):
* Tools/Scripts/run-jsc-stress-tests:

Canonical link: <a href="https://commits.webkit.org/282301@main">https://commits.webkit.org/282301@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/c6aeae19673a4f1f3ee80fc3e1577a49342ac1f1

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/62742 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/42098 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/15337 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/66762 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/13346 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/64862 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/49784 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/13630 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/50623 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/9218 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/65811 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/39152 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/54357 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/31300 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/35860 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/11686 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/12222 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/55852 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/57409 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/12017 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/68457 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/61985 "Built successfully and passed tests") | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/6688 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/11671 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/57939 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/6719 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/54410 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/58127 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/5595 "Passed tests") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/83748 "Built successfully") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/9452 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/37918 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/14732 "Passed tests") | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/38998 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/40109 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/38740 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | |

### CODE REVIEW

**Review by danlliu — COMMENTED** [review]
LGTM

**Comment by hyjorc1** [comment]
Why we remove `flag-turned-off.js` and `const-exprs-flag-off.js` completely?

**Comment by Constellation** [comment]
> Why can we remove `flag-turned-off.js` and `const-exprs-flag-off.js` completely?

These tests are just ensuring that they are working flag is off. And it is not testing some functionality we need to keep when flag is on.

**Review by hyjorc1 — APPROVED** [review]
r=me

**Comment by justinmichaud** [comment]
Nice

**Pull request merged**
