### PR TITLE
Update ANGLE to 2022-05-31 (b6a93d753bdd819ddc0dacb8cea554c86bc4c04e))

### PR DESCRIPTION
**Pull request by kenrussell**
#### 54f1485d92416e5b27b10fef5b47e9c4844f53d7
<pre>
Update ANGLE to 2022-05-31 (b6a93d753bdd819ddc0dacb8cea554c86bc4c04e))
<a href="https://bugs.webkit.org/show_bug.cgi?id=241140">https://bugs.webkit.org/show_bug.cgi?id=241140</a>

Patch by Kenneth Russell &lt;kbr@chromium.org &gt; on 2022-06-03
Reviewed by Kimmo Kinnunen.

Contains upstream commits:
git log --oneline 8291f2d3e72eca3a25826b689a013c292ef4ba94..b6a93d753bdd819ddc0dacb8cea554c86bc4c04e --pretty=%h %s
b6a93d753 GL: Temporarily enable validation for all GL calls.
d96cee668 Fix to invalidate cache when binding Transform Feedback.
86fce7a77 Roll SwiftShader from d070309f7d15 to 51c43dc015b7 (1 revision)
31c13df5d Revert &quot;Initialize buffer contents separately from BufferImpl::setData&quot;
213f669d3 Roll Chromium from 312583ebe76f to 85bb5555c93e (843 revisions)
0b533e64c Make GLProgram non-copyable.
9f4b9c650 Vulkan: Refactor command buffer retain calls.
ae74bdb3d Roll vulkan-deps from 528f7d8e618c to 59aa5963cf64 (8 revisions)
33b254fe8 Fix ValidateFragmentShaderColorBufferMaskMatch for indexed masks
e02848080 Roll SwiftShader from 5ca5b0ae5a7d to d070309f7d15 (5 revisions)
23f213d13 Vulkan: Make drawable size uniform
73019edeb Vulkan: SPIR-V Gen: No RelaxedPrecision on bitCount() and findLSB()
a2fe4445d Vulkan: Sync pipeline cache only when truly changed
9ea3967d3 Bug fix in GL_EXT_YUV_target
34cff1a14 Initialize buffer contents separately from BufferImpl::setData
2df17a127 Vulkan: Pack driver uniforms
98c2e169c Vulkan: Reduce pre-rotation spec const to bool
b267c009d Add support for comparison operator in FlatUnorderedSet
ee023e6af D3D11: fix constant buffer cache lookup.
cd42f669a Roll vulkan-deps from 6885957e17e7 to 528f7d8e618c (11 revisions)
5b74b1218 Roll SwiftShader from b5cb037f0292 to 5ca5b0ae5a7d (4 revisions)
aa2201725 Roll Chromium from f86f5d40df44 to 312583ebe76f (401 revisions)
c8989675e FramebufferTest: Add FramebufferConditionalFeedbackLoop test.
ae3de1a8c Add test for primitive state change
cd80b511e Metal: Upstream uniform limits from WebKit
54e08a5af Trace Tests: Remove Pixel 2 expectations.
757b84973 Vulkan: Fix reserve varying for xfb (take 2)
7495509b3 Roll vulkan-deps from c8893896acff to 6885957e17e7 (7 revisions)
7076ae5d0 Roll Chromium from 1f342b327faa to f86f5d40df44 (495 revisions)
891dd5b3d Vulkan: Fix mid-RP draw clear w.r.t growing scissor
7ad48b846 Revert &quot;Add Vulkan backend support for texture labels&quot;
fea195678 Vulkan: Remove removeEarlyFragmentTestsOpt flag
7b880204d Vulkan: Remove invalid ASSERT in DescriptorSetDesc.
4aa0975e6 Vulkan: Support Wayland EGL_DEFAULT_DISPLAY
4a20c9143 D3D: Fix race condition with parallel shader compile.
17750ab06 Roll vulkan-deps from 82a65519c521 to c8893896acff (10 revisions)
ccca0c25b libANGLE: Fix evaluating the sample count
2edb216bf Roll Chromium from d624307d6d25 to 1f342b327faa (484 revisions)
a81524477 Capture/Replay: Override eglCreateImage and eglDestroyImage
c608df696 Code Cleanup
802321922 Add ffz@google.com to OWNERS
615b2c685 D3D: implement whole-struct assignment in SSBOs.

Canonical link: <a href="https://commits.webkit.org/251262@main">https://commits.webkit.org/251262@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@295205">https://svn.webkit.org/repository/webkit/trunk@295205</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

### CODE REVIEW

**Comment by kenrussell** [comment]
@kkinnunen-apple please add merge-queue label if this looks OK to you - thanks.

**Comment by kenrussell** [comment]
@greggman @lexaknyazev @vonture FYI.

**Comment by kenrussell** [comment]
The mac-wk2 failure of webgl/2.0.0/conformance2/textures/image_bitmap_from_image_bitmap/tex-3d-r16f-red-float.html is a flake seemingly in WebKit's ImageBitmap implementation, and has been suppressed in #1188 .

**Comment by kenrussell** [comment]
@djg FYI - conflicted with #1200 and #1201 .

(I'm not sure what might have gone wrong in the last ANGLE roll in #999 .)

**Comment by kenrussell** [comment]
Ran `Tools/Scripts/update-angle --regenerate-changes-diff` to resolve the conflicts in `changes.diff`.

**Comment by kenrussell** [comment]
@kkinnunen-apple the `win` build failure seems like an infrastructure problem - or is there something wrong with the phrasing of this pull request?

Possible to get a review for this? The longer we wait the farther this gets out of date, and the less relevant it is - would be better to update ANGLE afresh again.

**Review by kkinnunen-apple — APPROVED** [review]

**Pull request merged**
