### PR TITLE
Delete helper scripts in imported/w3c/web-platform-tests/file-system-access/resources

### PR DESCRIPTION
**Pull request by szewai**
#### fe46c0dad388e24413d85ee5b9083afefa2761f5
<pre>
Delete helper scripts in imported/w3c/web-platform-tests/file-system-access/resources
<a href="https://bugs.webkit.org/show_bug.cgi?id=250855">https://bugs.webkit.org/show_bug.cgi?id=250855</a>
rdar://104437010

Reviewed by Tim Nguyen.

The tests that use these scripts were moved to fs/, and these scripts were copied to fs/resources/.

* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/message-target-dedicated-worker.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/message-target-service-worker.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/message-target-shared-worker.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/message-target.html: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/message-target.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/messaging-blob-helpers.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/messaging-helpers.js: Removed.
* LayoutTests/imported/w3c/web-platform-tests/file-system-access/resources/messaging-serialize-helpers.js: Removed.

Canonical link: <a href="https://commits.webkit.org/259120@main">https://commits.webkit.org/259120@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/7155d9179f4caaf4ff6fb4b2cde52c90decab27e

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/103948 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/13063 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/36890 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/113178 "Built successfully") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/173496 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/14093 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/3959 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/96199 "Built successfully") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/112269 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/109720 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/78/builds/10874 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/93939 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/38571 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/92712 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/25550 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/80222 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/6422 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/26931 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/6581 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/3460 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/12573 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/46461 "Passed tests") | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/6278 "Failed to push commit to Webkit repository") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/8355 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Review by nt1m — COMMENTED** [review]
These files seem to exist upstream: https://github.com/web-platform-tests/wpt/tree/master/file-system-access/resources , are we planning to remove them upstream as well?

**Comment by szewai** [comment]
> These files seem to exist upstream: https://github.com/web-platform-tests/wpt/tree/master/file-system-access/resources , are we planning to remove them upstream as well?

Yes, they are unused since https://github.com/web-platform-tests/wpt/commit/5798ab0381b11bea4f6e00cc3b5896c71e5f833f.

**Review by nt1m — APPROVED** [review]
Looks good, but please export the changes to WPT and have the files removed upstream as well.

**Comment by szewai** [comment]
> Looks good, but please export the changes to WPT and have the files removed upstream as well.

wpt pull request: https://github.com/web-platform-tests/wpt/pull/38073

**Pull request merged**
