### PR TITLE
[CMake][GLib] Symbol WebKit::GPUProcessMain should be public

### PR DESCRIPTION
**Pull request by aperezdc**
#### e3d83fa746241a811bbe944cf7dc437e5599871b
<pre>
[CMake][GLib] Symbol WebKit::GPUProcessMain should be public
<a href="https://bugs.webkit.org/show_bug.cgi?id=275110">https://bugs.webkit.org/show_bug.cgi?id=275110</a>

Reviewed by NOBODY (OOPS!).

Add a new GENERATE_LINKER_SCRIPT() CMake function which sets up rules to
process a template file through unifdef, sets the needed linker flags,
and arranges dependencies to workaround the fact that CMake does not
materialize build rules for files listed in a target&apos;s LINK_DEPENDS
property. This allows to set WebKit::GPUProcessMain() as public with
ENABLE_GPU_PROCESS=ON.

* Source/WebKit/PlatformGTK.cmake: Use GENERATE_LINKER_SCRIPT().
* Source/WebKit/PlatformWPE.cmake: Ditto.
* Source/WebKit/webkitglib-symbols.map.in: Renamed from Source/WebKit/webkitglib-symbols.map.
* Source/cmake/GLibMacros.cmake: Add GENERATE_LINKER_SCRIPT() function.
</pre>
https://github.com/WebKit/WebKit/commit/e3d83fa746241a811bbe944cf7dc437e5599871b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/54220 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/33608 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/6762 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/57497 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/4946 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/41135 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/4893 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/43922 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/3319 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/56316 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/31873 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/46957 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/25064 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/28679 "Passed tests") | | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/3093 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/47580 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/50394 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/4490 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/59089 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/53728 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/29428 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/4650 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/51342 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/30598 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/47065 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/50705 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/31572 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/66029 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/30381 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12577 "Passed tests") |

### CODE REVIEW

**Review by mcatanzaro — COMMENTED** [review]
Sooo this is OK, but surely it would be a lot easier to just always build and export GPUProcessMain, and just leave the implementation empty if `!ENABLE(GPU_PROCESS)`? Then we don't need to process the symbols map with unifdef, which is slightly hardcore.

(Besides, I don't think we expect to ever allow users to decide for themselves whether to enable/disable GPU process in a WPE/GTK release? Surely that's a choice for developers and not for users? So it should really probably not need to be conditional.)

**Comment by carlosgcampos** [comment]
> Sooo this is OK, but surely it would be a lot easier to just always build and export GPUProcessMain, and just leave the implementation empty if `!ENABLE(GPU_PROCESS)`? Then we don't need to process the symbols map with unifdef, which is slightly hardcore.
> 

Agree.

> (Besides, I don't think we expect to ever allow users to decide for themselves whether to enable/disable GPU process in a WPE/GTK release? Surely that's a choice for developers and not for users? So it should really probably not need to be conditional.)

GPU process will require DMA-BUF support and GBM, if not available it should be disabled.

**Comment by aperezdc** [comment]
Okay, I'll change this to avoid passing the `.map` file through `unifdef` and have the symbol always defined. Thanks for the idea!

**Comment by aperezdc** [comment]
Funny thing happened: I went to check, and there's already a `return 0` implementation of `GPUProcessMain()` that gets used with `!ENABLE(GPU_PROCESS)` so updating the `.map` file and making sure that the source file always gets built.

**Comment by aperezdc** [comment]
> Funny thing happened: I went to check, and there's already a `return 0` implementation of `GPUProcessMain()` that gets used with `!ENABLE(GPU_PROCESS)` so updating the `.map` file and making sure that the source file always gets built.

...but that didn't work, somehow the `GPUProcessMain()` symbol disappears with `!ENABLE(GPU_PROCESS)` and the linker complains about it not being there 😿

**Comment by aperezdc** [comment]
> > Funny thing happened: I went to check, and there's already a `return 0` implementation of `GPUProcessMain()` that gets used with `!ENABLE(GPU_PROCESS)` so updating the `.map` file and making sure that the source file always gets built.
> 
> ...but that didn't work, somehow the `GPUProcessMain()` symbol disappears with `!ENABLE(GPU_PROCESS)` and the linker complains about it not being there 😿

Okay, got it working now:

```
% nm -CD WebKitBuild/WPE/Release/lib/libWPEWebKit-2.0.so|grep GPUProcessMain        
0000000001fdaa80 T WebKit::GPUProcessMain(int, char**)
```

It was a type in the `.map` file 🤦🏼 &mdash; I'll update the patch momentarily.

**Comment by aperezdc** [comment]
No idea why `git webkit` created a new PR at https://github.com/WebKit/WebKit/pull/29502 

Anyway, closing this in favor of the new one.

**Pull request closed without merging**
