### PR TITLE
Restore one-click MiniBrowser builds from Xcode

### PR DESCRIPTION
**Pull request by saagarjha**
#### 40f091d7f3693bc2ba3cbb1580cf5523b74fa582
<pre>
Restore one-click MiniBrowser builds from Xcode
<a href="https://bugs.webkit.org/show_bug.cgi?id=247544">https://bugs.webkit.org/show_bug.cgi?id=247544</a>

Reviewed by Elliott Williams.

Add a new &quot;Everything up to MiniBrowser&quot; scheme that is a duplicate of
&quot;Everything up to WebKit&quot; but runs also MiniBrowser.

* WebKit.xcworkspace/xcshareddata/xcschemes/Everything up to MiniBrowser.xcscheme: Added.

Canonical link: <a href="https://commits.webkit.org/256466@main">https://commits.webkit.org/256466@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/96918f48645697832a0cd1eb51349672c7af33ea

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/95744 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/4998 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/28786 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/105320 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/5076 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/33756 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/88125 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/101158 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/101405 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/3729 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/82358 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/30786 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/85592 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/87505 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/73615 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/39489 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/19044 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/37182 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/20361 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4467 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/41249 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/43004 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/43205 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/39612 "Passed tests") | |

### CODE REVIEW

**Comment by ghost** [comment]
LGTM

**Comment by haze** [comment]
LGTM

**Review by emw-apple — CHANGES_REQUESTED** [review]
I think there's an issue here for non-Mac builds. This change causes MiniBrowser.app to build _unconditionally_, including for iOS or other embedded platforms. And MiniBrowser fails to compile outside of macOS.

One alternative approach is to add an "Everything up to MiniBrowser" scheme which builds MiniBrowser.app and implicit dependencies. Then you'd use that scheme to compile and launch all of WebKit + MiniBrowser.

**Comment by saagarjha** [comment]
Sounds good; I copied the changes over into a new scheme.

**Review by emw-apple — APPROVED** [review]
Thanks!

**Pull request merged**
