### PR TITLE
Update WPT workers/modules/ workers JS to not use www1.localhost

### PR DESCRIPTION
**Pull request by youennf**
#### 869ec83217340bb32966849b05f1a2c585fd3fd5
<pre>
Update WPT workers/modules/ workers JS to not use www1.localhost
<a href="https://bugs.webkit.org/show_bug.cgi?id=260865">https://bugs.webkit.org/show_bug.cgi?id=260865</a>
rdar://problem/114631363

Reviewed by Tim Nguyen.

Switch to hosts[alt] so that we will use 127.0.0.1 in WebKit test infra.

* LayoutTests/imported/w3c/web-platform-tests/workers/modules/dedicated-worker-import-referrer-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/workers/modules/resources/dynamic-import-remote-origin-referrer-checker-worker.sub.js:
* LayoutTests/imported/w3c/web-platform-tests/workers/modules/resources/static-import-remote-origin-referrer-checker-worker.sub.js:
* LayoutTests/imported/w3c/web-platform-tests/workers/modules/shared-worker-import-referrer-expected.txt:
* LayoutTests/platform/glib/imported/w3c/web-platform-tests/workers/modules/dedicated-worker-import-referrer-expected.txt: Removed.

Canonical link: <a href="https://commits.webkit.org/267451@main">https://commits.webkit.org/267451@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/8116e71e625395edef73454725bcdf52a2fe2ede

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/16579 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/16902 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/17345 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/18361 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/15549 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/20132 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/17043 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/17878 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/16777 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/17178 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/14345 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/19144 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/14422 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/15029 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/21813 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/15410 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/15195 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/19503 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/15792 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/13410 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/14989 "Built successfully") | | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/3982 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/19359 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/15618 "Built successfully") | | |

### CODE REVIEW

**Comment by youennf** [comment]
Submitted web-platform-tests pull request: https://github.com/web-platform-tests/wpt/pull/41698

**Comment by nt1m** [comment]
This doesn't seem to make a difference upstream: https://github.com/web-platform-tests/wpt/pull/41698/checks?check_run_id=16315896678

**Comment by youennf** [comment]
These tests pass in wpt.fyi already, this is only for our own test infra that it will help

**Comment by nt1m** [comment]
I'm not seeing that for the shared worker one: https://wpt.fyi/results/workers/modules/shared-worker-import-referrer.html?label=experimental&label=master&aligned

**Comment by youennf** [comment]
> I'm not seeing that for the shared worker one: https://wpt.fyi/results/workers/modules/shared-worker-import-referrer.html?label=experimental&label=master&aligned

This is a shared worker referrer issue, that is now fixed in trunk.

**Review by nt1m — APPROVED** [review]

**Pull request merged**
