### PR TITLE
`generate-bundle` fails at installing `toml`

### PR DESCRIPTION
**Pull request by obyknovenius**
#### 3a33119682b78d6fed5d8f6cffaf23a25aad2bda
<pre>
`generate-bundle` fails at installing `toml`
<a href="https://bugs.webkit.org/show_bug.cgi?id=262184">https://bugs.webkit.org/show_bug.cgi?id=262184</a>

Reviewed by Jonathan Bedard.

After `268269@main` `pyparsing` must be specified as a implicit
dependency of `toml`.

* Tools/Scripts/webkitpy/__init__.py:

Canonical link: <a href="https://commits.webkit.org/268547@main">https://commits.webkit.org/268547@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/af387f03dc23ecef0d5c1936f5c6e3d462ae902e

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/19914 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/20338 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/20958 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/21807 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/18600 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/20150 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/23595 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/20487 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/20122 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/20136 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/20107 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/17325 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/22661 "Built successfully") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/20100 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/17278 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/18120 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/24380 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/18354 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/18296 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/22366 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/18885 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/16011 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/18056 "Built successfully") | | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/4759 "") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/22405 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/2457 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/18709 "Built successfully") | | |

### CODE REVIEW

**Review by JonWBedard — CHANGES_REQUESTED** [review]
This won't work and will end up in an infinite loop with a fresh install. We need #18232.

**Comment by obyknovenius** [comment]
> This won't work and will end up in an infinite loop with a fresh install. We need #18232.

While I agree that we need #18232, I can assure you that this works. You can try it by wiping out  `Tools/Scripts/libraries/autoinstalled` directory and running `generate-bundle --help`.

**Comment by JonWBedard** [comment]
> > This won't work and will end up in an infinite loop with a fresh install. We need #18232.
> 
> While I agree that we need #18232, I can assure you that this works. You can try it by wiping out `Tools/Scripts/libraries/autoinstalled` directory and running `generate-bundle --help`.

Sorry for blocking this temporarily. If you look at what `AutoInstall.install(...)` does, if first checks if the library we're installing is in a small list of libraries required for setup tools (and `tomli` is one of those libraries). The trouble with this is that this check actually happens before we install any dependencies of that library. So in `tomli`'s case, we would normally expect that `pyparsing` is already installed, but that won't be true (or at least, wasn't true) because `pyparsing` wasn't one of the libraries required to use setup tools. I was mistaken about the infinite loop (perhaps that was older behavior?), but I do stand by this PR not doing what you thought it did without https://commits.webkit.org/268542@main. In any case, r+ed this now!

**Review by JonWBedard — APPROVED** [review]

**Comment by obyknovenius** [comment]
> Wait, I'm sorry, this is `toml`, not `tomli`, I was completely wrong!

It is easy to get confused. Thank you for merging it!

**Pull request merged**
