### PR TITLE
[WinCairo] Search inputs do not show icons

### PR DESCRIPTION
**Pull request by donny-dont**
#### 810eb196ed5979bcbf683288b10972a653d3542f
<pre>
[WinCairo] Search inputs do not show icons
<a href="https://bugs.webkit.org/show_bug.cgi?id=188175">https://bugs.webkit.org/show_bug.cgi?id=188175</a>

Reviewed by NOBODY (OOPS!).

Move Windows resources from WebKitLegacy into WebCore so it can be shared with WebKit.

* Source/WebCore/PlatformWin.cmake:
* Source/WebCore/platform/graphics/win/ImageWin.cpp:
* Source/WebCore/platform/win/WebCore.resources/WebCore.rc: Copied from Source/WebKitLegacy/win/WebKit.resources/WebKit.rc.
* Source/WebCore/platform/win/WebCore.resources/deleteButton.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/deleteButton.png.
* Source/WebCore/platform/win/WebCore.resources/deleteButtonPressed.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/deleteButtonPressed.png.
* Source/WebCore/platform/win/WebCore.resources/fsVideoAudioVolumeHigh.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/fsVideoAudioVolumeHigh.png.
* Source/WebCore/platform/win/WebCore.resources/fsVideoAudioVolumeLow.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/fsVideoAudioVolumeLow.png.
* Source/WebCore/platform/win/WebCore.resources/fsVideoExitFullscreen.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/fsVideoExitFullscreen.png.
* Source/WebCore/platform/win/WebCore.resources/fsVideoPause.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/fsVideoPause.png.
* Source/WebCore/platform/win/WebCore.resources/fsVideoPlay.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/fsVideoPlay.png.
* Source/WebCore/platform/win/WebCore.resources/missingImage.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/missingImage.png.
* Source/WebCore/platform/win/WebCore.resources/nullplugin.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/nullplugin.png.
* Source/WebCore/platform/win/WebCore.resources/panEastCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panEastCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panIcon.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panIcon.png.
* Source/WebCore/platform/win/WebCore.resources/panNorthCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panNorthCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panNorthEastCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panNorthEastCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panNorthWestCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panNorthWestCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panSouthCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panSouthCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panSouthEastCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panSouthEastCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panSouthWestCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panSouthWestCursor.png.
* Source/WebCore/platform/win/WebCore.resources/panWestCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/panWestCursor.png.
* Source/WebCore/platform/win/WebCore.resources/searchCancel.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/searchCancel.png.
* Source/WebCore/platform/win/WebCore.resources/searchCancelPressed.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/searchCancelPressed.png.
* Source/WebCore/platform/win/WebCore.resources/searchMagnifier.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/searchMagnifier.png.
* Source/WebCore/platform/win/WebCore.resources/searchMagnifierResults.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/searchMagnifierResults.png.
* Source/WebCore/platform/win/WebCore.resources/textAreaResizeCorner.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/textAreaResizeCorner.png.
* Source/WebCore/platform/win/WebCore.resources/verticalTextCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/verticalTextCursor.png.
* Source/WebCore/platform/win/WebCore.resources/zoomInCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/zoomInCursor.png.
* Source/WebCore/platform/win/WebCore.resources/zoomOutCursor.png: Renamed from Source/WebKitLegacy/win/WebKit.resources/zoomOutCursor.png.
* Source/WebCore/platform/win/resource.h: Copied from Source/WebKitLegacy/win/resource.h.
* Source/WebKitLegacy/win/WebKit.resources/WebKit.rc:
* Source/WebKitLegacy/win/WebKitDLL.cpp:
* Source/WebKitLegacy/win/resource.h:
* Tools/TestWebKitAPI/PlatformWin.cmake:
* Tools/TestWebKitAPI/win/TestWebCoreStubs.cpp: Removed.
</pre>
https://github.com/WebKit/WebKit/commit/810eb196ed5979bcbf683288b10972a653d3542f

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/107596 "3 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/16650 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/40491 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/116746 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/116159 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/111489 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/18073 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/7963 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/99766 "Built successfully") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/113351 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/13655 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/96836 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/41319 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/95566 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/28462 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/83162 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/9642 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/29815 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/10312 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/6711 "Found 1 new test failure: imported/w3c/web-platform-tests/xhr/formdata/append-formelement.html (failure)") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/15798 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/49396 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/11872 "Built successfully") | | | 
| | | | |

### CODE REVIEW

**Comment by donny-dont** [comment]
Rebase of @foopoiuyt ’s patch at https://bugs.webkit.org/show_bug.cgi?id=188175#c7

**Comment by fujii** [comment]
Win EWS failures seems to be true-positive. WebCore module is not a DLL. We should copy the resource images to WK2, or make WebCore module a DLL.

>  editing/execCommand/insertImage.html [ Failure ]
>  fast/images/inline-image-box-with-no-alt-should-collapse-no-quirks.html [ Failure ]
>  fast/images/inline-image-box-with-no-alt-should-collapse-quirks.html [ Failure ]

**Comment by donny-dont** [comment]
Yea the AppleWin failure is legit @fujii . I just want to try a couple things to see if I can get this working without just copying resources.

**Comment by donny-dont** [comment]
So my working theory is that `WebCore_LIBRARY_TYPE` being `STATIC` is causing the issue. A local WinCairo is able to load the resource in a WebKit and WebKitLegacy window within MiniBrowser and `WebCore_LIBRARY_TYPE` is `OBJECT` for them.

So if this works I think the way to go is to make a `WebCoreResources` library whose type is `OBJECT` and just contains the `.rc` file for its source. Not sure how this would work with the internal build but I think this would be the way.

**Comment by brentfulgham** [comment]
I moved the resources from WebKitLegacy to WebCore in PR #10162.

**Comment by donny-dont** [comment]
No longer relevant

**Pull request closed without merging**
