### PR TITLE
Use different cherry-pick format for main

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 659cd39a8658844cd7a44aeecfc4fa607b73eb73
<pre>
Use different cherry-pick format for main
<a href="https://bugs.webkit.org/show_bug.cgi?id=255088">https://bugs.webkit.org/show_bug.cgi?id=255088</a>
rdar://107708812

Reviewed by Dewei Zhu.

When cherry-picking into main, retain the original commit message in it&apos;s entireity
and tag the bottom of the commit with a &apos;Originally-landed-as&apos; message. Use existing behavior
for all other branches.

* Tools/Scripts/libraries/webkitscmpy/setup.py: Bump version.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py: Ditto.
* Tools/Scripts/hooks/prepare-commit-msg:
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/canonicalize/message.py:
(main): Do not insert lines between trailers.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/install_hooks.py:
(InstallHooks.main): Pass default branch, trailers to strip and source remotes to hook templates.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/canonicalize_unittest.py:
(TestCanonicalize.test_alternate_trailer):

Canonical link: <a href="https://commits.webkit.org/262726@main">https://commits.webkit.org/262726@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/b2e8d317db620f6783f1e88c200ca19a340eb5de

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/2343 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/2353 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/2457 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/3308 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/2371 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/2316 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/2480 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/2433 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/2105 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/2365 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/15/builds/2104 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/2112 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/3172 "Built successfully") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/2376 "Passed tests") | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/39/builds/83 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/2094 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/1969 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/2175 "Built successfully") | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/2121 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/3289 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/2142 "Passed tests") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/1933 "Passed tests") | | 
| [✅ 🧪 services](https://ews-build.webkit.org/#/builders/28/builds/2322 "Passed tests") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/2152 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/2100 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/2083 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/275 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/2274 "Built successfully") | | |

### CODE REVIEW

**Comment by JonWBedard** [comment]
#12457 is an example of what this actually looks like. We still have to have some tools adopt reading this new format, but that is being done in separate commits.

**Comment by aproskuryakov** [comment]
> #12457 is an example of what this actually looks like. We still have to have some tools adopt reading this new format, but that is being done in separate commits.

May be clearer to say "Originally landed as", not "Cherry-pick". Or at least "Cherry-pick from".

Otherwise, the new format looks good to me.

**Comment by JonWBedard** [comment]
> > #12457 is an example of what this actually looks like. We still have to have some tools adopt reading this new format, but that is being done in separate commits.
> 
> May be clearer to say "Originally landed as", not "Cherry-pick". Or at least "Cherry-pick from".
> 
> Otherwise, the new format looks good to me.

If we're diverging from the `Cherry-pick` terminology (which I think is fine), I think I'd prefer "Original landed as"

**Comment by JonWBedard** [comment]
> But now I'm thinking that it could confuse people into thinking that it's about originally landing, reverting and re-landing. "Originally landed on release branch as"?

Seems like we would be duplicating information with that that descriptor. Some full examples of our proposals here:
```
Cherry-pick: 259548.279@safari-7615-branch (41f425bc0ef8). rdar://107710008
Cherry-pick from: 259548.279@safari-7615-branch (41f425bc0ef8). rdar://107710008
Originally landed as: 259548.279@safari-7615-branch (41f425bc0ef8). rdar://107710008
Originally landed on release branch as: 259548.279@safari-7615-branch (41f425bc0ef8). rdar://107710008
```

I would prefer the shorter version of the "Originally landed as", but the longer version of the "Cherry-pick" one.

**Comment by JonWBedard** [comment]
`git-webkit` reading this is implemented in #12475

**Review by JonWBedard — COMMENTED** [review]
This version uses `Originally-landed-as`, I added the dashes because that makes it compatible with [`git-interpret-trailers`](https://git-scm.com/docs/git-interpret-trailers), should we have any desire to leverage that fact in the future.

**Review by dewei-zhu — APPROVED** [review]
r=me

**Pull request merged**
