### PR TITLE
[svn-create-patch] Remove

### PR DESCRIPTION
**Pull request by JonWBedard**
#### 15270a95afaa87d4ad991481c22b9b3fab9a8907
<pre>
[svn-create-patch] Remove
<a href="https://bugs.webkit.org/show_bug.cgi?id=271971">https://bugs.webkit.org/show_bug.cgi?id=271971</a>
<a href="https://rdar.apple.com/125725715">rdar://125725715</a>

Reviewed by Ryan Haddad and David Kilzer.

* Tools/Scripts/prepare-ChangeLog:
(createPatchCommand): Remove Subversion case.
* Tools/Scripts/svn-create-patch: Removed.

Canonical link: <a href="https://commits.webkit.org/276970@main">https://commits.webkit.org/276970@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/e767678f5db2115b8a125c2f6b343f85b38044d2

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/46077 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/25207 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/48662 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/48748 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/42117 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/48384 "Passed tests") | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/29539 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/51/builds/22648 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/37678 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/46655 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/22298 "Unexpected infrastructure issue, retrying build") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/39753 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/18868 "Passed tests") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/42/builds/19698 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/40850 "Passed tests") | [✅ 🛠 wpe-skia](https://ews-build.webkit.org/#/builders/52/builds/4121 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/42406 "EWS skipped this build as PR had skip-ews label when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/41200 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/50539 "Built successfully") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/21073 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/50/builds/17591 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/44840 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/22373 "Built successfully") | | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/43741 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/22732 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/6459 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/22067 "Built successfully") | | |

### CODE REVIEW

**Review by ryanhaddad — APPROVED** [review]

**Comment by JonWBedard** [comment]
@aproskuryakov has some concerns about special cases `svn-create-patch` handles that `git patch` doesn't, including @ddkilzer to see his thoughts. Less code is always better, but if we have something genuinely useful, we shouldn't get rid of this script.

**Comment by ddkilzer** [comment]
One moment while I make a trip down memory lane:
```
$ git log --author=ddkilzer --follow Tools/Scripts/svn-create-patch
```

**Comment by ddkilzer** [comment]
The only change I made to `svn-create-patch` was this:

> svn-create-patch fails when svn mv is used on directory trees
> <https://webkit.org/b/14590>
> Commit: [204343@main](https://commits.webkit.org/204343@main)

Looks like any git-related changes were to `Tools/Scripts/VCSUtils.pm`.  (BTW, there will be subroutines in `VCSUtils.pm` and some Perl tests that can be removed where `svn-create-patch` was the only tool that used those subroutines.)

So I think it's okay to remove `svn-create-patch` as it was only ever used for Subversion.  It's `svn-apply` that was dual-purpose.

—

Perhaps @aproskuryakov was thinking of this change I made to `svn-apply` to handle empty files in both svn and git?

> svn-apply fails when a patch has an empty file
> <https://webkit.org/b/29684>
> Commit: [201453@main](https://commits.webkit.org/201453@main)

**Review by ddkilzer — APPROVED** [review]
r=me

**Comment by JonWBedard** [comment]
>  ...
> So I think it's okay to remove `svn-create-patch` as it was only ever used for Subversion. It's `svn-apply` that is dual-purpose.
> 
>  ...

We'll be removing `svn-apply` soon too, although we need to replace EWS's usage with a pure `git` call (it already uses that when landing, so folks haven't been able to land SVN patches for years, at this point)

**Pull request merged**
