### PR TITLE
Move __objc_stubs symbols closer to symbols that jump to them when linking WebCore

### PR DESCRIPTION
**Pull request by achristensen07**
#### 8ef2f173d264f50c0360166948283f6d7449cf2a
<pre>
Move __objc_stubs symbols closer to symbols that jump to them when linking WebCore
<a href="https://bugs.webkit.org/show_bug.cgi?id=251391">https://bugs.webkit.org/show_bug.cgi?id=251391</a>
rdar://104834995

Reviewed by Elliott Williams.

Without this change and with some other unrelated changes from PR 9342 that slightly
increase WebCore&apos;s binary size, I get some linker errors like this:

ld: b(l) ARM64 branch out of range (134310948 max is +/-128MB)

That is because we are linking jumps to symbols in the __objc_stubs section which are
very far away from other symbols jumping to them from the __text section.  To fix this,
simply rename __objc_stubs to __text to merge them together and decrease the maximum
jumps to nowhere near 128MB.

* Source/WebCore/Configurations/WebCore.xcconfig:

Canonical link: <a href="https://commits.webkit.org/259606@main">https://commits.webkit.org/259606@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/412ae700128c0fb4ddb6cc5fcf39f85084a89df1

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/105366 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/14437 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/38242 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/114621 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/174798 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/109267 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/15623 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/5370 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/97672 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/114517 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/111124 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/12080 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/95063 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/39561 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/93946 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/26697 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/81237 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/7758 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/28057 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/7872 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/84/builds/4642 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/13901 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/47601 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/9661 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/75/builds/3544 "Built successfully and passed tests") | | | |

### CODE REVIEW

**Comment by AtariDreams** [comment]
Can't you choose where the stubs are located in the executable via a linker-script, or does it have to be done this way?

Can't you redefine the memory mapping so this rename isn't needed

**Comment by achristensen07** [comment]
There may be other ways to do this, but something like this needs to be done, and this is certainly a way to do it and I verified that it works.  I think we don't want to maintain a linker script and I'm not sure how to redefine the memory mapping.

**Comment by achristensen07** [comment]
This should probably only be done on debug builds.  Release builds aren't anywhere large enough to need this.

**Comment by emw-apple** [comment]
I'm not familiar with the implications of merging __objc_stubs in this way, but afaict nothing on the platform reads from this section; it's just an artifact of the linker pass that generates objc_msgSend stubs. So this seems safe as a workaround for what feels like should be a linker bug.

**Review by emw-apple — APPROVED** [review]

**Pull request merged**
