### PR TITLE
Make VTTCue.size() from 'int' to 'double'

### PR DESCRIPTION
**Pull request by Ahmad-S792**
#### b93351e6debe3c7ca46a6c14111bdcd85a3f823e
<pre>
Make VTTCue.size() from &apos;int&apos; to &apos;double&apos;

<a href="https://bugs.webkit.org/show_bug.cgi?id=260365">https://bugs.webkit.org/show_bug.cgi?id=260365</a>
rdar://problem/114089775

Reviewed by Jer Noble.

This patch aligns WebKit with Gecko / Firefox, Blink / Chromium and Web-Spec [1][2].

[1] <a href="https://w3c.github.io/webvtt/#the-vttcue-interface">https://w3c.github.io/webvtt/#the-vttcue-interface</a>
[2] <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=19836">https://www.w3.org/Bugs/Public/show_bug.cgi?id=19836</a>

Spec Commit: <a href="https://github.com/w3c/webvtt/commit/64825911acce356bdd95c5ce8a8755f87f1d0702">https://github.com/w3c/webvtt/commit/64825911acce356bdd95c5ce8a8755f87f1d0702</a>

In Web-Spec, `size` is double but in WebKit&apos;s implementation, it was using &apos;int&apos;,
so this PR just changes it to &apos;double&apos;.

* Source/WebCore/html/track/VTTCue.h: Change &apos;size&apos; to &apos;double&apos; and also usage in &apos;setSize()&apos; argument
* Source/WebCore/html/track/VTTCue.cpp:
(VTTCue::setSize): Update argument to &apos;double&apos;
* LayoutTests/imported/w3c/web-platform-tests/webvtt/api/VTTCue/size.html: Add Test Case (manually)
* LayoutTests/imported/w3c/web-platform-tests/webvtt/api/VTTCue/size-expected.txt: Add Test Case Expectation
* LayoutTests/imported/w3c/web-platform-tests/html/semantics/embedded-content/media-elements/track/track-element/vtt-cue-float-precision-expected.txt: Rebaselined
* LayoutTests/media/track/track-webvtt-tc019-cue-size.html: Removed in favor of &apos;WPT&apos; test
* LayoutTests/media/track/track-webvtt-tc019-cue-size-expected.txt: Ditto

Canonical link: <a href="https://commits.webkit.org/267041@main">https://commits.webkit.org/267041@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/f2c8ca5c6dc92611f438836137caf3cd042c36de

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/15473 "Failed to checkout and rebase branch from PR 16808") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/15777 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/16141 "Built successfully") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/17228 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/14508 "Built successfully") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/9/builds/15646 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/18294 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/15873 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/17228 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/15658 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/15/builds/16088 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/13157 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/2/builds/17971 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/39/builds/13358 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/10/builds/13957 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/2/builds/17971 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/14419 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/14124 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/2/builds/17971 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/14704 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/17/builds/12457 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/13961 "Built successfully") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/13805 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/18323 "Built successfully") | | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/1882 "Built successfully and passed tests") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/14525 "Built successfully") | | |

### CODE REVIEW

**Comment by Ahmad-S792** [comment]
@jernoble & @danae404 - it is not reviewed. :-(

**Comment by Ahmad-S792** [comment]
Plus it also progresses following test case: http://wpt.live/webvtt/parsing/file-parsing/tests/settings-size.html

**Comment by Ahmad-S792** [comment]
I am in favour of deleting 'local' (now failing test) test over WPT test. Any input?

**Comment by nt1m** [comment]
imported/w3c/web-platform-tests/html/semantics/embedded-content/media-elements/track/track-element/vtt-cue-float-precision.html needs rebaselining
media/track/track-webvtt-tc019-cue-size.htm needs updating (potentially need to add rounding in the test?)

**Comment by Ahmad-S792** [comment]
> imported/w3c/web-platform-tests/html/semantics/embedded-content/media-elements/track/track-element/vtt-cue-float-precision.html needs rebaselining
> media/track/track-webvtt-tc019-cue-size.htm needs updating (potentially need to add rounding in the test?)

Done.

**Comment by Ahmad-S792** [comment]
> The `media/track/track-webvtt-tc019-cue-size.html` test is definitely wrong now; the WebVTT source file specifies a `10.6%` size, which should generate a `size` value of `10.6` now that `size` is a float.
> 
> Looks like the test predates the change which made `size` a `double`: https://www.w3.org/Bugs/Public/show_bug.cgi?id=19836
> 
> I'd be in favor of just removing the `media/track/track-webvtt-tc019-cue-size.html` test.

Removed `media/track/track-webvtt-tc019-cue-size.html` in favour of WPT test.

**Review by jernoble — APPROVED** [review]
r=me

**Comment by Ahmad-S792** [comment]
Just pushed new commit to add 'radar'.

**Pull request merged**
